packages/PHP7_Sculpin/src/Source/SourceFileFilter/StaticSourceFilter.php

copy all .js files from assets to output

[PHP7_Sculpin] add .js files to static files sources

---

packages/DefaultAutowire/src/DependencyInjection/Definition/DefinitionAnalyzer.php
packages/DefaultAutowire/tests/DependencyInjection/Definition/DefinitionAnalyzerForFactoryTest.php
packages/DefaultAutowire/tests/DependencyInjection/Definition/DefinitionAnalyzerSource/TestEntity.php
packages/DefaultAutowire/tests/DependencyInjection/Definition/DefinitionAnalyzerSource/TestEntityRepository.php

These enhancements are required if you want have doctrine repositories defined as services.

Factory service enhancement

---

packages/Statie/src/Renderable/Latte/LatteDecorator.php
packages/Statie/tests/Renderable/Latte/LatteDecoratorSource/fileWithFileVariable.latte
packages/Statie/tests/Renderable/Latte/LatteDecoratorTest.php
packages/SymfonyEventDispatcher/src/Adapter/Symfony/DependencyInjection/Compiler/CollectEventSubscribersPass.php

[Statie] Add current file to template

---

packages/ControllerAutowire/src/Controller/Form/ControllerFormTrait.php

Hi !
Please can we have _createNamedBuilder_ in _ControllerFormTrait_ as its quite handy for situations where we have more than one form in a page ?
Thanks!

Add createNamedBuilder to ControllerFormTrait

---

packages/EasyCodingStandard/composer.json

ref https://github.com/composer/composer/issues/6253

[EasyCodingStandard] fix composer local package autoload 

---

packages/DoctrineMigrations/README.md
packages/DoctrineMigrations/composer.json
packages/DoctrineMigrations/src/DI/MigrationsExtension.php
packages/DoctrineMigrations/tests/DI/MigrationsExtension/BeforeCompileTest.php
packages/DoctrineMigrations/tests/DI/MigrationsExtension/LoadConfigurationTest.php
packages/DoctrineMigrations/tests/config/default.neon
packages/DoctrineMigrations/tests/config/manualUsage.neon

Tested on real project.
Closes #109

[DoctrineMigrations] Replaced event dispatcher implementation

---

packages/AutoServiceRegistration/README.md

1. Updated FQCN to the bundle class.
2. Fixed scanned path to "src" in the example configuration (%kernel.root_dir% is path to "app" so it pointed to "app/src" instead of "src").

update examples in README.md

---

composer.json
packages/SymbioticController/composer.json

Should have fixed travis build

Updated composer.json to use stable versions

---

packages/DefaultAutowire/src/DependencyInjection/DefinitionAnalyzer.php
packages/DefaultAutowire/tests/DependencyInjection/DefinitionAnalyzerSource/BuiltInArgumentsTypehints.php
packages/DefaultAutowire/tests/DependencyInjection/DefinitionAnalyzerTest.php

I need to add a test case for this.

[DefaultAutowiring] Fix DefinitionAnalyzer (closes #32)

---

composer.json
easy-coding-standard.neon
packages/EasyCodingStandard/src/Validator/CheckerTypeValidator.php

+ bump to object-calisthenics RC2

Security adviser added

---

packages/AutoServiceRegistration/composer.json
packages/AutoServiceRegistration/tests/Adapter/Symfony/CompleteTest.php
packages/CodingStandard/composer.json
packages/EasyCodingStandard/phpunit.xml
packages/EasyCodingStandard/tests/bootstrap.php
packages/PackageBuilder/composer.json
packages/SymbioticController/composer.json
packages/SymfonyEventDispatcher/composer.json
packages/SymfonySecurityVoters/composer.json

- wrong composer versions
- missing composer dependencies
- wrong composer autoloads
- or legacy layers

subsplit fixes

---

packages/SymfonyEventDispatcher/README.md

Added information about passing event objects in arguments.
Resolves #146

[SymfonyEventDispatcher] Updated readme.md

---

.coveralls.yml
.scrutinizer.yml
.travis.yml
README.md
easy-coding-standard.neon
packages/EasyCodingStandard/packages/SniffRunner/tests/File/FileTest.php
packages/ModularLatteFilters/tests/DI/MissingLatteDefinitionInExtensionTest.php
packages/ModularRouting/tests/Routing/AbstractRouteCollectionProviderTest.php
packages/PackageBuilder/tests/Adapter/Nette/DI/DefinitionFinderTest.php
packages/Statie/packages/FlatWhite/tests/Latte/DynamicStringLoaderTest.php
packages/Statie/tests/Application/StatieApplicationTest.php
packages/Statie/tests/Github/GithubPublishingProcessTest.php
packages/Statie/tests/Renderable/File/FileFactoryTest.php
packages/Statie/tests/Translation/MessageAnalyzerTest.php
packages/SymbioticController/tests/Adapter/Nette/Routing/PresenterMapperTest.php
packages/SymbioticController/tests/Adapter/Nette/Routing/PresenterRoute/BasicTest.php
packages/SymbioticController/tests/Adapter/Nette/Template/TemplateRendererTest.php
packages/SymbioticController/tests/Adapter/Nette/Validator/PresenterGuardianTest.php

Ref https://thephp.cc/news/2016/02/questioning-phpunit-best-practices
+ simlify travis.yml
+ replace scrutinizer with coveralls

[tests] update expectedException

---

README.md
docs/badges-for-all-packages.md
packages/CodingStandard/.coveralls.yml
packages/CodingStandard/.scrutinizer.yml
packages/CodingStandard/.travis.yml
packages/CodingStandard/README.md
packages/EasyCodingStandard/.coveralls.yml
packages/EasyCodingStandard/.scrutinizer.yml
packages/EasyCodingStandard/.travis.yml
packages/EasyCodingStandard/README.md
packages/ModularLatteFilters/.coveralls.yml
packages/ModularLatteFilters/.scrutinizer.yml
packages/ModularLatteFilters/.travis.yml
packages/ModularLatteFilters/README.md
packages/ModularRouting/.coveralls.yml
packages/ModularRouting/.scrutinizer.yml
packages/ModularRouting/.travis.yml
packages/ModularRouting/README.md
packages/PackageBuilder/.coveralls.yml
packages/PackageBuilder/.scrutinizer.yml
packages/PackageBuilder/.travis.yml
packages/PackageBuilder/README.md
packages/Statie/.coveralls.yml
packages/Statie/.scrutinizer.yml
packages/Statie/.travis.yml
packages/Statie/README.md
packages/SymbioticController/.coveralls.yml
packages/SymbioticController/.scrutinizer.yml
packages/SymbioticController/.travis.yml
packages/SymbioticController/README.md

Coveralls allow limiting min coverage, which is desired to be check by CI and not human (me :))

Migrate from Scrutinizer to Coveralls

---

packages/CodingStandard/README.md
packages/CodingStandard/composer.json
packages/CodingStandard/src/Sniffs/Commenting/VarConstantCommentSniff.php
packages/CodingStandard/src/Sniffs/Debug/DebugFunctionCallSniff.php
packages/CodingStandard/src/Sniffs/Naming/AbstractClassNameSniff.php
packages/CodingStandard/src/Sniffs/Naming/ExceptionNameSniff.php
packages/CodingStandard/src/Sniffs/Naming/InterfaceNameSniff.php
packages/CodingStandard/src/Sniffs/Naming/TraitNameSniff.php
packages/CodingStandard/tests/Sniffs/Naming/ExceptionName/ExceptionNameSniffTest.php
packages/CodingStandard/tests/Sniffs/Naming/ExceptionName/correct/correct.php.inc
packages/CodingStandard/tests/Sniffs/Naming/ExceptionName/wrong/wrong-fixed.php.inc
packages/CodingStandard/tests/Sniffs/Naming/ExceptionName/wrong/wrong.php.inc

[CodingStandard] readme

---

easy-coding-standard.neon
packages/PackageBuilder/src/HttpKernel/AbstractCliKernel.php
packages/PackageBuilder/src/Neon/Loader/NeonLoader.php
packages/PackageBuilder/src/Neon/NeonLoaderAwareKernelTrait.php
packages/PackageBuilder/tests/Adapter/Nette/GeneralContainerFactoryTest.php
packages/PackageBuilder/tests/Adapter/Nette/GeneratorContainerFactorySource/config.neon
packages/PackageBuilder/tests/Adapter/Symfony/AppKernel.php
packages/PackageBuilder/tests/Adapter/Symfony/Parameter/ParameterProviderSource/Neon/included-config.neon
packages/PackageBuilder/tests/Adapter/Symfony/Parameter/ParameterProviderSource/Neon/including-config.neon
packages/PackageBuilder/tests/Adapter/Symfony/Parameter/ParameterProviderSource/Yaml/included-config.yml
packages/PackageBuilder/tests/Adapter/Symfony/Parameter/ParameterProviderSource/Yaml/including-config.yml
packages/PackageBuilder/tests/Adapter/Symfony/Parameter/ParameterProviderTest.php
packages/PackageBuilder/tests/Adapter/Symfony/config/services.yml
packages/PackageBuilder/tests/Composer/VendorDirProviderTest.php
phpstan.neon

- allow including in `*.yaml`
- allow including in `*.neon`
- add `NeonLoaderAwareKernelTrait` for neon loading in AppKernel

[PackageBuilder] improve configs

---

packages/EasyCodingStandard/bin/easy-coding-standard.php
packages/PackageBuilder/src/Console/Style/SymfonyStyleFactory.php
packages/PackageBuilder/tests/Console/Style/SymfonyStyleFactoryTest.php

[EasyCodingStandard] throw nicer exception on Container build fail

---

easy-coding-standard.neon
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/packages/Configuration/src/Configuration.php
packages/EasyCodingStandard/packages/SniffRunner/tests/Application/FileProcessorTest.php
packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php
packages/EasyCodingStandard/tests/Indentation/IndentationSource/config-with-spaces-indentation.neon
packages/EasyCodingStandard/tests/Indentation/IndentationSource/config-with-tabs-indentation.neon
packages/EasyCodingStandard/tests/Indentation/IndentationTest.php

[EasyCodingStandard] allow indentation config

---

composer.json
packages/Statie/composer.json
packages/Statie/src/Amp/AmpLinkDecorator.php
packages/Statie/src/Amp/HtmlToAmpConvertor.php
packages/Statie/src/Cache/CacheFactory.php
packages/Statie/src/Exception/Amp/NonHtmlFileException.php
packages/Statie/src/Renderable/RenderableFilesProcessor.php
packages/Statie/tests/Amp/HtmlToAmpConvertorTest.php

[Statie] improve AMP

---

packages/CodingStandard/tests/Sniffs/AbstractSniffTestCase.php
packages/EasyCodingStandard/bin/easy-coding-standard.php
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/ChangedFilesDetector.php
packages/PackageBuilder/src/Configuration/ConfigFilePathHelper.php
packages/Statie/bin/statie
packages/SymbioticController/src/Adapter/Nette/Template/TemplateRenderer.php

file_exists actually means file_or_directory_exists

file_exists() -> is_file() [Closes #246]

---

packages/PackageBuilder/src/Configuration/ConfigFilePathHelper.php
packages/PackageBuilder/tests/Configuration/ConfigFilePathHelperTest.php

ie. `ecs --config c:\config.neon`
How to test it?

[PackageBuilder] support for absolute path in --config

---

packages/Statie/packages/FlatWhite/src/Latte/LatteRenderer.php
packages/Statie/packages/FlatWhite/tests/Latte/LatteRendererSource/expectedCode.latte
packages/Statie/packages/FlatWhite/tests/Latte/LatteRendererSource/latteWithCodeToHighlight.latte
packages/Statie/src/Renderable/Latte/LatteFileDecorator.php
packages/Statie/src/Renderable/Markdown/MarkdownFileDecorator.php
packages/Statie/tests/Renderable/Latte/LatteDecoratorTest.php

Follow up to improvements in #256

[Statie] Fix Latte rendering for latte code blocks

---

.travis.yml
composer.json
easy-coding-standard.neon
packages/CodingStandard/.travis.yml
packages/EasyCodingStandard/.travis.yml
packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/config/php71-checkers.neon
packages/EasyCodingStandard/config/psr2-checkers.neon
packages/EasyCodingStandard/packages/Configuration/src/CheckerConfigurationNormalizer.php
packages/EasyCodingStandard/packages/Configuration/src/Exception/NoCheckersLoadedException.php
packages/EasyCodingStandard/packages/Configuration/tests/ConfigurationNormalizerTest.php
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/EasyCodingStandard/src/DependencyInjection/CompilerPass/CollectorCompilerPass.php
packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php
packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtensionGuardian.php
packages/PackageBuilder/.travis.yml
packages/PackageBuilder/src/Neon/Loader/NeonLoader.php
packages/Statie/.travis.yml
packages/Statie/tests/Latte/Filter/GithubPrLinkFilterProviderTest.php
packages/SymbioticController/.travis.yml
packages/SymbioticController/tests/Adapter/Nette/Template/TemplateRendererTest.php

[EasyCodingStandard] inform about no checkers loaded + allow checker merging in configuration

---

easy-coding-standard.neon
packages/EasyCodingStandard/packages/Configuration/src/MutualCheckerExcluder.php
packages/EasyCodingStandard/packages/Configuration/tests/MutualCheckerExcluderTest.php
packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php

[EasyCodingStandard] MutualCheckerExcluder added

---

composer.json
easy-coding-standard.neon
packages/EasyCodingStandard/packages/ChangedFilesDetector/tests/ChangedFilesDetectorSource/OneClass.php
packages/EasyCodingStandard/tests/Finder/SourceFinderSource/Source/SomeClass.php
packages/SymbioticController/tests/Adapter/Nette/Application/PresenterFactorySource/ErrorPresenter.php
packages/SymbioticController/tests/Adapter/Nette/Application/PresenterFactorySource/SomePresenter.php

add SlamCsFixer\FinalInternalClassFixer

---

packages/Statie/packages/Amp/src/AmpLinkFileDecorator.php
packages/Statie/packages/Amp/tests/AmpLinkFileDecoratorTest.php

[Statie] fixed to not decorate when amp disabled

---

packages/Statie/src/Renderable/Latte/LatteFileDecorator.php

[Statie] fixed ability to set layout for posts

---

packages/CodingStandard/src/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer.php
packages/CodingStandard/tests/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer/Test.php
packages/CodingStandard/tests/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer/correct/correct6.php.inc

[CodingStandard] fix StandaloneLineInMultilieArray with comments

---

packages/CodingStandard/src/Sniffs/DependencyInjection/NoClassInstantiationSniff.php
packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyle.php
packages/EasyCodingStandard/tests/Console/Style/EasyCodingStandardStyleTest.php

To save your :eyes:  from pain

[EasyCodingStandard] less argessive fail

---

easy-coding-standard.neon
packages/CodingStandard/README.md
packages/CodingStandard/src/Fixer/ClassNotation/PropertyAndConstantSeparationFixer.php
packages/CodingStandard/src/Fixer/Property/ArrayPropertyDefaultValueFixer.php
packages/CodingStandard/src/Fixer/TokenBuilder.php
packages/CodingStandard/src/Sniffs/Commenting/VarConstantCommentSniff.php
packages/CodingStandard/src/Sniffs/DependencyInjection/NoClassInstantiationSniff.php
packages/CodingStandard/src/Sniffs/Property/DynamicPropertySniff.php
packages/CodingStandard/src/Tokenizer/ArrayTokensAnalyzer.php
packages/CodingStandard/src/Tokenizer/ClassTokensAnalyzer.php
packages/CodingStandard/src/Tokenizer/DocBlockAnalyzer.php
packages/CodingStandard/src/Tokenizer/DocBlockFinder.php
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/Test.php
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/fixed/fixed.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/fixed/fixed3.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/fixed/fixed4.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/wrong/wrong.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/wrong/wrong2.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/wrong/wrong3.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/wrong/wrong4.php.inc
packages/EasyCodingStandard/config/symplify-checkers.neon
packages/EasyCodingStandard/src/Error/Error.php
packages/EasyCodingStandard/src/Error/ErrorCollector.php
packages/EasyCodingStandard/tests/Console/Style/EasyCodingStandardStyleTest.php
packages/EasyCodingStandard/tests/Error/ErrorTest.php
phpstan.neon

Closes #336
- `ArrayPropertyDefaultValueFixer` make use of `TokensAnalyzer`

[CodingStandard] Fixer property constant separation

---

packages/CodingStandard/src/Fixer/Php/ClassStringToClassConstantFixer.php
packages/EasyCodingStandard/src/Application/Application.php

[EasyCodingStandards] Parse error reporting.

---

easy-coding-standard.neon
packages/CodingStandard/README.md
packages/CodingStandard/src/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer.php
packages/CodingStandard/src/Fixer/ClassNotation/PropertyAndConstantSeparationFixer.php
packages/CodingStandard/src/Tokenizer/ClassTokensAnalyzer.php
packages/CodingStandard/tests/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer/Test.php
packages/CodingStandard/tests/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer/fixed/fixed.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer/fixed/fixed2.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer/wrong/wrong.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer/wrong/wrong2.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/Test.php
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/fixed/fixed5.php.inc
packages/CodingStandard/tests/Fixer/ClassNotation/PropertyAndConstantSeparationFixer/wrong/wrong5.php.inc

[CodingStandard] add property and method separation fixer

---

README.md
packages/EasyCodingStandard/config/clean-code.neon

See https://www.tomasvotruba.cz/blog/2017/09/18/4-simple-checkers-for-coding-standard-haters-but-clean-code-lovers/

[EasyCodingStandard] add clean-code set

---

README.md
ecs.neon
packages/CodingStandard/README.md
packages/CodingStandard/src/Fixer/Commenting/AnnotateMagicContainerGetterFixer.php
packages/CodingStandard/tests/Fixer/ClassNotation/LastPropertyAndFirstMethodSeparationFixer/Test.php
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/Test.php
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/fixed/fixed.php.inc
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/fixed/fixed2.php.inc
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/fixed/fixed3.php.inc
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/wrong/wrong.php.inc
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/wrong/wrong2.php.inc
packages/CodingStandard/tests/Fixer/Commenting/AnnotatedMagicContainerGetterFixer/wrong/wrong3.php.inc
packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/SniffRunner/tests/Sniff/Finder/SniffFinderTest.php
packages/EasyCodingStandard/tests/Finder/SourceFinderTest.php
packages/PackageBuilder/README.md
packages/Statie/README.md
packages/Statie/packages/SimilarPosts/tests/Latte/Filter/SimilarPostsFilterTest.php
packages/Statie/packages/SimilarPosts/tests/SimilarPostsResolverTest.php
packages/Statie/tests/Output/FileSystemWriterTest.php
packages/Statie/tests/Renderable/File/FileFactoryTest.php
packages/Statie/tests/Renderable/File/FileTest.php
packages/Statie/tests/Renderable/Routing/RouteFileDecoratorTest.php
packages/SymbioticController/README.md

[CodingStandard] annotated magic gets fixer

---

README.md
packages/EasyCodingStandard/packages/Configuration/src/Configuration.php
packages/EasyCodingStandard/src/Application/Application.php
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php

[EasyCodingStandard] add --no-progress-bar option [closes #348], add --no-error-table [closes #357]

---

packages/CodingStandard/README.md
packages/CodingStandard/packages/FixerTokenWrapper/src/AbstractVariableWrapper.php
packages/CodingStandard/packages/FixerTokenWrapper/src/Naming/ClassFqnResolver.php
packages/CodingStandard/packages/FixerTokenWrapper/src/PropertyWrapper.php
packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/src/Tokenizer/ClassTokensAnalyzer.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/Test.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/correct/correct.php.inc
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/fixed/fixed2.php.inc
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/wrong/wrong2.php.inc
phpstan.neon

[CodingStandard] PropertyNameMatchingTypeFixer - add custom matching fnmatch

---

packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php
packages/EasyCodingStandard/src/Skipper.php
packages/EasyCodingStandard/src/Validator/CheckerTypeValidator.php
packages/EasyCodingStandard/tests/Validator/CheckerTypeValidatorTest.php

Validate excluded checkers

---

easy-coding-standard.neon
packages/CodingStandard/.travis.yml
packages/CodingStandard/README.md
packages/CodingStandard/packages/FixerTokenWrapper/src/NameAnalyzer.php
packages/CodingStandard/packages/FixerTokenWrapper/src/Naming/ClassFqnResolver.php
packages/CodingStandard/packages/FixerTokenWrapper/src/Naming/Name.php
packages/CodingStandard/packages/FixerTokenWrapper/src/Naming/NameAnalyzer.php
packages/CodingStandard/src/Fixer/Import/ImportNamespacedNameFixer.php
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/Test.php
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed2.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed3.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed4.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed5.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed6.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed7.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong2.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong3.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong4.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong5.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong6.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong7.php.inc
packages/EasyCodingStandard/.travis.yml
packages/EasyCodingStandard/config/symplify-checkers.neon
packages/EasyCodingStandard/packages/FixerRunner/src/ChangedLinesDetector.php
packages/PackageBuilder/.travis.yml
packages/Statie/.travis.yml
packages/Tokemon/README.md
phpstan.neon

[CodingStandard] ImportFixer

---

packages/CodingStandard/src/Sniffs/DependencyInjection/NoClassInstantiationSniff.php

[CodingStandard] skip new in bins bootstraps

---

.travis.yml
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php

It is possible composer script run don't work as expected while iffed in travis
Reference
- http://steven.casagrande.io/articles/travis-ci-and-if-statements/
- https://github.com/travis-ci/travis-ci/issues/1066
- https://github.com/travis-ci/travis-ci/issues/8752

test travis

---

packages/CodingStandard/packages/FixerTokenWrapper/src/DocBlockWrapper.php
packages/CodingStandard/src/Fixer/Commenting/RemoveUselessDocBlockFixer.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/Test.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed8.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong8.php.inc

[CodingStandard] fix edge case for RemoveUselessDocBlockFixer

---

packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/src/Error/Error.php
packages/PackageBuilder/tests/Adapter/Symfony/Parameter/ParameterProviderTest.php
packages/Statie/tests/Renderable/PostFilesProcessorTest.php

backport form master: https://github.com/Symplify/Symplify/commit/893d94bcbfaa78930687d081db30e1a9c66a34ce
will resolve https://github.com/Symplify/Symplify/issues/453

removed unnecessary dependency

---

packages/CodingStandard/src/Sniffs/Debug/CommentedOutCodeSniff.php
packages/CodingStandard/tests/Sniffs/Debug/CommentedOutCode/CommentedOutCodeSniffTest.php
packages/CodingStandard/tests/Sniffs/Debug/CommentedOutCode/wrong/wrong2.php.inc
packages/CodingStandard/tests/Sniffs/Debug/CommentedOutCode/wrong/wrong5.php.inc
packages/EasyCodingStandard/config/common/control-structures.neon
packages/EasyCodingStandard/packages/SniffRunner/src/File/File.php
packages/EasyCodingStandard/packages/SniffRunner/src/File/FileFactory.php
packages/EasyCodingStandard/packages/SniffRunner/src/Parser/FileToTokensParser.php
packages/TokenRunner/src/Wrapper/SnifferWrapper/ClassWrapper.php
phpstan.neon

[EasyCodingStandard] Allow warnings as error for specific sniffs

---

packages/TokenRunner/src/ReflectionDocBlock/Tag/TolerantParam.php
packages/TokenRunner/src/ReflectionDocBlock/Tag/TolerantReturn.php

[TokenRunner] Remove implementation from TolerantReturn and TolerantParam

---

packages/EasyCodingStandard/src/Application/Application.php
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyle.php

Thanks for inspiration @carusogabriel !

[EasyCodingStandard] ecs console style cleanup

---

packages/ChangelogLinker/src/Worker/ShortenReferencesWorker.php
packages/CodingStandard/src/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer.php
packages/EasyCodingStandard/packages/FixerRunner/src/Application/FixerFileProcessor.php
packages/EasyCodingStandard/packages/SniffRunner/src/Application/SniffFileProcessor.php
packages/EasyCodingStandard/src/Console/Command/ShowCommand.php
packages/EasyCodingStandard/src/Error/ErrorSorter.php
packages/Statie/packages/FlatWhite/src/Latte/LatteRenderer.php
packages/Statie/packages/Generator/src/Latte/Filter/RelatedItemsFilter.php
packages/Statie/src/FileSystem/FileFinder.php
packages/Statie/src/Latte/Filter/GithubPrLinkFilterProvider.php
packages/Statie/src/Latte/Filter/TimeFilterProvider.php
packages/Statie/src/Renderable/MarkdownFileDecorator.php
tests/PHPUnit/Listener/ClearLogAndCacheTestListener.php

While we can't find a Sniff for that :construction:

[Symplify] Return type closure

---

README.md

A feel grammar and struct changes to make our `README.md` cleaner :smile:

[Symplify] Improve README.md

---

packages/EasyCodingStandard/README.md

Fixed some relatives paths and clean up extra lines

[EasyCodingStandard] Improve README.md

---

packages/GitWrapper/README.md

Remove extra lines, fix types of block of codes and important title with `H2`.

[GitWrapper] Improve README.md

---

LICENSE
packages/BetterReflectionDocBlock/LICENSE
packages/ChangelogLinker/LICENSE
packages/PackageBuilder/LICENSE
packages/Statie/LICENSE
packages/TokenRunner/LICENSE

As [suggested](https://github.com/Symplify/Symplify/pull/553#issuecomment-354838199) by @TomasVotruba in #553

Update LICENSE year forever

---

packages/Statie/src/FileSystem/FileFinder.php

Fixes https://github.com/pehapkari/pehapkari.cz/issues/370

Convert Windows directory separator to normal slash

---

packages/EasyCodingStandard/packages/Configuration/tests/ConflictingCheckerGuardTest.php
packages/EasyCodingStandard/packages/Configuration/tests/Guard/DuplicatedCheckersToIncludesGuardTest.php
packages/EasyCodingStandard/tests/Application/ApplicationTest.php

As [mentioned](https://github.com/Symplify/Symplify/pull/570#discussion_r161271887) in #570

Use @doesNotPerformAssertions in tests that have no assertion

---

packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php
packages/EasyCodingStandard/src/Skipper.php

[EasyCodingStandard] exclude_file now typoproof + fnamtch support added

---

composer.json
packages/CodingStandard/src/Fixer/Import/ImportNamespacedNameFixer.php
packages/CodingStandard/src/Fixer/LineLength/BreakMethodCallsFixer.php
packages/CodingStandard/src/Sniffs/DeadCode/UnusedPublicMethodSniff.php
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/BreakMethodCallsFixerTest.php
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/correct/correct.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/correct/correct2.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/fixed/fixed.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/fixed/fixed2.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/fixed/fixed3.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/wrong/wrong.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/wrong/wrong2.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakMethodCallsFixer/wrong/wrong3.php.inc
packages/EasyCodingStandard/config/symplify.neon
packages/EasyCodingStandard/packages/SniffRunner/tests/DI/SniffServiceRegistrationTest.php
packages/Statie/src/Renderable/LatteFileDecorator.php
packages/TokenRunner/src/Wrapper/FixerWrapper/MethodCallWrapper.php
packages/TokenRunner/tests/DocBlock/DescriptionAnalyzerTest.php
packages/TokenRunner/tests/DocBlock/ParamAndReturnTagAnalyzerTest.php
phpstan.neon

[CodingStandard] Add line breaker for method calls

---

packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/PropertyNameMatchingTypeFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/correct/correct4.php.inc

[CodingStandard] fix PropertyNameMatchingTypeFixer for self cases

---

easy-coding-standard.neon
packages/BetterReflectionDocBlock/README.md
packages/BetterReflectionDocBlock/src/CleanFormatter.php
packages/BetterReflectionDocBlock/src/DocBlockSerializerFactory.php
packages/BetterReflectionDocBlock/src/FixedSerializer.php
packages/BetterReflectionDocBlock/src/Renderer/OriginalSpacingCompleter.php
packages/BetterReflectionDocBlock/src/TagTraverser/TagTraverser.php
packages/BetterReflectionDocBlock/tests/FixedSerializerSource/expectedDocBlock.txt
packages/BetterReflectionDocBlock/tests/FixedSerializerSource/originalDocBlock.txt
packages/BetterReflectionDocBlock/tests/FixedSerializerTest.php
packages/BetterReflectionDocBlock/tests/Renderer/OriginalSpacingCompleterSource/messed/messed1.txt
packages/BetterReflectionDocBlock/tests/Renderer/OriginalSpacingCompleterSource/messed/messed2.txt
packages/BetterReflectionDocBlock/tests/Renderer/OriginalSpacingCompleterSource/original/original1.txt
packages/BetterReflectionDocBlock/tests/Renderer/OriginalSpacingCompleterSource/original/original2.txt
packages/BetterReflectionDocBlock/tests/Renderer/OriginalSpacingCompleterTest.php

[BetterReflectionDocBlock] add respect for inter-tag spaces

---

packages/BetterReflectionDocBlock/README.md
packages/BetterReflectionDocBlock/src/CleanFormatter.php
packages/BetterReflectionDocBlock/tests/CleanFormatterSource/expectedDocBlock.txt
packages/BetterReflectionDocBlock/tests/CleanFormatterSource/originalDocBlock.txt
packages/BetterReflectionDocBlock/tests/CleanFormatterTest.php
packages/CodingStandard/src/Fixer/Commenting/RemoveUselessDocBlockFixer.php

[BetterReflectionDocBlock] keep original preslash only and if it was present

---

packages/BetterReflectionDocBlock/README.md
packages/BetterReflectionDocBlock/src/CleanFormatter.php
packages/BetterReflectionDocBlock/src/Tag/TolerantParam.php
packages/BetterReflectionDocBlock/tests/CleanFormatterSource/expectedDocBlock.txt
packages/BetterReflectionDocBlock/tests/CleanFormatterSource/originalDocBlock.txt
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/RemoveUselessDocBlockFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/correct/correct13.php.inc

See https://github.com/symfony/symfony/pull/25859

[CodingStandard] fixing few edge cases based on Symfony and RemoveUselessDocBlockFixer

---

packages/BetterReflectionDocBlock/src/CleanFormatter.php
packages/BetterReflectionDocBlock/tests/CleanFormatterSource/expectedDocBlock.txt
packages/BetterReflectionDocBlock/tests/CleanFormatterSource/originalDocBlock.txt
packages/CodingStandard/src/Fixer/Commenting/RemoveEmptyDocBlockFixer.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/RemoveUselessDocBlockFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/correct/correct14.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed15.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed16.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed17.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong15.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong16.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong17.php.inc
packages/TokenRunner/src/DocBlock/DescriptionAnalyzer.php

[CodingStandard] add useless doc block fixer cases

---

packages/EasyCodingStandard/config/symfony.neon

[ECS] Remove duplicated rule

---

packages/Monorepo/src/PackageToRepositorySplitter.php
packages/Monorepo/src/Process/SplitProcessInfo.php
packages/Monorepo/src/RepositoryToPackageMerger.php

- https://stackoverflow.com/questions/37733820/running-a-background-task-using-symfony-process-without-having-to-wait-for-the-p
- https://stackoverflow.com/questions/29223825/run-an-asynchronous-php-task-using-symfony-process
---

[Monorepo] own async split

---

packages/Monorepo/README.md
packages/Monorepo/bin/monorepo
packages/Monorepo/src/Configuration/ConfigurationOptions.php
packages/Monorepo/src/Console/Command/BuildCommand.php
packages/Monorepo/src/Console/Command/SplitCommand.php
packages/Monorepo/src/Exception/Filesystem/DirectoryNotFoundException.php
packages/Monorepo/src/Exception/Git/InvalidGitRepositoryException.php

[Monorepo] allow own config path

---

packages/CodingStandard/tests/Fixer/Php/ClassStringToClassConstantFixer/ExistenceNotRequiredTest.php
packages/TokenRunner/src/Wrapper/FixerWrapper/MethodWrapper.php

Found with https://github.com/vlajos/misspell_fixer

Fix some mispellings

---

easy-coding-standard.neon
packages/Monorepo/README.md
packages/Monorepo/bin/monorepo
packages/Monorepo/src/Configuration/BashFiles.php
packages/Monorepo/src/Configuration/RepositoryGuard.php
packages/Monorepo/src/Console/Command/SplitCommand.php
packages/Monorepo/src/PackageToRepositorySplitter.php
packages/Monorepo/src/Process/ProcessFactory.php
packages/Monorepo/src/Worker/MoveHistoryWorker.php
packages/Monorepo/src/bash/git-subsplit.sh

Closes #630 
- move `git subsplit` here, so the install is not needed
- add estimave progress bar for `history move`

[Monorepo] bundle subsplit with package

---

packages/Monorepo/src/PackageToRepositorySplitter.php
packages/Monorepo/src/Process/ProcessFactory.php

[Monorepo] move creating split process to ProcessFactory, report exception on Split bash fail

---

composer.json
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/src/Console/Application.php
packages/Statie/composer.json
packages/Statie/src/Console/Application.php

Done it the simple way. Doing it via DI configuration would be lot more verbose.

Output program name and version, fixes #579

---

packages/CodingStandard/tests/Fixer/LineLength/BreakArrayListFixer/BreakArrayListFixerTest.php
packages/CodingStandard/tests/Fixer/LineLength/BreakArrayListFixer/fixed/fixed3.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakArrayListFixer/wrong/wrong3.php.inc
packages/EasyCodingStandard/config/symplify.neon

[EasyCodingStandard] add missing BreakArrayListFixer to symplify.neon set

---

composer.json
packages/BetterReflectionDocBlock/composer.json
packages/BetterReflectionDocBlock/src/CleanFormatter.php
packages/BetterReflectionDocBlock/src/DependencyInjection/BetterReflectionDocBlockKernel.php
packages/BetterReflectionDocBlock/src/DependencyInjection/ContainerFactory.php
packages/BetterReflectionDocBlock/src/DocBlock/ArrayResolver.php
packages/BetterReflectionDocBlock/src/DocBlockSerializerFactory.php
packages/BetterReflectionDocBlock/src/config/services.yml
packages/BetterReflectionDocBlock/tests/AbstractContainerAwareTestCase.php
packages/BetterReflectionDocBlock/tests/CleanFormatterTest.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapper.php
phpstan.neon

Cherry picked improvements from #680

 [BetterReflectionDocBlock] decoupling + clean composer deps 

---

packages/EasyCodingStandard/src/Yaml/CheckerTolerantYamlFileLoader.php

[ECS] Fix CheckerTolerantYamlFileLoader (closes #681)

---

composer.json
packages/CodingStandard/composer.json
packages/CodingStandard/tests/PHPUnit/Constraint/FixedSameStringsConstraint.php
packages/CodingStandard/tests/bootstrap.php
packages/EasyCodingStandard/composer.json
packages/TokenRunner/composer.json
phpstan.neon
tests/PHPUnit/Listener/ClearLogAndCacheTestListener.php
tests/bootstrap.php

Follow up to #618 
Thanks @carusogabriel for initial PR
After https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3526

Bump to PHPUnit 7

---

packages/CodingStandard/README.md
packages/CodingStandard/src/Sniffs/CleanCode/ForbiddenReferenceSniff.php
packages/CodingStandard/tests/Sniffs/CleanCode/ForbiddenReferenceSniff/ForbiddenReferenceSniffTest.php
packages/CodingStandard/tests/Sniffs/CleanCode/ForbiddenReferenceSniff/wrong/wrong.php.inc
packages/EasyCodingStandard/config/symplify.yml
packages/Statie/packages/FlatWhite/src/Latte/LatteRenderer.php

[CodingStandard] Add forbidden reference Sniff

---

packages/EasyCodingStandard/bin/ecs-container.php
packages/EasyCodingStandard/src/Console/Application.php

After all, this is all that's being left to do for https://github.com/Symplify/Symplify/issues/683 as it turns out you use DI Yaml loader instead of standalone Yaml component, which already does rest of the points

Autodiscover yaml too

---

easy-coding-standard.yml
packages/BetterReflectionDocBlock/src/CleanFormatter.php
packages/TokenRunner/src/DocBlock/ParamAndReturnTagAnalyzer.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapper.php
packages/TokenRunner/src/Wrapper/FixerWrapper/MethodWrapper.php

With EarlyReturn practice, we can reduce function's complexity and nesting levels :smile:

Reduce function cyclomatic complexity

---

packages/EasyCodingStandard/bin/ecs
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/EasyCodingStandard/src/config/external-services.yml
packages/Statie/bin/statie
packages/Statie/src/config/external-services.yml
packages/TokenRunner/src/Wrapper/FixerWrapper/ClassWrapper.php

[ECS] Make error message more verbose

---

easy-coding-standard.yml
packages/CodingStandard/src/Fixer/Import/ImportNamespacedNameFixer.php
packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/Cache/CacheFactory.php
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/ChangedFilesDetector.php
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/config/services.yml
packages/EasyCodingStandard/packages/Configuration/src/Configuration.php
packages/EasyCodingStandard/packages/FixerRunner/src/Application/FixerFileProcessor.php
packages/EasyCodingStandard/packages/FixerRunner/src/Parser/FileToTokensParser.php
packages/EasyCodingStandard/packages/SniffRunner/src/Application/SniffFileProcessor.php
packages/EasyCodingStandard/packages/SniffRunner/src/File/FileFactory.php
packages/EasyCodingStandard/packages/SniffRunner/src/Parser/FileToTokensParser.php
packages/EasyCodingStandard/packages/SniffRunner/tests/Error/ErrorSorterTest.php
packages/EasyCodingStandard/packages/SniffRunner/tests/Parser/FileToTokensParserTest.php
packages/EasyCodingStandard/src/Application/Application.php
packages/EasyCodingStandard/src/Console/Output/CheckCommandReporter.php
packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyle.php
packages/EasyCodingStandard/src/Contract/Application/DualRunAwareFileProcessorInterface.php
packages/EasyCodingStandard/src/Contract/Application/FileProcessorInterface.php
packages/EasyCodingStandard/src/Error/Error.php
packages/EasyCodingStandard/src/Error/ErrorAndDiffCollector.php
packages/EasyCodingStandard/src/Error/ErrorFactory.php
packages/EasyCodingStandard/src/Error/FileDiff.php
packages/EasyCodingStandard/src/Error/FileDiffFactory.php
packages/EasyCodingStandard/src/FileSystem/CachedFileLoader.php
packages/EasyCodingStandard/tests/Console/Style/EasyCodingStandardStyleTest.php
packages/EasyCodingStandard/tests/Error/ErrorTest.php

- fix formating of performance table
**Before**
**After**
---
- fix missing green headline as in SymfonyStyle manualy defined
**Before**
**After**

Improve speed by caching, remove slow spots thanks to Blackfire

---

packages/EasyCodingStandard/packages/ChangedFilesDetector/src/FileHashComputer.php

Hi,
if I'm not mistaken, this should also detect ".yaml" files, right? (Following #698)

[ECS] Detect changes properly also in .yaml files

---

packages/PackageBuilder/src/Console/ExceptionRenderer.php
packages/PackageBuilder/tests/Console/ExceptionRendererTest.php

[PackageBuilder] Add ExceptionRenderer tests

---

easy-coding-standard.yml
packages/EasyCodingStandard/bin/ecs
packages/PackageBuilder/README.md
packages/PackageBuilder/src/Console/ThrowableRenderer.php
packages/PackageBuilder/tests/Console/ThrowableRendererTest.php
packages/Statie/bin/statie
phpstan.neon

- ref #713         
- as pre-step to Error handling

[PackageBuilder] rename ExceptionRenderer to ThrowableRender 

---

packages/PackageBuilder/src/Console/ThrowableRenderer.php
packages/PackageBuilder/tests/Console/ThrowableRendererTest.php

[PackageBuilder] ThrowableRenderer - add support for Error

---

easy-coding-standard.yml
packages/PackageBuilder/tests/Console/ThrowableRendererTest.php

- follow up to #732
- include verbosity test for Error

[PackageBuilder] Improve Throwable renderer tests

---

CHANGELOG.md

Based on using it to find information

Make Changelog nicer

---

composer.json
packages/CodingStandard/composer.json
packages/CodingStandard/src/Fixer/LineLength/BreakNewInstanceArgumentsFixer.php
packages/CodingStandard/tests/Fixer/LineLength/BreakNewInstanceArgumentsFixer/BreakNewInstanceArgumentsFixerTest.php
packages/CodingStandard/tests/Fixer/LineLength/BreakNewInstanceArgumentsFixer/config.yml
packages/CodingStandard/tests/Fixer/LineLength/BreakNewInstanceArgumentsFixer/fixed/fixed.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakNewInstanceArgumentsFixer/fixed/fixed2.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakNewInstanceArgumentsFixer/wrong/wrong.php.inc
packages/CodingStandard/tests/Fixer/LineLength/BreakNewInstanceArgumentsFixer/wrong/wrong2.php.inc
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/src/FileSystem/CachedFileLoader.php
packages/EasyCodingStandard/src/config/external-services.yml
packages/EasyCodingStandardTester/src/Testing/AbstractCheckerTestCase.php
packages/TokenRunner/composer.json

[CodingStandard] Add BreakNewInstanceArgumentsFixer Fixer

---

easy-coding-standard.yml
packages/EasyCodingStandard/src/Console/Output/CheckCommandReporter.php
packages/EasyCodingStandard/src/DependencyInjection/EasyCodingStandardKernel.php
packages/EasyCodingStandard/src/Skipper.php
packages/EasyCodingStandard/src/config/config.yml
packages/EasyCodingStandard/src/config/services.yml
packages/EasyCodingStandard/tests/SkipperRemoveUnusedTest.php
packages/EasyCodingStandard/tests/SkipperTest.php

[ECS] Fix missed unreported skips

---

packages/EasyCodingStandard/src/Yaml/CheckerConfigurationGuardian.php
packages/EasyCodingStandard/src/Yaml/CheckerServiceParametersShifter.php
packages/EasyCodingStandard/tests/Yaml/CheckerServiceParametersShifterTest.php

[ECS] Fix ParameterShifter for null + add tests

---

CHANGELOG.md
packages/BetterReflectionDocBlock/src/Tag/TolerantVar.php

Ref https://travis-ci.org/rectorphp/rector/builds/363894759?utm_source=github_status&utm_medium=notification

fix TolerantVar tag consistency

---

packages/BetterReflectionDocBlock/tests/Renderer/OriginalSpacingCompleterTest.php
packages/CodingStandard/tests/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer/StandaloneLineInMultilineArrayFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/BlockPropertyCommentFixer/BlockPropertyCommentFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveEmptyDocBlockFixer/RemoveEmptyDocBlockFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer/RemoveSuperfluousDocBlockWhitespaceFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/RemoveUselessDocBlockFixerTest.php
packages/CodingStandard/tests/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer/RequireFollowedByAbsolutePathFixerTest.php
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/ConfiguredImportNamespacedNameFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/ClassNameSuffixByParentFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/MagicMethodsNamingFixer/MagicMethodsNamingFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/PropertyNameMatchingTypeFixerTest.php
packages/CodingStandard/tests/Fixer/Php/ClassStringToClassConstantFixer/ClassStringToClassConstantFixerTest.php
packages/CodingStandard/tests/Fixer/Php/ClassStringToClassConstantFixer/ExistenceNotRequiredTest.php
packages/CodingStandard/tests/Fixer/Property/ArrayPropertyDefaultValueFixer/ArrayPropertyDefaultValueFixerTest.php
packages/CodingStandard/tests/Fixer/Solid/FinalInterfaceFixer/ConfiguredTest.php
packages/CodingStandard/tests/Fixer/Solid/FinalInterfaceFixer/FinalInterfaceFixerTest.php
packages/CodingStandard/tests/Fixer/Strict/BlankLineAfterStrictTypesFixer/BlankLineAfterStrictTypesFixerTest.php
packages/EasyCodingStandard/tests/Yaml/CheckerTolerantYamlFileLoader/DefinitionsTest.php
packages/Statie/tests/Renderable/Configuration/ConfigurationDecoratorTest.php
packages/Statie/tests/Renderable/Routing/RouteFileDecoratorTest.php
packages/Statie/tests/Utils/PathNormalizerTest.php
packages/TokenRunner/tests/DocBlock/DescriptionAnalyzerTest.php
packages/TokenRunner/tests/DocBlock/ParamAndReturnTagAnalyzerTest.php

Ref https://github.com/rectorphp/rector/pull/401

Apply ArrayToYieldDataProviderRector

---

packages/EasyCodingStandard/packages/SniffRunner/src/File/File.php
packages/EasyCodingStandard/src/Skipper.php
packages/EasyCodingStandard/tests/Skipper/SkipperRemoveUnusedTest.php
packages/EasyCodingStandardTester/README.md

[ECS] Skipper - remove global code skip from unused

---

packages/Statie/packages/Generator/src/Configuration/GeneratorConfiguration.php
packages/Statie/src/config/config.yml

With resolved parameter mergin this is now easy.
It fixes the case when people need to change one parameter, but need to copy everything: 
https://github.com/TomasVotruba/tomasvotruba.cz/blob/a73793a47b279b80051834e9adbb57a21df7d132/source/_data/generators.yml#L25

[Statie] fix 'posts' parameter overide of Generator

---

packages/BetterPhpDocParser/src/PhpDocModifier.php
packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfo.php
packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfoFactory.php
packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/BetterPhpDocParser/tests/PhpDocModifier/PhpDocModifierSource/after3.txt
packages/BetterPhpDocParser/tests/PhpDocModifier/PhpDocModifierSource/before.txt
packages/BetterPhpDocParser/tests/PhpDocModifier/PhpDocModifierSource/before2.txt
packages/BetterPhpDocParser/tests/PhpDocModifier/PhpDocModifierSource/before3.txt
packages/BetterPhpDocParser/tests/PhpDocModifier/PhpDocModifierTest.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoPrinterSource/doc9.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoPrinterTest.php
packages/CodingStandard/src/Fixer/Commenting/RemoveUselessDocBlockFixer.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapper.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapperFactory.php

Based on Rector feedback and dupicated code
- add `PhpDocModifier` class

Better phpdoc parser improvements

---

packages/EasyCodingStandard/config/symfony-risky.yml
packages/EasyCodingStandard/config/symfony.yml

Source: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.11/src/RuleSet.php

Fix inconsistencies in symfony/symfony-risky rules

---

packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfo.php
packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfoFactory.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoSource/doc.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoTest.php

Based on feedback from upgrade in Rector: https://github.com/rectorphp/rector/pull/446

[BetterPhpDocParser] add hasTag() to PhpDocInfo and other improvements

---

packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfo.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoSource/doc.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoTest.php

Based on feedback from upgrade in Rector: rectorphp/rector#446

[BetterPhpDocParser] add getParamTypeNodeByName()

---

packages/BetterPhpDocParser/composer.json
packages/BetterPhpDocParser/src/PhpDocModifier.php
packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfo.php
packages/BetterPhpDocParser/src/PhpDocParser/PhpDocInfoFactory.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoTest.php
phpstan.neon

Based on feedback from upgrade in Rector: rectorphp/rector#446

[BetterPhpDocParser] add replaceTagByAnother() method

---

packages/BetterPhpDocParser/src/PhpDocModifier.php
packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoSource/expected-replaced-tag.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoSource/expected-with-replaced-tag.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoSource/expected-with-replaced-type.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoSource/test-tag.txt
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoTest.php

Based on feedback from upgrade in Rector: rectorphp/rector#446

[BetterPhpDocParser] fix replaceTagByAnother() method

---

packages/BetterPhpDocParser/README.md
packages/BetterPhpDocParser/src/Contract/PhpDocInfoDecoratorInterface.php
packages/BetterPhpDocParser/src/DependencyInjection/CompilerPass/CollectDecoratorsToPhpDocInfoFactoryCompilerPass.php
packages/BetterPhpDocParser/src/PhpDocInfo/AbstractPhpDocInfoDecorator.php
packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfo.php
packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfoFactory.php
packages/BetterPhpDocParser/src/PhpDocModifier.php
packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/BetterPhpDocParser/tests/PhpDocModifier/PhpDocModifierTest.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoPrinterTest.php
packages/BetterPhpDocParser/tests/PhpDocParser/PhpDocInfoTest.php
packages/CodingStandard/src/Fixer/Import/ImportNamespacedNameFixer.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapper.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapperFactory.php
phpstan.neon

Based on feedback from upgrade in Rector: rectorphp/rector#446

[BetterPhpDocPaser] Add AbstractPhpDocInfoDecorator

---

packages/CodingStandard/src/Fixer/LineLength/LineLengthFixer.php
packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/LineLengthFixerTest.php
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/correct/correct10.php.inc
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/correct/correct9.php.inc
packages/TokenRunner/src/Analyzer/FixerAnalyzer/TokenSkipper.php
packages/TokenRunner/src/Transformer/FixerTransformer/LineLengthTransformer.php

LineLenghtFixer - keep body functions untouched

---

packages/CodingStandard/src/Fixer/Import/ImportNamespacedNameFixer.php
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/ImportNamespacedNameFixerTest.php
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed16.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed17.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/fixed/fixed18.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong16.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong17.php.inc
packages/CodingStandard/tests/Fixer/Import/ImportNamespacedNameFixer/wrong/wrong18.php.inc
phpstan.neon

ImportNamespacedNameFixer: add support for union and array types + uniquate doc types

---

packages/ChangelogLinker/README.md
packages/ChangelogLinker/bin/changelog-linker
packages/ChangelogLinker/src/ChangelogApplication.php
packages/ChangelogLinker/src/Worker/ReleaseReferencesWorker.php
packages/ChangelogLinker/tests/Worker/BracketsAroundReferencesWorker/BracketsAroundReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/DiffLinksToVersionsWorker/DiffLinksToVersionsWorkerTest.php
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/LinksToReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/ReleaseReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/Source/after/01.md
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/Source/after/02.md
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/Source/before/01.md
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/Source/before/02.md
packages/ChangelogLinker/tests/Worker/ShortenReferencesWorker/ShortenReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/UserReferencesWorker/UserReferencesWorkerTest.php

[ChangelogLinker] Add Unreleased to last tagged version feature

---

packages/ChangelogLinker/src/LinkAppender.php
packages/ChangelogLinker/src/Worker/LinkifyWorker.php
packages/ChangelogLinker/src/Worker/LinksToReferencesWorker.php
packages/ChangelogLinker/src/config/config.yml
packages/ChangelogLinker/src/config/services.yml
packages/ChangelogLinker/tests/Worker/LinkifyWorker/LinkifyWorkerTest.php
packages/ChangelogLinker/tests/Worker/LinkifyWorker/Source/after/01.md
packages/ChangelogLinker/tests/Worker/LinkifyWorker/Source/before/01.md
packages/ChangelogLinker/tests/Worker/LinkifyWorker/Source/config.yml

[ChangelogLinker] Add LinkifyWorker

---

packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/LineLengthFixerTest.php
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/correct/correct12.php.inc
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/fixed/fixed18.php.inc
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/wrong/wrong18.php.inc
packages/TokenRunner/src/Analyzer/FixerAnalyzer/IndentDetector.php
packages/TokenRunner/src/Transformer/FixerTransformer/LineLengthTransformer.php

LineLengthSniff: Initial support for tokens with newlines

---

composer.json
packages/ChangelogLinker/src/Worker/BracketsAroundReferencesWorker.php
packages/CodingStandard/composer.json
packages/CodingStandard/src/Sniffs/CleanCode/CognitiveComplexitySniff.php
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/config/clean-code.yml
packages/EasyCodingStandard/config/common/docblock.yml
packages/PackageBuilder/tests/Console/ThrowableRendererTest.php
packages/Statie/src/Renderable/RouteFileDecorator.php
packages/TokenRunner/composer.json

And make use of few new Fixers: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v2.12.0

Bump to PHP CS Fixer 2.12

---

packages/EasyCodingStandard/packages/FixerRunner/src/Application/FixerFileProcessor.php
packages/EasyCodingStandard/packages/SniffRunner/src/Application/SniffFileProcessor.php
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/EasyCodingStandard/src/Console/Command/ShowCommand.php

[ECS] Fix single file processing

---

packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/FixerRunner/src/WhitespacesFixerConfigFactory.php
packages/EasyCodingStandard/src/config/config.yml
packages/EasyCodingStandard/tests/Issues/Issue816Test.php
packages/EasyCodingStandard/tests/Issues/config/config816.yml
packages/EasyCodingStandard/tests/Issues/fixed/fixed816.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong816.2.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong816.php.inc

[EasyCodingStandard] Add support for line_ending configuration

---

composer.json
ecs.yml
packages/BetterPhpDocParser/composer.json
packages/ChangelogLinker/composer.json
packages/CodingStandard/composer.json
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandardTester/composer.json
packages/MonorepoBuilder/composer.json
packages/MonorepoBuilder/src/Command/BumpInterdependencyCommand.php
packages/MonorepoBuilder/src/Command/MergeCommand.php
packages/MonorepoBuilder/src/Command/PackageAliasCommand.php
packages/MonorepoBuilder/src/Command/ValidateVersionsCommand.php
packages/MonorepoBuilder/src/Composer/Section.php
packages/MonorepoBuilder/src/FileSystem/JsonFileManager.php
packages/MonorepoBuilder/src/PackageComposerFinder.php
packages/Statie/composer.json
packages/TokenRunner/composer.json

[MonorepoBuilder] Add new commands

---

changelog-linker.yml
composer.json
packages/ChangelogLinker/README.md
packages/ChangelogLinker/bin/changelog-linker
packages/ChangelogLinker/bin/changelog-linker-container.php
packages/ChangelogLinker/composer.json
packages/ChangelogLinker/src/Command/DumpMergesCommand.php
packages/ChangelogLinker/src/Exception/Github/GithubApiException.php
packages/ChangelogLinker/src/Github/GithubApi.php
packages/ChangelogLinker/src/config/config.yml
packages/ChangelogLinker/src/config/services.yml
packages/ChangelogLinker/tests/ChangelogApplicationTest/Source/after/01.md
packages/ChangelogLinker/tests/Worker/DiffLinksToVersionsWorker/Source/after/01.md
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/after/01.md
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/after/02.md
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/after/03.md
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/before/01.md

[ChangelogLinker] Add dump merges command

---

changelog-linker.yml
packages/ChangelogLinker/README.md
packages/ChangelogLinker/config/basic.yml
packages/ChangelogLinker/src/ChangelogApplication.php
packages/ChangelogLinker/src/Configuration/Configuration.php
packages/ChangelogLinker/src/DependencyInjection/ChangelogLinkerKernel.php
packages/ChangelogLinker/src/DependencyInjection/CompilerPass/AutowireWorkersCompilerPass.php
packages/ChangelogLinker/src/Worker/DiffLinksToVersionsWorker.php
packages/ChangelogLinker/src/Worker/LinkifyWorker.php
packages/ChangelogLinker/src/Worker/LinksToReferencesWorker.php
packages/ChangelogLinker/src/config/services.yml
packages/ChangelogLinker/tests/AbstractWorkerTestCase.php
packages/ChangelogLinker/tests/ChangelogApplicationTest/ChangelogApplicationTest.php
packages/ChangelogLinker/tests/ChangelogApplicationTest/Source/config.yml
packages/ChangelogLinker/tests/Worker/BracketsAroundReferencesWorker/BracketsAroundReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/BracketsAroundReferencesWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/DiffLinksToVersionsWorker/DiffLinksToVersionsWorkerTest.php
packages/ChangelogLinker/tests/Worker/DiffLinksToVersionsWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/LinkifyWorker/LinkifyWorkerTest.php
packages/ChangelogLinker/tests/Worker/LinkifyWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/LinksToReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/ReleaseReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/ReleaseReferencesWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/ShortenReferencesWorker/ShortenReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/ShortenReferencesWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/UserReferencesWorker/Source/config.yml
packages/ChangelogLinker/tests/Worker/UserReferencesWorker/UserReferencesWorkerTest.php

[ChangelogLinker] Change Worker registration from implicit to explicit

---

.travis.yml

[WIP] Fixes monorepo splitting by travis cron job

---

packages/ChangelogLinker/src/ChangeTree/ChangeSorter.php
packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php
packages/ChangelogLinker/src/Console/Output/DumpMergesReporter.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactoryTest.php
packages/ChangelogLinker/tests/Console/Output/DumpMergesReporterTest.php
packages/ChangelogLinker/tests/Console/Output/WithTagsSource/expected1.md
packages/ChangelogLinker/tests/Console/Output/WithTagsSource/expected2.md
packages/ChangelogLinker/tests/Console/Output/WithTagsSource/expected3.md
packages/ChangelogLinker/tests/Console/Output/WithTagsTest.php
packages/ChangelogLinker/tests/Git/GitCommitDateTagResolverTest.php

- fix ordering
- fix tests that Travis is unable to handle

[ChangelogLinker] Improve --in-tags option

---

packages/Statie/src/Contract/Renderable/FileDecoratorInterface.php
packages/Statie/src/DependencyInjection/CompilerPass/CollectorCompilerPass.php
packages/Statie/src/Renderable/ConfigurationDecorator.php
packages/Statie/src/Renderable/LatteFileDecorator.php
packages/Statie/src/Renderable/MarkdownFileDecorator.php
packages/Statie/src/Renderable/RenderableFilesProcessor.php
packages/Statie/src/Renderable/RouteFileDecorator.php
packages/Statie/src/config/services.yml

Basically reverts https://github.com/Symplify/Symplify/commit/13e40d1783b9ddad008450e8f155fda582df6569#diff-e23b538c68b90a19203298759ed1750f
- to allow extending without overriding whole config
- https://www.tomasvotruba.cz/blog/2018/06/14/collector-pattern-for-dummies/

 [Statie] Return collector-based approach to FileDecorators, with priorities

---

packages/CodingStandard/README.md
packages/CodingStandard/src/Fixer/Naming/ClassNameSuffixByParentFixer.php
packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/ConfiguredTest.php
packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/configured-config.yml
packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/fixed/fixed5.php.inc
packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/wrong/wrong5.php.inc

...to allow keeping originals.
Closes #898

[CodingStandard] Add 'extra_parent_types_to_suffixes' option to ClassNameSuffixByParentFixer

---

CHANGELOG.md
packages/ChangelogLinker/README.md
packages/ChangelogLinker/src/ChangelogApplication.php
packages/ChangelogLinker/src/ChangelogLinker.php
packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php
packages/ChangelogLinker/src/Console/Command/RunCommand.php
packages/ChangelogLinker/src/DependencyInjection/CompilerPass/CollectorCompilerPass.php
packages/ChangelogLinker/src/Github/GithubApi.php
packages/ChangelogLinker/src/Worker/LinksToReferencesWorker.php
packages/ChangelogLinker/tests/AbstractWorkerTestCase.php
packages/ChangelogLinker/tests/ChangelogApplicationTest/ChangelogApplicationTest.php
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/LinksToReferencesWorkerTest.php
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/after/03.md
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/after/04.md
packages/ChangelogLinker/tests/Worker/LinksToReferencesWorker/Source/before/04.md

[ChangelogLinker] Add --linkfy option to dump-merges command

---

composer.json
monorepo-builder.yml
packages/ChangelogLinker/composer.json
packages/LatteToTwigConverter/.gitattributes
packages/LatteToTwigConverter/.gitignore
packages/LatteToTwigConverter/.travis.yml
packages/LatteToTwigConverter/LICENSE
packages/LatteToTwigConverter/README.md
packages/LatteToTwigConverter/composer.json
packages/LatteToTwigConverter/phpunit.xml

[LatteToTwigConverter] Prepare the package

---

packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/FixerRunner/src/WhitespacesFixerConfigFactory.php
packages/EasyCodingStandard/src/config/external-services.yml
packages/EasyCodingStandard/tests/Issues/Issue923Test.php
packages/EasyCodingStandard/tests/Issues/config/config923.yml
packages/EasyCodingStandard/tests/Issues/fixed/fixed923.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong923.php.inc

[EasyCodingStandard] Add test case for #923

---

packages/ChangelogLinker/tests/ChangelogDumper/WithTagsSource/expected1-split.md
packages/ChangelogLinker/tests/ChangelogDumper/WithTagsSource/expected2-split.md
packages/ChangelogLinker/tests/ChangelogDumper/WithTagsSource/expected3-split.md
packages/ChangelogLinker/tests/ChangelogDumper/WithTagsTest.php
packages/PackageBuilder/src/FileSystem/FileSystem.php
packages/PackageBuilder/tests/FileSystem/FileSystemTest.php

[PackageBuilder] Add FileSystem with separateFilesAndDirectories() method

---

packages/Statie/packages/Latte/src/Renderable/LatteFileDecorator.php
packages/Statie/packages/Latte/tests/Renderable/LatteFileDecoratorSource/contact.latte
packages/Statie/packages/Latte/tests/Renderable/LatteFileDecoratorSource/expectedFileWithHighlightedCode.html
packages/Statie/packages/Latte/tests/Renderable/LatteFileDecoratorSource/fileWithHighlightedCode.latte
packages/Statie/packages/Latte/tests/Renderable/LatteFileDecoratorTest.php
packages/Statie/packages/Twig/src/Renderable/TwigFileDecorator.php
packages/Statie/src/Renderable/CodeBlocksProtector.php

Follow up to #977
Just for latte

[Statie] Fix latte code rendering in the post contents

---

packages/Statie/packages/Generator/tests/GeneratorSource/expected/post-with-latte-blocks-expected.html
packages/Statie/packages/Latte/src/Renderable/LatteFileDecorator.php
packages/Statie/packages/Twig/src/Renderable/TwigFileDecorator.php

 [Statie] Cleanup Twig and Latte FileDecorators, decouple constants

---

ecs.yml
packages/PackageBuilder/README.md
packages/PackageBuilder/src/Yaml/ParametersMergingYamlLoader.php
packages/PackageBuilder/tests/Yaml/ParametersMergingYamlLoader/ParametersMergingYamlLoaderTest.php
packages/PackageBuilder/tests/Yaml/ParametersMergingYamlLoader/Source/config.yml
packages/PackageBuilder/tests/Yaml/ParametersMergingYamlLoader/Source/imported-file.yml

```php
$parametersMergingYamlLoader = new Symplify\PackageBuilder\Yaml\ParametersMergingYamlLoader;
$parameterBag = $parametersMergingYamlLoader->loadParameterBagFromFile(__DIR__ . '/config.yml');
var_dump($parameterBag); 
// instance of "Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface"
```

[PackageBuilder] Add StandaloneParametersMergingYamlFileLoader

---

packages/ChangelogLinker/src/ChangeTree/ChangeSorter.php
packages/ChangelogLinker/tests/ChangeTree/ChangeSorterTogetherTest.php
packages/PackageBuilder/README.md

[ChangelogLinker] Fix ChangeSorter for tags

---

packages/PackageBuilder/README.md
packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass.php
packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/AutoBindParametersCompilerPassTest.php
packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/Source/AutoBindParametersKernel.php
packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/Source/ServiceWithAutowiredParameter.php
packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/Source/config.yml
packages/PackageBuilder/tests/DependencyInjection/DefinitionCollector/DefinitionCollectorTest.php
packages/PackageBuilder/tests/DependencyInjection/DefinitionCollector/Source/Collected.php
packages/PackageBuilder/tests/DependencyInjection/DefinitionCollector/Source/CollectedInterface.php
packages/PackageBuilder/tests/DependencyInjection/DefinitionCollector/Source/Collector.php
packages/PackageBuilder/tests/DependencyInjection/DefinitionCollector/Source/CollectorInterface.php
packages/PackageBuilder/tests/DependencyInjectionSource/CollectedInterface.php

[PackageBuilder] Add AutoBindParametersCompilerPass [closes #994]

---

README.md
packages/ChangelogLinker/src/DependencyInjection/ChangelogLinkerKernel.php
packages/ChangelogLinker/src/config/services.yml
packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/config/services.yml
packages/EasyCodingStandard/src/DependencyInjection/EasyCodingStandardKernel.php
packages/EasyCodingStandard/src/config/services.yml
packages/MonorepoBuilder/packages/Split/src/config/config.yml
packages/MonorepoBuilder/packages/Split/src/config/services.yml
packages/MonorepoBuilder/src/DependencyInjection/MonorepoBuilderKernel.php
packages/MonorepoBuilder/src/config/config.yml
packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass.php
packages/Statie/packages/Twig/src/config/services.yml
packages/Statie/src/DependencyInjection/StatieKernel.php

Follow up to #998 - make use of it in the code

make use of AutoBindParametersCompilerPass

---

packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/PropertyNameMatchingTypeFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/fixed/fixed7.php.inc
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/wrong/wrong7.php.inc

 [CS] Fix UPPERCASE start name for PropertyNameMatchingTypeFixer

---

packages/EasyCodingStandard/tests/Issues/Issue1024Test.php
packages/EasyCodingStandard/tests/Issues/config/config1024.yml
packages/EasyCodingStandard/tests/Issues/fixed/fixed1024.php.inc
packages/EasyCodingStandard/tests/Issues/fixed/fixed1024_2.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong1024.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong1024_2.php.inc

[ECS] Add test case for 1024

---

changelog-linker.yml
composer.json
packages/BetterPhpDocParser/composer.json
packages/ChangelogLinker/composer.json
packages/ChangelogLinker/src/Console/Input/PriorityResolver.php
packages/CodingStandard/composer.json
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandardTester/composer.json
packages/LatteToTwigConverter/composer.json
packages/MonorepoBuilder/README.md
packages/MonorepoBuilder/composer.json
packages/MonorepoBuilder/src/Configuration/Option.php
packages/MonorepoBuilder/src/Console/Command/BumpInterdependencyCommand.php
packages/MonorepoBuilder/src/Console/Command/PackageAliasCommand.php
packages/MonorepoBuilder/src/Console/Command/ReleaseCommand.php
packages/MonorepoBuilder/src/DependencyInjection/CompilerPass/CollectorCompilerPass.php
packages/MonorepoBuilder/src/EventSubscriber/ValidateBeforeCommandEventSubscriber.php
packages/MonorepoBuilder/src/Exception/Git/InvalidGitVersionException.php
packages/MonorepoBuilder/src/Exception/Validator/InvalidComposerJsonSetupException.php
packages/MonorepoBuilder/src/FileSystem/ComposerJsonProvider.php
packages/MonorepoBuilder/src/Utils/Utils.php
packages/MonorepoBuilder/src/Validator/SourcesPresenceValidator.php
packages/MonorepoBuilder/src/config/services.yml
packages/MonorepoBuilder/tests/Utils/UtilsTest.php
packages/PackageBuilder/composer.json
packages/Statie/composer.json
packages/TokenRunner/composer.json
phpstan.neon

```bash
vendor/bin/monorepo-builder release v4.7.0
vendor/bin/monorepo-builder release v4.7.0 --dry-run # won't run git commands
```

[MB] Add release command

---

packages/ChangelogLinker/src/ChangeTree/Resolver/PackageResolver.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactory/AbstractChangeFactoryTest.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactory/Resolver/CategoryResolverTest.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactory/Resolver/PackageResolverTest.php

[ChangelogLinker] Fix package name resolving

---

packages/ChangelogLinker/src/ChangeTree/ChangeFactory.php
packages/ChangelogLinker/src/DependencyInjection/ChangelogLinkerKernel.php
packages/ChangelogLinker/src/DependencyInjection/CompilerPass/DetectParametersCompilerPass.php
packages/ChangelogLinker/src/Exception/Git/InvalidGitRemoteException.php
packages/ChangelogLinker/src/Github/GithubRepositoryFromRemoteResolver.php
packages/ChangelogLinker/tests/Github/GithubRepositoryFromRemoteResolverTest.php

 [CL] Fix detection of Repository url from Git

---

packages/CodingStandard/src/Fixer/Naming/MagicMethodsNamingFixer.php

Hi Tomas, I believe wrong class is referenced here.

[CS] Fix wrong class reference to MagicMethodCasingFixer

---

composer.json
packages/MonorepoBuilder/README.md
packages/MonorepoBuilder/src/Console/Command/BumpInterdependencyCommand.php
packages/MonorepoBuilder/src/Console/Command/MergeCommand.php
packages/MonorepoBuilder/src/Console/Command/ReleaseCommand.php
packages/MonorepoBuilder/src/Console/Command/ValidateCommand.php
packages/MonorepoBuilder/src/Console/Reporter/ConflictingPackageVersionsReporter.php
packages/MonorepoBuilder/src/Exception/MissingComposerJsonFilesException.php
packages/MonorepoBuilder/src/FileSystem/ComposerJsonProvider.php
packages/MonorepoBuilder/src/FileSystem/JsonFileManager.php
packages/MonorepoBuilder/src/Guard/ComposerJsonFilesGuard.php
packages/MonorepoBuilder/src/Package/PackageComposerJsonMerger.php
packages/MonorepoBuilder/src/Validator/SourcesPresenceValidator.php
packages/MonorepoBuilder/src/VersionValidator.php
packages/MonorepoBuilder/src/config/services.yml
packages/MonorepoBuilder/tests/AbstractConfigAwareContainerTestCase.php
packages/MonorepoBuilder/tests/DevMasterAliasUpdater/DevMasterAliasUpdaterTest.php
packages/MonorepoBuilder/tests/FileSystem/JsonFileManager/JsonFileManagerTest.php
packages/MonorepoBuilder/tests/InterdependencyUpdater/InterdependencyUpdaterTest.php
packages/MonorepoBuilder/tests/Package/PackageComposerJsonMergerTest.php
packages/MonorepoBuilder/tests/Package/Source/config.yml
packages/MonorepoBuilder/tests/Package/Source/package-two.json
packages/MonorepoBuilder/tests/VersionValidator/VersionValidatorTest.php
phpstan.neon

[MB] Add validation into merge command [closes #1071]

---

packages/ChangelogLinker/README.md
packages/ChangelogLinker/src/Configuration/Option.php
packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php
packages/ChangelogLinker/src/Exception/DeprecatedException.php
packages/ChangelogLinker/src/Github/GithubApi.php
packages/ChangelogLinker/src/Guzzle/ResponseFormatter.php
packages/ChangelogLinker/src/config/config.yml
packages/ChangelogLinker/tests/Analyzer/IdsAnalyzer/IdsAnalyzerTest.php
packages/ChangelogLinker/tests/Analyzer/IdsAnalyzer/Source/ShopsysChangelog.md
packages/ChangelogLinker/tests/Analyzer/IdsAnalyzer/Source/SomeFileWithAnotherType.md
packages/ChangelogLinker/tests/Github/GithubApiTest.php
packages/PHPStanExtensions/README.md

- use "GITHUB_TOKEN=var" instead of "--token var"

[ChangelogLinker] Resolve new pull-request from merge date instead of id

---

packages/ChangelogLinker/composer.json
packages/ChangelogLinker/src/ChangeTree/ChangeFactory.php
packages/ChangelogLinker/src/ChangeTree/Resolver/PackageResolver.php
packages/ChangelogLinker/src/ChangelogFormatter.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactory/ChangeFactoryTest.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactory/config/config.yml

 [ChangelogLinker] Fix aliasing spaced and category resolving with spacing and slash

---

packages/EasyCodingStandard/tests/Issues/Issue1097Test.php
packages/EasyCodingStandard/tests/Issues/config/config1097.yml
packages/EasyCodingStandard/tests/Issues/fixed/fixed1097.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong1097.php.inc

Is this correct?
related: #1097

test(ECS): add Issue1097 test case

---

CHANGELOG.md
packages/MonorepoBuilder/src/Console/Command/ReleaseCommand.php
packages/TokenRunner/tests/DependencyInjection/TokenRunnerKernel.php

 [MonorepoBuilder] Add Unreleased to version and date in CHANGELOG.md to "release" command

---

packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php
packages/EasyCodingStandard/packages/Configuration/src/Configuration.php
packages/EasyCodingStandard/src/Console/Command/FindCommand.php
packages/MonorepoBuilder/packages/Init/src/Command/InitCommand.php
packages/MonorepoBuilder/src/Console/Command/BumpInterdependencyCommand.php
packages/MonorepoBuilder/src/Console/Command/ReleaseCommand.php
packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/AutoBindParametersCompilerPassTest.php
packages/Statie/src/Console/Command/GenerateCommand.php
phpstan.neon

Caused by new Symfony versions

static fixes

---

packages/MonorepoBuilder/src/Console/Command/MergeCommand.php
packages/MonorepoBuilder/src/Package/PackageComposerJsonMerger.php
packages/MonorepoBuilder/tests/Package/PackageComposerJsonMergerTest.php
packages/MonorepoBuilder/tests/Package/Source/config.yml
packages/MonorepoBuilder/tests/Package/Source/package-two.json
packages/PackageBuilder/src/Console/ShellCode.php

 [MonorepoBuilder] Fix duplicated require and require-dev items

---

packages/PackageBuilder/src/FileSystem/SmartFileInfo.php
packages/PackageBuilder/tests/FileSystem/SmartFileInfoTest.php
packages/Statie/packages/Latte/tests/LatteRendererTest.php
packages/Statie/packages/Latte/tests/Renderable/LatteFileDecoratorTest.php
packages/Statie/packages/Twig/tests/Renderable/TwigFileDecoratorTest.php
packages/Statie/packages/Twig/tests/TwigRendererTest.php
packages/Statie/tests/Renderable/Configuration/ConfigurationFileDecoratorTest.php
packages/Statie/tests/Renderable/Markdown/MarkdownFileDecoratorTest.php
packages/Statie/tests/Renderable/Routing/RouteFileDecoratorTest.php

[PackageBuilder] Fix SmartFileInfo invalid dir argument

---

packages/Statie/packages/Generator/src/Renderable/File/GeneratorFileFactory.php

Ref https://github.com/TomasVotruba/tomasvotruba.cz/issues/514

[Statie] Fix relative path to generated file 

---

packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/SniffRunner/src/File/File.php
packages/EasyCodingStandard/src/Skipper.php
packages/EasyCodingStandard/tests/Skipper/SkipperRemoveUnusedTest.php
packages/EasyCodingStandard/tests/Skipper/SkipperTest.php
packages/EasyCodingStandard/tests/Skipper/skip.php.inc
packages/EasyCodingStandard/tests/Skipper/skip.yml

[ECS] Add way to suppress specific sniff message

---

packages/CodingStandard/src/Fixer/Php/ClassStringToClassConstantFixer.php

Use early return to prevent unwanted autoload
Ref #1149

[CodingStandard] Improve ClassStringToClassConstantFixer class type matching

---

.travis.yml
composer.json
packages/CodingStandard/config/symplify.yml
packages/CodingStandard/src/Fixer/LineLength/LineLengthFixer.php
packages/CodingStandard/src/Fixer/Php/ClassStringToClassConstantFixer.php
packages/CodingStandard/src/Sniffs/DependencyInjection/NoClassInstantiationSniff.php
packages/PackageBuilder/src/Types/ClassLikeExistenceChecker.php
packages/TokenRunner/src/Wrapper/FixerWrapper/ClassWrapper.php
packages/TokenRunner/src/Wrapper/FixerWrapper/ClassWrapperFactory.php
packages/TokenRunner/src/config/services.yml
phpstan.neon

See foundings bellow
Closes #1149

[CodingStandard] Explore checking of classes with missing parent

---

packages/PackageBuilder/src/Composer/VendorDirProvider.php

Ref https://github.com/rectorphp/rector/issues/732

[PackageBuilder] Make VendorDirProvider work for global installs

---

packages/CodingStandard/README.md
packages/CodingStandard/src/Sniffs/Architecture/PreferredClassSniff.php
packages/CodingStandard/tests/Sniffs/Architecture/PreferredClassSniff/PreferredClassSniffTest.php
packages/CodingStandard/tests/Sniffs/Architecture/PreferredClassSniff/config.yml
packages/CodingStandard/tests/Sniffs/Architecture/PreferredClassSniff/wrong/wrong.php.inc
packages/CodingStandard/tests/Sniffs/Architecture/PreferredClassSniff/wrong/wrong2.php.inc
packages/CodingStandard/tests/Sniffs/Architecture/PreferredClassSniff/wrong/wrong3.php.inc

[CodingStandard] Add PreferredClassSniff 

---

composer.json
packages/BetterPhpDocParser/composer.json
packages/ChangelogLinker/composer.json
packages/CodingStandard/composer.json
packages/CodingStandard/src/Fixer/Commenting/RemoveUselessDocBlockFixer.php
packages/CodingStandard/src/Fixer/LineLength/LineLengthFixer.php
packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/src/Fixer/Order/MethodOrderByTypeFixer.php
packages/CodingStandard/src/Fixer/Php/ClassStringToClassConstantFixer.php
packages/CodingStandard/src/Fixer/Solid/FinalInterfaceFixer.php
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandardTester/composer.json
packages/LatteToTwigConverter/composer.json
packages/MonorepoBuilder/composer.json
packages/PHPStanExtensions/composer.json
packages/PackageBuilder/composer.json
packages/Statie/composer.json
packages/TokenRunner/composer.json

[CodingStandard] Simplify fixer configuration to make them readable

---

CHANGELOG.md
packages/ChangelogLinker/src/Analyzer/IdsAnalyzer.php
packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php
packages/ChangelogLinker/src/Github/GithubApi.php

[ChangelogLinker] Fix dump-merges for empty PR stack

---

ecs.yml
packages/ChangelogLinker/src/DependencyInjection/ChangelogLinkerKernel.php
packages/ChangelogLinker/src/config/services.yml
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/config/services.yml
packages/EasyCodingStandard/packages/FixerRunner/src/config/services.yml
packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyleFactory.php
packages/EasyCodingStandard/src/DependencyInjection/EasyCodingStandardKernel.php
packages/EasyCodingStandard/src/config/external-services.yml
packages/LatteToTwigConverter/src/DependencyInjection/LatteToTwigConverterKernel.php
packages/LatteToTwigConverter/src/config/services.yml
packages/MonorepoBuilder/src/DependencyInjection/MonorepoBuilderKernel.php
packages/MonorepoBuilder/src/config/services.yml
packages/PackageBuilder/README.md
packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutoReturnFactoryCompilerPass.php
packages/Statie/packages/Latte/src/LatteRenderer.php
packages/Statie/packages/Twig/src/config/services.yml
packages/Statie/src/DependencyInjection/StatieKernel.php
packages/Statie/src/config/external-services.yml
phpstan.neon

Based on https://www.tomasvotruba.cz/blog/2018/11/05/do-you-autowire-services-in-symfony-you-can-autowire-parameters-too/#how-far-can-we-push-autowiring-together

[Experimental][PackageBuilder] Add AutoReturnFactoryCompilerPass

---

packages/MonorepoBuilder/src/Package/PackageComposerJsonMerger.php
packages/MonorepoBuilder/tests/Package/PackageComposerJsonMergerTest.php
packages/MonorepoBuilder/tests/Package/SourceUniqueRepositories/package-one.json
packages/MonorepoBuilder/tests/Package/SourceUniqueRepositories/package-two.json

[MonorepoBuilder] Fix merging of duplicated items

---

packages/EasyCodingStandard/src/Application/Application.php
packages/EasyCodingStandard/src/Console/Application.php
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/MonorepoBuilder/src/Console/Command/MergeCommand.php
packages/MonorepoBuilder/src/Package/PackageComposerJsonMerger.php
packages/MonorepoBuilder/tests/Package/CombineStringsToArrayJsonMergerTest.php
packages/MonorepoBuilder/tests/Package/Source/config.yml
packages/MonorepoBuilder/tests/Package/SourceAutoloadSharedNamespaces/package-one.json
packages/MonorepoBuilder/tests/Package/SourceAutoloadSharedNamespaces/package-two.json
packages/PackageBuilder/src/Yaml/ParametersMerger.php

[MonorepoBuilder] Fix merging of scalar values in composer.json

---

packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/packages/FixerRunner/src/WhitespacesFixerConfigFactory.php
packages/EasyCodingStandard/src/Exception/Configuration/WhitespaceConfigurationException.php
packages/EasyCodingStandard/src/Finder/CheckerClassFinder.php

[ECS] Add support for 2 spaces indent

---

.travis.yml
packages/EasyCodingStandard/src/Application/Application.php

[ECS] Fix --no-progress-bar conflict with uninitialized advance

---

packages/MonorepoBuilder/packages/Init/templates/monorepo/monorepo-builder.yml

Fix typo in second package folder name

Fix typo in second package folder name in monorepo.yml

---

packages/ChangelogLinker/src/DependencyInjection/CompilerPass/DetectParametersCompilerPass.php
packages/ChangelogLinker/src/Git/GitCommitDateTagResolver.php
packages/MonorepoBuilder/packages/Release/src/Process/ProcessRunner.php
packages/MonorepoBuilder/packages/Split/src/Git/GitManager.php
phpstan.neon

Ref https://github.com/symfony/symfony/pull/27821

fix Symfony 4.2 compat

---

packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass.php

[PB] Fix AutowireSinglyImplementedCompilerPass for invalid Symfony definitions

---

packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/ParamReturnAndVarTagMalformsFixerTest.php
packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/fixed/fixed12.php.inc
packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/wrong/wrong12.php.inc
packages/EasyCodingStandard/src/Yaml/FileLoader/CheckerTolerantYamlFileLoader.php
packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutowireInterfacesCompilerPass.php
packages/PackageBuilder/src/Yaml/FileLoader/AbstractParameterImportsYamlFileLoader.php
packages/TokenRunner/src/DocBlock/MalformWorker/DuplicatedArrayMalformWorker.php

```diff
/**
- * @var string[]|array
+ * @var string[]
*/
private $allowedVariableNames = ['$this'];
```
Closes #1235

[CS] Add duplicated array type remover

---

packages/CodingStandard/src/Fixer/Property/BoolPropertyDefaultValueFixer.php
packages/CodingStandard/tests/Fixer/Property/BoolPropertyDefaultValueFixer/BoolPropertyDefaultValueFixerTest.php
packages/CodingStandard/tests/Fixer/Property/BoolPropertyDefaultValueFixer/Integration/simple.php.inc
packages/CodingStandard/tests/Fixer/Property/BoolPropertyDefaultValueFixer/config.yml
packages/EasyCodingStandardTester/src/Testing/IntegrationTestCaseTrait.php
packages/TokenRunner/src/Wrapper/FixerWrapper/DocBlockWrapper.php

[CS] Add BoolPropertyDefaultValueFixer

---

composer.json
packages/EasyCodingStandard/bin/ecs
packages/EasyCodingStandard/composer.json

[ECS] Add xdebug-handler to improve performance while xdebug is on

---

changelog-linker.yml
packages/MonorepoBuilder/packages/Release/src/ReleaseWorker/AbstractMutualDependencyReleaseWorker.php
packages/MonorepoBuilder/packages/Release/src/ReleaseWorker/SetCurrentMutualDependenciesReleaseWorker.php
packages/MonorepoBuilder/packages/Release/src/ReleaseWorker/SetNextMutualDependenciesReleaseWorker.php
packages/MonorepoBuilder/src/Console/Command/BumpInterdependencyCommand.php
packages/MonorepoBuilder/src/Console/Command/PropagateCommand.php
packages/MonorepoBuilder/src/DependencyUpdater.php
packages/MonorepoBuilder/tests/InterdependencyUpdater/InterdependencyUpdaterTest.php

43 s gif that tells the story
Closes #1244

[MB] Add PropagateCommand

---

packages/PackageBuilder/src/Configuration/LevelFileFinder.php

[PB] Improve LevelFileFinder exception reporting

---

packages/Autodiscovery/src/Doctrine/DoctrineEntityMappingAutodiscoverer.php
packages/Autodiscovery/src/FileSystem.php
packages/Autodiscovery/src/NamespaceDetector.php
packages/Autodiscovery/tests/DependencyInjection/AudiscoveryTestingKernel.php
packages/Autodiscovery/tests/Doctrine/DoctrineEntityAutodiscoverTest.php
packages/Autodiscovery/tests/KernelProjectDir/packages/ForTests/config/packages/doctrine/Context.Context.orm.xml
packages/Autodiscovery/tests/KernelProjectDir/packages/ForTests/config/packages/doctrine/Tag.Tag.orm.xml
phpstan.neon

 [Autodiscovery] Add xml Doctrine mapping discovery

---

packages/Statie/README.md
packages/Statie/packages/Generator/tests/GeneratorSource/source/_layouts/post.latte
packages/Statie/packages/Generator/tests/GeneratorSource/source/_posts/2016/2016-01-02-second-title.md
packages/Statie/packages/Generator/tests/GeneratorSource/source/_posts/2017-01-05-another-related-post.md
packages/Statie/packages/Generator/tests/GeneratorSource/source/_posts/2017-01-05-some-related-post.md
packages/Statie/packages/Generator/tests/GeneratorTest.php
packages/Statie/packages/Latte/tests/LatteFactoryTest.php
packages/Statie/packages/Twig/src/Renderable/TwigFileDecorator.php
packages/Statie/packages/Twig/tests/TwigFactory/TwigFactoryTest.php
packages/Statie/src/Renderable/RenderableFilesProcessor.php
packages/Statie/src/config/config.yml

[Statie] Configuring templating for user

---

CHANGELOG-4.md
packages/Statie/README.md
packages/Statie/packages/Generator/src/Configuration/GeneratorElementFactory.php
packages/Statie/src/Console/Command/CreatePostCommand.php
packages/Statie/src/Exception/Configuration/DuplicatedPostException.php
packages/Statie/src/FileSystem/CreatePostFileSystem.php
packages/Statie/src/config/config.yml
packages/Statie/templates/post/post.md
phpstan.neon

[Statie] Add create-post commad

---

packages/Autodiscovery/README.md
packages/Autodiscovery/src/Yaml/ExplicitToAutodiscoveryConverter.php
packages/Autodiscovery/src/Yaml/YamlKey.php
packages/Autodiscovery/tests/Yaml/Fixture/blog_post_votruba.yaml
packages/Autodiscovery/tests/Yaml/Fixture/short_tags.yaml

fixes https://github.com/Symplify/Symplify/issues/1292

autodiscovery should be autoconfigure

---

ecs.yml
packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/config/psr12.yml
packages/EasyCodingStandard/src/DependencyInjection/CompilerPass/RemoveExcludedCheckersCompilerPass.php
packages/EasyCodingStandard/src/Skipper.php
packages/EasyCodingStandard/src/config/external-services.yml
packages/EasyCodingStandard/tests/DependencyInjection/ExcludedCheckersSource/config.yml

Closes #1296
One step closer to better ux

[ECS] Move exclude_checkers to skip parameter

---

packages/Statie/src/Console/Command/InitCommand.php
packages/Statie/templates/travis-deploy/.travis.yml

[Statie] Add travis to InitCommand

---

packages/EasyCodingStandard/src/Skipper.php

[ECS] allow various format to skip

---

packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/Fixture/correct8.php.inc
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/PropertyNameMatchingTypeFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/Source/HardRock.php
phpstan.neon

[CodingStandard] Fix PropertyNameMatchingTypeFixer for double types

---

packages/CodingStandard/README.md
packages/CodingStandard/config/symplify.yml
packages/CodingStandard/src/Fixer/ControlStructure/PregDelimiterFixer.php
packages/CodingStandard/tests/Fixer/ControlStructure/PregDelimiterFixer/Fixture/function.php.inc
packages/CodingStandard/tests/Fixer/ControlStructure/PregDelimiterFixer/Fixture/static_call.php.inc
packages/CodingStandard/tests/Fixer/ControlStructure/PregDelimiterFixer/PregDelimiterFixerTest.php
packages/EasyCodingStandard/config/external-services.yml
packages/EasyCodingStandardTester/src/Testing/AbstractCheckerTestCase.php

[CodingStandard] Add PregDelimiterFixer

---

packages/CodingStandard/README.md
packages/CodingStandard/src/Fixer/Naming/CatchExceptionNameMatchingTypeFixer.php
packages/CodingStandard/tests/Fixer/Naming/CatchExceptionNameMatchingTypeFixer/CatchExceptionNameMatchingTypeFixerTest.php
packages/CodingStandard/tests/Fixer/Naming/CatchExceptionNameMatchingTypeFixer/Fixture/correct.php.inc
packages/CodingStandard/tests/Fixer/Naming/CatchExceptionNameMatchingTypeFixer/Fixture/wrong_to_fixed.php.inc
packages/CodingStandard/tests/Fixer/Naming/CatchExceptionNameMatchingTypeFixer/Source/DangerousException.php
packages/PackageBuilder/src/Console/HelpfulApplicationTrait.php

[CodingStandard] Add ExceptionNameMatchingTypeFixer

---

packages/FlexLoader/composer.json

[Flex Loader] Fix missing dependency Nette\Utils

---

packages/CodingStandard/README.md
packages/CodingStandard/src/Fixer/ControlStructure/PregDelimiterFixer.php
packages/CodingStandard/tests/Fixer/ControlStructure/PregDelimiterFixer/Fixture/concat_skip.php.inc
packages/CodingStandard/tests/Fixer/ControlStructure/PregDelimiterFixer/Fixture/function.php.inc
packages/CodingStandard/tests/Fixer/ControlStructure/PregDelimiterFixer/PregDelimiterFixerTest.php

[CodingStandard] Add flags support to PregDelimiterFixer + cover quotes + make configurable

---

packages/Statie/README.md
packages/Statie/packages/PostHeadlineLinker/config/services.yml
packages/Statie/packages/PostHeadlineLinker/src/EventSubscriber/DecoratePostHeadlinesEventSubscriber.php
packages/Statie/packages/PostHeadlineLinker/src/PostHeadlineLinker.php
packages/Statie/packages/PostHeadlineLinker/tests/PostHeadlineLinkerTest.php

[Statie] add post headline linker

---

composer.json
monorepo-builder.yml
packages/Autodiscovery/composer.json
packages/BetterPhpDocParser/composer.json
packages/ChangelogLinker/composer.json
packages/CodingStandard/composer.json
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandardTester/composer.json
packages/FlexLoader/composer.json
packages/LatteToTwigConverter/README.md
packages/LatteToTwigConverter/composer.json
packages/LatteToTwigConverter/config/config.yml
packages/LatteToTwigConverter/src/Command/ConvertCommand.php
packages/LatteToTwigConverter/src/Command/RenameCommand.php
packages/MonorepoBuilder/composer.json
packages/PHPStanExtensions/composer.json
packages/PackageBuilder/composer.json
packages/Statie/composer.json
packages/TokenRunner/composer.json

[LatteToTwigConverter] Add rename command

---

packages/LatteToTwigConverter/src/CaseConverter/FilterCaseConverter.php
packages/LatteToTwigConverter/src/CaseConverter/LoopsCaseConverter.php
packages/LatteToTwigConverter/src/CaseConverter/NClassMacroCaseConverter.php
packages/LatteToTwigConverter/src/CaseConverter/NMacrosCaseConverter.php
packages/LatteToTwigConverter/tests/LatteToTwigConverterTest.php
packages/LatteToTwigConverter/tests/Source/latte/filter_with_arguments.latte
packages/LatteToTwigConverter/tests/Source/latte/n-macro/n-class.latte
packages/LatteToTwigConverter/tests/Source/latte/n-macro/n-ifset.latte
packages/LatteToTwigConverter/tests/Source/latte/n-macro/n-inner-foreach.latte
packages/LatteToTwigConverter/tests/Source/twig/filter_with_arguments.twig
packages/LatteToTwigConverter/tests/Source/twig/n-macro/n-class.twig
packages/LatteToTwigConverter/tests/Source/twig/n-macro/n-ifset.twig
packages/LatteToTwigConverter/tests/Source/twig/n-macro/n-inner-foreach.twig

[LatteToTwigConverter] Add n:ifset, n:inner-foreach, n:class

---

packages/MonorepoBuilder/src/Package/PackageComposerJsonMerger.php

[MonorepoBuilder] Fix package classmap merging

---

packages/MonorepoBuilder/src/DependencyUpdater.php
packages/PackageBuilder/tests/Parameter/ParameterTypoProofreader/config.yml

[MB] Extend dependency updater to allow skip callback 

---

packages/ChangelogLinker/src/Worker/LinkifyWorker.php
packages/ChangelogLinker/tests/ChangelogLinker/ChangelogLinkerTest.php
packages/ChangelogLinker/tests/ChangelogLinker/Source/after/11.md
packages/ChangelogLinker/tests/ChangelogLinker/Source/before/11.md
packages/ChangelogLinker/tests/ChangelogLinker/Source/config.yml

[ChangelogLinker] link only full matching names

---

packages/Statie/templates/statie-website/gulpfile.js

This allows to run statie's gulp inside docker on Windows. I could also supply the Dockerfile and docker-compose file I'm using as a PR

[Statie] Listen on every address

---

packages/Statie/bin/statie
packages/Statie/composer.json

[Statie] Add xdebug-handler to improve performance

---

packages/MonorepoBuilder/src/Package/PackageComposerJsonMerger.php

[MonorepoBuilder] Resolve complete paths for 'exclude-from-classmap'

---

packages/PackageBuilder/src/FileSystem/SmartFileInfo.php
packages/Statie/packages/Migrator/src/Worker/ParametersAdder.php
packages/Statie/packages/Migrator/tests/AbstractProjectToStatieMigratorTest.php
packages/Statie/packages/MigratorJekyll/src/JekyllToStatieMigrator.php
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/after/source/_data/companies.yaml
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/after/source/_data/some_config.yml
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/after/statie.yaml
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/before/_data/companies.yaml

[Statie] Add parameter name by file to migrate-jekyll

---

packages/PackageBuilder/src/Http/BetterGuzzleClient.php

[PackageBuilder] Make BetterGuzzleClient pass on success code

---

packages/Statie/packages/MigratorJekyll/src/JekyllToStatieMigrator.php
packages/Statie/packages/MigratorJekyll/src/Worker/DashToUnderscoreParameterNameMigratorWorker.php
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/after/source/_data/some_config.yml
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/after/source/contact.twig
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/before/_data/some_config.yml
packages/Statie/packages/MigratorJekyll/tests/JekyllToStatieMigrator/Source/Fixture/before/contact.html
packages/Statie/templates/statie-website-twig/source/_snippets/footer.twig

[Statie] Add - to _ param name converter to migrate-jekyll

---

packages/FlexLoader/src/Flex/FlexPathsFactory.php
packages/FlexLoader/tests/Flex/FlexLoader/MicroKernelTraitTest.php
packages/FlexLoader/tests/Flex/FlexLoader/Source/MicroKernelTraitKernel.php
packages/FlexLoader/tests/Flex/FlexLoader/Source/project-dir-micro-kernel/config/parameters.yaml
packages/FlexLoader/tests/Flex/FlexLoader/Source/project-dir-micro-kernel/config/parameters_dev.yaml

Hi Tomáš,
sending PR fixing non-loaded parameters from default paths
Fixes #1370

[FlexLoader] Load parameters.* as well

---

packages/TokenRunner/src/Transformer/FixerTransformer/LineLengthTransformer.php

[CodingStandard] Fix LineLengthTransformer for short lines

---

packages/Autodiscovery/bin/autodiscovery
packages/ChangelogLinker/bin/changelog-linker
packages/EasyCodingStandard/bin/ecs
packages/LatteToTwigConverter/bin/latte-to-twig-converter
packages/MonorepoBuilder/bin/monorepo-builder
packages/Statie/bin/statie

Ref https://github.com/Symplify/Symplify/commit/5130e0287bb88e97d8c9438e0191de47348cf66c

make bin commands fail for error

---

composer.json
monorepo-builder.yml
packages/MonorepoBuilder/src/ComposerJsonDecorator/ReplaceSectionJsonDecorator.php
packages/MonorepoBuilder/src/Console/Command/MergeCommand.php

[MonorepoBuilder] Add replace section on merge

---

packages/MonorepoBuilder/config/config.yml

[MonorepoBuilder] Add suggest section to merge

---

packages/NeonToYamlConverter/src/NeonToYamlConverter.php

[NeonToYamlConvertor] fix %env conversion

---

packages/NeonToYamlConverter/README.md
packages/NeonToYamlConverter/src/ArrayParameterCollector.php
packages/NeonToYamlConverter/src/Command/ConvertCommand.php
packages/NeonToYamlConverter/src/Finder/NeonAndYamlFinder.php
packages/NeonToYamlConverter/src/NeonToYamlConverter.php
packages/NeonToYamlConverter/tests/MultipleFileSource/neon/parameters.neon
packages/NeonToYamlConverter/tests/MultipleFileSource/neon/services.neon
packages/NeonToYamlConverter/tests/MultipleFileSource/yaml/parameters.yaml
packages/NeonToYamlConverter/tests/MultipleFileSource/yaml/services.yaml
packages/NeonToYamlConverter/tests/MultipleFileTest.php
packages/NeonToYamlConverter/tests/NeonToYamlConverterTest.php
packages/NeonToYamlConverter/tests/Source/neon/parameters/skip_parameter_inline.neon
packages/NeonToYamlConverter/tests/Source/yaml/parameters/nested_parameter.yaml
packages/NeonToYamlConverter/tests/Source/yaml/parameters/skip_parameter_inline.yaml
packages/NeonToYamlConverter/tests/Source/yaml/services/arguments.yaml
packages/NeonToYamlConverter/tests/Source/yaml/services/basic.yaml
packages/NeonToYamlConverter/tests/Source/yaml/services/list.yaml
packages/PackageBuilder/src/Tests/AbstractKernelTestCase.php

[NeonToYamlConverter] Make parameter order independent, inline array params smart way

---

packages/Statie/packages/Tweeter/src/Tweet/PostTweet.php

Closes https://github.com/TomasVotruba/tomasvotruba.cz/issues/666

[Statie] Fix in-title url for similiar Tweet text

---

ecs.yml
packages/PHPStanExtensions/src/Php/Type/NativeFunctionDynamicFunctionReturnTypeExtension.php
packages/PHPStanExtensions/src/Rules/Classes/MatchingTypeConstantRule.php
packages/PHPStanExtensions/src/Symfony/Type/ContainerGetTypeExtension.php
packages/Statie/packages/Twig/tests/TwigFactory/TwigFactoryTest.php
packages/Statie/src/Application/StatieApplication.php
packages/Statie/src/FileSystem/FileFinder.php
packages/Statie/src/Renderable/File/AbstractFile.php
packages/Statie/tests/Application/StatieApplicationSource/expected-file.html
packages/Statie/tests/Application/StatieApplicationSource/source/file.md
packages/Statie/tests/Application/StatieApplicationTest.php
packages/Statie/tests/Templating/FilterProvider/GithubFilterProvider/GithubFilterProviderTest.php

[Statie] Fix missing .md file generation

---

packages/EasyCodingStandard/tests/Issues/Issue1107Test.php
packages/EasyCodingStandard/tests/Issues/config/config1107.yml
packages/EasyCodingStandard/tests/Issues/fixed/fixed1107.php.inc
packages/EasyCodingStandard/tests/Issues/wrong/wrong1107.php.inc

[EasyCodingStandard] Add test case for issue1107

---

packages/LatteToTwigConverter/src/CaseConverter/DateCaseConverter.php
packages/LatteToTwigConverter/src/CaseConverter/SprintfCaseConverter.php
packages/LatteToTwigConverter/tests/LatteToTwigConverterTest.php
packages/LatteToTwigConverter/tests/Source/latte/date.latte
packages/LatteToTwigConverter/tests/Source/latte/sprintf.latte
packages/LatteToTwigConverter/tests/Source/twig/date.twig
packages/LatteToTwigConverter/tests/Source/twig/nested_variable.twig
packages/LatteToTwigConverter/tests/Source/twig/sprintf.twig

[LatteToTwigConverter] Add date and sprintf support

---

packages/BetterPhpDocParser/packages/Attributes/src/Ast/AttributeAwareNodeFactory.php
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/Fixture/wrong21.php.inc
packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/RemoveUselessDocBlockFixerTest.php

[BetterPhpDocParser] Fix incorret intersection to union retype

---

composer.json
packages/BetterPhpDocParser/composer.json
packages/BetterPhpDocParser/packages/Attributes/src/Ast/AttributeAwareNodeFactory.php
packages/BetterPhpDocParser/packages/Attributes/tests/Ast/AttributeAwareNodeFactoryTest.php
packages/BetterPhpDocParser/src/Ast/NodeTraverser.php
packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php

[BetterPhpDocParser] add createFromNode() method

---

packages/BetterPhpDocParser/README.md
packages/MonorepoBuilder/src/ComposerJsonDecorator/AppenderComposerJsonDecorator.php
packages/MonorepoBuilder/tests/Package/AbstractMergeTestCase.php
packages/MonorepoBuilder/tests/Package/CombineStringsToArrayJsonMergerTest.php
packages/MonorepoBuilder/tests/Package/PackageComposerJsonMergerTest.php
packages/MonorepoBuilder/tests/Package/SourceUniqueRepositories/package-three.json

[MonorepoBuilder] Fix appended extra repository duplicate

---

composer.json
ecs.yml
packages/CodingStandard/config/symplify.yml
packages/CodingStandard/packages/TokenRunner/src/Analyzer/SnifferAnalyzer/Naming.php
packages/CodingStandard/src/Sniffs/Commenting/AnnotationTypeExistsSniff.php
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/config/php70.yml
packages/EasyCodingStandard/config/php71.yml
packages/EasyCodingStandard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsSource/checkers-parent.yml
packages/EasyCodingStandard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsTest.php

[CS] Bump to slevomat coding-standard 5.0

---

packages/EasyCodingStandard/packages/SniffRunner/src/File/File.php

Hello,
I had sniff class to report warning at error for closed the issue https://github.com/Symplify/Symplify/issues/1494

[EasyCodingStandard] raised error for PSR2 warning sniff

---

.gitattributes

Added docs and *.md to export-ginore for .gitattribute

---

packages/EasyCodingStandard/README.md

As asked in #1523 i added a list of tool integrations at the bottom of the README file.

Add list of tool integration

---

packages/Statie/packages/MigratorJekyll/config/config.yaml
packages/Statie/packages/MigratorSculpin/config/config.yaml
packages/Statie/src/Renderable/RouteFileDecorator.php

[Statie] Add custom `output_path` to generator elements

---

composer.json
packages/EasyCodingStandard/composer.json

Fixes #1557
Long term, code should be refactored to remove usage of deprecated classes.

Add psr/simple-cache as a dependency

---

packages/MonorepoBuilder/packages/Split/src/Git/GitManager.php

Handle if GITHUB_TOKEN is an empty string

---

packages/ChangelogLinker/src/DependencyInjection/CompilerPass/AddRepositoryUrlAndRepositoryNameParametersCompilerPass.php
packages/CodingStandard/packages/TokenRunner/tests/Analyzer/SniffAnalyzer/CognitiveComplexityAnalyzer/CognitiveComplexityAnalyzerTest.php
packages/CodingStandard/src/Fixer/Spacing/RemoveSpacingAroundModifierAndConstFixer.php
packages/CodingStandard/tests/Fixer/Spacing/RemoveSpacingAroundModifierAndConst/Fixture/wrong.php.inc
packages/CodingStandard/tests/Fixer/Spacing/RemoveSpacingAroundModifierAndConst/RemoveSpacingAroundModifierAndConstFixerTest.php
packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyle.php
packages/PackageBuilder/src/Composer/VendorDirProvider.php
phpstan.neon

```diff
class SomeClass
{
-    public     $protected;
+    public $protected;
-    protected     static     $value;
+    protected static $value;
-   private      const    VALUE = 5;
+   private const VALUE = 5;
}
```

[CodingStandard] Add RemoveSpacingAroundModifierAndConstFixer

---

ecs.yaml
packages/EasyCodingStandard/src/Console/Command/ValidateCommand.php

A command that checks various points, startin with:
- report checkers, that are already in imported files, to prevent longer config than is needed

[ECS] Add validate command

---

.travis.yml
packages/CodingStandard/packages/TokenRunner/src/Transformer/FixerTransformer/LineLengthTransformer.php
packages/CodingStandard/src/Fixer/LineLength/LineLengthFixer.php
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/Fixture/correct_heredoc.php.inc
packages/CodingStandard/tests/Fixer/LineLength/LineLengthFixer/LineLengthFixerTest.php
phpstan.neon

[CS] Fix LineLenght for breaking nowdoc

---

packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/config/config.yaml
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/Cache/Simple/FilesystemCacheFactory.php
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/ChangedFilesDetector.php
packages/EasyCodingStandard/packages/ChangedFilesDetector/src/CompilerPass/AddGetCwdWebalizedParameterCompilerPass.php
packages/EasyCodingStandard/src/Error/ErrorAndDiffCollector.php
packages/EasyCodingStandard/src/FileSystem/CachedFileLoader.php
packages/EasyCodingStandard/src/HttpKernel/EasyCodingStandardKernel.php
packages/PackageBuilder/src/FileSystem/SmartFileInfo.php

improve caching

---

packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass.php
packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutoReturnFactoryCompilerPass.php

Subj
Edit:. closes #1614, by @TomasVotruba

Bugfix of https://github.com/Symplify/Symplify/issues/1614

---

packages/EasyCodingStandard/src/HttpKernel/EasyCodingStandardKernel.php

This allows you to add custom output formats.

Autowire OutputFormatterInterface

---

packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/EasyCodingStandard/src/Console/EasyCodingStandardConsoleApplication.php
packages/EasyCodingStandard/src/Console/Output/ConsoleOutputFormatter.php

Only print metadata for console output

---

CHANGELOG.md
packages/ChangelogLinker/src/ChangeTree/ChangeResolver.php
packages/ChangelogLinker/src/Regex/RegexPattern.php

[ChangelogLinker] Skip tests

---

.travis.yml
composer.json
packages/Autodiscovery/tests/Yaml/ExplicitToAutodiscoveryConverterTest.php
packages/Autodiscovery/tests/Yaml/Fixture/blog_post_votruba.yaml
packages/Autodiscovery/tests/Yaml/Fixture/elasticr.yaml
packages/Autodiscovery/tests/Yaml/Fixture/exclude.yaml
packages/Autodiscovery/tests/Yaml/Fixture/existing_autodiscovery.yaml
packages/Autodiscovery/tests/Yaml/Fixture/first.yaml
packages/Autodiscovery/tests/Yaml/Fixture/shopsys.yaml
packages/Autodiscovery/tests/Yaml/Fixture/short_tags.yaml
packages/Autodiscovery/tests/Yaml/Fixture/singly_implemented_interfaces.yaml
packages/Autodiscovery/tests/Yaml/Fixture/singly_implemented_interfaces_excluded.yaml
packages/Autodiscovery/tests/Yaml/Fixture/untouch.yaml
packages/EasyCodingStandard/tests/Console/Output/JsonOutputFormatterTest.php
packages/EasyCodingStandardTester/src/Testing/AbstractCheckerTestCase.php
packages/EasyCodingStandardTester/src/Testing/IntegrationTestCaseTrait.php
packages/Statie/tests/Console/Command/GenerateCommandTest.php

I have never used Travis and I have no idea what I'm doing :)
I tried to replicate what you did in https://github.com/rectorphp/rector/pull/2278
We'll see how it goes!

Travis Windows + composer paths

---

packages/ChangelogLinker/src/ChangeTree/Resolver/CategoryResolver.php
packages/ChangelogLinker/src/Configuration/Category.php
packages/ChangelogLinker/tests/ChangeTree/ChangeFactory/Resolver/CategoryResolverTest.php

[CL] Make changed category as default fallback, add deprecated category

---

composer.json
packages/ChangelogLinker/src/ChangeTree/ChangeResolver.php
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/src/DependencyInjection/CompilerPass/ConflictingCheckersCompilerPass.php
packages/PackageBuilder/src/Tests/AbstractKernelTestCase.php

See https://github.com/symfony/symfony/pull/31202/files

[PB] Fix kernel shutdown

---

packages/MonorepoBuilder/packages/Split/src/Command/SplitCommand.php

Fixes #1680 
See https://github.com/Symplify/Symplify/pull/1175#issuecomment-557832893

[MB] Fix option value regression

---

packages/PHPStanExtensions/config/config.neon
packages/PHPStanExtensions/config/php.level.neon
packages/PHPStanExtensions/config/symfony.level.neon

See https://github.com/phpstan/phpstan-src/pull/22#issuecomment-557825215
Not tested, but hopefully this will help in the future

[PHPStanExtensions] Make extension future compatible with prefixed everything

---

packages/MonorepoBuilder/packages/Split/src/Command/SplitCommand.php
packages/MonorepoBuilder/packages/Split/src/Configuration/Option.php
packages/MonorepoBuilder/packages/Split/src/Git/GitManager.php
packages/MonorepoBuilder/packages/Split/src/PackageToRepositorySplitter.php

Related to #1673 .
Allow user to use a specific tag during split command.

[MB] Add optional --tag input to set tag manually

---

composer.json
ecs.yaml
packages/ChangelogLinker/tests/Github/GithubRepositoryFromRemoteResolverTest.php
packages/CodingStandard/packages/TokenRunner/src/Wrapper/FixerWrapper/ArgumentWrapperFactory.php
packages/CodingStandard/packages/TokenRunner/src/Wrapper/FixerWrapper/MethodWrapper.php
packages/CodingStandard/src/Fixer/LineLength/LineLengthFixer.php
packages/CodingStandard/src/Sniffs/Debug/CommentedOutCodeSniff.php
packages/EasyCodingStandard/bin/ecs
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/config/set/dead-code.yaml
packages/EasyCodingStandard/config/set/php70.yaml
packages/EasyCodingStandard/config/set/types.yaml
packages/EasyCodingStandard/src/Finder/SourceFinder.php
packages/EasyCodingStandard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsSource/checkers-parent.yaml
packages/EasyCodingStandard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsSource/config-with-bool.yaml
packages/EasyCodingStandard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsTest.php
packages/MonorepoBuilder/packages/Split/src/Command/SplitCommand.php
packages/MonorepoBuilder/packages/Split/src/Configuration/Option.php
packages/MonorepoBuilder/packages/Split/src/Git/GitManager.php
packages/MonorepoBuilder/packages/Split/src/PackageToRepositorySplitter.php
packages/PackageBuilder/src/Reflection/PrivatesAccessor.php
packages/PackageBuilder/src/Reflection/PrivatesCaller.php
packages/Statie/src/Application/StatieApplication.php
packages/Statie/src/Console/StatieConsoleApplication.php
phpstan.neon

[ECS] Bump to Slevomat 6, add dead-code

---

packages/PackageBuilder/composer.json

[PackageBuilder] Remove dependency on symfony/debug

---

packages/PHPStanExtensions/src/ErrorFormatter/SymplifyErrorFormatter.php
phpstan.neon

Based on frustration of users fighting with spaces

[PHPStanExtensions] Drop confusing path ignore

---

packages/CodingStandard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/Fixture/correct8.php.inc
packages/CodingStandard/tests/Fixer/Naming/PropertyNameMatchingTypeFixer/PropertyNameMatchingTypeFixerTest.php

[CS] Fix PropertyNameMatchingTypeFixer for intersection

---

composer.json
ecs.yaml
monorepo-builder.yaml
packages/AutoBindParameter/.gitattributes
packages/AutoBindParameter/.github/FUNDING.yml
packages/AutoBindParameter/.gitignore
packages/AutoBindParameter/.travis.yml
packages/AutoBindParameter/LICENSE
packages/AutoBindParameter/README.md
packages/AutoBindParameter/composer.json
packages/AutoBindParameter/phpunit.xml
packages/AutoBindParameter/src/DependencyInjection/CompilerPass/AutoBindParameterCompilerPass.php
packages/AutoBindParameter/tests/DependencyInjection/CompilerPass/AutoBindParameterCompilerPassTest.php
packages/AutoBindParameter/tests/HttpKernel/AutoBindParameterHttpKernel.php
packages/AutoBindParameter/tests/Source/SomeServiceWithParameter.php
packages/AutoBindParameter/tests/config/auto_bind_parameter.yaml
packages/AutoBindParameter/upgrade/rector/auto-bind-parameter-72.yaml
packages/AutowireArrayParameter/tests/DependencyInjection/CompilerPass/AutowireArrayParameterCompilerPassTest.php
packages/ChangelogLinker/composer.json
packages/ChangelogLinker/src/HttpKernel/ChangelogLinkerKernel.php
packages/EasyCodingStandard/composer.json
packages/EasyCodingStandard/src/HttpKernel/EasyCodingStandardKernel.php
packages/MonorepoBuilder/composer.json
packages/MonorepoBuilder/src/HttpKernel/MonorepoBuilderKernel.php
packages/PackageBuilder/README.md
packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass.php
packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/Source/AutoBindParametersKernel.php
packages/Statie/composer.json
packages/Statie/src/HttpKernel/StatieKernel.php

[AutoBindParameter] Decouple new package

---

packages/SetConfigResolver/src/Exception/SetNotFoundException.php
packages/SetConfigResolver/src/SetResolver.php

Closes https://github.com/rectorphp/rector/issues/2462

fix SetNotFoundException namespace

---

.travis.yml
packages/CodingStandard/packages/TokenRunner/tests/Analyzer/SniffAnalyzer/CognitiveComplexityAnalyzer/CognitiveComplexityAnalyzerTest.php
packages/CodingStandard/packages/TokenRunner/tests/Analyzer/SniffAnalyzer/CognitiveComplexityAnalyzer/Source/function9.php.inc
phpunit.xml

Added test for correct calculation of nesting increments cognitive complexity.
See #1719

Cognitive complexity nesting

---

packages/EasyCodingStandard/src/Console/Command/CheckCommand.php
packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyle.php

[ECS] show reported by rule, so its easier to recognize from message

---

.github/workflows/code_checks.yaml
.gitignore
composer.json
ecs.yaml
packages/EasyCodingStandard/README.md
packages/EasyCodingStandard/config/config.yaml
packages/EasyCodingStandard/packages/Configuration/src/Configuration.php
packages/EasyCodingStandard/src/Console/Command/CheckCommand.php

Inspired by https://github.com/rectorphp/rector/pull/2302/files

[ECS] Add paths parameter to ECS

---

packages/CodingStandard/packages/TokenRunner/config/config.yaml
packages/CodingStandard/packages/TokenRunner/src/Analyzer/FixerAnalyzer/BlockFinder.php
packages/CodingStandard/packages/TokenRunner/src/Naming/Name/NameFactory.php
packages/CodingStandard/packages/TokenRunner/src/Transformer/FixerTransformer/LineLengthTransformer.php
packages/CodingStandard/packages/TokenRunner/src/ValueObject/BlockInfo.php
packages/CodingStandard/packages/TokenRunner/src/ValueObject/Name.php
packages/CodingStandard/packages/TokenRunner/src/Wrapper/FixerWrapper/ArrayWrapperFactory.php
packages/CodingStandard/src/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer.php
packages/CodingStandard/src/Fixer/LineLength/LineLengthFixer.php
packages/EasyCodingStandard/config/config.yaml
phpstan.neon

[CodingStandard] Make import paths phar friendly

---

packages/monorepo-builder/packages/split/src/Command/SplitCommand.php
packages/monorepo-builder/packages/split/src/Configuration/Option.php
packages/monorepo-builder/packages/split/src/Exception/InvalidBranchException.php
packages/monorepo-builder/packages/split/src/Git/GitManager.php
packages/monorepo-builder/packages/split/src/PackageToRepositorySplitter.php
packages/monorepo-builder/packages/split/src/Process/ProcessFactory.php
packages/monorepo-builder/packages/split/tests/Process/ProcessFactoryTest.php

This PR is related to #1744
It is still work in progress, I want to see what github actions has for me 😄

[MonorepoBuilder] Specific branch for split

---

.github/workflows/check_coding_standard_readme_sync.yaml
ci/check_coding_standard_readme_sync.php
ecs.yaml
packages/autodiscovery/src/ValueObject/ServiceConfig.php
packages/autodiscovery/src/Yaml/CommonNamespaceResolver.php
packages/autodiscovery/src/Yaml/ExplicitToAutodiscoveryConverter.php
packages/autodiscovery/src/Yaml/YamlServiceProcessor.php
packages/autodiscovery/tests/Yaml/CommonNamespaceResolverTest.php
packages/coding-standard/README.md
packages/coding-standard/config/symplify.yaml
packages/coding-standard/packages/token-runner/src/Naming/PropertyNaming.php
packages/coding-standard/packages/token-runner/src/Transformer/FixerTransformer/LineLengthResolver.php
packages/coding-standard/packages/token-runner/src/Transformer/FixerTransformer/LineLengthTransformer.php
packages/coding-standard/src/Fixer/Naming/PropertyNameMatchingTypeFixer.php
packages/coding-standard/src/Fixer/Spacing/RemoveSpacingAroundModifierAndConstFixer.php
packages/coding-standard/src/Sniffs/CleanCode/ClassCognitiveComplexitySniff.php
packages/coding-standard/tests/Sniffs/CleanCode/ClassCognitiveComplexitySniff/ClassCognitiveComplexitySniffTest.php
packages/coding-standard/tests/Sniffs/CleanCode/ClassCognitiveComplexitySniff/Fixture/wrong.php.inc
packages/easy-coding-standard-tester/src/Testing/AbstractCheckerTestCase.php

[CodingStandard] Add ClassCognitiveComplexitySniff

---

composer.json
monorepo-builder.yaml
packages/phpstan-extensions/src/Rules/Classes/MatchingTypeConstantRule.php
packages/symfony-static-dumper/.gitattributes
packages/symfony-static-dumper/.gitignore
packages/symfony-static-dumper/LICENSE
packages/symfony-static-dumper/README.md
packages/symfony-static-dumper/composer.json
packages/symfony-static-dumper/config/config.yaml
packages/symfony-static-dumper/phpunit.xml
packages/symfony-static-dumper/src/Command/DumpStaticSiteCommand.php
packages/symfony-static-dumper/src/Exception/ShouldNotHappenException.php
packages/symfony-static-dumper/src/HttpFoundation/ControllerContentResolver.php
phpstan.neon

Ref #1793
See https://github.com/TomasVotruba/friendsofphp.org/pull/162

[SymfonyStaticDumper] Add new package

---

packages/symfony-static-dumper/src/Application/SymfonyStaticDumperApplication.php
packages/symfony-static-dumper/src/Controller/ControllerDumper.php
packages/symfony-static-dumper/src/Routing/RoutesProvider.php

Closes https://github.com/symplify/symplify/issues/1846

[SSD] Improve progress reporting

---

packages/easy-coding-standard/config/config.yaml
packages/easy-coding-standard/config/services.yaml
packages/easy-coding-standard/packages/configuration/src/Configuration.php
packages/easy-coding-standard/src/Console/Command/CheckCommand.php

[ECS] Deprecate "psr2" set

---

packages/symfony-static-dumper/src/HttpFoundation/ControllerContentResolver.php
packages/symfony-static-dumper/tests/Application/SymfonyStaticDumperApplicationTest.php
packages/symfony-static-dumper/tests/Fixture/expected/static.html
packages/symfony-static-dumper/tests/test_project/config/routes.yaml
packages/symfony-static-dumper/tests/test_project/templates/static.twig

[SSD] Handle render page created with TemplateController

---

packages/coding-standard/README.md
packages/coding-standard/src/Rules/Naming/NoClassWithStaticMethodWithoutStaticNameRule.php
packages/coding-standard/tests/Rules/Naming/NoClassWithStaticMethodWithoutStaticNameRule/Fixture/ClassWithMethod.php
packages/coding-standard/tests/Rules/Naming/NoClassWithStaticMethodWithoutStaticNameRule/Fixture/SkipEventSubscriber.php
packages/coding-standard/tests/Rules/Naming/NoClassWithStaticMethodWithoutStaticNameRule/Fixture/SkipValueObjectFactory.php
packages/coding-standard/tests/Rules/Naming/NoClassWithStaticMethodWithoutStaticNameRule/NoClassWithStaticMethodWithoutStaticNameRuleTest.php
packages/phpstan-extensions/src/Rules/ClassMethod/BoolishClassMethodPrefixRule.php

[CS] Add NoClassWithStaticMethodWithoutStaticNameRule

---

.travis.yml
packages/easy-coding-standard/compiler/bin/compile
packages/easy-coding-standard/compiler/composer.json
packages/easy-coding-standard/compiler/config/config.yaml
packages/easy-coding-standard/compiler/src/Command/CompileCommand.php
packages/easy-coding-standard/compiler/src/Composer/ComposerJsonManipulator.php
packages/easy-coding-standard/compiler/src/Console/EasyCodingStandardCompilerApplication.php
packages/easy-coding-standard/compiler/src/HttpKernel/EasyCodingStandardCompilerKernel.php

Inspired by https://github.com/rectorphp/rector/pull/2941

[ECS] Switch compiler to kernel

---

.travis.yml

See https://github.com/rectorphp/rector/commit/69774af193e0cfd48d03a00aadaad1192f239e21#diff-354f30a63fb0907d4ad57269548329e3

Add token to increate GitHub api on Travis

---

packages/changelog-linker/src/Github/GithubRepositoryFromRemoteResolver.php
packages/easy-coding-standard/config/set/psr12.yaml
packages/easy-coding-standard/tests/Set/Psr12/fixed/fixed.php.inc

Issue #1926: Fix PSR12 order of imports.

---

packages/coding-standard/README.md
packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/src/Rules/SeeAnnotationToTestRule.php
packages/coding-standard/src/Sniffs/Debug/CommentedOutCodeSniff.php
packages/coding-standard/tests/Rules/SeeAnnotationToTestRule/Fixture/RuleWithoutSee.php
packages/coding-standard/tests/Rules/SeeAnnotationToTestRule/SeeAnnotationToTestRuleTest.php
packages/coding-standard/tests/Rules/SeeAnnotationToTestRule/config/see_rule_config.neon
phpstan.neon

[CS] Add @see rule to refer test case

---

packages/coding-standard/README.md
packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/src/Rules/ForceMethodCallArgumentConstantRule.php
packages/coding-standard/tests/Rules/ForceMethodCallArgumentConstantRule/Fixture/SomeMethodCallWithoutConstant.php
packages/coding-standard/tests/Rules/ForceMethodCallArgumentConstantRule/Fixture/WithConstant.php
packages/coding-standard/tests/Rules/ForceMethodCallArgumentConstantRule/ForceMethodCallArgumentConstantRuleTest.php
packages/coding-standard/tests/Rules/ForceMethodCallArgumentConstantRule/Source/AlwaysCallMeWithConstant.php

[CS] Add ForceMethodCallArgumentConstantRule

---

packages/smart-file-system/src/Finder/FinderSanitizer.php
packages/smart-file-system/tests/Finder/FinderSanitizer/FinderSanitizerTest.php
packages/smart-file-system/tests/SmartFileInfo/SmartFileInfoTest.php

[SmartFileSystem] read zero sized files

---

composer.json
packages/autodiscovery/config/config.yaml
packages/autodiscovery/src/Discovery.php
packages/autodiscovery/src/Doctrine/DoctrineEntityMappingAutodiscoverer.php
packages/autodiscovery/src/Finder/AutodiscoveryFinder.php
packages/autodiscovery/src/Routing/AnnotationRoutesAutodiscoverer.php
packages/autodiscovery/src/Translation/TranslationPathAutodiscoverer.php
packages/autodiscovery/src/Twig/TwigPathAutodiscoverer.php
packages/changelog-linker/config/config.yaml
packages/easy-coding-standard/config/services.yaml
packages/monorepo-builder/packages/merge/config/config.yaml
phpstan.neon

[phpstan] add TestCaseWithSuffixRule rule

---

packages/changelog-linker/src/Worker/LinkifyWorker.php
packages/changelog-linker/tests/ChangelogLinker/ChangelogLinkerTest.php
packages/changelog-linker/tests/ChangelogLinker/Fixture/single_package_link.md
packages/package-builder/src/Tests/StaticFixtureLoader.php

[ChangelogLinker] Fix inner-link of words to link

---

packages/easy-coding-standard/src/Set/EasyCodingStandardSetProvider.php

add "strict" set to EasyCodingStandardSetProvider

---

packages/phpstan-extensions/src/ErrorFormatter/SymplifyErrorFormatter.php

[PHPStanExtensions] Clear trait path in report

---

packages/easy-coding-standard/config/set/common.php

```
[ERROR] Cannot load resource                                                                                           
".../vendor/symplify/easy-coding-standard/config/set/common/array.yaml".   
```

[ECS] Fix common.php

---

packages/easy-coding-standard/README.md

[ECS] Simplify README

---

packages/coding-standard/config/symplify-rules.neon
packages/easy-coding-standard/src/Console/Command/CheckMarkdownCommand.php
packages/easy-coding-standard/src/Console/Command/MarkdownCodeFormatterCommand.php
packages/easy-coding-standard/src/Markdown/MarkdownPHPCodeFormatter.php
packages/easy-coding-standard/tests/Markdown/Fixture/multi_items.md
packages/easy-coding-standard/tests/Markdown/Fixture/some_file.md
packages/easy-coding-standard/tests/Markdown/MarkdownPHPCodeFormatterTest.php
packages/easy-coding-standard/tests/Markdown/config/array_fixer.php

Post cleanup + test case for https://github.com/symplify/symplify/pull/2118

[ECS] Decouple MarkdownPHPCodeFormatter + add test

---

packages/easy-coding-standard/src/Formatter/AbstractPHPFormatter.php
packages/easy-coding-standard/src/HeredocNowdoc/HeredocNowdocPHPCodeFormatter.php
packages/easy-coding-standard/tests/HeredocNowdoc/Fixture/trim.php.inc
packages/easy-coding-standard/tests/HeredocNowdoc/Fixture/with-open-php-tag.php.inc
packages/easy-coding-standard/tests/Markdown/Fixture/class.md
packages/easy-coding-standard/tests/Markdown/Fixture/multi_items.md
packages/easy-coding-standard/tests/Markdown/Fixture/trim.md

In Code Snippet:
- keep `<?php` open tag  if exists
- don't add `<?php ` if not exists

Formatter: don't add <?php open tag if not exists in code snippet

---

packages/easy-coding-standard/src/Console/Command/CheckHeredocNowdocCommand.php
packages/easy-coding-standard/src/Console/Command/CheckMarkdownCommand.php
packages/easy-coding-standard/src/Formatter/AbstractPHPFormatter.php
packages/easy-coding-standard/tests/HeredocNowdoc/HeredocNowdocPHPCodeFormatterTest.php
packages/easy-coding-standard/tests/Markdown/MarkdownPHPCodeFormatterTest.php

This include PR #2140 since the code changes are related. Need rebase when #2140 merged.

Added --no-strict-types-declaration option to Formatter

---

packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/docs/phpstan_rules.md
packages/coding-standard/src/Contract/ManyNodeRuleInterface.php
packages/coding-standard/src/Rules/AbstractManyNodeTypeRule.php
packages/coding-standard/src/Rules/NoAbstactMethodRule.php
packages/coding-standard/tests/Rules/NoAbstractMethodRule/Fixture/SkipNonAbstractMethod.php
packages/coding-standard/tests/Rules/NoAbstractMethodRule/Fixture/SomeAbstractMethod.php
packages/coding-standard/tests/Rules/NoAbstractMethodRule/NoAbstractMethodRuleTest.php

[CS] Add NoAbstractMethodRule

---

packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/docs/phpstan_rules.md
packages/coding-standard/docs/phpstan_rules_object_calisthenics.md
packages/coding-standard/src/Contract/ManyNodeRuleInterface.php
packages/coding-standard/src/Rules/NoPostIncPostDecRule.php
packages/coding-standard/tests/Rules/NoPostIncPostDecRule/Fixture/WithPostDec.php
packages/coding-standard/tests/Rules/NoPostIncPostDecRule/Fixture/WithPostInc.php
packages/coding-standard/tests/Rules/NoPostIncPostDecRule/NoPostIncPostDecRuleTest.php
packages/easy-coding-standard/src/Console/Command/CheckHeredocNowdocCommand.php
packages/monorepo-builder/packages/split/src/PackageToRepositorySplitter.php

[CS] Add NoPostIncPostDecRule

---

packages/easy-coding-standard/src/DependencyInjection/CompilerPass/ConflictingCheckersCompilerPass.php

[ECS] Report conflicting unary

---

packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/AbstractMalformWorker.php
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/FixturePhp74/skip_nested_call.php.inc
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Php74Test.php

[CS] Fix ParamReturnAndVarTagMalformsFixer for fn()

---

composer.json
packages/auto-bind-parameter/composer.json
packages/autodiscovery/composer.json
packages/autowire-array-parameter/composer.json
packages/changelog-linker/composer.json
packages/coding-standard/composer.json
packages/composer-json-manipulator/composer.json
packages/console-color-diff/composer.json
packages/easy-coding-standard-tester/composer.json
packages/easy-coding-standard/compiler/composer.json
packages/easy-coding-standard/composer.json
packages/easy-hydrator/composer.json
packages/easy-testing/composer.json
packages/flex-loader/composer.json
packages/monorepo-builder/compiler/composer.json
packages/monorepo-builder/composer.json
packages/package-builder/composer.json
packages/phpstan-extensions/composer.json
packages/set-config-resolver/composer.json
packages/smart-file-system/composer.json
packages/symfony-static-dumper/composer.json

See https://github.com/symfony/symfony/pull/36876

composer: be open about PHP 8 and beyond

---

packages/autodiscovery/config/config.php
packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/docs/phpstan_rules.md
packages/coding-standard/src/Rules/NoMissingDirPathRule.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/FileMissing.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/SkipAssertMethod.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/SkipExistingFile.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/SkipFileExistsFuncCall.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/SkipFnMatch.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/SkipVendorAutoload.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/NoMissingDirPathRuleTest.php
packages/easy-coding-standard/config/services.php
packages/easy-coding-standard/packages/configuration/config/services.php
packages/easy-coding-standard/packages/fixer-runner/config/services.php
packages/easy-coding-standard/packages/sniff-runner/config/services.php
packages/easy-hydrator/config/config.php
packages/monorepo-builder/compiler/config/config.php
packages/monorepo-builder/config/services.php
packages/monorepo-builder/packages/release/config/config.php
packages/monorepo-builder/packages/split/config/config.php
rector-ci.php

Closes https://github.com/symplify/symplify/issues/2019

[CS] Add CheckDirPathExistanceRule

---

packages/coding-standard/src/PhpParser/FileExistFuncCallAnalyzer.php
packages/coding-standard/src/Rules/NoMissingDirPathRule.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/Fixture/SkipFileExistsFuncCallOneLayerAbove.php
packages/coding-standard/tests/Rules/NoMissingDirPathRule/NoMissingDirPathRuleTest.php

[CS] Add parent if check to NoMissingDirPathRule

---

packages/coding-standard/docs/phpcs_fixer_fixers.md
packages/coding-standard/src/Fixer/Annotation/RemovePHPStormAnnotationFixer.php
packages/coding-standard/tests/Fixer/Annotation/RemovePHPStormAnnotationFixer/Fixture/simple_annotation.php.inc
packages/coding-standard/tests/Fixer/Annotation/RemovePHPStormAnnotationFixer/Fixture/skip_non_phpstorm.php.inc
packages/coding-standard/tests/Fixer/Annotation/RemovePHPStormAnnotationFixer/RemovePHPStormAnnotationFixerTest.php

Closes https://github.com/symplify/symplify/issues/2179

[CS] Add RemovePHPStormAnnotationFixer

---

packages/coding-standard/src/Fixer/Strict/BlankLineAfterStrictTypesFixer.php
packages/easy-coding-standard/src/Console/Output/ConsoleOutputFormatter.php
phpstan.neon

remove static properties where possible

---

packages/coding-standard/src/Rules/NoProtectedElementInFinalClassRule.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/Fixture/SomeFinalClassUsesTrait.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/Fixture/SomeFinalClassWithNoPropertyAndNoMethod.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/Fixture/SomeInterface.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/Fixture/SomeNotFinalClass.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/Fixture/SomeTrait.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/NoProtectedElementInFinalClassRuleTest.php
packages/symfony-static-dumper/tests/test_project/src/HttpKernel/TestSymfonyStaticDumperKernel.php

Follow up to https://github.com/symplify/symplify/pull/2194

[CS] Resolve fqn name for class in NoProtectedElementInFinalClassRule

---

.github/inactive-workflows/code_coverage.yaml
easy-ci.php
packages/easy-coding-standard/src/Application/EasyCodingStandardApplication.php
packages/easy-coding-standard/src/Console/Style/EasyCodingStandardStyle.php

Just add `-v` to show memory/time

[ECS] Enable debug progress bar on -v

---

packages/coding-standard/src/Rules/NoProtectedElementInFinalClassRule.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/Fixture/SomeInterface.php
packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/NoProtectedElementInFinalClassRuleTest.php

no need to check instance of Class_ check

Bug fix: parent of ClassMethod always be a Class_, 

---

packages/easy-hydrator/src/ValueResolver.php
packages/easy-hydrator/tests/ArrayToValueObjectHydratorTest.php
packages/easy-hydrator/tests/Fixture/ImmutableTimeEvent.php

[EasyHydrator] DateTimeImmutable resolver (symplify#2254)

---

packages/easy-coding-standard/src/Error/ErrorAndDiffCollector.php
packages/easy-coding-standard/src/Exception/NotSniffNorFixerException.php

Closes https://github.com/symplify/symplify/issues/2296

[ECS] Fix missing exception

---

composer.json
packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/docs/phpstan_rules.md
packages/coding-standard/src/Rules/CheckUnneededSymfonyStyleUsageRule.php
packages/coding-standard/src/Rules/ClassNameRespectsParentSuffixRule.php
packages/coding-standard/src/Rules/ForbiddenArrayDestructRule.php
packages/coding-standard/src/Rules/NoContainerInjectionInConstructorRule.php
packages/coding-standard/src/Rules/NoParentMethodCallOnEmptyStatementInParentMethodRule.php
packages/coding-standard/tests/Rules/ClassNameRespectsParentSuffixRule/ClassNameRespectsParentSuffixRuleTest.php
packages/coding-standard/tests/Rules/ClassNameRespectsParentSuffixRule/Fixture/NonTestSuffix.php
packages/coding-standard/tests/Rules/ClassNameRespectsParentSuffixRule/Fixture/SkipAbstractTestCase.php
packages/coding-standard/tests/Rules/ClassNameRespectsParentSuffixRule/Fixture/SkipTest.php
packages/coding-standard/tests/Rules/NoContainerInjectionInConstructorRule/Fixture/SkipContainerBuilder.php
packages/coding-standard/tests/Rules/NoContainerInjectionInConstructorRule/Fixture/SkipNonContainerClass.php
packages/coding-standard/tests/Rules/NoContainerInjectionInConstructorRule/Fixture/WithContainerDependency.php
packages/coding-standard/tests/Rules/NoContainerInjectionInConstructorRule/NoContainerInjectionInConstructorRuleTest.php
phpstan.neon

Ref https://github.com/symplify/symplify/issues/2268

various static improvement

---

packages/coding-standard/src/Fixer/Spacing/MethodChainingNewlineFixer.php
packages/coding-standard/tests/Fixer/Spacing/MethodChainingNewlineFixer/Fixture/skip_clone_call.php.inc
packages/coding-standard/tests/Fixer/Spacing/MethodChainingNewlineFixer/Fixture/skip_in_array_more.php.inc

[CS] Skip array square wrap over multi chain call

---

packages/coding-standard/src/Rules/ForbiddenMultipleClassLikeInOneFileRule.php
packages/coding-standard/tests/Rules/ForbiddenMultipleClassLikeInOneFileRule/Fixture/OneClassWithAnonymousClass.php
packages/coding-standard/tests/Rules/ForbiddenMultipleClassLikeInOneFileRule/Fixture/OneClassWithoutAnonymousClass.php
packages/coding-standard/tests/Rules/ForbiddenMultipleClassLikeInOneFileRule/ForbiddenMultipleClassLikeInOneFileRuleTest.php

cc @samsonasik This need to be covered too
Feel free to join this PR/copy it

[CS] Add failing class with anonymous

---

packages/coding-standard/config/symplify-rules.neon
packages/coding-standard/docs/phpstan_rules.md
packages/coding-standard/src/Rules/NoSuffixValueObjectClassRule.php
packages/coding-standard/tests/Rules/NoSuffixValueObjectClassRule/Fixture/SkipNoValueObjectInNamespace.php
packages/coding-standard/tests/Rules/NoSuffixValueObjectClassRule/Fixture/ValueObject/MoneyValueObject.php
packages/coding-standard/tests/Rules/NoSuffixValueObjectClassRule/Fixture/ValueObject/SkipValueObjectWithoutValueObjectSuffix.php
packages/coding-standard/tests/Rules/NoSuffixValueObjectClassRule/NoSuffixValueObjectClassRuleTest.php
phpstan.neon

[CS] Add NoSuffixValueObjectClassRule

---

packages/autodiscovery/src/NamespaceDetector.php

#2334: Autodiscovery: NamespaceDecetor not work for doctrine mapped-superclass

---

packages/easy-coding-standard/README.md
packages/easy-coding-standard/packages/configuration/src/Configuration.php
packages/easy-coding-standard/src/Application/EasyCodingStandardApplication.php
packages/easy-coding-standard/src/Console/Command/AbstractCheckCommand.php
packages/easy-coding-standard/src/Finder/SourceFinder.php
packages/easy-coding-standard/src/Git/GitDiffProvider.php
packages/easy-coding-standard/src/ValueObject/Option.php
rector-ci.php

Mirrors https://github.com/rectorphp/rector/pull/2347/files

[ECS] Add --match-git-diff option

---

packages/phpstan-rules/composer.json

Enable PHPStan Extension installer to autoload this extension

Define package as PHPStan Extension

---

packages/coding-standard/src/Fixer/Commenting/RemoveUselessClassCommentFixer.php
packages/coding-standard/tests/Fixer/Commenting/RemoveUselessClassCommentFixer/Fixture/skip_usefull_class_constructor_comment.php.inc
packages/coding-standard/tests/Fixer/Commenting/RemoveUselessClassCommentFixer/Fixture/useless_class_constructor_comment.php.inc

Alternative for https://github.com/symplify/symplify/pull/2518

[CS] Fixes #2517 improve RemoveUselessClassCommentFixer : remove useless constructor comment

---

.github/workflows/cron_generate_changenlog.yaml
.github/workflows/daily_pull_request.yaml
.github/workflows/split_unused_packages.yaml
.github/workflows/test_lowest_dependencies.yaml
.github/workflows/unit_tests.yaml
packages/coding-standard/docs/rules_overview.md
packages/phpstan-rules/docs/rules_overview.md
packages/phpstan-rules/src/Rules/CheckConstantExpressionDefinedInConstructOrSetupRule.php
packages/rule-doc-generator/src/Category/CategoryResolver.php
packages/rule-doc-generator/src/Command/GenerateCommand.php
packages/rule-doc-generator/src/Contract/Category/CategoryInfererInterface.php
packages/rule-doc-generator/src/DirectoryToMarkdownPrinter.php
packages/rule-doc-generator/src/HttpKernel/RuleDocGeneratorKernel.php
packages/rule-doc-generator/src/Printer/RuleDefinitionsPrinter.php
packages/rule-doc-generator/src/ValueObject/Option.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/DirectoryToMarkdownPrinterTest.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/configurable_phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/configurable_phpstan_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/phpstan_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/composer_json_aware_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/configurable_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/extra_file_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_categorized.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Fixture/Rector/ComposerJsonAware/ComposerJsonAwareRector.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Fixture/Rector/Configurable/ConfigurableRector.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Fixture/Rector/Standard/SomeRector.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Source/SimpleCategoryInferer.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/config/config_with_category_inferer.php

- add rule count
- remove redundant composer install
- update docs for rules

[RuleDocGenerator] Add count to the top + category

---

packages/phpstan-rules/src/Rules/ForbiddenMethodCallOnTypeRule.php
packages/phpstan-rules/tests/Rules/ForbiddenMethodCallOnTypeRule/Fixture/HasDirectDocCommentCall.php
packages/phpstan-rules/tests/Rules/ForbiddenMethodCallOnTypeRule/Fixture/SkipPropertyReflection.php
packages/phpstan-rules/tests/Rules/ForbiddenMethodCallOnTypeRule/ForbiddenMethodCallOnTypeRuleTest.php
packages/phpstan-rules/tests/Rules/ForbiddenMethodCallOnTypeRule/config/configured_rule.neon
packages/rule-doc-generator/src/ValueObject/CodeSample/ComposerJsonAwareCodeSample.php
packages/rule-doc-generator/src/ValueObject/CodeSample/ConfiguredCodeSample.php
packages/rule-doc-generator/src/ValueObject/CodeSample/ExtraFileCodeSample.php

Solves also https://github.com/rectorphp/rector/issues/4756#issuecomment-738757362

[PHPStanRules] Add ForbiddenMethodCallOnTypeRule

---

.github/workflows/build_scoped_packages.yaml
.github/workflows/cron_generate_changenlog.yaml
.github/workflows/daily_checks.yaml
.github/workflows/daily_pull_request.yaml
.github/workflows/split_monorepo.yaml
.github/workflows/split_tests.yaml
.github/workflows/split_unused_packages.yaml
.github/workflows/unit_tests.yaml
packages/monorepo-builder/src/Command/PackagesJsonCommand.php
packages/monorepo-builder/src/Json/PackageJsonProvider.php
packages/package-scoper/templates/github/workflows/build_scoped_packages.yaml

Follow up to https://github.com/symplify/symplify/pull/2592

[CI] Handle packges-json in key-aware approach

---

packages/phpstan-rules/composer.json

[PHPStanRules] Remove auto-installation with phpstan/extension-installer

---

packages/phpstan-rules/src/Rules/AbstractSymplifyRule.php
packages/phpstan-rules/src/Rules/CheckClassNamespaceFollowPsr4Rule.php
packages/phpstan-rules/src/Rules/CheckUsedNamespacedNameOnClassNodeRule.php
packages/phpstan-rules/src/Rules/ExcessivePublicCountRule.php
packages/phpstan-rules/src/Rules/ForbiddenNewOutsideFactoryServiceRule.php
packages/phpstan-rules/src/Rules/ForbiddenParentClassRule.php
packages/phpstan-rules/src/Rules/NoDuplicatedShortClassNameRule.php
packages/phpstan-rules/src/Rules/NoProtectedElementInFinalClassRule.php
packages/phpstan-rules/src/Rules/NoSuffixValueObjectClassRule.php
packages/phpstan-rules/src/Rules/PreferredClassRule.php
packages/phpstan-rules/src/Rules/PrefixAbstractClassRule.php
packages/phpstan-rules/src/Rules/SeeAnnotationToTestRule.php
packages/static-detector/src/Collector/StaticNodeCollector.php
packages/static-detector/src/NodeVisitor/StaticCollectNodeVisitor.php

Ensure namespacedName property exists when call $Class_->namespacedName

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/RequireStringRegexMatchKeyRule.php
packages/phpstan-rules/src/ValueObject/PHPStanAttributeKey.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/NumericDim.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/NumericDimDirectNext.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/NumericDimInsideIfCond.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/NumericDimOtherNameMultipleValues.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/SkipNotRegexMatchResult.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/SkipNotUsed.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/Fixture/SkipStringDim.php
packages/phpstan-rules/tests/Rules/RequireStringRegexMatchKeyRule/RequireStringRegexMatchKeyRuleTest.php
phpstan.neon

[PHPStanRules] Add RequireStringRegexMatchKeyRule

---

packages/package-builder/src/DependencyInjection/DefinitionFinder.php
packages/package-builder/src/Strings/StringFormatConverter.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/RequireThisCallOnLocalMethodRule.php
packages/phpstan-rules/tests/Rules/RequireThisCallOnLocalMethodRule/Fixture/CallLocalMethod.php
packages/phpstan-rules/tests/Rules/RequireThisCallOnLocalMethodRule/Fixture/ParentClass.php
packages/phpstan-rules/tests/Rules/RequireThisCallOnLocalMethodRule/Fixture/SkipCallLocalStaticMethod.php
packages/phpstan-rules/tests/Rules/RequireThisCallOnLocalMethodRule/Fixture/SkipCallParentMethodStatically.php
packages/phpstan-rules/tests/Rules/RequireThisCallOnLocalMethodRule/RequireThisCallOnLocalMethodRuleTest.php

 [PHPStanRules]  Add RequireThisCallOnLocalMethodRule 

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/ForbiddenAnonymousClassRule.php
packages/phpstan-rules/tests/Rules/ForbiddenAnonymousClassRule/Fixture/AnonymousClass.php
packages/phpstan-rules/tests/Rules/ForbiddenAnonymousClassRule/Fixture/SkipDedicatedClass.php
packages/phpstan-rules/tests/Rules/ForbiddenAnonymousClassRule/ForbiddenAnonymousClassRuleTest.php
phpstan.neon

[PHPStanRules]  Add ForbiddenAnonymousClassRule

---

packages/astral/src/NodeValue/NodeValueResolver.php
packages/phpstan-rules/src/Rules/RequireSkipPrefixForRuleSkippedFixtureRule.php
packages/phpstan-rules/tests/Rules/ForbiddenNewOutsideFactoryServiceRule/Fixture/NotAFactoryClassNonStar.php
packages/phpstan-rules/tests/Rules/ForbiddenNewOutsideFactoryServiceRule/ForbiddenNewOutsideFactoryServiceRuleTest.php
packages/phpstan-rules/tests/Rules/RequireSkipPrefixForRuleSkippedFixtureRule/Fixture/ExtraPrefix.php
packages/phpstan-rules/tests/Rules/RequireSkipPrefixForRuleSkippedFixtureRule/RequireSkipPrefixForRuleSkippedFixtureRuleTest.php
phpstan.neon

Ref https://github.com/symplify/symplify/issues/2728

[PHPStanRules] Add unskipped test fixture

---

packages/easy-testing/src/Command/ValidateFixtureSkipNamingCommand.php

ref https://github.com/rectorphp/rector/pull/5081#issuecomment-753648064

[EasyTesting] Update wording error on ValidateFixtureSkipNamingCommand

---

packages/easy-testing/src/Command/ValidateFixtureSkipNamingCommand.php
packages/easy-testing/src/MissplacedSkipPrefixResolver.php
phpstan.neon

[EasyTesting] Check ---- in ValidateFixtureSkipNaming Command

---

packages/coding-standard/src/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer.php
packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/ParamNameReferenceMalformWorker.php
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/param_reference.php.inc

[CodingStandard] Remove reference on @param for ParamReturnAndVarTagMalformsFixer

---

packages/changelog-linker/src/Github/GithubApi.php

[changelog-linker] Include none if no pull requests have been merged since provided last id

---

packages/changelog-linker/src/Configuration/HighestMergedIdResolver.php
packages/changelog-linker/src/Console/Command/DumpMergesCommand.php
packages/changelog-linker/src/Github/GithubApi.php

[changelog-linker] Prevent duplication in changelog when only PR no. 1 was merged

---

packages/astral/src/Naming/SimpleNameResolver.php
packages/astral/src/NodeNameResolver/NamespaceNodeNameResolver.php
packages/astral/src/StaticFactory/SimpleNameResolverStaticFactory.php
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/packages/cognitive-complexity/src/Rules/ClassLikeCognitiveComplexityRule.php
packages/phpstan-rules/packages/cognitive-complexity/tests/AstCognitiveComplexityAnalyzer/AstCognitiveComplexityAnalyzerTest.php
packages/phpstan-rules/packages/cognitive-complexity/tests/AstCognitiveComplexityAnalyzer/config/configured_service.neon
packages/phpstan-rules/packages/cognitive-complexity/tests/Rules/FunctionLikeCognitiveComplexityRule/FunctionLikeCognitiveComplexityRuleTest.php
packages/phpstan-rules/packages/cognitive-complexity/tests/Rules/FunctionLikeCognitiveComplexityRule/config/configured_rule.neon
packages/phpstan-rules/src/NodeAnalyzer/DependencyNodeAnalyzer.php
packages/phpstan-rules/src/NodeFinder/ParentNodeFinder.php
packages/phpstan-rules/src/Rules/AbstractSymplifyRule.php
packages/phpstan-rules/src/Rules/CheckConstantExpressionDefinedInConstructOrSetupRule.php
packages/phpstan-rules/src/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule.php
packages/phpstan-rules/src/Rules/CheckOptionArgumentCommandRule.php
packages/phpstan-rules/src/Rules/CheckParentChildMethodParameterTypeCompatibleRule.php
packages/phpstan-rules/src/Rules/CheckTypehintCallerTypeRule.php
packages/phpstan-rules/src/Rules/CheckUsedNamespacedNameOnClassNodeRule.php
packages/phpstan-rules/src/Rules/ForbiddenArrayWithStringKeysRule.php
packages/phpstan-rules/src/Rules/ForbiddenNodeRule.php
packages/phpstan-rules/src/Rules/ForbiddenPrivateMethodByTypeRule.php
packages/phpstan-rules/src/Rules/ForbiddenTestsNamespaceOutsideTestsDirectoryRule.php
packages/phpstan-rules/src/Rules/NoClassWithStaticMethodWithoutStaticNameRule.php
packages/phpstan-rules/src/Rules/NoDynamicNameRule.php
packages/phpstan-rules/src/Rules/NoFactoryInConstructorRule.php
packages/phpstan-rules/src/Rules/RequireThisCallOnLocalMethodRule.php
packages/phpstan-rules/src/Rules/RequireThisOnParentMethodCallRule.php
packages/phpstan-rules/src/ValueObject/Regex.php
packages/vendor-patches/tests/Finder/VendorFilesFinderTest.php

Closes https://github.com/symplify/symplify/issues/2695

Re-use node name resolver

---

packages/easy-coding-standard/packages/changed-files-detector/tests/ChangedFilesDetectorSource/OneClass.php
packages/easy-coding-standard/packages/changed-files-detector/tests/FileHashComputerSource/ChangedScannedClass.php
packages/easy-coding-standard/packages/changed-files-detector/tests/FileHashComputerSource/SomeScannedClass.php
packages/easy-coding-standard/packages/sniff-runner/tests/Application/FixerSource/SomeFile.php
packages/easy-coding-standard/packages/sniff-runner/tests/Error/ErrorSorterSource/SomeFile.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/NoEmptyClassRule.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipException.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipFinalChildOfAbstract.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipMarkerInterface.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipWithCommentAbove.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipWithCommentInterface.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipWithContent.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SomeEmptyClass.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/NoEmptyClassRuleTest.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Source/AbstractAnother.php
packages/set-config-resolver/src/ConfigResolver.php
packages/static-detector/src/NodeTraverser/StaticCollectNodeTraverser.php
packages/symplify-kernel/tests/Console/AbstractSymplifyConsoleApplication/AutowiredConsoleApplicationTest.php
packages/symplify-kernel/tests/HttpKernel/OnlyForTestsKernel.php
packages/template-checker/tests/SomeBundle/RealClassBundle.php
rector.php

Closes https://github.com/symplify/symplify/issues/2760

[PHPStanRules] Add NoEmptyClassRule

---

packages/coding-standard/src/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer.php
packages/coding-standard/src/Fixer/LineLength/LineLengthFixer.php
packages/coding-standard/src/Fixer/Spacing/StandaloneLinePromotedPropertyFixer.php
packages/coding-standard/src/TokenRunner/Transformer/FixerTransformer/LineLengthTransformer.php
packages/coding-standard/src/TokenRunner/Transformer/FixerTransformer/TokensNewliner.php
packages/coding-standard/src/TokenRunner/Whitespace/IndentResolver.php
packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/FixturePhp80/skip_property_promotion.php.inc
packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/Php80Test.php
packages/coding-standard/tests/Fixer/Spacing/StandaloneLinePromotedPropertyFixer/Fixture/promoted_properties.php.inc
packages/coding-standard/tests/Fixer/Spacing/StandaloneLinePromotedPropertyFixer/StandaloneLinePromotedPropertyFixerTest.php
packages/package-builder/src/Reflection/PrivatesAccessor.php
packages/sniffer-fixer-to-ecs-converter/phpunit.xml
packages/sniffer-fixer-to-ecs-converter/tests/bootstrap.php

```diff
-public function __construct(private string $name, private string $surname)
+public function __construct(
+    private string $name,
+    private string $surname
+)
{
}
```

[CodingStandard] Add promoted property newliner

---

packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNewlineInNestedAnnotationFixer/Fixture/attribute_overrides.php.inc

Tests for issue #2776 

---

packages/phpstan-rules/src/Rules/PreventDuplicateClassMethodRule.php
packages/phpstan-rules/tests/Rules/PreventDuplicateClassMethodRule/Fixture/SkipClassUseTrait1.php
packages/phpstan-rules/tests/Rules/PreventDuplicateClassMethodRule/Fixture/SkipClassUseTrait2.php
packages/phpstan-rules/tests/Rules/PreventDuplicateClassMethodRule/PreventDuplicateClassMethodRuleTest.php

[PHPStanRules] Skip check trait method content on PreventDuplicateClassMethodRule

---

.github/workflows/split_tests.yaml
README.md
composer.json
packages/amnesia/.gitattributes
packages/amnesia/.github/FUNDING.yml
packages/amnesia/.github/workflows/split_repository.yaml
packages/amnesia/.gitignore
packages/amnesia/LICENSE
packages/amnesia/README.md
packages/amnesia/composer.json
packages/amnesia/config/config.php
packages/amnesia/src/ValueObject/Symfony/Extension/TwigExtension.php
packages/astral/README.md
packages/astral/config/services.neon
packages/composer-json-manipulator/tests/ComposerJsonFactory/ComposerJsonFactoryTest.php
packages/composer-json-manipulator/tests/ComposerJsonFactory/Source/full_composer.json
packages/composer-json-manipulator/tests/ComposerJsonFactory/Source/some_composer.json
packages/easy-ci/bin/easy-ci.php
packages/easy-ci/src/HttpKernel/EasyCIKernel.php
packages/monorepo-builder/src/Command/PackagesJsonCommand.php
packages/monorepo-builder/src/Json/PackageJsonProvider.php
packages/monorepo-builder/src/Package/PackageProvider.php
packages/monorepo-builder/src/ValueObject/Option.php
packages/monorepo-builder/src/ValueObject/Package.php
packages/symfony-static-dumper/composer.json

Closes https://github.com/symplify/symplify/issues/2803

[Amnesia] Init new package

---

packages/monorepo-builder/packages/init/src/Command/InitCommand.php
packages/monorepo-builder/packages/init/templates/monorepo/monorepo-builder.php
packages/monorepo-builder/packages/init/templates/monorepo/monorepo-builder.yaml

Fixes https://github.com/symplify/symplify/issues/2828

[MonorepoBuilder] Update monorepo builder init to use PHP

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/ForbiddenThisArgumentRule.php
packages/phpstan-rules/tests/Rules/ForbiddenThisArgumentRule/Fixture/SkipExtendsKernel.php
packages/phpstan-rules/tests/Rules/ForbiddenThisArgumentRule/Fixture/SkipNotThis.php
packages/phpstan-rules/tests/Rules/ForbiddenThisArgumentRule/Fixture/SkipNotVariable.php
packages/phpstan-rules/tests/Rules/ForbiddenThisArgumentRule/Fixture/ThisArgument.php
packages/phpstan-rules/tests/Rules/ForbiddenThisArgumentRule/Fixture/ThisArgumentCopy.php
packages/phpstan-rules/tests/Rules/ForbiddenThisArgumentRule/ForbiddenThisArgumentRuleTest.php
phpstan.neon

[PHPStanRules] Add ForbiddenThisArgumentRule

---

packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/NodeAnalyzer/ConditionCounter.php
packages/phpstan-rules/src/NodeAnalyzer/IfReturnAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/ScalarAnalyzer.php
packages/phpstan-rules/src/Rules/ConstantMapRuleRule.php
packages/phpstan-rules/src/Types/ScalarTypeAnalyser.php
packages/phpstan-rules/src/ValueObject/ScalarAndNonScalarCounter.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/ConstantMapRuleRuleTest.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/ManyIfsThenStaticCall.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/SkipEmptyArray.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/SkipHalfHalf.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/SkipMethodsCalls.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/SkipSomeReflectionMethod.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/SkipVariousReturns.php
packages/phpstan-rules/tests/Rules/ConstantMapRuleRule/Fixture/TypicalMap.php

Closes https://github.com/symplify/symplify/issues/2700

[PHPStanRules] Add ConstantMapRuleRule

---

packages/changelog-linker/src/ChangelogCleaner.php
packages/changelog-linker/src/Console/Input/PriorityResolver.php
packages/composer-json-manipulator/src/ValueObject/ComposerJson.php
packages/config-transformer/src/DependencyInjection/Loader/IdAwareXmlFileLoader.php
packages/config-transformer/src/Guard/InputValidator.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/YamlToPhpTest.php
packages/easy-coding-standard/packages/changed-files-detector/src/FileHashComputer.php
packages/easy-coding-standard/src/Console/Output/OutputFormatterCollector.php
packages/easy-coding-standard/src/DependencyInjection/CompilerPass/ConflictingCheckersCompilerPass.php
packages/easy-coding-standard/src/DependencyInjection/CompilerPass/RemoveMutualCheckersCompilerPass.php
packages/easy-coding-standard/src/Git/GitDiffProvider.php
packages/latte-to-twig-converter/src/CaseConverter/LoopsCaseConverter.php
packages/monorepo-builder/packages/init/src/Composer/PackageNameVersionProvider.php
packages/monorepo-builder/packages/merge/src/ComposerJsonDecorator/FilterOutDuplicatedRequireAndRequireDevJsonDecorator.php
packages/package-builder/src/Strings/StringFormatConverter.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/NoNestedFuncCallRule.php
packages/phpstan-rules/tests/Rules/ForbiddenAssignInLoopRule/ForbiddenAssignInLoopRuleTest.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/Fixture/NestedFuncCall.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/Fixture/SkipCount.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/Fixture/SkipNonNested.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/NoNestedFuncCallRuleTest.php
packages/smart-file-system/src/SmartFileSystem.php

Closes https://github.com/symplify/symplify/issues/2835

[PHPStanRules] Add NoNestedFuncCallRule

---

.kodiak.toml
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/PhpDoc/BarePhpDocParser.php
packages/phpstan-rules/src/Rules/MatchingTypeConstantRule.php
packages/phpstan-rules/src/Rules/ValidNetteInjectRule.php
packages/phpstan-rules/tests/Rules/ForbiddenAssignInLoopRule/ForbiddenAssignInLoopRuleTest.php
packages/phpstan-rules/tests/Rules/ValidNetteInjectRule/Fixture/InvalidInject.php
packages/phpstan-rules/tests/Rules/ValidNetteInjectRule/Fixture/PrivateInject.php
packages/phpstan-rules/tests/Rules/ValidNetteInjectRule/Fixture/PrivateInjectMethod.php
packages/phpstan-rules/tests/Rules/ValidNetteInjectRule/Fixture/SkipCorrectInject.php
packages/phpstan-rules/tests/Rules/ValidNetteInjectRule/ValidNetteInjectRuleTest.php

Ref https://github.com/symplify/symplify/issues/2850

[PHPStanRules] Add ValidNetteInjectAnnotationRule

---

packages/amnesia/composer.json
packages/amnesia/src/Functions/env.php

Closes https://github.com/symplify/symplify/issues/2823

[Amnesia] Add env() function

---

packages/phpstan-rules/config/nette-rules.neon
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/config/symplify-rules.neon
packages/phpstan-rules/src/Nette/NetteInjectAnalyzer.php
packages/phpstan-rules/src/Rules/NoNetteInjectAndConstructorRule.php
packages/phpstan-rules/src/Rules/SingleNetteInjectMethodRule.php
packages/phpstan-rules/tests/Rules/NoNetteInjectAndConstructorRule/Fixture/InjectMethodAndConstructor.php
packages/phpstan-rules/tests/Rules/NoNetteInjectAndConstructorRule/Fixture/InjectPropertyAndConstructor.php
packages/phpstan-rules/tests/Rules/NoNetteInjectAndConstructorRule/Fixture/SkipOnlyConstructor.php
packages/phpstan-rules/tests/Rules/NoNetteInjectAndConstructorRule/NoNetteInjectAndConstructorRuleTest.php
packages/phpstan-rules/tests/Rules/SingleNetteInjectMethodRule/Fixture/DoubleInjectMethod.php
packages/phpstan-rules/tests/Rules/SingleNetteInjectMethodRule/Fixture/SkipAnotherNamedMethod.php
packages/phpstan-rules/tests/Rules/SingleNetteInjectMethodRule/Fixture/SkipSingleInjectMethod.php
packages/phpstan-rules/tests/Rules/SingleNetteInjectMethodRule/SingleNetteInjectMethodRuleTest.php
packages/smart-file-system/src/Json/JsonFileSystem.php
packages/symfony-static-dumper/src/Contract/ControllerWithDataProviderInterface.php

- Closes https://github.com/symplify/symplify/issues/2859
- Closes https://github.com/symplify/symplify/issues/2858

[PHPStanRules] Add nette-rules set and SingleNetteInjectMethodRule, NoNetteInjectAndConstructorRule

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/NoDynamicPropertyOnStaticCallRule.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/Fixture/DynamicMethodCall.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/Fixture/DynamicPropertyCall.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/Fixture/SkipNonDynamicMethodCall.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/Fixture/SkipNonDynamicProperty.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/Fixture/SkipNonDynamicPropertyCall.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/Fixture/SkipSelfStatic.php
packages/phpstan-rules/tests/Rules/NoDynamicPropertyOnStaticCallRule/NoDynamicPropertyOnStaticCallRuleTest.php

[PHPStanRules] Add NoDynamicPropertyOnStaticCallRule

---

packages/php-config-printer/src/Yaml/CheckerServiceParametersShifter.php

Fixes https://github.com/symplify/symplify/issues/2873

A patch to fix #2873

---

packages/phpstan-rules/src/Rules/PreferConstantValueRule.php
packages/phpstan-rules/tests/Rules/PreferConstantValueRule/Fixture/FoundInConstantValue.php
packages/phpstan-rules/tests/Rules/PreferConstantValueRule/Fixture/SkipNotFoundInConstantValue.php
packages/phpstan-rules/tests/Rules/PreferConstantValueRule/Fixture/SkipUseDefinedConstant.php
packages/phpstan-rules/tests/Rules/PreferConstantValueRule/PreferConstantValueRuleTest.php
packages/phpstan-rules/tests/Rules/PreferConstantValueRule/config/configured_rule.neon

[PHPStanRules] Add PreferConstantValueRule

---

.github/workflows/rector.yaml
packages/phpstan-rules/config/nette-rules.neon
packages/phpstan-rules/src/Rules/NoNetteDoubleTemplateAssignRule.php
packages/phpstan-rules/src/Rules/RequireTemplateInNetteControlRule.php
packages/phpstan-rules/tests/Rules/RequireTemplateInNetteControlRule/Fixture/ControlWithoutExplicitTemplate.php
packages/phpstan-rules/tests/Rules/RequireTemplateInNetteControlRule/Fixture/SkipWithSetFile.php
packages/phpstan-rules/tests/Rules/RequireTemplateInNetteControlRule/Fixture/SkipWithTemplateRender.php
packages/phpstan-rules/tests/Rules/RequireTemplateInNetteControlRule/RequireTemplateInNetteControlRuleTest.php

Closes https://github.com/symplify/symplify/issues/2892

[PHPStanRules] Add RequireTemplateInNetteControlRule

---

.github/workflows/rector.yaml
CHANGELOG.md
packages/changelog-linker/src/FileSystem/ChangelogFileSystem.php
packages/changelog-linker/tests/FileSystem/ChangelogFileSystem/ChangelogFileSystemTest.php
packages/changelog-linker/tests/FileSystem/ChangelogFileSystem/Source/EXPECTED_CHANGELOG_LIST_DATA.md
packages/phpstan-rules/src/Rules/NoNetteDoubleTemplateAssignRule.php

ref https://github.com/rectorphp/rector/pull/5386#issuecomment-770344327

[ChangelogLinker] Regex fix ChangelogFileSystem on multi digit number and - after []

---

packages/phpstan-php-config/composer.json

https://github.com/symplify/phpstan-php-config/issues/1

Fix "vendor/bin/phpstan-php-config" not being available

---

packages/coding-standard/src/Fixer/Spacing/StandaloneLinePromotedPropertyFixer.php
packages/package-builder/src/ValueObject/MethodName.php
packages/phpstan-rules/composer.json
packages/phpstan-rules/src/NodeAnalyzer/DependencyNodeAnalyzer.php
packages/phpstan-rules/src/Reflection/MethodNodeAnalyser.php
packages/phpstan-rules/src/Rules/CheckConstantExpressionDefinedInConstructOrSetupRule.php
packages/phpstan-rules/src/Rules/CheckParentChildMethodParameterTypeCompatibleRule.php
packages/phpstan-rules/src/Rules/ExclusiveDependencyRule.php
packages/phpstan-rules/src/Rules/ForbiddenArrayWithStringKeysRule.php
packages/phpstan-rules/src/Rules/ForbiddenDependencyByTypeRule.php
packages/phpstan-rules/src/Rules/InvokableControllerByRouteNamingRule.php
packages/phpstan-rules/src/Rules/NoConstructorInTestRule.php
packages/phpstan-rules/src/Rules/NoGetRepositoryOutsideConstructorRule.php
packages/phpstan-rules/src/Rules/NoNetteInjectAndConstructorRule.php
packages/phpstan-rules/src/Rules/PreventDuplicateClassMethodRule.php
packages/phpstan-rules/src/Rules/RequireInvokableControllerRule.php
packages/phpstan-rules/src/TypeAnalyzer/CallableTypeAnalyzer.php
packages/phpstan-rules/src/VariableAsParamAnalyser.php

Closes https://github.com/symplify/symplify/issues/2910

[PackageBuilder] Add MethodName value object with common method names

---

packages/phpstan-rules/src/Rules/NoEmptyClassRule.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Fixture/SkipEmptyClassWithImplements.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/NoEmptyClassRuleTest.php
packages/phpstan-rules/tests/Rules/NoEmptyClassRule/Source/AnInterface.php

ref https://github.com/rectorphp/rector/blob/ec66688a8c9d40e40f9bf526871c40f5e647bebf/phpstan.neon#L524

[PHPStanRules] Improve NoEmptyClassRule: skip if class has implements

---

packages/phpstan-rules/src/Rules/ExclusiveNamespaceRule.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/ExclusiveNamespaceRuleTest.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/Fixture/Presenter/Contract/SkipContract.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/Fixture/Presenter/Exception/SkipException.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/Fixture/Presenter/SkipPresenter.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/Fixture/Presenter/SkipSomeTest.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/Fixture/Presenter/SomeRepository.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/Fixture/SkipNotMatched.php
packages/phpstan-rules/tests/Rules/ExclusiveNamespaceRule/config/configured_rule.neon

Extract from @rectorphp https://github.com/rectorphp/rector/pull/5451

[PHPStanRules] Add ExclusiveNamespaceRule

---

packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/src/NodeAnalyzer/Symfony/SymfonyConfigMethodCallAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/Symfony/SymfonyConfigRectorValueObjectResolver.php
packages/phpstan-rules/src/NodeAnalyzer/Symfony/SymfonyPhpConfigClosureAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/TypeAndNameAnalyzer.php
packages/phpstan-rules/src/Rules/ForbiddenComplexArrayConfigInSetRule.php
packages/phpstan-rules/src/Rules/PreventDoubleSetParameterRule.php
packages/phpstan-rules/src/Rules/ServiceAndValueObjectHaveSameStartsRule.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/HaveDifferentStarts.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/SkipConfigureValueObjectImplementsInterface.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/SkipDifferentType.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/SkipHaveSameStarts.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/SkipNoCall.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/SkipNoCallConfigure.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Fixture/SkipNoInlineValueObjects.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/ServiceAndValueObjectHaveSameStartsRuleTest.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Source/ChangeMethodVisibilityRector.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Source/ConfigureValueObject.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Source/ConfigureValueObjectWithInterface.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/Source/ValueObjectInterface.php
packages/phpstan-rules/tests/Rules/ServiceAndValueObjectHaveSameStartsRule/config/configured_rule.neon

Mirror to https://github.com/rectorphp/rector/pull/5452/files
Import rule from @rectorphp for generic use

[PHPStanRules] Add ServiceAndValueObjectHaveSameStartsRule

---

.github/workflows/build_scoped_packages.yaml

Here should be ECS 9.1+ https://packagist.org/packages/symplify/easy-coding-standard-prefixed

[ECS] Tests build scoped version

---

packages/monorepo-builder/config/parameters.php
packages/monorepo-builder/packages/release/src/ReleaseWorker/PushNextDevReleaseWorker.php
packages/monorepo-builder/packages/release/src/ReleaseWorker/TagVersionReleaseWorker.php
packages/monorepo-builder/packages/testing/src/ComposerJson/ComposerVersionManipulator.php
packages/monorepo-builder/src/Command/PackageAliasCommand.php
packages/monorepo-builder/src/DevMasterAliasUpdater.php
packages/monorepo-builder/src/ValueObject/Option.php

Fixes https://github.com/symplify/symplify/issues/2957

[MonorepoBuilder] Add DEFAULT_BRANCH_NAME parameter

---

packages/rule-doc-generator/src/ValueObject/RuleDefinition.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/configurable_phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/configurable_phpstan_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/phpstan_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/composer_json_aware_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/configurable_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/extra_file_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_categorized.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_content.md

refs https://github.com/symplify/symplify/pull/2983#discussion_r579727391

[RuleDocGenerator] Ensure rule file path has / prefix in generation

---

composer.json
packages/monorepo-builder/composer.json
packages/monorepo-builder/packages/release/src/ReleaseWorker/TagVersionReleaseWorker.php

[MonorepoBuilder] Use original version string for tag

---

packages/easy-testing/src/DataProvider/StaticFixtureFinder.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/NoNullablePropertyRule.php
packages/phpstan-rules/tests/Rules/NoNullablePropertyRule/Fixture/NullableProperty.php
packages/phpstan-rules/tests/Rules/NoNullablePropertyRule/Fixture/SkipNoType.php
packages/phpstan-rules/tests/Rules/NoNullablePropertyRule/NoNullablePropertyRuleTest.php

[PHPStanRules]  Add NoNullablePropertyRule

---

packages/changelog-linker/src/Github/GithubApi.php

[CL] Fix get pull requests since id without base-branch option

---

packages/changelog-linker/src/FileSystem/ChangelogFileSystem.php
packages/changelog-linker/tests/FileSystem/ChangelogFileSystem/ChangelogFileSystemTest.php
packages/phpstan-rules/src/Rules/NoInheritanceRule.php
phpstan.neon

ref https://github.com/rectorphp/rector/issues/5666#issuecomment-787429707

[ChangelogLinker] Auto create CHANGELOG.md when CHANGELOG.md not exists on dump-merges command

---

packages/easy-coding-standard/config/services.php
packages/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php

```bash
vendor/bin/ecs check src
```
```bash
vendor/bin/ecs src
```

[ECS] Make check command run by default

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/NoMagicClosureRule.php
packages/phpstan-rules/tests/Rules/NoMagicClosureRule/Fixture/MagicClosure.php
packages/phpstan-rules/tests/Rules/NoMagicClosureRule/Fixture/SkipClosureAssign.php
packages/phpstan-rules/tests/Rules/NoMagicClosureRule/NoMagicClosureRuleTest.php

Fixes https://github.com/symplify/symplify/issues/2988

[PHPStanRules] Add NoMagicClosureRule

---

packages/git-wrapper/src/Process/GitProcess.php
packages/monorepo-builder/packages/merge/src/Arrays/ArraySorter.php
packages/php-config-printer/src/Sorter/YamlArgumentSorter.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/NoBinaryOpCallCompareRule.php
packages/phpstan-rules/src/Rules/ServiceAndValueObjectHaveSameStartsRule.php
packages/phpstan-rules/tests/Rules/NoBinaryOpCallCompareRule/Fixture/CompareToFuncCall.php
packages/phpstan-rules/tests/Rules/NoBinaryOpCallCompareRule/Fixture/SkipAssign.php
packages/phpstan-rules/tests/Rules/NoBinaryOpCallCompareRule/Fixture/SkipConcat.php
packages/phpstan-rules/tests/Rules/NoBinaryOpCallCompareRule/Fixture/SkipFuncCallCount.php
packages/phpstan-rules/tests/Rules/NoBinaryOpCallCompareRule/NoBinaryOpCallCompareRuleTest.php
phpstan.neon

Closes https://github.com/symplify/symplify/issues/3013

[PHPStanRules] Add NoBinaryOpCallCompareRule

---

packages/phpstan-rules/docs/rules_overview.md
packages/phpstan-rules/src/Rules/CheckTypehintCallerTypeRule.php
packages/phpstan-rules/src/Rules/CheckUnneededSymfonyStyleUsageRule.php
packages/rule-doc-generator/src/Command/GenerateCommand.php
packages/rule-doc-generator/src/RuleDefinitionsResolver.php
packages/rule-doc-generator/src/ValueObject/RuleDefinition.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/configurable_phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/configurable_phpstan_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/phpstan_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/composer_json_aware_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/configurable_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/extra_file_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_categorized.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_content.md
packages/smart-file-system/src/SmartFileInfo.php

Ref https://twitter.com/BackEndTea/status/1369988782913622021

[RuleDocGenerator] Attempt to fix relative paths

---

packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/SwitchedTypeAndNameMalformWorker.php
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/wrong3.php.inc

[CodingStandard] Handle piped type switched in ParamReturnAndVarTagMalformsFixer

---

.github/workflows/build_ecs_prefixed.yaml
build/ecs-scoped/target-repository/.github/workflows/bare_run.yaml

This should make bugs https://github.com/symplify/symplify/issues/3056 easier to discover
Tests are now missing in https://github.com/symplify/easy-coding-standard-prefixed, this should add at least bare run

[ECS] add .github wofklows to prefixed version

---

packages/simple-php-doc-parser/src/PhpDocNodeTraverser.php
phpstan.neon

Ref https://github.com/rectorphp/rector/pull/5780/checks?check_run_id=2112374405

Trying to fix traverse loop

---

packages/coding-standard/src/Fixer/Annotation/DoctrineAnnotationNewlineInNestedAnnotationFixer.php
packages/coding-standard/src/TokenAnalyzer/SymfonyClosureAnalyzer.php
packages/composer-json-manipulator/tests/ComposerJsonFactory/ComposerJsonFactoryTest.php
packages/easy-coding-standard/scoper.inc.php

[EasyCodingStandard] Fixes Scoper replace Composer\InstalledVersions prefix on ECS scoper config

---

packages/composer-json-manipulator/src/ComposerJsonFactory.php
packages/composer-json-manipulator/src/ValueObject/ComposerJson.php
packages/composer-json-manipulator/src/ValueObject/ComposerJsonSection.php
packages/composer-json-manipulator/tests/ComposerJsonFactory/Source/full_composer.json

[TASK] Keep version in composer.json if exists

---

packages/easy-coding-standard/scoper.inc.php
packages/git-wrapper/src/GitCommits.php
packages/git-wrapper/tests/GitWorkingCopyTest.php

[ECS] Fix reserved keyword parent in ECS scoper

---

.github/workflows/test_ecs_prefixed.yaml

Fixes https://github.com/symplify/symplify/issues/3102

[ECS] Use dev-main for test ECS prefixed on merge

---

.github/workflows/test_ecs_prefixed.yaml
packages/phpstan-extensions/src/Testing/AbstractServiceAwareRuleTestCase.php
packages/phpstan-rules/tests/Rules/CheckConstantExpressionDefinedInConstructOrSetupRule/Fixture/SkipAllowMagicConstantWithConcatMethodCall.php
packages/phpstan-rules/tests/Rules/CheckConstantExpressionDefinedInConstructOrSetupRule/Fixture/SkipAssignOfVariable.php
packages/phpstan-rules/tests/Rules/CheckConstantExpressionDefinedInConstructOrSetupRule/Fixture/SkipInConstructOrSetUpMethod.php

Reverts symplify/symplify#3106

Revert "[ECS] Remove test ECS prefixed action on merge"

---

.github/workflows/test_ecs_prefixed.yaml

Fixing test ecs prefixed on merge (2)

---

composer.json
packages/easy-coding-standard/composer.json
packages/sniffer-fixer-to-ecs-converter/composer.json

Based on https://github.com/symplify/symplify/pull/3107#issuecomment-822255227

Use squizlabs/php_codesniffer:^3.6

---

composer.json
packages/git-wrapper/composer.json

:eyes: 
None of [BC changes](https://github.com/OndraM/ci-detector/blob/main/CHANGELOG.md#400---2021-02-02) have impact here.

[GitWrapper] Update dev-dependency

---

packages/phpstan-extensions/composer.json
packages/phpstan-extensions/config/php.level.neon

Make use of https://github.com/phpstan/extension-installer

[PHPStanExtensions] Add config phpstan/extension-installer

---

packages/easy-coding-standard-tester/src/Testing/AbstractCheckerTestCase.php
packages/easy-coding-standard/src/Error/ErrorAndDiffResultFactory.php
packages/easy-coding-standard/src/Reporter/ProcessedFileReporter.php
packages/easy-coding-standard/tests/Console/Output/JsonOutputFormatterTest.php
packages/easy-coding-standard/tests/Error/ErrorCollector/SniffFileProcessorTest.php
packages/phpstan-rules/config/services-rules.neon
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/docs/rules_overview.md
packages/phpstan-rules/packages/cognitive-complexity/config/cognitive-complexity-services.neon
packages/phpstan-rules/packages/cognitive-complexity/src/AstCognitiveComplexityAnalyzer.php
packages/phpstan-rules/packages/cognitive-complexity/src/NodeTraverser/ComplexityNodeTraverserFactory.php
packages/phpstan-rules/src/Naming/ClassNameAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/ConstructorDefinedPropertyNodeAnalyzer.php
packages/phpstan-rules/src/Rules/AbstractSymplifyRule.php
packages/phpstan-rules/src/Rules/NoDependencyJugglingRule.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/JugglingDependency.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/SkipArray.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/SkipFactory.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/SkipFactoryMethod.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/SkipNodeVisitor.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/SkipPrivatesCaller.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Fixture/ValueObject/SkipValueObject.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/NoDependencyJugglingRuleTest.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/Source/JuggleBall.php
packages/phpstan-rules/tests/Rules/NoDependencyJugglingRule/config/configured_rule.neon
packages/set-config-resolver/src/SetAwareConfigResolver.php
phpstan.neon

Closes https://github.com/symplify/symplify/issues/3110

[PHPStanRules] Add NoDependencyJugglingRule

---

packages/coding-standard/src/Fixer/LineLength/DocBlockLineLengthFixer.php
packages/composer-json-manipulator/src/ValueObject/ComposerJson.php
packages/easy-coding-standard-tester/src/Testing/AbstractCheckerTestCase.php
packages/easy-coding-standard/src/Console/Reporter/CheckerListReporter.php
packages/easy-hydrator/src/ArrayToValueObjectHydrator.php
packages/monorepo-builder/packages/merge/src/ComposerJsonDecorator/SortComposerJsonDecorator.php
packages/package-builder/README.md
packages/php-config-printer/config/config.php
packages/phpstan-rules/src/Rules/NoNestedFuncCallRule.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/Fixture/NestedArrayFilter.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/Fixture/NestedYourself.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/NoNestedFuncCallRuleTest.php
packages/static-detector/config/config.php
packages/symfony-static-dumper/src/HttpFoundation/ControllerContentResolver.php

Closes https://github.com/symplify/symplify/issues/3068
Closes https://github.com/symplify/symplify/issues/3143

[PHPStanRules] Make NoNestedFuncCallRule work for nested expressions

---

packages/easy-coding-standard/README.md

Sorry for the PR on the wrong repo, I hope this is the right one now. 🙂

 Update README to add -prefix install command

---

packages/easy-coding-standard/config/set/common/spaces.php
packages/easy-coding-standard/config/set/php-cs-fixer.php

[ECS] ClassAttributesSeparationFixer updated

---

.github/workflows/code_analysis.yaml
packages/vendor-patches/config/config.php
packages/vendor-patches/src/Console/VendorPatchesConsoleApplication.php

Closes https://github.com/symplify/symplify/issues/3188

[VendorPatches] Add missing console app

---

composer.json
packages/phpstan-rules/src/Rules/SuffixInterfaceRule.php
packages/phpstan-rules/src/Rules/SuffixTraitRule.php
packages/phpstan-rules/tests/Rules/SuffixInterfaceRule/Fixture/NotAnInterface.php
packages/phpstan-rules/tests/Rules/SuffixInterfaceRule/SuffixInterfaceRuleTest.php
packages/phpstan-rules/tests/Rules/SuffixTraitRule/Fixture/SomeNotTrait.php
packages/phpstan-rules/tests/Rules/SuffixTraitRule/SuffixTraitRuleTest.php
tests/bootstrap.php

Closes https://github.com/symplify/symplify/issues/3190

[PHPStanRules] Make sure Trait suffix and Interface suffix IS NOT on invalid class type, e.g. Trait cannot be on class or interface

---

packages/autowire-array-parameter/src/Skipper/ParameterSkipper.php
packages/symfony-php-config/src/ValueObjectInliner.php

Reverts symplify/symplify#3202

Revert "[Autowire] remove @noRector on ParameterSkipper const"

---

packages/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Reflection/MethodNodeAnalyser.php
packages/phpstan-rules/src/Rules/ForbiddenParamTypeRemovalRule.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Fixture/RemoveParentType.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Fixture/SkipIndirectRemoval.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Fixture/SkipNoType.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Fixture/SkipPhpDocType.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Fixture/SkipPresentType.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/ForbiddenParamTypeRemovalRuleTest.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Source/NoTypeInterface.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Source/PhpDocType.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Source/SomeNode.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/Source/SomeRectorInterface.php
packages/phpstan-rules/tests/Rules/ForbiddenParamTypeRemovalRule/config/configured_rule.neon

Helps to identify removed param-variance https://github.com/sabbelasichon/typo3-rector/commit/ab33106ea7cd0baeb29647a794d628bd857e0ea1

[PHPStanRules] Add ForbiddenParamTypeRemovalRule

---

packages/phpstan-rules/config/nette-rules.neon
packages/phpstan-rules/src/Nette/NetteInjectAnalyzer.php
packages/phpstan-rules/src/PhpDoc/BarePhpDocParser.php
packages/phpstan-rules/src/Rules/ForbiddenNetteInjectPropertyAssignRule.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/Fixture/OverrideInjectedVariable.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/Fixture/OverrideParentInject.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/Fixture/SkipCurrentMethodInject.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/Fixture/SkipNonInjectAssign.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/ForbiddenNetteInjectPropertyAssignRuleTest.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/Source/AbstractInjectParentClass.php
packages/phpstan-rules/tests/Rules/ForbiddenNetteInjectPropertyAssignRule/config/configured_rule.neon

Closes https://github.com/symplify/symplify/issues/3216

[PHPStanRules] Add ForbiddenNetteInjectPropertyAssignRule

---

packages/phpstan-rules/src/Rules/NoVoidGetterMethodRule.php
packages/skipper/README.md

Fixes https://github.com/symplify/symplify/pull/3238#discussion_r637873393

[Typo] Typo fix somethign -> something

---

packages/easy-coding-standard/scoper.php

Unprefix the PHPUnit\Framework\TestCase class

---

packages/monorepo-builder/packages-tests/Testing/ComposerJson/ComposerJsonSymlinkerTest.php
packages/monorepo-builder/packages-tests/Testing/ComposerJson/Fixture/expected_deeper_path_repository.json
packages/monorepo-builder/packages-tests/Testing/ComposerJson/packages/with-more-depth/package-four/composer.json
packages/monorepo-builder/packages-tests/Testing/PathResolver/PackagePathResolverTest.php
packages/monorepo-builder/packages/Testing/ComposerJson/ComposerJsonSymlinker.php
packages/monorepo-builder/packages/Testing/ComposerJsonRepositoriesUpdater.php
packages/monorepo-builder/packages/Testing/PathResolver/PackagePathResolver.php

[Monorepo Builder] Fix error when packages have different depth to the root

---

packages/package-builder/src/DependencyInjection/FileLoader/ParameterMergingPhpFileLoader.php

ref https://github.com/rectorphp/rector-src/pull/134

[PackageBuilder] Fix ParameterMergingPhpFileLoader::load()

---

packages/easy-coding-standard/scoper.php

This reverts commit 0431749548aa02c22cd1d4322c765e8fdf066805.

Revert "use local patching"

---

packages/phpstan-rules/README.md

Closes https://github.com/symplify/symplify/issues/3256

Added docs regarding additional service definitions

---

.github/workflows/lock_threads.yaml

Closes https://github.com/symplify/symplify/issues/3275

GithubAction: don‘t run lock-threads on forks

---

.github/workflows/daily_pull_request.yaml

Similar to https://github.com/symplify/symplify/issues/3275
These jobs error in forks

GithubAction: dont run daily cron on forks

---

.github/workflows/weekly_pull_requests.yaml

Similar to https://github.com/symplify/symplify/issues/3275
These jobs error in forks

GithubAction: dont run weekly cron on forks

---

packages/phpstan-rules/config/symfony-rules.neon
packages/phpstan-rules/src/Rules/Symfony/RequireNativeArraySymfonyRenderCallRule.php
packages/phpstan-rules/tests/Rules/Symfony/RequireNativeArraySymfonyRenderCallRule/Fixture/ParameterAsSecondArgument.php
packages/phpstan-rules/tests/Rules/Symfony/RequireNativeArraySymfonyRenderCallRule/Fixture/SkipCorrectControllerRender.php
packages/phpstan-rules/tests/Rules/Symfony/RequireNativeArraySymfonyRenderCallRule/Fixture/SkipNoSecondArgument.php
packages/phpstan-rules/tests/Rules/Symfony/RequireNativeArraySymfonyRenderCallRule/RequireNativeArraySymfonyRenderCallRuleTest.php
packages/phpstan-rules/tests/Rules/Symfony/RequireNativeArraySymfonyRenderCallRule/config/configured_rule.neon

Closes https://github.com/symplify/symplify/issues/3267

[PHPStanRules] Add RequireNativeArraySymfonyRenderCallRule

---

packages/phpstan-rules/src/PhpDoc/ClassAnnotationResolver.php
packages/phpstan-rules/src/PhpDoc/FullyQualifyingPhpDocNodeVisitor.php
packages/phpstan-rules/src/Rules/Missing/CheckRequiredClassInAnnotationRule.php
packages/phpstan-rules/tests/Rules/Missing/CheckRequiredClassInAnnotationRule/CheckRequiredClassInAnnotationRuleTest.php
packages/phpstan-rules/tests/Rules/Missing/CheckRequiredClassInAnnotationRule/Fixture/NonExistingClassAnnotationInConstantFetch.php
packages/phpstan-rules/tests/Rules/Missing/CheckRequiredClassInAnnotationRule/Fixture/SkipExistingClassAnnotationWithConstant.php

- misc
- [PHStanRules] Add costnat check too

[PHStanRules] Add constant check too

---

packages/phpstan-rules/src/Rules/NoMaskWithoutSprintfRule.php
packages/phpstan-rules/tests/Rules/NoMaskWithoutSprintfRule/Fixture/SkipIdentical.php
packages/phpstan-rules/tests/Rules/NoMaskWithoutSprintfRule/NoMaskWithoutSprintfRuleTest.php

Ref https://github.com/rectorphp/rector-src/pull/207/checks?check_run_id=2807810751#step:5:45

[PHPStanRules] Skip BinaryOp on NoMaskWithoutSprintfRule

---

ecs.php
packages/easy-coding-standard/packages-tests/Parallel/Command/WorkerCommandLineFactoryTest.php
packages/easy-coding-standard/packages/FixerRunner/Application/FixerFileProcessor.php
packages/easy-coding-standard/packages/Parallel/Application/ParallelFileProcessor.php
packages/easy-coding-standard/packages/Parallel/Command/WorkerCommandLineFactory.php
packages/easy-coding-standard/packages/Parallel/CpuCoreCountProvider.php
packages/easy-coding-standard/packages/Parallel/FileSystem/FilePathNormalizer.php
packages/easy-coding-standard/packages/Parallel/Scheduler.php
packages/easy-coding-standard/packages/Parallel/ValueObject/Action.php
packages/easy-coding-standard/packages/Parallel/ValueObject/Bridge.php
packages/easy-coding-standard/packages/Parallel/ValueObject/StreamBuffer.php
packages/easy-coding-standard/packages/SniffRunner/Application/SniffFileProcessor.php
packages/easy-coding-standard/src/Application/EasyCodingStandardApplication.php
packages/easy-coding-standard/src/Configuration/ConfigurationFactory.php
packages/easy-coding-standard/src/Console/Command/CheckCommand.php
packages/easy-coding-standard/src/Console/Command/WorkerCommand.php
packages/easy-coding-standard/src/Console/Output/ConsoleOutputFormatter.php
packages/easy-coding-standard/src/Reporter/ProcessedFileReporter.php
packages/easy-coding-standard/src/ValueObject/Configuration.php
packages/easy-coding-standard/src/ValueObject/Error/ErrorAndDiffResult.php
phpstan.neon

Ref https://github.com/symplify/symplify/issues/3313

[ECS] Making Encode/Decode aproach work with json - part #4

---

ecs.php
packages/easy-coding-standard/src/Console/Command/WorkerCommand.php
packages/easy-coding-standard/src/DependencyInjection/DelegatingLoaderFactory.php
packages/easy-coding-standard/src/DependencyInjection/EasyCodingStandardContainerFactory.php
packages/easy-coding-standard/src/HttpKernel/EasyCodingStandardKernel.php

Ref https://github.com/symplify/symplify/issues/3313

use ECS cache kernel with constant value

---

composer.json
packages/php-config-printer/src/NodeTraverser/ImportFullyQualifiedNamesNodeTraverser.php
packages/php-config-printer/src/ValueObject/FullyQualifiedImport.php
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/Complexity/ForbiddenArrayMethodCallRule.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenArrayMethodCallRule/Fixture/ReturnCallable.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenArrayMethodCallRule/Fixture/SkipNormalArray.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenArrayMethodCallRule/ForbiddenArrayMethodCallRuleTest.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenArrayMethodCallRule/config/configured_rule.neon

- bump rector
- [PHPStanRules] Add ForbiddenArrayMethodCallRule

[PHPStanRules] Add ForbiddenArrayMethodCallRule

---

.github/workflows/weekly_pull_requests.yaml

Like in https://github.com/rectorphp/rector-src/pull/309

Use auto-merge on weekly PR

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_arguments.yaml
packages/php-config-printer/src/NodeFactory/ArgsNodeFactory.php
packages/php-config-printer/src/ValueObject/FunctionName.php

Import these just like any other function.

[ConfigTransformer] Import `tagged_iterator` and `tagged_locator`

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/resource_arguments_and_bind.yaml
packages/php-config-printer/src/NodeFactory/CommonNodeFactory.php
packages/php-config-printer/src/ServiceOptionConverter/BindAutowireAutoconfigureServiceOptionKeyYamlToPhpFactory.php

Somehow only `false` was supported.

[ConfigTransformer] Support `true` as auto bind value on resources

---

packages/coding-standard/src/TokenAnalyzer/DoctrineAnnotationElementAnalyzer.php
packages/config-transformer/build/config/config-downgrade.php
packages/easy-coding-standard/build/config/config-downgrade.php
packages/easy-coding-standard/src/HttpKernel/EasyCodingStandardKernel.php
packages/monorepo-builder/build/config/config-downgrade.php
packages/phpstan-rules/config/configurable-rules.neon
packages/psr4-switcher/src/Configuration/Psr4SwitcherConfiguration.php
packages/psr4-switcher/src/ValueObjectFactory/Psr4NamespaceToPathFactory.php

Possibly solves https://github.com/symplify/symplify/issues/3398

[ECS] Fix frozen container on different configs

---

.github/workflows/code_analysis.yaml
packages/easy-ci/src/Command/CheckCommentedCodeCommand.php
packages/easy-ci/src/Comments/CommentedCodeAnalyzer.php
packages/easy-ci/src/ValueObject/Option.php
packages/easy-ci/tests/Comments/CommentedCodeAnalyzerTest.php
packages/easy-ci/tests/Comments/Fixture/some_commented_code.php.inc
packages/easy-coding-standard/src/HttpKernel/EasyCodingStandardKernel.php
packages/easy-coding-standard/tests/HttpKernel/EasyCodingStandardKernelTest.php

See https://github.com/symplify/symplify/issues/3395

[EasyCI] Add check-commented-code command

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/ForbiddenForeachEmptyMissingArrayRule.php
packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/Fixture/OnEmptyMissingArray.php
packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/Fixture/SkipCoalesceMethodCall.php
packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/Fixture/SkipCoalesceNotEmptyMissingArray.php
packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/Fixture/SkipNotEmpty.php
packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/ForbiddenForeachEmptyMissingArrayRuleTest.php
packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/config/configured_rule.neon

Fixes https://github.com/symplify/symplify/issues/3232

[PHPStanRules] Add ForbiddenForeachEmptyMissingArrayRule

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_parent.yaml
packages/php-config-printer/src/ServiceOptionConverter/ParentServiceOptionKeyYamlToPhpFactory.php
packages/php-config-printer/src/ValueObject/YamlKey.php

Cherry pick of https://github.com/symplify/symplify/pull/3389
- [PhpConfigTransformer] Support `parent` on `service`
- [ConfigTransformer] Add support for parent() call on service

[PhpConfigTransformer] Add support for parent() on service

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_lazy.yaml
packages/php-config-printer/src/ServiceOptionConverter/ParentLazyServiceOptionKeyYamlToPhpFactory.php
packages/php-config-printer/src/ValueObject/YamlKey.php

Merge and fix of https://github.com/symplify/symplify/pull/3390

[ConfigTransformer] Add lazy() keyword support on service

---

packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/DoctrineBlockFinder.php
packages/monorepo-builder/packages-tests/Merge/Package/CombineStringsToArrayJsonMerger/CombineStringsToArrayJsonMergerTest.php
packages/monorepo-builder/src/FileSystem/ComposerJsonProvider.php
packages/php-config-printer/src/NodeFactory/Service/AutoBindNodeFactory.php
packages/phpstan-rules/config/code-complexity-rules.neon
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/src/PhpDoc/PhpDocResolver.php
packages/phpstan-rules/src/Rules/Complexity/ForbiddenInlineClassMethodRule.php
packages/phpstan-rules/src/Rules/ForbiddenNodeRule.php
packages/phpstan-rules/src/Rules/NoClassWithStaticMethodWithoutStaticNameRule.php
packages/phpstan-rules/src/Rules/SeeAnnotationToTestRule.php
packages/phpstan-rules/src/TypeAnalyzer/ForbiddenAllowedTypeAnalyzer.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenInlineClassMethodRule/Fixture/SkipNoMethodCall.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenInlineClassMethodRule/Fixture/SkipUsedTwice.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenInlineClassMethodRule/Fixture/SomeClassWithInlinedMethod.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenInlineClassMethodRule/ForbiddenInlineClassMethodRuleTest.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenInlineClassMethodRule/config/configured_rule.neon
packages/phpstan-rules/tests/Rules/NoClassWithStaticMethodWithoutStaticNameRule/NoClassWithStaticMethodWithoutStaticNameRuleTest.php
phpstan.neon

Closes https://github.com/symplify/symplify/issues/3369

[PHPStanRules] Add ForbiddenInlineClassMethodRule

---

packages/easy-coding-standard/scoper.php

Reverts symplify/symplify#3422

Revert "[ECS] Add additional patcher to scoper.php"

---

packages/easy-testing/src/StaticFixtureSplitter.php
packages/php-config-printer/src/Printer/ArrayDecorator/ServiceConfigurationDecorator.php
packages/php-config-printer/tests/Printer/SmartPhpConfigPrinter/Fixture/expected_value_objects_file2.php.inc
packages/php-config-printer/tests/Printer/SmartPhpConfigPrinter/SmartPhpConfigPrinterTest.php
packages/phpstan-rules/packages/cognitive-complexity/src/CompositionOverInheritanceAnalyzer.php
packages/phpstan-rules/packages/cognitive-complexity/tests/AstCognitiveComplexityAnalyzer/AstCognitiveComplexityAnalyzerTest.php
packages/phpstan-rules/packages/cognitive-complexity/tests/CompositionOverInheritanceAnalyzer/CompositionOverInheritanceAnalyzerTest.php

Fixes https://github.com/symplify/symplify/issues/3441

[PhpConfigPrinter] Handle associative array for config printer

---

packages/phpstan-rules/config/doctrine-rules.neon
packages/phpstan-rules/src/Naming/BoolishNameAnalyser.php

- add equals, match and matches
- [PHPStanRules] Skip entity maanger in event subscribers

[PHPStanRules] Skip entity maanger in event subscribers

---

packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/Rules/Domain/RequireAttributeNamespaceRule.php
packages/phpstan-rules/tests/Rules/Domain/RequireAttributeNamespaceRule/Fixture/Attribute/SkipCorrectAttribute.php
packages/phpstan-rules/tests/Rules/Domain/RequireAttributeNamespaceRule/Fixture/MisslocatedAttribute.php
packages/phpstan-rules/tests/Rules/Domain/RequireAttributeNamespaceRule/RequireAttributeNamespaceRuleTest.php
packages/phpstan-rules/tests/Rules/Domain/RequireAttributeNamespaceRule/config/configured_rule.neon

- add equals, match and matches
- [PHPStanRules] Add RequireAttributeNamespaceRule

[PHPStanRules] Add RequireAttributeNamespaceRule

---

packages/composer-json-manipulator/src/FileSystem/JsonFileManager.php
packages/easy-coding-standard/scoper.php
packages/easy-coding-standard/src/Testing/PHPUnit/AbstractCheckerTestCase.php
packages/monorepo-builder/tests/FileSystem/JsonFileManager/JsonFileManagerTest.php

This might help with https://github.com/symplify/symplify/issues/3424

[ECS] Remove test dependency on AbstractKernelTestCase

---

packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/DoctrineBlockFinder.php
packages/easy-ci/src/Latte/Analyzer/ForbiddenVariableConstantOrCallAnalyzer.php
packages/easy-ci/src/Latte/Analyzer/MissingClassConstantLatteAnalyzer.php
packages/easy-ci/src/Latte/Analyzer/MissingClassStaticCallLatteAnalyzer.php
packages/easy-ci/src/Latte/Analyzer/MissingClassesLatteAnalyzer.php
packages/easy-ci/src/Latte/Analyzer/SingleColonLatteAnalyzer.php
packages/easy-coding-standard/packages/FixerRunner/WhitespacesFixerConfigFactory.php
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/src/NodeAnalyzer/SprintfSpecifierTypeResolver.php
packages/phpstan-rules/src/Rules/Missing/CheckReferencedClassInAnnotationRule.php
packages/phpstan-rules/src/Rules/Missing/CheckSprinfMatchingTypesRule.php
packages/phpstan-rules/src/Rules/RequireNewArgumentConstantRule.php
packages/phpstan-rules/src/TypeAnalyzer/MatchingTypeAnalyzer.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/CheckSprinfMatchingTypesRuleTest.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/Fixture/MissMatchSprinft.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/Fixture/SkipCorrectForeachKey.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/Fixture/SkipCorrectSprinft.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/Fixture/SkipToString.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/Source/SomeToString.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/config/configured_rule.neon
packages/symfony-static-dumper/tests/Application/SymfonyStaticDumperApplicationTest.php

Closes https://github.com/symplify/symplify/issues/3448

[PHPStanRules] Add CheckSprinfMatchingTypesRule

---

packages/psr4-switcher/config/config.php
packages/psr4-switcher/src/Console/PSR4SwitcherConsoleApplication.php

Closes https://github.com/symplify/symplify/issues/3455

[PSR-4 Switcher] Add missing console app

---

packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/config/static-rules.neon
packages/phpstan-rules/docs/rules_overview.md
packages/phpstan-rules/src/Rules/ExclusiveDependencyRule.php
packages/phpstan-rules/src/Rules/Explicit/ValueObjectOverArrayShapeRule.php
packages/phpstan-rules/src/Rules/ForbiddenCallOnTypeRule.php
packages/phpstan-rules/src/Rules/ForbiddenDependencyByTypeRule.php
packages/phpstan-rules/src/Rules/NoDependencyJugglingRule.php
packages/phpstan-rules/tests/Rules/Explicit/ValueObjectOverArrayShapeRule/Fixture/SkipJsonSerializable.php
packages/phpstan-rules/tests/Rules/Explicit/ValueObjectOverArrayShapeRule/Fixture/SkipNoArrayShape.php
packages/phpstan-rules/tests/Rules/Explicit/ValueObjectOverArrayShapeRule/Fixture/SomeArrayShapeReturn.php
packages/phpstan-rules/tests/Rules/Explicit/ValueObjectOverArrayShapeRule/ValueObjectOverArrayShapeRuleTest.php
packages/phpstan-rules/tests/Rules/Explicit/ValueObjectOverArrayShapeRule/config/configured_rule.neon

Closes https://github.com/symplify/symplify/issues/3475

[PHPStanRules] Add ValueObjectOverArrayShapeRule

---

packages/easy-coding-standard/config/services.php
packages/easy-coding-standard/src/Application/EasyCodingStandardApplication.php
packages/easy-coding-standard/src/Console/Command/WorkerCommand.php

The try to fix results merging issue (#3467).

[ECS] Fix result merging

---

packages/php-config-printer/src/PhpParser/NodeFactory/ConfiguratorClosureNodeFactory.php
rector.php

Closes https://github.com/symplify/symplify/issues/3493

[PhpConfigPrinter] Make oruter configurator string to avoid prefixing

---

composer.json
packages/easy-coding-standard/src/ValueObject/Error/SystemError.php
packages/phpstan-rules/composer.json
packages/phpstan-rules/src/NodeAnalyzer/SprintfSpecifierTypeResolver.php
packages/phpstan-rules/src/NodeAnalyzer/Symfony/Twig/MissingTwigTemplateRenderVariableResolver.php
packages/phpstan-rules/src/NodeAnalyzer/Symfony/Twig/TwigVariableNamesResolver.php
packages/phpstan-rules/src/Twig/NodeVisitor/VariableCollectingNodeVisitor.php
phpstan.neon

Follow up to https://github.com/symplify/symplify/pull/3505/files

[PHPStanRules] Make use of existing environment

---

packages/phpstan-rules/config/symfony-rules.neon
packages/phpstan-rules/packages/symfony/config/symfony-rules.neon
packages/phpstan-rules/packages/symfony/config/symfony-services.neon
packages/phpstan-rules/packages/symfony/src/Rules/NoTwigMissingMethodCallRule.php
packages/phpstan-rules/packages/symfony/src/Twig/TwigNodeVisitor/MissingMethodCallNodeVisitor.php
packages/phpstan-rules/packages/symfony/src/TypeAnalyzer/TemplateVariableTypesResolver.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Fixture/SkipExistingMethod.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Fixture/SomeMissingVariableController.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/NoTwigMissingMethodCallRuleTest.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Source/SomeType.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Source/non_existing_method.twig
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Source/skip_existing_method.twig
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/config/configured_rule.neon
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingVariableRule/Fixture/SomeMissingVariableController.php
phpstan.neon

First kick-off for simple direct method access.
The next step is foreach :)

[PHPStanRules] Add NoTwigMissingMethodCallRule

---

packages/astral/src/NodeValue/NodeValueResolver.php
packages/phpstan-rules/packages/symfony/config/symfony-services.neon
packages/phpstan-rules/packages/symfony/src/NodeAnalyzer/Template/TwigVariableNamesResolver.php
packages/phpstan-rules/packages/symfony/src/ObjectTypeMethodAnalyzer.php
packages/phpstan-rules/packages/symfony/src/Rules/NoTwigMissingMethodCallRule.php
packages/phpstan-rules/packages/symfony/src/Twig/TwigMissingMethodCallAnalyzer.php
packages/phpstan-rules/packages/symfony/src/Twig/TwigNodeTravser/TwigNodeTraverserFactory.php
packages/phpstan-rules/packages/symfony/src/Twig/TwigNodeVisitor/MissingMethodCallNodeVisitor.php
packages/phpstan-rules/packages/symfony/src/TypeAnalyzer/TemplateVariableTypesResolver.php
packages/phpstan-rules/packages/symfony/src/ValueObject/ForeachVariable.php
packages/phpstan-rules/packages/symfony/src/ValueObject/VariableAndMissingMethodName.php
packages/phpstan-rules/packages/symfony/src/ValueObject/VariableAndType.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Fixture/SomeForeachMissingVariableController.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/NoTwigMissingMethodCallRuleTest.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Source/non_existing_method_foreach.twig
packages/phpstan-rules/src/NodeAnalyzer/PathResolver.php
phpstan.neon

- name method
- improve phpstan errors

[PHPStanRules] Add for nested support for variable in twig resolver

---

packages/config-transformer/config/config.php
packages/config-transformer/src/ConfigLoader.php
packages/config-transformer/src/Converter/ConfigFormatConverter.php
packages/config-transformer/src/DependencyInjection/Loader/IdAwareXmlFileLoader.php
packages/config-transformer/src/Exception/XmlConfigParsingException.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Fixture/doctrine_config.xml

Fix https://github.com/symplify/symplify/issues/3502

[ConfigTransformer] Allow doctrine extension loading from xml

---

packages/config-transformer/config/config.php
packages/config-transformer/src/DependencyInjection/ExtensionFaker.php
packages/config-transformer/src/DependencyInjection/Loader/IdAwareXmlFileLoader.php
packages/config-transformer/src/ValueObject/DependencyInjection/Extension/AliasAndNamespaceConfigurableExtension.php
packages/config-transformer/src/ValueObject/DependencyInjection/Extension/AliasConfigurableExtension.php

Closes https://github.com/symplify/symplify/issues/3502

[ConfigTransformer] Fix doctrine faking

---

packages/phpstan-rules/packages/nette/src/Dibi/QueryMasksResolver.php
packages/phpstan-rules/packages/nette/src/Rules/DibiMaskMatchesVariableTypeRule.php
packages/phpstan-rules/packages/nette/tests/Rules/DibiMaskMatchesVariableTypeRule/DibiMaskMatchesVariableTypeRuleTest.php
packages/phpstan-rules/packages/nette/tests/Rules/DibiMaskMatchesVariableTypeRule/Fixture/InvalidArray.php
packages/phpstan-rules/packages/nette/tests/Rules/DibiMaskMatchesVariableTypeRule/Fixture/InvalidAssignType.php
packages/phpstan-rules/packages/nette/tests/Rules/DibiMaskMatchesVariableTypeRule/Fixture/SkipMaskNonDibi.php
packages/phpstan-rules/packages/nette/tests/Rules/DibiMaskMatchesVariableTypeRule/Fixture/SkipValidArray.php
packages/phpstan-rules/packages/nette/tests/Rules/DibiMaskMatchesVariableTypeRule/Fixture/SkipValidAssignType.php
rector.php

- Add assign array dim fetch case
- one more test

[PHPStanRules] Improve DibiMaskMatchesVariableTypeRule array/assign types

---

packages/phpstan-rules/packages/nette/config/nette-services.neon
packages/phpstan-rules/packages/nette/src/Latte/RelatedFileResolver/IncludedSnippetTemplateFileResolver.php
packages/phpstan-rules/packages/nette/src/Latte/RelatedFileResolver/ParentLayoutTemplateFileResolver.php
packages/phpstan-rules/packages/nette/src/LatteVariableNamesResolver.php

- decopule tempalte file resovler services
- fixup! decopule tempalte file resovler services

tv cleanup stuff

---

packages/monorepo-builder/bin/monorepo-builder.php

Changing order in $possibleAutoloadPaths (fixes #3570)

---

packages/easy-coding-standard/src/Application/EasyCodingStandardApplication.php
phpstan.neon

Closes https://github.com/symplify/symplify/issues/3470

[ECS] Fix progress bar hiding in parallel

---

packages/easy-coding-standard/src/Configuration/ConfigurationFactory.php
phpstan.neon

Resolves https://github.com/symplify/symplify/issues/3381 for now
On Windows the paralell cannot work now. This makes sure it's always off :+1:

[ECS] Do not run parallel for windows

---

composer.json
ecs.php
packages/easy-coding-standard/packages-tests/Parallel/Command/WorkerCommandLineFactoryTest.php
packages/easy-coding-standard/packages/Parallel/Application/ParallelFileProcessor.php
packages/easy-coding-standard/packages/Parallel/Command/WorkerCommandLineFactory.php
packages/easy-coding-standard/packages/Parallel/Enum/Action.php
packages/easy-coding-standard/packages/Parallel/Exception/ParallelShouldNotHappenException.php
packages/easy-coding-standard/packages/Parallel/ValueObject/ParallelProcess.php
packages/easy-coding-standard/packages/Parallel/ValueObject/ProcessPool.php
packages/easy-coding-standard/packages/Parallel/ValueObject/ReactCommand.php
packages/easy-coding-standard/packages/Parallel/ValueObject/ReactEvent.php
packages/easy-coding-standard/src/Application/EasyCodingStandardApplication.php
packages/easy-coding-standard/src/Configuration/ConfigurationFactory.php
packages/easy-coding-standard/src/Console/Command/AbstractCheckCommand.php
packages/easy-coding-standard/src/Console/Command/WorkerCommand.php
packages/easy-coding-standard/src/Console/Output/ConsoleOutputFormatter.php
packages/easy-coding-standard/src/HttpKernel/EasyCodingStandardKernel.php
packages/easy-coding-standard/src/ValueObject/Configuration.php
packages/easy-coding-standard/src/ValueObject/Option.php

---
Inspiration for next experiment:
https://github.com/phpstan/phpstan-src/blob/1e717d73c22061a2b275fb73fd27c704588b2be1/src/Command/WorkerCommand.php#L137-L143

[ECS] Make check command X-times faster where X is number of CPU-cores

---

packages/easy-hydrator/src/ParameterTypeRecognizer.php
packages/easy-hydrator/src/TypeCaster/ArrayTypeCaster.php
packages/easy-hydrator/tests/ArrayToValueObjectHydratorTest.php
packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/NoTwigMissingMethodCallRuleTest.php
packages/phpstan-rules/packages/twig-phpstan-printer/src/PhpParser/NodeVisitor/TwigGetAttributeExpanderNodeVisitor.php
packages/phpstan-rules/packages/twig-phpstan-printer/src/TwigToPhpCompiler.php
packages/phpstan-rules/packages/twig-phpstan-printer/tests/TwigToPhpCompiler/TwigToPhpCompilerTest.php

Follow up to https://github.com/symplify/symplify/pull/3601

[PHPStanRules] Fix property fetch on missing method call

---

packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/packages/nette/src/Rules/LatteCompleteCheckRule.php
packages/phpstan-rules/packages/nette/src/TemplateFileVarTypeDocBlocksDecorator.php
packages/phpstan-rules/packages/nette/src/TypeAnalyzer/ComponentMapResolver.php
packages/phpstan-rules/packages/nette/tests/Rules/LatteCompleteCheckRule/LatteCompleteCheckRuleTest.php
packages/phpstan-rules/packages/symfony/src/NodeAnalyzer/SymfonyRenderWithParametersMatcher.php
packages/phpstan-rules/src/Templates/RenderTemplateWithParametersMatcher.php
packages/phpstan-rules/src/Templates/TemplateErrorsFactory.php
packages/phpstan-rules/src/Templates/TemplateRulesRegistry.php

Closes https://github.com/symplify/symplify/pull/3618

[PHPStanRules] Fix multiline PHP expression to match line in latte correctly + extract template generic RenderTemplateWithParametersMatcher

---

packages/monorepo-builder/build/config/config-downgrade.php

[downgrade] Skip HttpKernelBrowser

---

packages/phpstan-rules/packages/nette/config/nette-services.neon
packages/phpstan-rules/packages/symfony/config/symfony-services.neon

Fixes https://github.com/symplify/symplify/issues/3635

[PHPStan Rules] Fix neon file is missing

---

packages/twig-phpstan-compiler/src/Twig/TolerantTwigEnvironment.php
packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Fixture/foreached_variable.twig
packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Fixture/simple_file.twig
packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Fixture/simple_filter.twig
packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Fixture/var_doc_variable.twig
packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/FixtureWithTypes/expected_compiled.php

- [TwigPHPStanCompiler] Add existing filter/Function if possible
- update strlen to noescape filter
Ref https://github.com/symplify/symplify/issues/3602

[TwigPHPStanCompiler] Add existing filter/Function if possible

---

packages/phpstan-rules/packages/symfony/src/Rules/TwigCompleteCheckRule.php
packages/twig-phpstan-compiler/src/TwigToPhpCompiler.php
packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Fixture/block_comment_block.twig

- more ignores
- fix comment removal on block usage

[TwigPHPStanCompiler] Fix comment between blocks

---

packages/easy-coding-standard/build/build-preload.php

Ref https://github.com/symplify/symplify/issues/3630

[ECS] Fix missing React\Promise\resolve() function in case own react/promise package is installed

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/YamlToPhpTest.php
packages/package-builder/src/Testing/AbstractKernelTestCase.php
packages/php-config-printer/tests/Printer/SmartPhpConfigPrinter/SmartPhpConfigPrinterTest.php

- remove unused bootKernelWithConfigsAndStaticCache()
- typo

[PackageBuilder] Remove unused bootKernelWithConfigsAndStaticCache() method

---

packages/config-transformer/composer.json
packages/config-transformer/src/Exception/ShouldNotHappenException.php
packages/config-transformer/src/HttpKernel/ConfigTransformerKernel.php
packages/easy-ci/bin/easy-ci.php
packages/monorepo-builder/bin/monorepo-builder.php
packages/symplify-kernel/src/ValueObject/KernelBootAndApplicationRun.php
packages/vendor-patches/composer.json
packages/vendor-patches/src/HttpKernel/VendorPatchesKernel.php
phpstan.neon

Follow up to https://github.com/symplify/symplify/pull/3726
Let's get slim :)

[ConfigTransformer] Remove dependency on http-kernel

---

packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/MissingParamNameMalformWorker.php
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/param-array.php.inc
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/skip_curly_newline.php.inc

[CodingStandard] Skip curly new line on ParamReturnAndVarTagMalformsFixer

---

packages/easy-ci/src/Latte/LatteTemplateAnalyzer/MissingClassesLatteAnalyzer.php
packages/easy-ci/tests/Latte/LattePersistence/LatteFilterPersistenceTest.php
packages/easy-ci/tests/Latte/LatteTemplateAnalyzer/MissingClassesLatteAnalyzer/Fixture/skip_double_instanceof_javascript.latte
packages/easy-ci/tests/Latte/LatteTemplateAnalyzer/MissingClassesLatteAnalyzer/Fixture/skip_instanceof_javascript.latte
packages/easy-ci/tests/Latte/LatteTemplateAnalyzer/MissingClassesLatteAnalyzer/MissingClassesLatteAnalyzerTest.php
packages/symplify-kernel/src/ContainerBuilderFactory.php

[EasyCI] Skip javascript in check-latte-template

---

packages/easy-ci/packages/ActiveClass/Command/CheckActiveClassCommand.php
packages/easy-ci/packages/ActiveClass/Reporting/UnusedClassReporter.php
packages/easy-ci/packages/ActiveClass/UseImportsResolver.php

[EasyCI] Add progres bar - closes #3739

---

easy-ci.php
packages/monorepo-builder/packages/Release/Guard/ReleaseGuard.php
packages/monorepo-builder/packages/Release/Version/VersionFactory.php
packages/monorepo-builder/src/Contract/Git/TagResolverInterface.php
packages/monorepo-builder/src/Git/MostRecentTagResolver.php

It allows you to use a different tag resolving strategy.

[MonorepoBuilder] Added contract for tag resolving

---

packages/easy-ci/config/config.php
packages/easy-ci/packages-tests/Config/ConfigFileAnalyzer/NonExistingClassConfigFileAnalyzer/Fixture/config/skip_entity.neon
packages/easy-ci/packages-tests/Config/ConfigFileAnalyzer/NonExistingClassConfigFileAnalyzer/NonExistingClassConfigFileAnalyzerTest.php
packages/easy-ci/packages-tests/Neon/Application/NeonFilesProcessor/Fixture/skip_helper_entity.neon
packages/easy-ci/packages-tests/Neon/Application/NeonFilesProcessor/NeonFilesProcessorTest.php
packages/easy-ci/packages/Neon/NeonClassExtractor.php

- add entity helper
- skip empty class

[Symplify] Easy CI - skip empty class

---

packages/phpstan-twig-rules/tests/Rules/NoTwigRenderUnusedVariableRule/Fixture/SkipControllerRouter.php
packages/phpstan-twig-rules/tests/Rules/NoTwigRenderUnusedVariableRule/NoTwigRenderUnusedVariableRuleTest.php
packages/template-phpstan-compiler/src/Reporting/TemplateErrorsFactory.php
packages/twig-phpstan-compiler/src/NodeAnalyzer/UnusedTwigTemplateVariableAnalyzer.php

Ref https://github.com/symplify/symplify/issues/3751

[PHPStanTwigRules] Do not report missing variables on non-render calls

---

composer.json
phpstan.neon

Ref https://github.com/timeweb/phpstan-enum/pull/24

[DX] Switch PHPStan extension from abandoned timeweb to maintained marc-be

---

packages/autowire-array-parameter/src/Skipper/ParameterSkipper.php
packages/autowire-array-parameter/tests/SourcePhp8/SkipMe/UnionTypes.php
packages/autowire-array-parameter/tests/config/php8_config.php

Fixes https://github.com/symplify/symplify/issues/3580

[AutowireArrayParameter] Skip union types on autowire

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Fixture/multiple_tags.xml
packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Fixture/single_service_tag.xml
packages/php-config-printer/src/Converter/ServiceOptionsKeyYamlToPhpFactory/TagsServiceOptionKeyYamlToPhpFactory.php

Closes #3761  Fixes https://github.com/symplify/symplify/issues/3754

[ConfigTransformer] Handle tag on XmlToPhp

---

composer.json
packages/astral/composer.json
packages/latte-phpstan-compiler/composer.json
packages/phpstan-extensions/composer.json
packages/phpstan-latte-rules/composer.json
packages/phpstan-latte-rules/tests/Rules/LatteCompleteCheckRule/config/configured_rule.neon
packages/phpstan-rules/composer.json
packages/phpstan-twig-rules/composer.json
packages/phpstan-twig-rules/tests/Rules/TwigCompleteCheckRule/config/configured_rule.neon
packages/rule-doc-generator/composer.json
packages/symfony-php-config/composer.json
packages/symfony-static-dumper/composer.json
packages/template-phpstan-compiler/composer.json
packages/template-phpstan-compiler/src/Rules/TemplateRulesRegistry.php
packages/twig-phpstan-compiler/composer.json

Resolves https://github.com/symplify/symplify/issues/3769

Fixed incompatibility with PHPStan 1.2.0

---

packages/phpstan-rules/config/code-complexity-rules.neon
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/docs/rules_overview.md
packages/phpstan-rules/src/Exception/UnknownValueTypeException.php
packages/phpstan-rules/src/Rules/Complexity/ForbiddenSameNamedAssignRule.php
packages/phpstan-rules/src/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule.php
packages/phpstan-rules/src/TypeAnalyzer/ClassMethodReturnTypeAnalyzer.php
packages/phpstan-rules/src/TypeAnalyzer/PropertyFetchTypeAnalyzer.php
packages/phpstan-rules/src/TypeResolver/NativePropertyFetchTypeResolver.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenSameNamedAssignRule/Fixture/SkipArrayFilterValues.php
packages/phpstan-rules/tests/Rules/Complexity/ForbiddenSameNamedAssignRule/ForbiddenSameNamedAssignRuleTest.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/ArrayGetterNullable.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/IntegerGetterFloat.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/SkipInterface.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/SkipMatchingArrayType.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/SkipNullableSetter.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/SkipUntrustableDocblock.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/RespectPropertyTypeInGetterReturnTypeRuleTest.php
packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/config/configured_rule.neon
packages/vendor-patches/README.md
phpstan.neon

- [PHPStanRules] Skip array filter values
- [PHPStanRules] Add RespectPropertyTypeInGetterReturnTypeRule

[PHPStanRules] Add RespectPropertyTypeInGetterReturnTypeRule

---

packages/astral/config/services.neon
packages/astral/src/Reflection/MethodCallParser.php
packages/astral/src/Reflection/ReflectionParser.php
packages/phpstan-rules/config/code-complexity-rules.neon
packages/phpstan-rules/packages/nette/src/NetteInjectAnalyzer.php
packages/phpstan-rules/src/ParentClassMethodNodeResolver.php
packages/phpstan-rules/src/Rules/Explicit/NoVoidAssignRule.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/Fixture/DocblockVoidAssign.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/Fixture/ImplicitVoid.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/Fixture/SkipInternalClassAssign.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/Fixture/SkipReturnNumber.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/Fixture/SomeVoidAssign.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/NoVoidAssignRuleTest.php
packages/phpstan-rules/tests/Rules/Explicit/NoVoidAssignRule/config/configured_rule.neon

PHPStan replacement for too strict Rector rule https://github.com/rectorphp/rector-src/pull/1313

[PHPStanRules] Add NoVoidAssignRule

---

packages/latte-phpstan-compiler/src/PhpParser/NodeVisitor/LinkNodeVisitor.php
packages/latte-phpstan-compiler/src/TemplateFileVarTypeDocBlocksDecorator.php
packages/php-config-printer/src/CaseConverter/ConfiguredServiceCaseConverter.php
packages/php-config-printer/src/CaseConverter/NestedCaseConverter/InstanceOfNestedCaseConverter.php
packages/php-config-printer/src/NodeFactory/ContainerNestedNodesFactory.php
packages/php-config-printer/src/NodeFactory/Service/SingleServicePhpNodeFactory.php
packages/php-config-printer/src/Printer/ArrayDecorator/ServiceConfigurationDecorator.php
packages/php-config-printer/src/Printer/SmartPhpConfigPrinter.php
packages/php-config-printer/src/ServiceOptionConverter/ConfigureServiceOptionKeyYamlToPhpFactory.php
packages/php-config-printer/tests/Printer/SmartPhpConfigPrinter/SmartPhpConfigPrinterTest.php
packages/rule-doc-generator-contracts/src/Contract/RuleCodeSamplePrinterInterface.php
packages/rule-doc-generator/src/Command/GenerateCommand.php
packages/rule-doc-generator/src/DirectoryToMarkdownPrinter.php
packages/rule-doc-generator/src/Printer/CodeSamplePrinter/CodeSamplePrinter.php
packages/rule-doc-generator/src/Printer/RuleDefinitionsPrinter.php
packages/rule-doc-generator/src/RuleCodeSamplePrinter/ConfiguredCodeSamplerPrinter.php
packages/rule-doc-generator/src/RuleCodeSamplePrinter/PHPCSFixerRuleCodeSamplePrinter.php
packages/rule-doc-generator/src/RuleCodeSamplePrinter/PHPCodeSnifferRuleCodeSamplePrinter.php
packages/rule-doc-generator/src/RuleCodeSamplePrinter/PHPStanRuleCodeSamplePrinter.php
packages/rule-doc-generator/src/RuleCodeSamplePrinter/RectorRuleCodeSamplePrinter.php
packages/rule-doc-generator/src/ValueObject/Option.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/DirectoryToMarkdownPrinterTest.php
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/configurable_rector_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Fixture/Rector/Configurable/WithPHPStanTypeObject.php
tests/bootstrap.php

Closes https://github.com/symplify/symplify/issues/3809

[RuleDocGenerator] Add configure() docs method support via --configure-method command option

---

.github/workflows/daily_pull_request.yaml
packages/latte-phpstan-compiler/src/LinkProcessor/LinkProcessorFactory.php
packages/latte-phpstan-compiler/src/LinkProcessor/PresenterActionLinkProcessor.php
packages/latte-phpstan-compiler/src/LinkProcessor/SignalLinkProcessor.php
packages/latte-phpstan-compiler/src/PhpParser/NodeVisitor/LinkNodeVisitor.php
packages/phpstan-latte-rules/src/LatteTemplateHolder/NetteApplicationUIPresenter.php
packages/phpstan-latte-rules/src/LatteTemplateHolder/TemplateRenderMethodCall.php
packages/phpstan-latte-rules/src/Rules/LatteCompleteCheckRule.php

For :
- Re-Propagate Composer Dependencies to Packages
- Re-Apply Rector Rules
This is to handle pending start github action workflow:
- Compared to weekly pull request, it is using ACCESS_TOKEN instead of GITHUB_TOKEN
- Enable auto merge as well.

[Daily] Using Access Token instead of Github Token + Enable Auto merge

---

composer.json

So only update when there is new version.

[Dep] Update rector version to ^0.12.7

---

composer.json
packages/config-transformer/build/config/config-downgrade.php
packages/easy-coding-standard/build/config/config-downgrade.php
packages/monorepo-builder/build/config/config-downgrade.php

Makes use of https://github.com/rectorphp/rector-src/pull/1448

Update downgrade variant Rector types

---

easy-ci.php
packages/latte-phpstan-compiler/config/services.neon
packages/latte-phpstan-compiler/src/Contract/LatteToPhpCompilerNodeVisitorInterface.php
packages/latte-phpstan-compiler/src/LatteToPhpCompiler.php
packages/latte-phpstan-compiler/src/PhpParser/NodeVisitor/InstanceofRenderableNodeVisitor.php
packages/latte-phpstan-compiler/src/PhpParser/NodeVisitor/LinkNodeVisitor.php
packages/latte-phpstan-compiler/src/PhpParser/NodeVisitor/MagicFilterToExplicitCallNodeVisitor.php
packages/latte-phpstan-compiler/src/PhpParser/NodeVisitor/NClassNodeVisitor.php

[Latte PHPStan Compiler] NodeVisitors as services

---

packages/monorepo-builder/packages-tests/Testing/ComposerJson/ComposerJsonSymlinkerTest.php
packages/monorepo-builder/packages-tests/Testing/ComposerJson/config/test_config.php
packages/monorepo-builder/src/Exception/ConfigurationException.php
packages/monorepo-builder/src/Finder/PackageComposerFinder.php

- fix cs
- [MonorepoBuilder] Fix missing packages parameter in merge command

[MonorepoBuilder] Fix missing packages parameter in merge command

---

packages/package-builder/src/Reflection/PrivatesAccessor.php

@staabm The template type docblock was incomplete, that's why return type changed.
This fixes it.

Fix template type

---

.github/workflows/build_downgraded_and_prefixed_tools.yaml
packages/config-transformer/build/downgrade-config-transformer.sh
packages/easy-ci/build/build-easy-ci-scoped.sh
packages/easy-ci/build/config/config-downgrade.php
packages/easy-ci/build/downgrade-easy-ci.sh
packages/easy-ci/build/target-repository/.github/FUNDING.yml
packages/easy-ci/build/target-repository/.github/workflows/auto_closer.yaml
packages/easy-ci/build/target-repository/.github/workflows/bare_run.yaml
packages/easy-ci/build/target-repository/README.md
packages/easy-ci/build/target-repository/composer.json
packages/monorepo-builder/build/downgrade-monorepo-builder.sh

Ref https://github.com/symplify/symplify/issues/3883

[EasyCI] Add downgrade meta files

---

packages/easy-ci/config/config.php
packages/easy-ci/src/Console/EasyCIApplication.php
packages/monorepo-builder/config/services.php
packages/monorepo-builder/src/Console/MonorepoBuilderApplication.php
packages/vendor-patches/config/config.php
packages/vendor-patches/src/Console/VendorPatchesApplication.php

Closes https://github.com/symplify/symplify/issues/3894
Closes https://github.com/symplify/symplify/pull/3895

[DX] Autowire commands to avoid miss-adding

---

packages/phpstan-rules/src/Rules/NoNestedFuncCallRule.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/Fixture/SkipAssert.php
packages/phpstan-rules/tests/Rules/NoNestedFuncCallRule/NoNestedFuncCallRuleTest.php

Closes https://github.com/symplify/symplify/issues/3872

[PHPStanRules] Skip assert in NoNestedFuncCallRule

---

packages/easy-coding-standard/src/Configuration/ConfigurationFactory.php
packages/easy-coding-standard/src/Console/Command/AbstractCheckCommand.php
packages/easy-coding-standard/src/Console/Command/CheckCommand.php
packages/easy-coding-standard/src/Console/Command/WorkerCommand.php
packages/easy-coding-standard/src/Exception/Configuration/InitializationException.php
packages/easy-coding-standard/src/MemoryLimitter.php
packages/easy-coding-standard/src/ValueObject/Configuration.php
packages/easy-coding-standard/src/ValueObject/Option.php
packages/easy-parallel/src/CommandLine/WorkerCommandLineFactory.php
phpstan.neon

Closes https://github.com/symplify/symplify/issues/3890

[ECS] Add --memory-limit option to configure memory in parallel

---

packages/symplify-kernel/.gitignore
packages/symplify-kernel/README.md
packages/symplify-kernel/composer.json
packages/symplify-kernel/phpunit.xml
packages/symplify-kernel/src/ContainerBuilderFactory.php
packages/symplify-kernel/tests/ContainerBuilderFactory/ContainerBuilderFactoryTest.php
packages/symplify-kernel/tests/ContainerBuilderFactory/config/some_services.php

Closes https://github.com/symplify/symplify/issues/3904

[SymplifyKernel] Add README and basic test

---

packages/phpstan-rules/src/Rules/Explicit/NoMixedMethodCallerRule.php
packages/phpstan-rules/src/Rules/Explicit/NoMixedPropertyFetcherRule.php
packages/phpstan-rules/tests/Rules/Explicit/NoMixedMethodCallerRule/Fixture/MagicMethodName.php
packages/phpstan-rules/tests/Rules/Explicit/NoMixedMethodCallerRule/NoMixedMethodCallerRuleTest.php
packages/phpstan-rules/tests/Rules/Explicit/NoMixedPropertyFetcherRule/Fixture/DynamicName.php
packages/phpstan-rules/tests/Rules/Explicit/NoMixedPropertyFetcherRule/Fixture/SkipDynamicNameWithKnownType.php
packages/phpstan-rules/tests/Rules/Explicit/NoMixedPropertyFetcherRule/NoMixedPropertyFetcherRuleTest.php

* Closes https://github.com/symplify/symplify/pull/3921
* Resolves https://github.com/symplify/symplify/issues/3919
- Make message a bit more clear for no mixed rules.
- Adjust tests for the changes.
- Fix up PHPStan.
- show exact caller part

[PHPStanRules] Improve NoMixedMethodCallerRule error message to make it easier to find

---

packages/phpstan-rules/packages/symfony/src/Rules/RequireNamedCommandRule.php
packages/phpstan-rules/packages/symfony/tests/Rules/RequireNamedCommandRule/Fixture/SkipAttributeNamedCommand.php
packages/phpstan-rules/packages/symfony/tests/Rules/RequireNamedCommandRule/RequireNamedCommandRuleTest.php

[PHPStanRules] RequireNamedCommandRule - AsCommand attribute support

---

packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/ParamNameTypoMalformWorker.php
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/skip_callable_param.php.inc
packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Source/Schedule.php

Fixes case like https://github.com/rectorphp/rector-src/pull/1837/files#diff-7951837beface243ca718e3795755e8c26a0bf48bad3fc8afef2d1631bc1b1ddR55

[CS] Fix mallform doc fixer on closures

---

.github/workflows/build_ecs_prefixed.yaml

Ref: https://github.com/symplify/symplify/pull/3955

[ECS] Remove remote docs directory to avoid piling up deleted gif in remote repository

---

.github/workflows/build_ecs_prefixed.yaml

Ref: https://github.com/symplify/symplify/pull/4003#issuecomment-1068913325

[ECS] Copy docs to remote repository

---

packages/coding-standard/src/TokenRunner/Transformer/FixerTransformer/LineLengthCloserTransformer.php
packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/Fixture/wrong_array_bracket_position_in_arg_list.php.inc

Closes https://github.com/symplify/symplify/pull/4014
Fixes https://github.com/symplify/symplify/issues/4013

[CS] Fix handle empty array to not add new line on LineLengthFixer

---

packages/git-wrapper/src/GitWrapper.php

ref https://github.com/rectorphp/rector-src/pull/2081 remove null from mixed nullable.

Re trigger Rectify

---

packages/phpstan-extensions/config/bleeding-edge-enable-connecting-node-visitor.neon
packages/phpstan-extensions/config/config.neon
packages/phpstan-rules/packages/cognitive-complexity/src/CompositionOverInheritanceAnalyzer.php
packages/phpstan-rules/src/Rules/ClassExtendingExclusiveNamespaceRule.php
packages/phpstan-rules/src/Rules/NoBinaryOpCallCompareRule.php
packages/phpstan-rules/src/Rules/NoProtectedElementInFinalClassRule.php
packages/phpstan-rules/tests/Rules/NoProtectedElementInFinalClassRule/config/configured_rule.neon
phpstan.neon
rector.php

Testing new Scope refresh feature from Rector: https://github.com/rectorphp/rector-src/pull/2292

Try Rector dev with Scope refresh

---

packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/CheckSprinfMatchingTypesRuleTest.php
packages/phpstan-rules/tests/Rules/Missing/CheckSprinfMatchingTypesRule/Fixture/SkipValidTernary.php

Add failing test for https://github.com/symplify/symplify/issues/4061.

---

composer.json
packages/easy-ci/packages-tests/Neon/NeonClassExtractor/Fixture/phpstan_rules.neon
packages/easy-ci/packages-tests/Neon/NeonClassExtractor/Fixture/some_services.neon
packages/easy-ci/packages-tests/Neon/NeonClassExtractor/NeonClassExtractorTest.php
packages/easy-ci/packages/Neon/NeonClassExtractor.php
packages/package-builder/composer.json
packages/rule-doc-generator/composer.json

There is some BC break in new nette/neon package:
https://github.com/nette/neon/compare/v3.3.2...master
But so far I got it only locally :thinking:

[EasyCI] Add support for checking phpstan classes

---

packages/easy-coding-standard/README.md

- Showing usage of upgraded `ContainerConfigurator` -> `ECSConfig`

Updated README

---

packages/easy-coding-standard/config/set/php-cs-fixer-risky.php
packages/easy-coding-standard/config/set/php-cs-fixer.php
packages/easy-coding-standard/config/set/psr12.php
packages/easy-coding-standard/config/set/symfony-risky.php
packages/easy-coding-standard/config/set/symfony.php
packages/easy-coding-standard/config/set/symplify.php
packages/easy-coding-standard/packages/FixerRunner/WhitespacesFixerConfigFactory.php
packages/easy-coding-standard/src/DependencyInjection/CompilerPass/ConflictingCheckersCompilerPass.php
packages/easy-coding-standard/src/DependencyInjection/CompilerPass/RemoveExcludedCheckersCompilerPass.php
packages/easy-coding-standard/src/DependencyInjection/CompilerPass/RemoveMutualCheckersCompilerPass.php
packages/easy-coding-standard/src/DependencyInjection/DeprecationReporter.php
packages/easy-coding-standard/src/DependencyInjection/EasyCodingStandardContainerFactory.php
packages/php-config-printer/src/NodeFactory/ArgsNodeFactory.php
phpstan.neon

Closes https://github.com/symplify/symplify/issues/4077

[ECS] report deprecated configs only once on main config run

---

packages/composer-json-manipulator/src/ComposerJsonFactory.php
packages/composer-json-manipulator/src/ValueObject/ComposerJson.php
packages/composer-json-manipulator/src/ValueObject/ComposerJsonSection.php
packages/composer-json-manipulator/tests/ComposerJsonFactory/Source/full_composer.json
packages/git-wrapper/tests/AbstractGitWrapperTestCase.php
packages/monorepo-builder/config/parameters.php
packages/monorepo-builder/packages-tests/Merge/ComposerJsonDecorator/AbstractComposerJsonDecoratorTest.php
packages/monorepo-builder/packages-tests/Merge/ComposerJsonMerger/Fixture/with_provide.json
packages/monorepo-builder/packages/Merge/Command/MergeCommand.php
packages/monorepo-builder/packages/Merge/ComposerKeyMerger/ProvideComposerKeyMerger.php

[MonorepoBuilder] Support for merging "provide" section

---

.github/workflows/build_ecs_prefixed.yaml
composer.json
packages/easy-coding-standard/composer.json

- [ECS] Reorder patching packages
- remove event-dispatcher from ECS build

tv ecs lighter

---

packages/coding-standard/src/Fixer/LineLength/LineLengthFixer.php
packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/BlockFinder.php
packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/Fixture/break_attribute.php.inc
packages/phpstan-rules/src/Rules/NoFactoryInConstructorRule.php
packages/rule-doc-generator/src/Printer/CodeSamplePrinter/BadGoodCodeSamplePrinter.php

- LineLengthFixer should break attributes
- WIP > doesn't work
- fix T_ATTRIBUTE opening tag

[CodingStandard] Add #[...] attribute to break attributes

---

packages/phpstan-rules/packages/nette/src/NetteInjectAnalyzer.php
packages/phpstan-rules/packages/nette/tests/Rules/ForbiddenNetteInjectOverrideRule/Fixture/SkipParentAnnotatedProperty.php
packages/phpstan-rules/packages/nette/tests/Rules/ForbiddenNetteInjectOverrideRule/ForbiddenNetteInjectOverrideRuleTest.php
packages/phpstan-rules/packages/nette/tests/Rules/ForbiddenNetteInjectOverrideRule/Source/AbstractParentAnnotatedProperty.php
packages/phpstan-rules/src/NodeAnalyzer/AutowiredMethodPropertyAnalyzer.php

- space
- [PHPStanRules] Skip annotated proeprty in NetteInjectAnalyzer

[PHPStanRules] Skip annotated proeprty in NetteInjectAnalyzer

---

packages/astral/config/services.neon
packages/astral/src/NodeFinder/SimpleNodeFinder.php
packages/astral/src/Reflection/MethodCallParser.php
packages/astral/src/ValueObject/AttributeKey.php

see https://github.com/symplify/symplify/issues/4169#issuecomment-1153717192
partly reverts https://github.com/symplify/symplify/pull/4157 and

partly revert bd7f735 to keep BC relevant parts

---

packages/php-config-printer/src/NodeFactory/Service/AutoBindNodeFactory.php
packages/phpstan-rules/config/collector-rules.neon
packages/phpstan-rules/config/services/services.neon
packages/phpstan-rules/config/symplify-rules.neon
packages/phpstan-rules/docs/rules_overview.md
packages/phpstan-rules/src/Collector/ClassConstFetchCollector.php
packages/phpstan-rules/src/Collector/PublicClassLikeConstCollector.php
packages/phpstan-rules/src/DeadCode/UnusedPublicClassConstRule.php
packages/phpstan-rules/src/Matcher/ClassLikeNameMatcher.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/Fixture/SkipApiPublicConstant.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/Fixture/SkipPrivateConstant.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/Fixture/SkipUsedPublicConstant.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/Fixture/UnusedPublicConstant.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/Fixture/UnusedPublicConstantFromInterface.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/Source/ConstantUser.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/UnusedPublicClassConstRuleTest.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/config/configured_rule.neon
packages/symfony-static-dumper/src/ValueObject/SymfonyStaticDumperConfig.php
phpstan.neon

First prototype rule of https://phpstan.org/developing-extensions/collectors :)

[PHPStanRules] Add first collector rule to detect unused public class constants

---

packages/easy-coding-standard/packages/SniffRunner/Application/SniffFileProcessor.php
packages/phpstan-rules/src/Collector/ClassMethod/PublicClassMethodCollector.php
packages/phpstan-rules/src/Rules/NoProtectedElementInFinalClassRule.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/Fixture/InterfaceWithExtraMethod.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/Fixture/SkipImplementsInterfaceCoveredByContract.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/Source/Contract/MethodRequiredInterface.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/UnusedPublicClassMethodRuleTest.php

- add fixture
- [PHPStanRules] Check interface methods over the contract

[PHPStanRules] Check interface methods over the contract

---

packages/phpstan-rules/src/Collector/ClassMethod/MethodCallCollector.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/Fixture/SkipChildUsedPublicMethod.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/Source/Repository/AbstractRepository.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/Source/Repository/ChildRepository.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/UnusedPublicClassMethodRuleTest.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/config/configured_rule.neon

- [PHPStanRules] Add parent abstract call check
- [PHPStanRules] Include parent calls

[PHPStanRules] Add parent abstract call check

---

packages/php-config-printer/src/Sorter/FullyQualifiedImportSorter.php
packages/phpstan-rules/config/collector-rules.neon
packages/phpstan-rules/packages/Nette/NetteInjectAnalyzer.php
packages/phpstan-rules/packages/Nette/Rules/ForbiddenNetteInjectOverrideRule.php
packages/phpstan-rules/src/Collector/MethodCall/MethodCallArgTypesCollector.php
packages/phpstan-rules/src/NodeAnalyzer/TypeNodeAnalyzer.php
packages/phpstan-rules/src/ParentGuard/ParentClassMethodGuard.php
packages/phpstan-rules/src/Printer/CollectorMetadataPrinter.php
packages/phpstan-rules/src/Rules/BoolishClassMethodPrefixRule.php
packages/phpstan-rules/src/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule.php
packages/phpstan-rules/src/Rules/NoProtectedElementInFinalClassRule.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Fixture/SkipClassStringPassed.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Fixture/SkipExpectedClassType.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/NarrowPublicClassMethodParamTypeByCallerTypeRuleTest.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedClassString/FirstTypedCaller.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedClassString/SecondTypedCaller.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedClassType/FirstClassTypedCaller.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedClassType/SecondClassTypedCaller.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/PassMeAsType.php

Follow up to https://github.com/symplify/symplify/pull/4213

[PHPStanRules] Improve class-string, array NarrowPublicClassMethodParamTypeByCallerTypeRule

---

packages/phpstan-rules/config/collector-rules.neon
packages/phpstan-rules/src/Collector/MethodCall/MethodCallArgTypesCollector.php
packages/phpstan-rules/src/Enum/Types/ResolvedTypes.php
packages/phpstan-rules/src/Printer/CollectorMetadataPrinter.php
packages/phpstan-rules/src/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Fixture/SkipApiMarked.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Fixture/SkipMixedAndString.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/NarrowPublicClassMethodParamTypeByCallerTypeRuleTest.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedNodeApi/CallWithProperty.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/MixedAndString/FirstCaller.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/MixedAndString/SecondCaller.php
packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/MixedAndString/ThirdCaller.php

- [PHPStanRules] Improve type detection for mixed types, class-string and objects
- [PHPStanRules] Skip mixed type, skip union types

[PHPStanRules] Skip mixed type, skip union types

---

packages/easy-coding-standard/packages/Caching/Cache.php
packages/easy-coding-standard/packages/Caching/ValueObject/Storage/FileCacheStorage.php
phpstan.neon

- cache string types
- remove fixed phpstan errors

Cleanup phpstan errors

---

packages/phpstan-rules/config/code-complexity-rules.neon
packages/phpstan-rules/src/NodeVisitor/StringOutsideConcatFindingNodeVisitor.php
packages/phpstan-rules/src/Rules/Explicit/NoRelativeFilePathRule.php
packages/phpstan-rules/tests/Rules/Explicit/NoRelativeFilePathRule/Fixture/SkipHereNowDoc.php
packages/phpstan-rules/tests/Rules/Explicit/NoRelativeFilePathRule/Fixture/SkipMaskFinder.php
packages/phpstan-rules/tests/Rules/Explicit/NoRelativeFilePathRule/Fixture/SkipNoFileBefore.php
packages/phpstan-rules/tests/Rules/Explicit/NoRelativeFilePathRule/Fixture/SkipRegexConsts.php
packages/phpstan-rules/tests/Rules/Explicit/NoRelativeFilePathRule/Fixture/SkipStrEndsWith.php
packages/phpstan-rules/tests/Rules/Explicit/NoRelativeFilePathRule/NoRelativeFilePathRuleTest.php
phpstan.neon

- skip weird file paths
- checks

Cover edge cases and enable rule

---

packages/astral/src/Reflection/ReflectionParser.php
packages/easy-ci/src/Latte/LatteTemplateProcessor.php
packages/easy-coding-standard/bin/ecs.php
packages/easy-coding-standard/src/Testing/PHPUnit/AbstractCheckerTestCase.php
packages/easy-testing/src/StaticFixtureSplitter.php
packages/phpstan-rules/config/collector-rules.neon
packages/phpstan-rules/src/Collector/Variable/VariableNameCollector.php
packages/phpstan-rules/src/Finder/ClassLikeNameFinder.php
packages/phpstan-rules/src/Rules/Enum/RequireEnumDocBlockOnConstantListPassRule.php
packages/phpstan-rules/src/Rules/Explicit/NoDuplicatedVariableCasingNameRule.php
packages/phpstan-rules/src/ValueObject/VariableNameMetadata.php
packages/rule-doc-generator/src/RuleCodeSamplePrinter/PHPStanRuleCodeSamplePrinter.php
packages/smart-file-system/src/SmartFileSystem.php
phpstan.neon

- enable
- enable rules, fix duplicated names

[DX] Enable rule for duplicated case variables name

---

packages/config-transformer/bin/config-transformer.php

fix: move dependency autoload before monorepo and package #4238

---

composer.json
packages/coding-standard/composer.json
packages/coding-standard/config/config.php
packages/coding-standard/config/symplify.php
packages/coding-standard/src/Exception/ShouldNotHappenException.php
packages/coding-standard/src/Fixer/Naming/StandardizeHereNowDocKeywordFixer.php
packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/BlockFinder.php
packages/easy-coding-standard/composer.json
packages/rule-doc-generator/composer.json
phpstan.neon

- [CS] Fix new enum types in php-cs-fixer
- bump php-cs-fixer

[CS] Bump php-cs-fixer to 3.9.5 and make use of enum types

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/config_with_multiple_when_keys.yaml
packages/php-config-printer/src/NodeFactory/ContainerConfiguratorReturnClosureFactory.php

fix: always framework key under `when@env` and group condition statements together

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/tags/no_empty_attributes_tags.yaml
packages/php-config-printer/src/Converter/ServiceOptionsKeyYamlToPhpFactory/TagsServiceOptionKeyYamlToPhpFactory.php

- add empty array fixture in tag
- remove empty 2nd args

[ConfigTransformer] Fix 2nd empty array arg in tags

---

packages/config-transformer/src/DependencyInjection/ExtensionFaker.php

https://github.com/symplify/symplify/issues/4272

Add some bundles to the extension faker

---

packages/config-transformer/src/Console/ConfigTransformerApplication.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/order-public-alias/alias-first.yaml
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/order-public-alias/exact-config.yaml
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/order-public-alias/public-first.yaml

Fixes https://github.com/symplify/symplify/issues/4270

[ConfigTransformer] Add test fixture for service key order

---

packages/config-transformer/src/Converter/ConfigFormatConverter.php
packages/config-transformer/src/Converter/YamlToPhpConverter.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/routes.yaml
packages/config-transformer/tests/Converter/YamlToPhpConverter/YamlToPhpConverterTest.php
packages/php-config-printer/src/Enum/RouteOption.php
packages/php-config-printer/src/RoutingCaseConverter/PathRoutingCaseConverter.php

Closes https://github.com/symplify/symplify/issues/4259

[ConfigTransformer] Add options support to routes

---

packages/config-transformer/src/Converter/YamlToPhpConverter.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/conditional/when_routes.yaml
packages/php-config-printer/src/CaseConverter/AliasCaseConverter.php
packages/php-config-printer/src/CaseConverter/ClassServiceCaseConverter.php
packages/php-config-printer/src/CaseConverter/ConfiguredServiceCaseConverter.php
packages/php-config-printer/src/CaseConverter/ExtensionConverter.php
packages/php-config-printer/src/CaseConverter/ImportCaseConverter.php
packages/php-config-printer/src/CaseConverter/NameOnlyServiceCaseConverter.php
packages/php-config-printer/src/CaseConverter/NestedCaseConverter/InstanceOfNestedCaseConverter.php
packages/php-config-printer/src/CaseConverter/ParameterCaseConverter.php
packages/php-config-printer/src/CaseConverter/ResourceCaseConverter.php
packages/php-config-printer/src/CaseConverter/ServicesDefaultsCaseConverter.php
packages/php-config-printer/src/Contract/CaseConverterInterface.php
packages/php-config-printer/src/Contract/RoutingCaseConverterInterface.php
packages/php-config-printer/src/NodeFactory/ContainerConfiguratorReturnClosureFactory.php
packages/php-config-printer/src/NodeFactory/ContainerNestedNodesFactory.php
packages/php-config-printer/src/NodeFactory/RoutingConfiguratorReturnClosureFactory.php
packages/php-config-printer/src/RoutingCaseConverter/ConditionalEnvRoutingCaseConverter.php
packages/php-config-printer/src/RoutingCaseConverter/ImportRoutingCaseConverter.php
packages/php-config-printer/src/RoutingCaseConverter/PathRoutingCaseConverter.php
packages/rule-doc-generator/src/CaseConverter/ECSRuleCaseConverter.php
packages/rule-doc-generator/src/CaseConverter/RectorRuleCaseConverter.php

Inspired by https://github.com/symplify/symplify/pull/4179
* Closes https://github.com/symplify/symplify/issues/4273
* Closes https://github.com/symplify/symplify/issues/4260

[ConfigTransformer] Add nested condition to routing

---

packages/phpstan-rules/packages/Symfony/NodeAnalyzer/SymfonyPhpConfigClosureAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/AutowiredMethodPropertyAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/ClassAnalyzer.php
packages/phpstan-rules/src/NodeAnalyzer/DependencyNodeAnalyzer.php
packages/phpstan-rules/src/NodeFinder/ClassMethodNodeFinder.php
packages/phpstan-rules/src/ParentGuard/ParentClassMethodGuard.php
packages/phpstan-rules/src/Rules/Complexity/ForbiddenSameNamedNewInstanceRule.php
packages/phpstan-rules/src/Rules/ExclusiveDependencyRule.php
packages/phpstan-rules/src/Rules/NoNestedFuncCallRule.php
packages/phpstan-rules/src/Rules/PreventDuplicateClassMethodRule.php
packages/phpstan-rules/src/Rules/RequireStringRegexMatchKeyRule.php
packages/phpstan-rules/src/Rules/RequireThisCallOnLocalMethodRule.php
packages/phpstan-rules/tests/Rules/ExclusiveDependencyRule/ExclusiveDependencyRuleTest.php
phpstan.neon

Follow up to https://github.com/symplify/symplify/pull/4297

[PHPStanRules] Remove unnecessary dependencies to allow easy install on lower PHP - #3

---

packages/coding-standard/src/Enum/BlockBorderType.php
packages/coding-standard/src/Fixer/ArrayNotation/ArrayOpenerAndCloserNewlineFixer.php
packages/coding-standard/src/ValueObject/BlockInfoMetadata.php
packages/coding-standard/tests/Fixer/ArrayNotation/ArrayOpenerAndCloserNewlineFixer/Fixture/nested_array.php.inc
packages/easy-coding-standard/config/set/common/array.php
packages/easy-coding-standard/tests/Set/Array/ArrayTest.php
packages/easy-coding-standard/tests/Set/Array/Fixture/nested_array.php.inc
packages/easy-coding-standard/tests/Set/Array/Fixture/nested_array_complex.php.inc
packages/easy-coding-standard/tests/Set/Array/config.php
phpstan.neon

Fixes https://github.com/symplify/symplify/pull/4287

[CodingStandard] Fix order in ArrayOpenerAndCloserNewlineFixer

---

packages/config-transformer/src/Converter/YamlToPhpConverter.php
packages/config-transformer/src/Routing/RoutingConfigDetector.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/packages/routing.yaml
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/YamlToPhpTest.php
packages/config-transformer/tests/Routing/RoutingConfigDetectorTest.php

Fixes https://github.com/symplify/symplify/pull/4286

[ConfigTransformer] Add test case and fix for packages/routing.yaml

---

packages/easy-ci/src/Template/TemplatePathsResolver.php

This adds the support for the templates folder of Symfony as discussed here https://github.com/symplify/symplify/issues/4328
---
EDIT @TomasVotruba closes https://github.com/symplify/symplify/issues/4328

Support for Symfony default template folder

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/bundle_import.yaml
packages/php-config-printer/src/ExprResolver/StringExprResolver.php
packages/php-config-printer/src/NodeFactory/ArgsNodeFactory.php
packages/php-config-printer/src/RoutingCaseConverter/ImportRoutingCaseConverter.php

Fixes https://github.com/symplify/symplify/pull/4289

 [ConfigTransformer] Keep imported bundle config for routing

---

packages/config-transformer/src/ConfigLoader.php
packages/config-transformer/src/DependencyInjection/Loader/CheckerTolerantYamlFileLoader.php
packages/config-transformer/src/DependencyInjection/Loader/MissingAutodiscoveryDirectoryTolerantYamlFileLoader.php
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/services_test.yaml
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/YamlToPhpTest.php

Closes https://github.com/symplify/symplify/pull/4336

[ConfigTransformer] Add MissingAutodiscoveryDirectoryTolerantYamlFileLoader to skip loaded directory if missing

---

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/controller_reference.yaml
packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/routes_with_defaults_controller.yaml
packages/php-config-printer/src/Enum/RouteOption.php
packages/php-config-printer/src/RoutingCaseConverter/PathRoutingCaseConverter.php

Inspired by https://github.com/symfony/symfony/pull/24180/files#r141346267

[ConfigTransformer] Move single _defaults directly to call controller() method

---

packages/easy-coding-standard/packages/SniffRunner/ValueObject/File.php

Closes https://github.com/symplify/symplify/issues/4357

Add sniff UnusedFunctionParameterSniff to REPORT_WARNINGS_SNIFFS

---

packages/phpstan-rules/src/Rules/DeadCode/UnusedPublicClassConstRule.php
packages/phpstan-rules/src/Rules/DeadCode/UnusedPublicClassMethodRule.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassConstRule/UnusedPublicClassConstRuleTest.php
packages/phpstan-rules/tests/Rules/DeadCode/UnusedPublicClassMethodRule/UnusedPublicClassMethodRuleTest.php

refs https://github.com/symplify/symplify/issues/4400#issuecomment-1249470349

Use more precise messages in UnusedPublic*-Rules

---

packages/composer-json-manipulator/README.md

A short but real-world example that modifies composer.json, satisfies #4434

expand example in README

---

.github/workflows/build_ecs_prefixed.yaml
.github/workflows/build_tools.yaml
.github/workflows/downgrade_packages.yaml
.github/workflows/rector.yaml
.github/workflows/split_monorepo.yaml
.github/workflows/split_tests.yaml

Upgrade deprecated set-*

---

composer.json
packages/phpstan-rules/src/Formatter/SeaLevelRuleErrorFormatter.php
packages/phpstan-rules/src/Rules/Explicit/ParamTypeDeclarationSeaLevelRule.php
packages/phpstan-rules/src/Rules/Explicit/PropertyTypeDeclarationSeaLevelRule.php
packages/phpstan-rules/src/Rules/Explicit/ReturnTypeDeclarationSeaLevelRule.php
packages/smart-file-system/README.md
packages/smart-file-system/composer.json
packages/smart-file-system/src/Finder/FinderSanitizer.php
packages/smart-file-system/tests/Finder/FinderSanitizer/FinderSanitizerTest.php

- remove platform check
- [SmartFileSystem] Remove NetteFinder from sanitizer, not used

Trying faster Rector :)

---

packages/easy-coding-standard/src/Console/Command/AbstractCheckCommand.php
packages/easy-coding-standard/src/Console/Command/ListCheckersCommand.php
packages/easy-coding-standard/src/Console/Command/ShowCommand.php
packages/easy-coding-standard/src/Console/Reporter/CheckerListReporter.php

Reverts symplify/symplify#3927
Now we need this command for tools inter-operability :+1:

[ECS] Add "list-checkers" command to allow tools interoperability

---

packages/easy-ci/src/Git/ConflictResolver.php
packages/easy-ci/tests/Git/ConflictResolver/ConflictResolverTest.php
packages/easy-ci/tests/Git/ConflictResolver/Fixture/some_other_file.txt

Updates the regex to seven characters, so it will trigger on git conflicts.
Closes #4498

[Easy-CI] check-conflicts regex update

---

composer.json
packages/php-config-printer/src/Printer/PhpParserPhpConfigPrinter.php
packages/php-config-printer/tests/Printer/SmartPhpConfigPrinter/Fixture/expected_constant_file.php.inc
packages/php-config-printer/tests/Printer/SmartPhpConfigPrinter/Fixture/expected_file.php.inc
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/configurable_phpcsfixer_content.md
packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/configurable_rector_content.md
phpstan.neon

Balances cleanup from ECS: https://github.com/easy-coding-standard/easy-coding-standard/pull/45

[PhpDocPrinter] Prepare automated array indent
