packages/ControllerAutowire/src/DependencyInjection/Compiler/DecorateControllerResolverPass.php, packages/ControllerAutowire/tests/DependencyInjection/Compiler/DecorateControllerResolverPassTest.php
There is used bad reference ID when you are injecting old decorated service into decorator. See docs: http://symfony.com/doc/current/service_container/service_decoration.html
=> Fix injection of old decorated controller resolver service

packages/Statie/src/Console/Command/GenerateCommand.php, packages/Statie/src/Console/Command/PushToGithubCommand.php
@TomasVotruba I just don't see any point in catching the exception - commands from Symfony & Doctrine don't do that either.
=> Remove try-catch from commands

packages/Statie/src/Console/Command/PushToGithubCommand.php, packages/Statie/src/Github/GihubPublishingProcess.php, packages/Statie/tests/Github/GihubPublishingProcessTest.php
I'm using GH pages, but I want to have only the base url **example.github.io** . But the output code has to be uploaded in master branch instead of command's default "gh-pages". So I've added a new option to the **push-to-github** command **--branch**. The default value is still "gh-pages", so the change won't affect anything. Sniffer has passed.
=> [Statie] Add: branch option to push-to-github command

composer.json, easy-coding-standard.neon, packages/Statie/composer.json, packages/Statie/src/Metrics/PostSimilarityAnalyzer.php, packages/Statie/src/config/services.neon, packages/Statie/tests/Latte/Filter/SimilarPostsFilterTest.php, packages/Statie/tests/Metrics/SimilarPostsResolverTest.php, packages/Statie/tests/PostsSource/2017-01-05-another-related-post.md, packages/Statie/tests/PostsSource/2017-01-05-some-related-post.md
`similar_text` algorithm was to slow, so I replaced it by [custom one](https://github.com/Symplify/Symplify/pull/95#issuecomment-285973481), as advised by @tomasfejfar
Thank you, Tom.
From 50 ms to 4 ms.
=> [Statie] related posts filters fixes

packages/SymbioticController/src/Adapter/Nette/Application/InvokablePresenterAwareApplication.php, packages/SymfonyEventDispatcher/src/Adapter/Nette/DI/NetteEventListFactory.php, packages/SymfonyEventDispatcher/src/Adapter/Nette/Event/RequestReceivedEvent.php, packages/SymfonyEventDispatcher/tests/Adapter/Nette/NetteEvent/DispatchApplicationTest.php, packages/SymfonyEventDispatcher/tests/Adapter/Nette/NetteEvent/EventSubscriber/ApplicationSubscriber.php
I consider this to be a BC break - anyone who is using this event, including me, will need to update all event subscribers listening to this event.
=> [SymbioticController] Fixed typo in nette application request event name

packages/CodingStandard/composer.json, packages/EasyCodingStandard/easy-coding-standard.neon, packages/EasyCodingStandard/packages/Configuration/src/CheckerConfigurationNormalizer.php, packages/EasyCodingStandard/packages/Configuration/src/Exception/InvalidConfigurationTypeException.php, packages/EasyCodingStandard/packages/Configuration/tests/ConfigurationNormalizerTest.php, packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php, packages/PackageBuilder/composer.json, packages/Statie/composer.json
This now allows more open configuration in `easy-coding-standard.neon`:
```yaml
checkers:
PHP_CodeSniffer\Standards\Generic\Sniffs\Files\LineLengthSniff:
```
and
```yaml
checkers:
```
and informative Exception for
```yaml
checkers:
LineLenghtChecker: 120 # oh, I don't know there should be property name in array
```
=> [EasyCodingStandard] allow checker with empty configuration [closes #203]

packages/EasyCodingStandard/src/DependencyInjection/AppKernel.php, packages/PackageBuilder/src/Exception/Neon/InvalidSectionException.php, packages/PackageBuilder/src/Neon/Loader/NeonLoader.php, packages/PackageBuilder/tests/Neon/Loader/NeonLoaderSource/configWithAllowedSections.neon, packages/PackageBuilder/tests/Neon/Loader/NeonLoaderSource/configWithUnknownSections.neon, packages/PackageBuilder/tests/Neon/Loader/NeonLoaderTest.php, phpstan.neon
Closes #213 
Solution invalid sections in config, as mentioned in https://github.com/Symplify/Symplify/issues/202#issuecomment-311943605
Use in `AppKernel` like this: https://github.com/Symplify/Symplify/pull/223/files#diff-9440496cf7711249c9897be866c8b3daR32
What do you think @dg?
=> [PackageBuilder] NeonLoader - validate allowed sections feature added

packages/EasyCodingStandard/src/DependencyInjection/Extension/CheckersExtension.php, packages/EasyCodingStandard/tests/Indentation/IndentationTest.php
… because nothing else has sense
How to test it?
=> [CheckersExtension] uses PHP_EOL for line-ending 

packages/EasyCodingStandard/bin/easy-coding-standard.php
For errors like "missing configuration file" etc.
=> [EasyCodingStandard] error is propagated to exit code

easy-coding-standard.neon, packages/CodingStandard/README.md, packages/CodingStandard/src/Fixer/Php/ClassStringToClassConstantFixer.php, packages/CodingStandard/src/Sniffs/Namespaces/ClassNamesWithoutPreSlashSniff.php, packages/CodingStandard/tests/Fixer/Php/ClassStringToClassConstantFixerTest.php, packages/CodingStandard/tests/Fixer/Php/fixed/fixed.php.inc, packages/CodingStandard/tests/Fixer/Php/fixed/fixed2.php.inc, packages/CodingStandard/tests/Fixer/Php/fixed/fixed3.php.inc, packages/CodingStandard/tests/Fixer/Php/wrong/wrong.php.inc, packages/CodingStandard/tests/Fixer/Php/wrong/wrong2.php.inc, packages/CodingStandard/tests/Fixer/Php/wrong/wrong3.php.inc, packages/EasyCodingStandard/packages/SniffRunner/tests/Error/ErrorSorterTest.php, packages/SymbioticController/tests/Adapter/Nette/Application/PresenterFactoryTest.php
Closes #260 
Converts: `SomeClass` => `\SomeClass::class`
=> [CodingStandard] ClassStringToClassCosntantFixer init

composer.json, packages/EasyCodingStandard/README.md, packages/EasyCodingStandard/src/Contract/Finder/CustomSourceProviderInterface.php, packages/EasyCodingStandard/src/Exception/Finder/InvalidSourceTypeException.php, packages/EasyCodingStandard/src/Finder/FinderSanitizer.php, packages/EasyCodingStandard/src/Finder/SourceFinder.php, packages/EasyCodingStandard/tests/Finder/FinderSanitizerSource/FileWithClass.php, packages/EasyCodingStandard/tests/Finder/FinderSanitizerTest.php, packages/EasyCodingStandard/tests/Finder/SourceFinderSource/PhpAndIncFilesSourceProvider.php, packages/EasyCodingStandard/tests/Finder/SourceFinderTest.php
**Empty files were causing bugs**, because PHP-CS-Fixer excluded them in own Finder and not in the fixer code itself, for more info see: https://github.com/nette/coding-standard/issues/12#issuecomment-319102644
Allow `CustomSourceProviderInterface` to be more error proof by using sanitizer service and more DX friendly requiring only iterator to return.
This is less WTF to `Finder` users, because `iterator_to_array` is never used in their context in common cases.
```php
final class PhpAndIncFilesSourceProvider implements CustomSourceProviderInterface
{
/**
* @param string[] $source
* @return mixed[]|SymfonyFinder|NetteFinder
*/
public function find(array $source)
{
$finder = Finder::find('*.php.inc')->in($source);
return iterator_to_array($finder->getIterator());
}
}
```
```php
final class …
```
=> [EasyCodingStandard] fix empty file error add FinderSanitizer, makes SourceFinder error proof

packages/Statie/src/Latte/Filter/GithubPrLinkFilterProvider.php, packages/Statie/tests/Latte/Filter/GithubPrLinkFilterProviderTest.php
It is possible to define source directory in generate command via an argument, but in Github latte filter the path to a file is hardcoded though couldn't be changed. This change fixes it.
=> [Statie] removed hardcoded path from github filter

packages/CodingStandard/src/Fixer/Property/ArrayPropertyDefaultValueFixer.php, packages/CodingStandard/tests/Fixer/Property/ArrayPropertyDefaultValueFixer/Test.php, packages/CodingStandard/tests/Fixer/Property/ArrayPropertyDefaultValueFixer/fixed/fixed3.php.inc, packages/CodingStandard/tests/Fixer/Property/ArrayPropertyDefaultValueFixer/wrong/wrong3.php.inc
A single-lined annotation is a valid annotation. In my opinion, deciding that they are errors or not should be matter of another fixer.
=> ArrayPropertyDefaultValueFixer: allow single-lined anotations

packages/CodingStandard/README.md, packages/CodingStandard/src/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer.php, packages/CodingStandard/tests/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer/Test.php, packages/CodingStandard/tests/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer/fixed/fixed.php.inc, packages/CodingStandard/tests/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer/fixed/fixed2.php.inc, packages/CodingStandard/tests/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer/wrong/wrong.php.inc, packages/CodingStandard/tests/Fixer/ControlStructure/RequireFollowedByAbsolutePathFixer/wrong/wrong2.php.inc, packages/EasyCodingStandard/bin/easy-coding-standard.php, packages/EasyCodingStandard/config/symplify-checkers.neon, packages/Statie/bin/statie.php
Cover cases like:
```php
require 'vendor/autoload.php';
require '/vendor/autoload.php';
```
=>
```php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/autoload.php';
````
---
```php
require 'phar://' . __FILE__ . '/tracy.php';
```
=> [CodingStandard] add RequireFollowedByAbsolutePathFixer

packages/CodingStandard/src/Tokenizer/DocBlockAnalyzer.php, packages/CodingStandard/tests/Fixer/Property/ArrayPropertyDefaultValueFixer/Test.php, packages/CodingStandard/tests/Fixer/Property/ArrayPropertyDefaultValueFixer/correct/correct.php.inc, packages/PackageBuilder/src/HttpKernel/AbstractCliKernel.php
For Doctrine collections Slevomat coding standard forces me to define them like this:
```php
/**
* @var Collection|Foo[]
*/
private $foo;
```
This confuses ArrayPropertyDefaultValueFixer to think it's an array property and should be initialized with `= []` while it is in fact a collection and should be initialized with `new ArrayCollection()` in constructor instead.
=> [CodingStandard] Fix ArrayPropertyDefaultValueFixer

packages/CodingStandard/README.md, packages/CodingStandard/packages/FixerTokenWrapper/src/AbstractVariableWrapper.php, packages/CodingStandard/packages/FixerTokenWrapper/src/DocBlockWrapper.php, packages/CodingStandard/packages/FixerTokenWrapper/src/MethodWrapper.php, packages/CodingStandard/packages/FixerTokenWrapper/src/PropertyWrapper.php, packages/CodingStandard/src/Fixer/Commenting/RemoveUselessDocBlockFixer.php, packages/CodingStandard/src/Sniffs/Debug/CommentedOutCodeSniff.php, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/Test.php, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/correct/correct.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed2.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed3.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/fixed/fixed4.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong2.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong3.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/wrong/wrong4.php.inc, packages/EasyCodingStandard/README.md, packages/EasyCodingStandard/config/clean-docblock.neon, packages/EasyCodingStandard/packages/SniffRunner/src/File/File.php
Closes #416 
- add `clean-docblock.neon` set to ECS
=> [CodingStandard] no extra doc block Fixer

packages/CodingStandard/README.md, packages/CodingStandard/src/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer.php, packages/CodingStandard/tests/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer/RemoveSuperfluousDocBlockWhitespaceFixerTest.php, packages/CodingStandard/tests/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer/fixed/fixed.php.inc, packages/CodingStandard/tests/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer/wrong/wrong.php.inc, packages/EasyCodingStandard/config/symplify.neon, phpstan.neon
- class: [`Symplify\CodingStandard\Fixer\Commenting\RemoveSuperfluousDocBlockWhitespaceFixer`](/src/Fixer/Commenting/RemoveSuperfluousDocBlockWhitespaceFixer.php)
:x:
```php
/**
* @param int $value
*
*
* @return array
*/
public function setCount($value)
{
}
```
:+1:
```php
/**
* @param int $value
*
* @return array
*/
public function setCount($value)
{
}
```
=> [CodingStandard] add RemoveSuperfluousDocBlockWhitespaceFixer

packages/Statie/src/Renderable/RouteFileDecorator.php
Since the introduction of Generators the possibility of not having a `route_prefix` is not working anymore. When it's set:
```yml
parameters:
generators:
posts:
route_prefix: ''
```
there is one `DIRECTORY_SEPARATOR` in the beginning of the relative url.
This simple change will allow to have no prefix.
=> [Statie] blank route_prefix

packages/CodingStandard/README.md
I've made some improvements to the `README.md` file in `CodingStandard`:
- Make links relatives, so they can work even in the main repo, as well as in it's on read-me only;
- Remove duplicate unused lines;
- Fix some examples.
=> [CodingStandard] Improve README.md

build/clear_readmes.sh, composer.json, packages/ChangelogLinker/README.md, packages/CodingStandard/README.md, packages/PackageBuilder/README.md
As [suggested](https://github.com/Symplify/Symplify/pull/546#issuecomment-354517267) by @TomasVotruba, we should have a `.sh` to help us keep our `README.md` cleans :sunglasses:
=> [Symplify] Create clear_readmes.sh

packages/Statie/src/FileSystem/FileFinder.php
On windows DIRECTORY_SEPARATOR is backslash, escaping the ending hash.
=> Properly quote regex contents

packages/EasyCodingStandard/config/symfony.neon
=> Remove PHP codesniffer rules from symfony.neon

packages/Statie/packages/Generator/src/Generator.php, packages/Statie/src/Renderable/RenderableFilesProcessor.php
Before this, sorting of objects is called before object has set atributes.
So it didn't work
=> [Statie] fix race condition for element sorting with configuration

monorepo.yml, packages/ChangelogLinker/.travis.yml, packages/EasyCodingStandard/.travis.yml, packages/Monorepo/.travis.yml, packages/Monorepo/bin/monorepo, packages/Monorepo/src/Console/Command/SplitCommand.php, packages/Monorepo/src/Exception/Worker/PackageToRepositorySplitException.php, packages/Monorepo/src/PackageToRepositorySplitter.php, packages/Statie/.travis.yml
There is been speed improvement for split, but spatie/async return error codes on success process. No idea how/why. Also the fluent API has some flaws that break autocomplete and provide missing types and vice versa.
The priority now is working tool, so it needed to be removed for `split` command.
Remains for history rename, where works fine.
=> [Monorepo] PackageSplitter - remove async

packages/Monorepo/src/Console/Command/BuildCommand.php, packages/Monorepo/src/Filesystem/Filesystem.php, packages/Monorepo/src/RepositoryToPackageMerger.php, packages/Monorepo/src/Worker/MoveHistoryWorker.php
Reasons for this changes:
- outputting every commit for history of 5000 files was compute time demaning and memory leaking
- informattie message would do you just fine and speed up process from hours to minutes
Reported by @Miroslav-Stopka
=> [Monorepo] improve reporting messages, decrease reporting at mv-history

easy-coding-standard.neon, packages/CodingStandard/README.md, packages/CodingStandard/src/Fixer/Naming/ClassNameSuffixByParentFixer.php, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/ClassNameSuffixByParentFixerTest.php, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/fixed/fixed.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/fixed/fixed2.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/fixed/fixed3.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/fixed/fixed4.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/wrong/wrong.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/wrong/wrong2.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/wrong/wrong3.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/wrong/wrong4.php.inc, packages/EasyCodingStandard/config/symplify.neon, packages/TokenRunner/src/Wrapper/FixerWrapper/ClassWrapper.php
=> [CodingStandard] Add ClassNameSuffixByParentFixer

packages/EasyCodingStandard/composer.json
I know you locked it to prevent BC breaks. That's why I changed it to `~2.10.0` instead of `^2.10`.
=> Allow PHP-CS-Fixer 2.10.x

composer.json, packages/EasyCodingStandard/composer.json
The findBlockStart method was added in v2.10.3.
```
In FixerFileProcessor.php line 125:
Fixing of "src/ContactAdministration/DomainModel/Address/UpdateAddressInformation/AddressInformationUpdated.php" file by "Symplify\CodingStandard\Fixer\ArrayNotation\StandaloneLineInMultilineArray  
Fixer" failed: Call to undefined method PhpCsFixer\Tokenizer\Tokens::findBlockStart() in file .../vendor/symplify/token-runner/src/Analyzer/FixerAnalyzer/TokenSkipper.php on line 39     
```
=> [EasyCodingStandard] Fix required php-cs-fixer version

packages/CodingStandard/src/Fixer/Commenting/BlockPropertyCommentFixer.php
This fixer needs to be run before PhpCsFixer\Fixer\Phpdoc\PhpdocVarWithoutNameFixer to avoid this situation
first run
```diff
-    /** @var Delete $delete */
+    /**
+     * @var Delete $delete
+     */
private $delete;
```
second run
```diff
/**
-     * @var Delete $delete
+     * @var Delete
*/
private $delete;
```
=> Adjust priority of BlockPropertyCommentFixer

composer.json, packages/CodingStandard/src/Fixer/LineLength/BreakMethodArgumentsFixer.php, packages/CodingStandard/tests/Fixer/LineLength/BreakMethodArgumentsFixer/BreakMethodArgumentsFixerTest.php, packages/CodingStandard/tests/Fixer/LineLength/BreakMethodArgumentsFixer/correct/correct.php.inc, packages/TokenRunner/src/Wrapper/FixerWrapper/MethodWrapper.php
Failing test for #668.
In the future you might want to fix it to
```php
return function () use (
$someLongVariableName,
$anotherLongVariableName,
$yetAnotherLongVariableName,
$andOneMoreLongVariableName
) {};
```
=> Add failing test

easy-coding-standard.yml
When I clone this repo and run `composer complete-check` it will remove annotations like `@param object $name` in favor of typehint. This should not happen though since Symplify should be compatible with PHP 7.1 and the typehint was added in PHP 7.2.
The sniff doing this actually has a configuration to fix this which I'm adding in this PR.
However for some reason it's currently broken - the `false` from configuration somehow becomes an empty string which causes a failure. I don't have time to investigate further now so I'll just leave it here.
```
[ERROR] Return value of                                                        
SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff::isVal
idTypeHint() must be of the type boolean, string returned    
```
=> Fix ECS configuration

packages/EasyCodingStandard/src/Yaml/CheckerTolerantYamlFileLoader.php, packages/EasyCodingStandard/tests/Yaml/CheckerTolerantYamlFileLoaderSource/config-with-bool.yml, packages/EasyCodingStandard/tests/Yaml/CheckerTolerantYamlFileLoaderTest.php
=> [ECS] Tolerant checker yaml file loader test fix for non-strings

packages/EasyCodingStandard/config/symfony.yml, packages/EasyCodingStandard/src/DependencyInjection/CompilerPass/RemoveMutualCheckersCompilerPass.php
Various deprecated fixers from php-cs-fixer used in symfony ruleset renamed to their new equivalents.
Not sure about the `RemoveMutualCheckersCompilerPass` - is this right?
=> [ECS] Rename deprecated Fixers to their new equivalents

packages/EasyCodingStandard/src/Console/Application.php
Hi, `-c` is widely used shortcut for config file, so it would by nice to have it in ECS as well.
Used for example by:
- [PHPUnit](https://phpunit.de/manual/current/en/textui.html)
- [PHPStan](https://github.com/phpstan/phpstan#configuration)
- [Steward](https://github.com/lmc-eu/steward/wiki/Configuration-file#usage) :-)
- ...
=> [ECS] Add shortcut for config file

packages/EasyCodingStandard/bin/ecs-container.php, packages/EasyCodingStandard/packages/ChangedFilesDetector/src/ChangedFilesDetector.php, packages/PackageBuilder/README.md, packages/PackageBuilder/src/Configuration/ConfigFileFinder.php, packages/PackageBuilder/src/Configuration/ConfigFilePathHelper.php, packages/PackageBuilder/src/Configuration/LevelFileFinder.php, packages/PackageBuilder/tests/Configuration/ConfigFileFinderTest.php, packages/PackageBuilder/tests/Configuration/ConfigFilePathHelperTest.php, packages/PackageBuilder/tests/Configuration/LevelConfigShortcutFinderTest.php, packages/PackageBuilder/tests/Configuration/LevelFileFinderTest.php, packages/Statie/bin/statie
Follow up fix to #705 
Surpasses #711 
- both classes accept `--config`, `-c` resp. `--level`, `-l` option names
- renamed classes to `*FileFinder` to unite naming
```diff
-use Symplify\PackageBuilder\Configuration\ConfigFilePathHelper;
+use Symplify\PackageBuilder\Configuration\ConfigFileFinder;
```
```diff
-use Symplify\PackageBuilder\Configuration\LevelConfigShortcutFinder;
+use Symplify\PackageBuilder\Configuration\LevelFileFinder;
```
=> [PackageBuilder] Make Config finder more flexible

composer.json, packages/PackageBuilder/composer.json, packages/PackageBuilder/src/Console/ThrowableRenderer.php, packages/PackageBuilder/tests/Console/ThrowableRendererTest.php
Be consistent with original Exception and use FatalThrowableError: https://github.com/symfony/symfony/pull/25255/files#diff-38eebdda7d6ebfcb7405b91167f05c9cR124
Part of #723
=> [PackageBuilder] ThrowableRenderer consistency

packages/EasyCodingStandard/src/Skipper.php
These skips were reported as unused, even if found:
```yml
parameters:
skip:
PHP_CodeSniffer\Standards\Generic\Sniffs\CodeAnalysis\AssignmentInConditionSniff.Found: ~
```
=> [ECS] fix false report of unused erros while using code for all

packages/EasyCodingStandard/src/Console/Command/CheckCommand.php, packages/EasyCodingStandard/src/Console/Style/EasyCodingStandardStyle.php
Ref #775 .
It seems SymfonyStyle has Warnings in red... https://github.com/symfony/console/blob/master/Style/SymfonyStyle.php#L155
I don't care that much (it is ok for me), so its up to you if you'd like to redefine the style or use the red color :). What do you think?
=> [ECS] Print fixable messages as warnings [WIP]

packages/CodingStandard/tests/Issues/Issue855Test.php, packages/CodingStandard/tests/Issues/config/config855.yml, packages/CodingStandard/tests/Issues/correct/correct855.php.inc
See #855 . 
Hope I got it right :). Both wrong and fixed are the same files, because the expected behavior is the file will be left untouched by the Sniff.
=> [CS] Add test case for #855

packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/RemoveUselessDocBlockFixerTest.php, packages/CodingStandard/tests/Fixer/Commenting/RemoveUselessDocBlockFixer/correct/correct18.php.inc
Fixes #869 
This is a work in progress, only failing test describing the issue yet.
=> RemoveUselessDocBlockFixer should not reformat custom annotations

ecs.yml, packages/CodingStandard/README.md, packages/CodingStandard/src/Fixer/Naming/ClassNameSuffixByParentFixer.php, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/ConfiguredTest.php, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/ListConfiguredTest.php, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/configured-config.yml, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/fixed/fixed5.php.inc, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/list-configured-config.yml, packages/CodingStandard/tests/Fixer/Naming/ClassNameSuffixByParentFixer/wrong/wrong5.php.inc
Closes #899 
```yaml
services:
Symplify\CodingStandard\Fixer\Naming\ClassNameSuffixByParentFixer:
extra_parent_types_to_suffixes:
'*FileDecorator': 'FileDecorator'
```
```diff
services:
Symplify\CodingStandard\Fixer\Naming\ClassNameSuffixByParentFixer:
extra_parent_types_to_suffixes:
-            '*FileDecorator': 'FileDecorator'
+            'FileDecorator': 'FileDecorator'
```
**or even**
```diff
services:
Symplify\CodingStandard\Fixer\Naming\ClassNameSuffixByParentFixer:
extra_parent_types_to_suffixes:
-            'FileDecorator': 'FileDecorator'
+            - 'FileDecorator'
```
=>  [CodingStandard] Allow list option in ClassNameSuffixByParentFixer

CHANGELOG.md, packages/ChangelogLinker/README.md, packages/ChangelogLinker/src/ChangeTree/ChangeSorter.php, packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php, packages/ChangelogLinker/src/Console/Output/DumpMergesReporter.php, packages/ChangelogLinker/src/Exception/MissingPlaceholderInChangelogException.php, packages/ChangelogLinker/tests/Console/Output/DumpMergesReporterTest.php, packages/ChangelogLinker/tests/Console/Output/WithTagsTest.php
=> [ChangelogLinker] Add --dry-run option to dump-merges command to dump to the output vs write into CHANGELOG.md

.travis.yml, composer.json, packages/MonorepoBuilder/packages/Split/bash/subsplit.sh, packages/MonorepoBuilder/packages/Split/src/Command/SplitCommand.php, packages/MonorepoBuilder/packages/Split/src/PackageToRepositorySplitter.php, packages/MonorepoBuilder/packages/Split/src/Process/ProcessFactory.php, packages/MonorepoBuilder/packages/Split/tests/Configuration/RepositoryGuardTest.php, packages/MonorepoBuilder/packages/Split/tests/Process/ProcessFactoryTest.php, packages/MonorepoBuilder/tests/ComposerJsonDecorator/AutoloadRelativePathComposerJsonDecorator/AutoloadRelativePathComposerJsonDecoratorTest.php
Fixes https://travis-ci.org/Symplify/MonorepoBuilder/jobs/398644876
=> [MonorepoBuilder] Fix AutoloadRelativePathComposerJsonDecoratorTest on split + cleanup subsplit.sh

packages/EasyCodingStandard/packages/SniffRunner/src/File/File.php, packages/EasyCodingStandard/src/Application/Application.php, packages/EasyCodingStandard/src/Application/SingleFileProcessor.php, packages/EasyCodingStandard/src/Error/ErrorAndDiffCollector.php, packages/EasyCodingStandard/src/Finder/FinderSanitizer.php, packages/EasyCodingStandard/tests/Finder/SourceFinderSource/AppendFileSourceProvider.php, packages/EasyCodingStandard/tests/Finder/SourceFinderSource/config-with-append-file-provider.yml, packages/EasyCodingStandard/tests/Finder/SourceFinderTest.php, phpstan.neon
Closes #939
This allows
```php
<?php declare(strict_types=1);
namespace Shopsys\CodingStandards\Finder;
use IteratorAggregate;
use SplFileInfo;
use Symfony\Component\Finder\Finder;
use Symfony\Component\Finder\SplFileInfo as SymfonySplFileInfo;
use Symplify\EasyCodingStandard\Contract\Finder\CustomSourceProviderInterface;
final class FileFinder implements CustomSourceProviderInterface
{
/**
* @param string[] $source
* @return IteratorAggregate
*/
public function find(array $source): IteratorAggregate
{
$directories = [];
$files = [];
foreach ($source as $singleSource) {
if (is_file($singleSource)) {
$fileInfo = new SplFileInfo($singleSource);
$files[$fileInfo->getPath()] = new SymfonySplFileInfo($singleSource, $fileInfo->getPath(), $fileInfo->getPathname());
} else {
$directories[] = …
```
=> [EasyCodingStandard] Fix custom source provider troubles

packages/EasyCodingStandard/src/Skipper.php, packages/EasyCodingStandard/tests/Skipper/SkipperTest.php
```yaml
parameters:
skip:
SomeClass:
- 'packages/LatteToTwigConverter/src/CaseConverter/*CaseConverter.php'
- '*packages/LatteToTwigConverter/src/CaseConverter/*CaseConverter.php'
```
```yaml
parameters:
skip:
SomeClass:
- 'packages/LatteToTwigConverter/src/CaseConverter/*CaseConverter.php'
- '*packages/LatteToTwigConverter/src/CaseConverter/*CaseConverter.php'
```
=> [EasyCodingStandard] Make fnmatch skipping more user-friendly [closes #942]

.travis.yml, packages/ChangelogLinker/tests/ChangeTree/ChangeFactoryTest.php, packages/ChangelogLinker/tests/ChangelogDumper/WithTagsTest.php, packages/ChangelogLinker/tests/Git/GitCommitDateTagResolverTest.php
Closes #866
Closes #937 as not a big performance issue
Related  https://github.com/travis-ci/travis-ci/issues/7422
The full git clone is like 3 seconds, so no problem at all:
=> [ChangelogLinker] [MonorepoBuilder] Fix Travis-related Tagging

CHANGELOG.md
Instead of property `parent_types_to_suffixes` in `ClassNameSuffixByParentFixer` one should use `defaultParentClassToSuffixMap` when migrating to `ClassNameSuffixByParentSniff`.
See https://github.com/Symplify/Symplify/issues/985.
=> CHANGELOG: Correct ClassNameSuffixByParentSniff migration instruction

packages/ChangelogLinker/src/DependencyInjection/ChangelogLinkerKernel.php, packages/ChangelogLinker/src/config/services.yml, packages/EasyCodingStandard/src/DependencyInjection/EasyCodingStandardKernel.php, packages/EasyCodingStandard/src/config/services.yml, packages/LatteToTwigConverter/src/DependencyInjection/LatteToTwigConverterKernel.php, packages/LatteToTwigConverter/src/config/config.yml, packages/MonorepoBuilder/src/DependencyInjection/MonorepoBuilderKernel.php, packages/MonorepoBuilder/src/config/config.yml, packages/PackageBuilder/README.md, packages/PackageBuilder/src/DependencyInjection/CompilerPass/PublicDefaultCompilerPass.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutoBindParametersCompilerPass/Source/config.yml, packages/Statie/src/DependencyInjection/StatieKernel.php, packages/Statie/src/config/services.yml
To get rid of cherry-picking public: true/false. It really has no added value in those packages
=> [PackageBuilder] Add PublicDefaultCompilerPass

packages/MonorepoBuilder/src/ComposerJsonDecorator/AutoloadRelativePathComposerJsonDecorator.php, packages/MonorepoBuilder/tests/ComposerJsonDecorator/AutoloadRelativePathComposerJsonDecorator/AutoloadRelativePathComposerJsonDecoratorTest.php, packages/MonorepoBuilder/tests/ComposerJsonDecorator/AutoloadRelativePathComposerJsonDecorator/SourceOverlappingNamespaces/PackageA/composer.json, packages/MonorepoBuilder/tests/ComposerJsonDecorator/AutoloadRelativePathComposerJsonDecorator/SourceOverlappingNamespaces/PackageB/composer.json
There is a problem when two packages are using namespaces like `App` and `App\Foo`.
Currently only the namespace itself is checked to be contained within a `composer.json`, so when you have a namespace `App` it will be found in each `composer.json` using `App\<whatever>` and the path of the last matching `composer.json` will be taken.
I tried to fix this by adding quotation marks for the lookup, so partial matches won't be successful anymore.
=> [MonorepoBuilder] Fix autoloading for overlapping namespaces

packages/EasyCodingStandard/bin/container.php, packages/EasyCodingStandard/packages/FixerRunner/tests/Application/FileProcessorTest.php, packages/EasyCodingStandard/packages/FixerRunner/tests/DependencyInjection/FixerServiceRegistrationTest.php, packages/EasyCodingStandard/packages/SniffRunner/tests/Application/FileProcessorTest.php, packages/EasyCodingStandard/packages/SniffRunner/tests/DI/SniffServiceRegistrationTest.php, packages/EasyCodingStandard/src/DependencyInjection/ContainerFactory.php, packages/EasyCodingStandard/src/DependencyInjection/EasyCodingStandardKernel.php, packages/EasyCodingStandard/tests/DependencyInjection/ConfigurationFileTest.php, packages/EasyCodingStandard/tests/DependencyInjection/ConflictingCheckersTest.php, packages/EasyCodingStandard/tests/DependencyInjection/ContainerFactoryTest.php, packages/EasyCodingStandard/tests/DependencyInjection/ExcludedCheckersTest.php, packages/EasyCodingStandard/tests/DependencyInjection/MutualExcludedCheckersTest.php, packages/EasyCodingStandard/tests/Error/ErrorCollector/FixerFileProcessorTest.php, packages/EasyCodingStandard/tests/Error/ErrorCollector/SniffFileProcessorTest.php, packages/EasyCodingStandard/tests/Finder/SourceFinderTest.php, packages/EasyCodingStandard/tests/Indentation/IndentationTest.php, packages/EasyCodingStandardTester/src/Testing/AbstractCheckerTestCase.php, packages/PHPStanExtensions/README.md
This change fixes previously invalid behavior, when `--level ...` isuses could not be ingnored, because `ecs.yml` would never be loaded.
This might cause to pop up new errors when `--level` and `--config` fixers are applied. The propper use is to have just one run and make it pass, so be sure to fix it and make it pass.
=> [ECS] Allow combination of --level and --config [closes #1072]

packages/EasyCodingStandard/src/Finder/FinderSanitizer.php, packages/PHPStanExtensions/src/Type/SplFileInfoTolerantDynamicMethodReturnTypeExtension.php, packages/PackageBuilder/src/Configuration/LevelFileFinder.php, packages/Statie/packages/Generator/src/Renderable/File/GeneratorFileGuard.php, phpstan.neon
**Symfony**\SplFileInfo->getRealPath() always exists, since it comes from Symfony\Finder, that finds only existing files
This removes many false positives that have to be excluded manually otherwise.
=> [PHPStanExtensions] Add SplFileInfoTolerantDynamicMethodReturnTypeExtension

packages/EasyCodingStandard/config/psr12.yml
Allow NoExtraBlankLinesFixer to be used in PSR-12.
Related to #1138
=> [ECS] Allow NoExtraBlankLinesFixer in PSR-12

packages/BetterPhpDocParser/src/PhpDocParser/TypeNodeToStringsConvertor.php
@TomasVotruba What is the reason for this `TypeNodeToStringsConvertor`? Can't we just use `TypeNode::__toString()`?
=> [BetterPhpDocParser] Add support for GenericTypeNode

packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/ParamReturnAndVarTagMalformsFixerTest.php, packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/fixed/fixed8.php.inc, packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/fixed/fixed9.php.inc, packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/wrong/wrong8.php.inc, packages/CodingStandard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/wrong/wrong9.php.inc, packages/EasyCodingStandard/config/clean-code.yml, packages/TokenRunner/src/DocBlock/MalformWorker/MissingParamNameMalformWorker.php, packages/TokenRunner/src/DocBlock/MalformWorker/SuperfluousVarNameMalformWorker.php
```diff
/**
- * @var $this
+ * @var self
*/
```
```diff
/**
- * @param int value
+ * @param int $value
*/
function ($value) {
}
```
=> [CodingStandard] Improve ParamReturnAndVarTagMalformsFixer for this and missing dollar signs

packages/EasyCodingStandard/src/Console/Command/CheckCommand.php, packages/EasyCodingStandard/src/Console/Output/CheckCommandReporter.php
Move all print functionality inside CheckCommandReporter.
This will allow to extract a common interface, and implement `CheckCommandJsonReporter` and `CheckCommandTableReporter` as mentioned here:
* https://github.com/Symplify/Symplify/issues/1095#issuecomment-420994905
* https://github.com/Symplify/Symplify/issues/1118
=> [ECS] Decouple reporting from CheckCommand to CheckCommandReporter

packages/BetterPhpDocParser/src/DependencyInjection/BetterPhpDocParserKernel.php, packages/ChangelogLinker/src/DependencyInjection/ChangelogLinkerKernel.php, packages/EasyCodingStandard/src/DependencyInjection/EasyCodingStandardKernel.php, packages/EasyCodingStandardTester/src/Testing/AbstractCheckerTestCase.php, packages/LatteToTwigConverter/src/DependencyInjection/LatteToTwigConverterKernel.php, packages/MonorepoBuilder/src/DependencyInjection/MonorepoBuilderKernel.php, packages/Statie/src/DependencyInjection/StatieKernel.php
Focus on public/private brings no value here, no need to play with compiler passes, if you why this was introduced - to move from named service locator to DI. DI is first class citizen here since the very beggining.
=> make public expicit instead of compiler pass

packages/CodingStandard/src/Fixer/Solid/FinalInterfaceFixer.php, packages/CodingStandard/tests/Fixer/Solid/FinalInterfaceFixer/FinalInterfaceFixerTest.php, packages/CodingStandard/tests/Fixer/Solid/FinalInterfaceFixer/Fixture/correct6.php.inc, packages/CodingStandard/tests/Fixer/Solid/FinalInterfaceFixer/Fixture/wrong4.php.inc, packages/TokenRunner/src/Wrapper/FixerWrapper/ClassWrapper.php
FinalInterfaceFixer adds `final` keyword onto anonymous classes which implement a interface. This is considered false positive code fixing.
```diff
// true positive code fixing
-class SomeClass implements SomeSpecialInterface
+final class SomeClass implements SomeSpecialInterface
{
public function createAnonymousClassImplementsInterface(): SomeInterface
{
// false positive code fixing
-        return new class implements SomeInterface
+        return new final class implements SomeInterface
{
};
}
}
```
This merge request solve the problem by adding modification that skips the target classes if they are anonymous classes.
```diff
// true positive code fixing
-class SomeClass implements SomeSpecialInterface
+final class SomeClass implements SomeSpecialInterface
{
public function …
```
=> [CodingStandard] fix FinalInterfaceFixer false positive for anonymous class

packages/FlexLoader/src/Flex/FlexLoader.php
Instead of using private constant to define config extensions, we can allow configuration via Loader's constructor. I think it's good to also have a default, considering that MicroKernelTraitKernel from /tests doesn't declare CONFIG_EXTS constant and can use the default. What do you think?
=> Add posibility to setup config extensions

packages/MonorepoBuilder/packages/Release/src/Command/ReleaseCommand.php
- the message "Version XY is now released!" is confusing when using stages
- we have the stage "release-candidate" that ends with sending the release-candidate branch for code-review and someone might get a fright when he sees the message telling him that the version is released
=> [MB] ReleaseCommand: stage is taken into account in success message

.gitignore, ecs.yml, packages/Statie/README.md, packages/Statie/config/config.yml, packages/Statie/src/Application/StatieApplication.php, packages/Statie/src/Renderable/ApiGenerator.php
Statie web [Friendsofphp.org](https://friendsofphp.org/) provide info about PHP meetups and groups. They're already stored in parameters. Do you want to publish them as JSON API?
```yaml
parameters:
api_parameters:
- 'groups'
- 'meetups'
```
This will generate 2 pages:
```bash
/api/groups.json
/api/meetups.json
```
With parameters as JSON, that anyone can use now.
=> [Statie] Add api generator

packages/FlexLoader/src/Flex/FlexLoader.php, packages/FlexLoader/src/Flex/FlexPathsFactory.php, packages/FlexLoader/tests/Flex/FlexLoader/Source/MicroKernelTraitKernel.php
Hi Tomáš,
sending PR - extra service paths are now checked for existence same way as the default ones in FlexPathsFactory
Fixes #1371
=> [FlexLoader] loading fails when extra path does not exists

packages/MonorepoBuilder/config/config.yml
Add `suggest` to `section_order` to avoid it to be moved at the top of the composer.json file.
Related to #1406
=> [MonorepoBuilder] Add suggest to section_order

packages/MonorepoBuilder/README.md
Simple PR just for a typo in the readme.
=> [MonorepoBuilder] Fix typo in readme to use the right package name.

packages/PackageBuilder/src/FileSystem/SmartFileInfo.php
originally I found this as problem on Windows with Statie, see #1408 ; please see discussion in issue first
=> fix SmartFileInfo getRelativePath on Windows - use normalized path

packages/CodingStandard/composer.json
Remove token-runner dependency from coding-standard because it is already directly included
=> Remove token-runner dependency from coding-standard

packages/PackageBuilder/src/Configuration/LevelFileFinder.php
getRealPath fails on phar paths. So I added a fallback. Its required for rector
=> [PackageBuilder] Fix LevelFinder bundled in phar file

packages/Statie/packages/HeadlineAnchorLinker/src/HeadlineAnchorLinker.php, packages/Statie/packages/HeadlineAnchorLinker/tests/HeadlineAnchorLinkerTest.php
New code strips all tags from `id` attribute and does not generate `<a>` element when title contains some (in any part of the title).
Let's have a look on two possible cases:
Consider heading on input
```html
<h3>Hi <b>Tom<b></h3>
```
```html
<h3 id="hi-b-tom-b">
<a href="#hi-tom">Hi <b>Tom<b></a>
</h3>
```
```html
<h3 id="hi-tom">
<a href="#hi-tom">Hi <b>Tom<b></a>
</h3>
```
Consider heading on input
```html
<h4>
<a href="https://www.webexpo.net/prague2018/talk?id=impactful-storytelling-for-innovators-and-disruptors">Impactful Storytelling for Innovators and Disruptors</a>
</h4>
```
```html
<h4 id="a-href-https-www-webexpo-net-prague2018-talk-id-impactful-storytelling-for-innovators-and-disruptors-impactful-storytelling-for-innovators-and-disruptors-a">
<a …
```
=> [Statie] Take care of elements in anchor linker

packages/ChangelogLinker/src/Github/GithubRepositoryFromRemoteResolver.php, packages/ChangelogLinker/tests/Github/GithubRepositoryFromRemoteResolverTest.php
Hello, I experienced issue with repository remote url that includes user name in it. I have added test and fix to solve my issue.
=> [CL] added support for resolving repository name from URL with user name included

packages/Statie/packages/HeadlineAnchorLinker/src/HeadlineAnchorLinker.php, packages/Statie/packages/HeadlineAnchorLinker/tests/HeadlineAnchorLinkerTest.php
According to https://github.com/crazko/statie-web/pull/38, this PR does:
- exclude `h1` from having anchors
- add `class="headline-anchor"` to headings without links
=> [Statie] Headline linker

packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass.php
=> Fixed AutowireSinglyImplementedCompilerPass - alias referencing itself

packages/PackageBuilder/src/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass/AutowireSinglyImplementedCompilerPassTest.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass/Source/AutowireSinglyImplementedInterfaceKernel.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass/Source/ServiceA.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass/Source/ServiceB.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass/Source/ServiceInterface.php, packages/PackageBuilder/tests/DependencyInjection/CompilerPass/AutowireSinglyImplementedCompilerPass/Source/config.yml
=> AutowireSinglyImplementedCompilerPass - Skipping singly implemented service if alias for interface is already registered

packages/PackageBuilder/src/Composer/VendorDirProvider.php
I tried to stay with the same logic to get the composer vendor directory, but other solution is to remove all the code and let the call of the fallback method :
```
public static function provide(): string
{
return self::reflectionFallback();
}
```
PS : tested on linux & windows
=> [PackageBuilder] Allow custom vendor path on windows system (#1577)

packages/Statie/packages/Migrator/src/Filesystem/MigratorFilesystem.php, packages/Statie/packages/Migrator/src/Worker/MarkdownSuffixCanonicaliser.php, packages/Statie/packages/MigratorJekyll/src/JekyllToStatieMigrator.php
Statie requires markdown files to be suffixed with .md, by default
jekyll has a variety of markdown file suffixes, change them all to .md.
Fixes #1586
=> [Statie] Canonicalise md suffix for jekyll migrations

packages/MonorepoBuilder/packages/Split/src/Configuration/RepositoryGuard.php, packages/MonorepoBuilder/packages/Split/tests/Configuration/RepositoryGuardTest.php
Fixes #1594 
Change the remote URL validation regex to not require the URL to end with `.git`.
I had to remove the `RepositoryGuardTest::testInvalid` unit test because there is now no way to differentiate between a GitHub project home and a GitHub repository. If I have enough free time, I might split the RepositoryGuard into several classes, one for each possible host (GitHub and Azure DevOps for now, but it would make it extensible to other hosts).
=> [MonorepoBuilder] Stop requiring the remote URL to end with '.git'

packages/MonorepoBuilder/packages/Init/src/Command/InitCommand.php, packages/MonorepoBuilder/packages/Init/templates/monorepo/monorepo-builder.yml, packages/MonorepoBuilder/src/Composer/ComposerFactory.php
This PR will allow the `init` command to resolve the current version of MonorepoBuilder and set it in the generated files.
=> [MonorepoBuilder] Dynamic monorepo-builder version in Init templates

packages/EasyCodingStandard/src/Error/ErrorAndDiffCollector.php, packages/PackageBuilder/src/FileSystem/SmartFileInfo.php
When the file's path is not below the cwd, the relative path was not being determined correctly.
Fixes #1600
=> Determine relative paths using Symfony's makePathRelative()

packages/ChangelogLinker/README.md, packages/ChangelogLinker/src/Analyzer/IdsAnalyzer.php, packages/ChangelogLinker/src/Configuration/Option.php, packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php, packages/ChangelogLinker/src/Github/GithubApi.php
These modifications enable you to release versions in multiple branches, for more information, see the following pull requests:
- https://github.com/Symplify/ChangelogLinker/pull/3
- https://github.com/shopsys/shopsys/pull/1244
~https://github.com/Symplify/MonorepoBuilder/pull/4~ - unnecessary in the end, achievable using `stages_to_allow_existing_tag` config option
=> [ChangelogLinker] allow releasing in multiple branches

packages/PackageBuilder/src/Configuration/ConfigFileFinder.php, packages/PackageBuilder/tests/Configuration/ConfigFileFinderTest.php
For another pull request, I discovered that I would need to be able to pass `-c` as a parameter to a new console command. My first attempts failed because it was always parsed as an option for the monorepo-builder configuration file.
A deeper look revealed that symfony itself has support to stop option parsing for parameters following `--` which was just what I needed.
I thought it may make sense even in the case my other pull request would be denied, so I created a pull request for this change only.
Hope you find it useful, too.
=> [PackageBuilder] Skip parameters following an end of options (--) signal

composer.json
Composer 2.0+ requires a lowercase dependency
=> Apply lowercase to compose dependencies

packages/MonorepoBuilder/packages/Split/src/Git/GitManager.php
Fix reading GIT tags in Windows non-Terminal (ConEmu, git bash, mingw cli, e.g.) CLI interfaces.
=> Fix reading GIT tags in Windows OS

ecs.yaml, packages/EasyCodingStandard/README.md, packages/EasyCodingStandard/bin/ecs, packages/EasyCodingStandard/config/set/php71.yaml, packages/EasyCodingStandard/src/Bootstrap/ConfigResolver.php, packages/EasyCodingStandard/src/Bootstrap/SetOptionResolver.php, packages/EasyCodingStandard/src/Bootstrap/SetsResolver.php, packages/EasyCodingStandard/src/Exception/Configuration/SetNotFoundException.php, packages/EasyCodingStandard/src/Set/Set.php, phpstan.neon
Closes #1651
```yaml
imports:
- { resource: 'vendor/symplify/easy-coding-standard/config/set/psr12.yaml' }
- { resource: 'vendor/symplify/easy-coding-standard/config/set/php71.yaml' }
- { resource: 'vendor/symplify/easy-coding-standard/config/set/common.yaml' }
- { resource: 'vendor/symplify/easy-coding-standard/config/set/clean-code.yaml' }
```
```yaml
parameters:
sets:
- 'psr12'
- 'php71'
- 'common'
- 'clean-code'
```
Inspiration:  https://github.com/rectorphp/rector/pull/2221
=> [ECS] Add "sets" parameter for shorter imports of native configs

packages/ChangelogLinker/composer.json, packages/EasyCodingStandard/composer.json
The following commit introduced SetConfigResolver as a separate package:
https://github.com/Symplify/Symplify/commit/30ce8c3d31162eec19ecd31975899c8762f7b88d
Packages EasyCodingStandard and ChangelogLinker use this dependency but their composer.json files were not updated in the commit above to contain the new package in "require" section.
This PR fixes the issue.
=> Add missing composer dependency on the new package SetConfigResolver

packages/SetConfigResolver/src/SetResolver.php
Fixes
```
Return value of Symplify\SetConfigResolver\SetResolver::detectFromNameAndDirectory()    
must be of the type string, boolean returned  
```
for PHAR
=> add relative path for phar

packages/EasyCodingStandard/src/DependencyInjection/CompilerPass/RemoveMutualCheckersCompilerPass.php, packages/EasyCodingStandard/tests/DependencyInjection/MutualExcludedCheckersSource/config.yml, packages/EasyCodingStandard/tests/DependencyInjection/MutualExcludedCheckersTest.php
=> [EasyCodingStandard] Prefer IncludeFixer over LanguageConstructSpacingSniff

packages/PackageBuilder/src/Strings/StringFormatConverter.php, packages/PackageBuilder/tests/Strings/StringFormatConverterTest.php
=> [PackageBuilder] Handle single characters in the StringFormatConverter::camelCaseToGlue() method

packages/ChangelogLinker/src/ChangelogLinker.php, packages/ChangelogLinker/src/Console/Command/DumpMergesCommand.php, packages/ChangelogLinker/src/Console/Command/LinkCommand.php, packages/ChangelogLinker/src/FileSystem/ChangelogFileSystem.php, packages/ChangelogLinker/src/LinkAppender.php
ChangelogLinker do not adds a _new line_ at the end of changelog files. I already tried to fix this with PR #1605, details can be found in issue #1604.
It turns out that the code I wrote is never called in _DumpMergesCommand_ nor in _LinkCommand_.
This PR fix this.
=> [CL] Honouring final new line in changelog (for real)

packages/EasyCodingStandard/README.md
The documentation was incorrect about the file path of the default cache folder as per the YAML,
it is supposed to be `'%sys_get_temp_dir%/_changed_files_detector%env(TEST_SUFFIX)%'`.
=> [ECS] Fix default cache directory documentation

packages/phpstan-extensions/config/config.neon, packages/phpstan-extensions/config/rules.neon, packages/phpstan-extensions/src/Rules/ClassMethod/BoolishClassMethodPrefixRule.php, packages/phpstan-extensions/tests/Rules/ClassMethod/BoolishClassMethodPrefixRuleTest.php, packages/phpstan-extensions/tests/Rules/ClassMethod/Source/InterfaceWithReturnType.php, packages/phpstan-extensions/tests/Rules/ClassMethod/Source/SkipRequiredByInterface.php
=> [PHPStanExtensions] Make BoolishClassMethodPrefixRule skip parent interface required methods

packages/flex-loader/src/Flex/FlexLoader.php, packages/flex-loader/src/Flex/FlexPathsFactory.php, packages/flex-loader/tests/Flex/FlexLoader/MicroKernelTraitTest.php, packages/flex-loader/tests/Flex/FlexLoader/Source/extra-dir/config.yml, packages/flex-loader/tests/Flex/FlexLoader/Source/project-dir-micro-kernel/config/packages/config.yml
Hi,
here is promised PR for https://github.com/symplify/symplify/issues/1780
Hope it's more clear now from the test. Before this change
```php
$container->getParameter('package_param_overridable_on_app_level')
```
would return `default_value` instead of `app_level_value`
In my oppition now it has the same behaviour as Symfony. As you are able to override params in same structure like for example doctrine params in `config/packages/doctrine.yaml`
What do you think? :)
=> [FlexLoader] Priority of loaded configs

CHANGELOG.md, composer.json, packages/monorepo-builder/src/Console/Command/SortAutoloadNamespaceCommand.php, packages/monorepo-builder/src/FileSystem/JsonFileManager.php
This commands sorts namespaces in "autoload"/"autoload-dev" PSR-4 sections:
```bash
vendor/bin/monorepo-builder sort-autoload-namespace
```
Closes #1778
=> [MB] Add SortAutoloadNamespaceCommand

packages/monorepo-builder/README.md, packages/monorepo-builder/config/config.yaml, packages/monorepo-builder/src/Finder/PackageComposerFinder.php, packages/monorepo-builder/tests/Finder/PackageComposerFinder/Source/First/ExcludeThis/composer.json, packages/monorepo-builder/tests/Finder/PackageComposerFinder/Source/source_config.yaml
I've added a new feature to ignoring specific composer.json in specific folders. 
Example for monorepo-builder.yml
```
parameters:
package_directories_excludes:
- 'ExcludeThis'
```
I need this for my project.
=> [MonorepoBuilder] Add composer exclude folders dynamicly

packages/symfony-static-dumper/README.md
On a fresh install of Symfony, after require static dumper, and importing it's config, I get this error : 
```
In DefinitionErrorExceptionPass.php line 54:
Cannot autowire service "Symplify\SymfonyStaticDumper\ControllerWithDataProviderMatcher": argument "$controllerWithDataProviders" of method "__construct()" is type-hinted "array", you should configure its value explicitly.   
```
When adding the compilerPass `AutowireArrayParameterCompilerPass`, it's fixed.
I think it should be mentionned :+1:
=> [Static Dumper] [Docs] Add compiler pass in kernel

packages/symfony-static-dumper/README.md
I've just tried to use the package following the readme but the actual command is `dump-static-site` so just fixing it for everybody else.
=> Fix command in README.md

packages/auto-bind-parameter/composer.json
It is required only for tests, so no need to install it for every installation
=> Move PackageBuilder dependency to require-dev

packages/monorepo-builder/README.md, packages/monorepo-builder/packages/release/src/Command/ReleaseCommand.php, packages/monorepo-builder/packages/release/src/Guard/ReleaseGuard.php, packages/monorepo-builder/packages/release/src/ValueObject/SemVersion.php, packages/monorepo-builder/packages/release/src/Version/VersionFactory.php
Closes #1838
```bash
vendor/bin/monorepo-builder release v0.7.x... what was the last patch version?
```
Let tool solve it for you!
```bash
vendor/bin/monorepo-builder release patch
```
:+1: 
Note: works with `minor` and `major` keywords too.
=> [MB] Add release keyword for ReleaseCommand

packages/monorepo-builder/packages/init/src/Command/InitCommand.php
Fixes #1871.
Actually `init` command fails if a version number is not explicitly set in `monorepo-builder/composer.json`.
This PR catches the exception and looks for the package version in `vendor/composer/installed.json`, if the file is not available (e.g. custom installation/workflow) a friendly warning is shown:
```
[WARNING] Could not update "symplify/monorepo-builder" version, please update it manually inside the root              
"composer.json" file
```
And `%UPDATE_VERSION_HERE%` will be replaced in the template.
=> [MonorepoBuilder] Handling version exceptions in "init" command

packages/easy-coding-standard/.gitattributes
Prevent box.phar false autocomplete like
=> [ECS] Do not install box.phar on ecs require

packages/easy-coding-standard/src/Yaml/CheckerServiceParametersShifter.php, packages/easy-coding-standard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsSource/config-with-at.yaml, packages/easy-coding-standard/tests/Yaml/FileLoader/CheckerTolerantYamlFileLoader/DefinitionsTest.php
Bugfix when service definition contains multiple '@'. Better Yaml config loader tests. Fix #1921.
=> Bugfix when service definition contains multiple '@'

packages/coding-standard/src/Bundle/SymplifyCodingStandardBundle.php, packages/coding-standard/tests/HttpKernel/SymplifyCodingStandardKernel.php, packages/easy-coding-standard/src/Bundle/EasyCodingStandardBundle.php, packages/easy-coding-standard/src/HttpKernel/EasyCodingStandardKernel.php
Might fix https://github.com/symplify/symplify/issues/1952
=> [ECS] Dislocate bundle locations to prevent symfony/flex autoregistration

packages/changelog-linker/tests/ChangelogLinker/Fixture/link_inside_repository_url.md
As in #1963.
Test fails on this error:
```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
'## CodingStandard
- [shopsys/microservice-product] is part of names_to_urls
-- [#1850]: https://github.com/shopsys/microservice-product/pull/1850
+- [#1850]: https://github.com/[shopsys/microservice-product]/pull/1850
[shopsys/microservice-product]: https://github.com/shopsys/microservice-product
'
/git/symplify/packages/changelog-linker/tests/ChangelogLinker/ChangelogLinkerTest.php:44
```
And I think so use case in test is correct, but I may be wrong.
=> [ChangelogLinker] added failing test with expected result in ChangelogLinkerTest

packages/monorepo-builder/README.md
Putting fixed url into monorepo according to:
https://github.com/symplify/monorepo-builder/pull/8#issuecomment-654696202
=> Fix broken URL in monorepo-builder Readme

packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/DocBlockFinder.php
=> Find only docblocks that are parseable by phpdoc-parser

packages/easy-coding-standard/src/DependencyInjection/CompilerPass/ConflictingCheckersCompilerPass.php
- Create a conflict resolution between a PSR-12 sniff requiring a newline and a PHP-CS-Fixer rule that removes newlines
=> Add a new conflict resolution

packages/composer-json-manipulator/src/FileSystem/JsonFileManager.php, packages/composer-json-manipulator/tests/ComposerJsonSchemaValidation/ComposerJsonSchemaValidationTest.php, packages/composer-json-manipulator/tests/ComposerJsonSchemaValidation/Source/symfony-website_skeleton-composer.json, packages/easy-hydrator/src/ValueResolver.php
This PR fixes #2000.
I think that removing empty keys in `JsonFileManager::encodeJsonToFileContent()` should solve the problem ensuring that any dumped file gets cleaned up properly.
I also tried to create a test case but I don't know much about this topic, so I have some questions:
- I don't know if using a custom `composer.json` template would be a good idea so I used a real one from https://github.com/symfony/website-skeleton (it shows many interesting cases: empty keys, empty nested keys, custom keys, etc.), is it ok?
- I decided to validate the resulting json file using `composer validate`, but I don't know if there's a better way to run a composer command programmatically
- I used some classes from external dependecies that might not be included in the **Composer Json Manipulator** …
=> [ComposerJsonManipulator] Removing empty keys from json content before dumping to file

packages/easy-coding-standard/config/set/symfony.php
Fixes:
```
PHP Fatal error:  Uncaught Symfony\Component\OptionsResolver\Exception\InvalidOptionsException:
The option "comment_types" with value "hash" is expected to be of type "array", but is of type "string".
in /path/to/project/vendor/symfony/options-resolver/OptionsResolver.php:1017
```
=> Correct the type of the configuration.

packages/easy-coding-standard/src/Console/Command/FindCommand.php
Command will removed, because the number of rule is growing very quickly and "googling" in CLI sucks.
Also we're moving to PHP configuration based on constant autocomplete: 
* https://twitter.com/rectorphp/status/1288874586084433925
* https://twitter.com/rectorphp/status/1289288283655036930
In CLI class rename change can cause head ache, e.g.
```bash
vendor/bin/ecs find array sniff
// how was it?
vendor/bin/ecs find arraySniff
```
With PHP, the PHPStorm IDE is here for you much advanced with fuzzy search
```php
<?php
declare(strict_types=1);
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symplify\EasyCodingStandard\Configuration\Option;
return static function (ContainerConfigurator $containerConfigurator): void {
$services = …
```
=> [ECS] Deprecate "find" command

packages/easy-coding-standard/bin/ecs
The ECS is moving from YAML to PHP syntax. This should prepare whole community in time, 
before YAML is dropped and make use of upcoming PHP features.
```bash
composer require migrify/config-transformer --dev
vendor/bin/config-transformer switch-format -i yaml -o php ecs.yaml
composer remove migrify/config-transformer
```
If any problem appears, create an issue in
https://github.com/migrify/config-transformer
<br>
We'll do what we can to resolve it promptly so you can migrate safely
<br>
Thank you for patience and cooperation with this big step :+1:  
We belieive it will bring solid ground for more lazy features like `SetList::PSR_12` name autocompletes
=> [ECS] Warn about deprecated YAML syntax

monorepo-builder.php, packages/monorepo-builder/README.md, packages/monorepo-builder/packages/split/src/Command/SplitCommand.php, packages/monorepo-builder/packages/split/src/PackageToRepositorySplitter.php, phpstan.neon
```php
$parameters->set(Option::DIRECTORIES_TO_REPOSITORIES, [
'packages/autowire-array-parameter' => 'git@github.com:symplify/autowire-array-parameter.git',
'packages/auto-bind-parameter' => 'git@github.com:symplify/auto-bind-parameter.git',
'packages/smart-file-system' => 'git@github.com:symplify/smart-file-system.git',
'packages/package-builder' => 'git@github.com:symplify/package-builder.git',
'packages/easy-coding-standard' => 'git@github.com:symplify/easy-coding-standard.git',
'packages/easy-coding-standard-tester' => 'git@github.com:symplify/easy-coding-standard-tester.git',
'packages/coding-standard' => 'git@github.com:symplify/coding-standard.git',
'packages/changelog-linker' => 'git@github.com:symplify/changelog-linker.git',
'packages/monorepo-builder' => …
```
=> [MonorepoBuilder] Add asterisk split support

packages/coding-standard/README.md, packages/coding-standard/docs/php_code_sniffer_sniffs.md, packages/coding-standard/docs/phpcs_fixer_fixers.md, packages/coding-standard/docs/phpstan_rules.md, packages/coding-standard/src/Fixer/Annotation/NewlineInNestedAnnotationFixer.php, packages/coding-standard/tests/Fixer/Annotation/NewlineInNestedAnnotationFixer/Fixture/basic_annotation_join.php.inc, packages/easy-coding-standard/config/set/doctrine-annotations.php, packages/set-config-resolver/src/SetResolver.php
=> [CS] Improving README

packages/monorepo-builder/packages/release/src/Process/ProcessRunner.php
This actually respects previous behavior
Fix after  #2080
=> do not show output if not needed

packages/coding-standard/composer.json
As far as I can tell `symplify/smart-file-system` and `symplify/phpstan-extensions` are only used in tests.
I found out by wondering why is `symplify/phpstan-extensions` installed to my project even though don't want it. (The rules there seem incorrect to me.) `composer why` revealed that it was a dependency of `coding-standard`.
=> Move dependencies to require-dev

packages/easy-coding-standard/src/Formatter/AbstractPHPFormatter.php, packages/easy-coding-standard/src/HeredocNowdoc/HeredocNowdocPHPCodeFormatter.php
using `msU` fix the multiple snippet, but seems cause a bug on trimming code:
```php
There was 1 failure:
1) Symplify\EasyCodingStandard\Tests\HeredocNowdoc\HeredocNowdocPHPCodeFormatterTest::test with data set #5 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
packages/easy-coding-standard/tests/HeredocNowdoc/Fixture/trim.php.inc
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
public function getDefinition(): string
{
return <<<'PHP'
+
<?php
class Definition
{
public function getResult(): array
{
-        return ['test' => 'data'];
+        return array('test' => 'data');
}
}
+
PHP;
}
}
'
/Users/samsonasik/www/symplify/packages/easy-coding-standard/tests/HeredocNowdoc/HeredocNowdocPHPCodeFormatterTest.php:51
```
=> Fix heredoc/nowdoc formatter regex for multiple code snippet in single php file

packages/changelog-linker/src/Github/GithubRepositoryFromRemoteResolver.php, packages/changelog-linker/tests/Github/GithubRepositoryFromRemoteResolverTest.php
`rtrim` second parameter is a list, the order of characters doesn't matter.
Example: 
```php 
$url = 'git@github.com:space/low-orbit.git';
rtrim($url, '.git'); // "git@github.com:space/low-orb"
```
The correct output should be `git@github.com:space/low-orbit`. I fixed that.
=> [ChangelogLinker] Fix url resolving for repos in SSH format

packages/easy-coding-standard/src/Console/Output/ConsoleOutputFormatter.php
```diff
- Found 1 error that need to be fixed manually.
- Found 2 errors that needs to be fixed manually.
+ Found 1 error that needs to be fixed manually.
+ Found 2 errors that need to be fixed manually.
```
=> Correct when to pluralise word

packages/easy-coding-standard/src/DependencyInjection/CompilerPass/ConflictingCheckersCompilerPass.php
It seems there is no conflict after all.
The first runs explicitly before the latter: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/bb9f72904497cea78b59faa3abeca21aaa5390a5/src/Fixer/Operator/NotOperatorWithSpaceFixer.php#L44-L52
=> [ECS] Remove unary/not-operator conflicts, false positive

packages/coding-standard/src/Rules/NoProtectedElementInFinalClassRule.php, packages/coding-standard/tests/Rules/NoProtectedElementInFinalClassRule/NoProtectedElementInFinalClassRuleTest.php
Like in the `isMethodExistInTraits()`, the `isPropertyExistInTraits()` should check namespaced class name as well.
=> Bug fix: NoProtectedElementInFinalClassRule::isPropertyExistInTraits() should check namespaced class name

packages/coding-standard/config/symplify-rules.neon, packages/coding-standard/docs/phpstan_rules.md, packages/coding-standard/src/Rules/NoAbstractMethodRule.php, packages/coding-standard/tests/Rules/NoAbstractMethodRule/NoAbstractMethodRuleTest.php
=> Typo fix: NoAbstactMethodRule should be NoAbstractMethodRule

packages/monorepo-builder/packages/split/src/FileSystem/DirectoryToRepositoryProvider.php, packages/monorepo-builder/packages/split/tests/FileSystem/DirectoryToRepositoryProvider/DirectoryToRepositoryProviderTest.php
Absolute paths cannot be used on git split, see https://travis-ci.com/github/rectorphp/rector/jobs/397778613
This will make them relative
=> [MB] Fix absolute to relative paths

packages/coding-standard/config/symplify-rules.neon, packages/coding-standard/src/Rules/AbstractSymplifyRule.php, packages/coding-standard/src/Rules/CheckRequiredAbstractKeywordForClassNameStartWithAbstractRule.php, packages/coding-standard/src/Rules/CheckUsedNamespacedNameOnClassNodeRule.php, packages/coding-standard/src/Rules/ClassNameRespectsParentSuffixRule.php, packages/coding-standard/src/Rules/ForbiddenParentClassRule.php, packages/coding-standard/src/Rules/NoClassWithStaticMethodWithoutStaticNameRule.php, packages/coding-standard/src/Rules/PreferredClassRule.php, packages/coding-standard/src/Rules/SeeAnnotationToTestRule.php, packages/coding-standard/tests/Rules/CheckUsedNamespacedNameOnClassNodeRule/CheckUsedNamespacedNameOnClassNodeRuleTest.php, packages/coding-standard/tests/Rules/CheckUsedNamespacedNameOnClassNodeRule/Fixture/SkippedVariableNamedShortClassName.php
=> improve CheckUsedNamespacedNameOnClassNodeRule

packages/coding-standard/src/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule.php
On Windows `CheckNotTestsNamespaceOutsideTestsDirectoryRule` wouldn't have worked as inteded.
=> Use DIRECTORY_SEPARATOR constant instead of `/`

packages/easy-hydrator/composer.json
Fix missing dependencies for [ParameterTypeRecognizer](https://github.com/symplify/symplify/blob/master/packages/easy-hydrator/src/ParameterTypeRecognizer.php)
=> [EasyHydrator] fix missing ParameterTypeRecognizer dependencies

packages/easy-coding-standard/README.md
someone must have a really bad keyboard to have that many typos.
=> ecs/readme: fix fdefault typo

packages/easy-hydrator/src/TypeCaster/ObjectTypeCaster.php, packages/easy-hydrator/tests/ArrayToValueObjectHydratorTest.php, packages/easy-hydrator/tests/Fixture/PersonsCollection.php, phpstan.neon
Allow use indexed arrays, eg.:
```json
{
"permissions": {
"article" : {
"create": false,
"read": true,
"update": false,
"delete": false
},
"category" : {
"create": false,
"read": true,
"update": false,
"delete": false
}
}
}
```
=> [EasyHydrator] ObjectTypeCaster fix indexed array of objects

packages/phpstan-rules/src/Rules/CheckTypehintCallerTypeRule.php, packages/phpstan-rules/tests/Rules/CheckTypehintCallerTypeRule/CheckTypehintCallerTypeRuleTest.php, packages/phpstan-rules/tests/Rules/CheckTypehintCallerTypeRule/Fixture/SkipMultipleUsed.php, packages/phpstan-rules/tests/Rules/CheckTypehintCallerTypeRule/Fixture/SkipNotPrivate.php
Non private can be used outside/derived class, while multiple usecase can make the following case:
```php
if ($var instanceof PropertyFetch) {
$this->call($var);
}
if ($var instanceof MethodCall) {
$this->call($var);
}
```
as noted at https://github.com/rectorphp/rector/pull/4727/files#r532124867
=> [PHPStanRules] Improve CheckTypehintCallerTypeRule : skip non private and multiple usages

packages/autodiscovery/config/config.php, packages/changelog-linker/config/config.php, packages/composer-json-manipulator/config/config.php, packages/console-color-diff/config/config.php, packages/console-package-builder/tests/DependencyInjection/CompilerPass/config/command_config.php, packages/easy-coding-standard/config/services.php, packages/easy-coding-standard/packages/changed-files-detector/config/services.php, packages/markdown-diff/config/config.php, packages/phpstan-rules/composer.json, packages/phpstan-rules/tests/Rules/NoFuncCallInMethodCallRule/Fixture/Functions/Namespaced.php, packages/phpstan-rules/tests/Rules/NoFuncCallInMethodCallRule/Fixture/SkipNamespacedFunction.php, packages/phpstan-rules/tests/Rules/NoFuncCallInMethodCallRule/Source/Namespaced.php, packages/static-detector/config/config.php, packages/symfony-php-config/src/ValueObjectInliner.php, packages/symfony-route-usage/config/config.php, packages/symfony-route-usage/tests/config/config_test.php, packages/symfony-static-dumper/config/config.php, packages/symplify-kernel/config/common-config.php, packages/template-checker/config/config.php, packages/vendor-patches/config/config.php
[Symfony deprecated](https://github.com/symfony/dependency-injection/blob/5.x/CHANGELOG.md#510) `ref()` and `inline()` dependency injection functions were deprecated since symfony/dependency-injection 5.1. 
Because Symplify requires symfony/dependency-injection as ^5.1, there is no reason to not drop legacy functions.
=> Drop support for ref() and inline()

.github/workflows/code_analysis.yaml, .github/workflows/cron_generate_changenlog.yaml, .github/workflows/unit_tests.yaml, composer.json, packages/composer-json-manipulator/src/ValueObject/ComposerJson.php, packages/easy-ci/composer.json, packages/easy-ci/config/config.php, packages/easy-ci/src/Command/PhpJsonCommand.php, packages/easy-ci/src/Command/PhpVersionsJsonCommand.php, packages/easy-ci/src/Composer/SupportedPhpVersionResolver.php, packages/easy-ci/src/ValueObject/PhpVersionList.php, packages/easy-ci/tests/Composer/SupportedPhpVersionResolverTest.php, packages/package-builder/src/Testing/AbstractKernelTestCase.php, phpstan.neon
Closes https://github.com/symplify/symplify/issues/2584
Closes https://github.com/symplify/symplify/pull/2579
The output of `php-json` here: https://github.com/symplify/symplify/pull/2592/checks?check_run_id=1503614394
=> [EasyCI] Add php-json command to provide currently support PHP versions

packages/composer-json-manipulator/src/ComposerJsonFactory.php, packages/composer-json-manipulator/src/ValueObject/ComposerJson.php, packages/composer-json-manipulator/src/ValueObject/ComposerJsonSection.php, packages/monorepo-builder/packages/merge/src/ComposerKeyMerger/AuthorComposerKeyMerger.php, packages/monorepo-builder/packages/merge/tests/ComposerJsonDecorator/AbstractComposerJsonDecoratorTest.php, packages/monorepo-builder/packages/merge/tests/ComposerJsonMerger/ComposerJsonMergerTest.php, packages/monorepo-builder/packages/merge/tests/ComposerJsonMerger/Source/expected-root.json, packages/monorepo-builder/packages/merge/tests/ComposerJsonMerger/Source/main-composer.json, packages/monorepo-builder/packages/merge/tests/ComposerJsonMerger/Source/package1-composer.json, packages/monorepo-builder/packages/merge/tests/ComposerJsonMerger/Source/package2-composer.json
I noticed that `vendor/bin/monorepo-builder merge` would remove the `authors` section from the root `composer.json`.
To fix this, I added a new AuthorComposerKeyMerger that combines all the `authors` and merges them to the root `composer.json`. It uses the `name` key to produce a unique list.
Fixes #2599
=> Add AuthorComposerKeyMerger

packages/composer-json-manipulator/src/ValueObject/ComposerJson.php, packages/composer-json-manipulator/tests/ComposerJsonFactory/ComposerJsonFactoryTest.php, packages/composer-json-manipulator/tests/ComposerJsonFactory/Source/full_composer.json, packages/package-scoper/tests/ComposerJson/ScopedComposerJsonFactory/Fixture/Expected/expected_scoped_composer.json
Followup of https://github.com/symplify/symplify/pull/2604
The test was not using the `getJsonData`.
=> [ComposerJsonManipulator] Export `authors`, `type` and `conflicting`

packages/phpstan-rules/src/ComposerAutoloadResolver.php, packages/phpstan-rules/src/Rules/AbstractSymplifyRule.php
=> [PHPStanRules] Fixes CheckClassNamespaceFollowPsr4Rule check is in named directory in Windows Operating System

packages/monorepo-builder/README.md
Following the instructions to install the monorepo builder, I executed:
```bash
vendor/bin/monorepo-builder release v7.0 --dry-run
```
And I got an error:
```
[ERROR] There are no release workers registered. Be sure to add them to "monorepo-builder.php" 
```
So I added the release workers in that same step
=> Improved documentation (to avoid error)

packages/monorepo-builder/packages/testing/src/ComposerJson/ComposerJsonSymlinker.php, packages/monorepo-builder/packages/testing/tests/ComposerJson/ComposerJsonSymlinkerTest.php, packages/monorepo-builder/packages/testing/tests/ComposerJson/packages/package-three/composer.json
As requested in https://github.com/symplify/symplify/pull/2712#discussion_r549346977.
Currently, if `composer.json` already has an entry for the local package `packages/package-one`, like this:
```json
{
"name": "example/package-three",
"repositories": [
{
"type": "path",
"url": "../../packages/package-one",
"options": {
"symlink": true
}
}
]
}
```
after running `monorepo-builder localize-composer-paths` it would duplicate the entry, like this:
```json
{
"name": "example/package-three",
"repositories": [
{
"type": "path",
"url": "../../packages/package-one",
"options": {
"symlink": true
}
},
{
"type": "path",
"url": "../../packages/package-one",
"options": {
"symlink": false
}
}
]
}
```
In this PR, it checks if the entry exists, and if so it already uses it:
```json
{
"name": …
```
=> [Monorepo Builder] Avoid duplicating entries in composer.json's repositories

packages/phpstan-rules/src/Rules/ClassNameRespectsParentSuffixRule.php, packages/phpstan-rules/tests/Rules/ClassNameRespectsParentSuffixRule/ClassNameRespectsParentSuffixRuleTest.php, packages/phpstan-rules/tests/Rules/ClassNameRespectsParentSuffixRule/Fixture/SkipAnonymousClass.php
=> [PHPStanRules] Skip ClassNameRespectsParentSuffixRule on anonymous class

packages/smart-file-system/src/SmartFileSystem.php, packages/smart-file-system/tests/SmartFileSystem/SmartFileSystemTest.php, packages/smart-file-system/tests/SmartFileSystem/Source/file.txt
to avoid rector notice that make public method to private mehtod for `SmartFileSystem::readFileToSmartFileInfo()` method.
=> [Test] Test for SmartFileSystem::readFileToSmartFileInfo()

packages/monorepo-builder/README.md
Updating documentation to link to master branch version of github actions `split_monorepo.yaml` as the current linked code does not work anymore.
=> Fix link to github actions example

packages/phpstan-rules/src/ParentClassMethodNodeResolver.php
=> [PHPStanRules] Workaround parseFileToNodes() not work in php 7.4 on  Magento 2 DataObject class

composer.json, packages/phpstan-rules/src/ParentClassMethodNodeResolver.php
The reason why it doesn't work is that calling PhpParser directly causes to call [PhpParserDecorator](https://github.com/phpstan/phpstan-src/blob/master/src/Parser/PhpParserDecorator.php) which in turn calls `PHPStan\Parser\Parser::parseString()`. For some reason the abstract class was already cached in [CachedParser](https://github.com/phpstan/phpstan-src/blob/master/src/Parser/CachedParser.php) when parsed as string which means that the [RichParser.php](https://github.com/phpstan/phpstan-src/blob/master/src/Parser/RichParser.php) with the NodeConnectingVisitor wasn't used, so the `$node->getAttribute('parent')` was missing.
I might also fix this in PHPStan in CachedParser so that this situation doesn't happen but for now, this fixes it ;)
=> Use PHPStan's rich parser in ParentClassMethodNodeResolver (Fix compatibility with PHPStan 0.12.70)

packages/phpstan-rules/config/configurable-rules.neon, packages/phpstan-rules/src/Rules/MaxFileLengthRule.php, packages/phpstan-rules/tests/Rules/MaxFileLengthRule/Fixture/ItIsVeryLongFileThatPassedMaxLengthConfig.php, packages/phpstan-rules/tests/Rules/MaxFileLengthRule/Fixture/ItIsVeryLongFileThatPassedMaxLengthConfigItIsVeryLongFileThatPassedMaxLengthConfigss.php, packages/phpstan-rules/tests/Rules/MaxFileLengthRule/Fixture/SkipNotLong.php, packages/phpstan-rules/tests/Rules/MaxFileLengthRule/MaxFileLengthRuleTest.php, packages/phpstan-rules/tests/Rules/MaxFileLengthRule/config/configured_rule.neon, phpstan.neon
=> [PHPStanRules] Add MaxFileLengthRule

ecs.php, packages/easy-coding-standard/config/set/php56-migration-risky.php, packages/easy-coding-standard/config/set/php70-migration.php, packages/easy-coding-standard/config/set/php70.php, packages/easy-coding-standard/config/set/php71-migration-risky.php, packages/easy-coding-standard/config/set/php71-migration.php, packages/easy-coding-standard/config/set/php71.php, packages/easy-coding-standard/config/set/php73-migration.php, packages/easy-coding-standard/config/set/phpunit30-migration-risky.php, packages/easy-coding-standard/config/set/phpunit32-migration-risky.php, packages/easy-coding-standard/config/set/phpunit35-migration-risky.php, packages/easy-coding-standard/config/set/phpunit43-migration-risky.php, packages/easy-coding-standard/config/set/phpunit48-migration-risky.php, packages/easy-coding-standard/config/set/phpunit50-migration-risky.php, packages/easy-coding-standard/config/set/phpunit52-migration-risky.php, packages/easy-coding-standard/config/set/phpunit54-migration-risky.php, packages/easy-coding-standard/config/set/phpunit55-migration-risky.php, packages/easy-coding-standard/config/set/phpunit56-migration-risky.php, packages/easy-coding-standard/config/set/phpunit57-migration-risky.php, packages/easy-coding-standard/config/set/phpunit60-migration-risky.php, packages/easy-coding-standard/config/set/phpunit75-migration-risky.php, packages/easy-coding-standard/src/ValueObject/Set/SetList.php
Tokens are proven to be very false positives. Let's deprecate these sets that can cause more harm and make cs focus on coding standards only.
For upgrades, use http://github.com/rectorphp/rector instead
=> [ECS] Deprecate "upgrade" sets, use Rector instead

packages/coding-standard/src/DocBlock/UselessDocBlockCleaner.php, packages/coding-standard/src/Fixer/AbstractArrayFixer.php, packages/coding-standard/src/Fixer/AbstractSymplifyFixer.php, packages/coding-standard/src/Fixer/Annotation/RemovePHPStormAnnotationFixer.php, packages/coding-standard/src/Fixer/ArrayNotation/ArrayOpenerAndCloserNewlineFixer.php, packages/coding-standard/src/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer.php, packages/coding-standard/src/Fixer/Commenting/RemoveUselessDefaultCommentFixer.php, packages/coding-standard/src/Fixer/LineLength/LineLengthFixer.php, packages/coding-standard/src/Fixer/Spacing/NewlineServiceDefinitionConfigFixer.php, packages/coding-standard/src/Fixer/Spacing/StandaloneLinePromotedPropertyFixer.php, packages/coding-standard/src/TokenAnalyzer/SymfonyClosureAnalyzer.php, packages/coding-standard/tests/Fixer/Spacing/NewlineServiceDefinitionConfigFixer/Fixture/many_methods.php.inc, packages/coding-standard/tests/Fixer/Spacing/NewlineServiceDefinitionConfigFixer/Fixture/skip_already_newlined.php.inc, packages/coding-standard/tests/Fixer/Spacing/NewlineServiceDefinitionConfigFixer/Fixture/skip_not_config_call.php.inc, packages/coding-standard/tests/Fixer/Spacing/NewlineServiceDefinitionConfigFixer/Fixture/wrong.php.inc, packages/coding-standard/tests/Fixer/Spacing/NewlineServiceDefinitionConfigFixer/NewlineServiceDefinitionConfigFixerTest.php, packages/easy-coding-standard/config/set/common/spaces.php, packages/symfony-php-config/README.md
Closes https://github.com/symplify/symplify/issues/2944
```diff
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symplify\CodingStandard\Fixer\LineLength\LineLengthFixer;
return static function (ContainerConfigurator $containerConfigurator): void {
$services = $containerConfigurator->services();
-    $services->set(LineLengthFixer::class)->call('configure', [['values']]);
+    $services->set(LineLengthFixer::class)
+        ->call('configure', [['values']]);
};
```
=> [CodingStandard] Add NewlineServiceDefinitionConfigFixer

packages/rule-doc-generator/composer.json, packages/rule-doc-generator/src/Command/GenerateCommand.php, packages/rule-doc-generator/src/DirectoryToMarkdownPrinter.php, packages/rule-doc-generator/src/Finder/ClassByTypeFinder.php, packages/rule-doc-generator/src/Printer/RuleDefinitionsPrinter.php, packages/rule-doc-generator/src/RuleDefinitionsResolver.php, packages/rule-doc-generator/src/ValueObject/RuleClassWithFilePath.php, packages/rule-doc-generator/src/ValueObject/RuleDefinition.php, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/DirectoryToMarkdownPrinterTest.php, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/configurable_phpcsfixer_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/php-cs-fixer/phpcsfixer_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/configurable_phpstan_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/phpstan/phpstan_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/composer_json_aware_rector_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/configurable_rector_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/extra_file_rector_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_categorized.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_content.md
Fixes https://github.com/rectorphp/rector/issues/5476
Is this the right approach? If so, I can fix the PHPStan errors.
=> [RuleDocGenerator] Link rule class to source

packages/monorepo-builder/packages/testing/src/ComposerJson/ComposerVersionManipulator.php, packages/phpstan-rules/src/Rules/CheckTypehintCallerTypeRule.php, packages/rule-doc-generator/src/DirectoryToMarkdownPrinter.php, packages/rule-doc-generator/src/ValueObject/AbstractCodeSample.php, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_categorized.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Expected/rector/rector_content.md, packages/rule-doc-generator/tests/DirectoryToMarkdownPrinter/Fixture/Rector/Standard/SomeWhiteSpaceCodeSampleRector.php
To ensure same code with different whitespace not marked as different.
=> [RuleDocGenerator] Ensure trim $badCode and $goodCode in AbstractCodeSample

packages/phpstan-rules/src/Rules/RequireStringArgumentInConstructorRule.php, packages/phpstan-rules/src/Rules/RequireStringArgumentInMethodCallRule.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/Fixture/SkipWithConstant.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/Fixture/SkipWithString.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/Fixture/SkipWithVariable.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/Fixture/WithClassConstant.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/RequireStringArgumentInConstructorRuleTest.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/Source/AlwaysCallMeWithString.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/Source/AnotherClassWithConstant.php, packages/phpstan-rules/tests/Rules/RequireStringArgumentInConstructorRule/config/configured_rule.neon, packages/phpstan-rules/tests/Rules/RequireStringArgumentInMethodCallRule/config/configured_rule.neon
This can be used in Rector to prevent issues with prefixing.
See https://github.com/rectorphp/rector/issues/5596 and https://github.com/rectorphp/rector/pull/5597
=> [PHPStanRules] Add RequireStringArgumentInConstructorRule

.github/workflows/code_analysis.yaml, packages/coding-standard/src/Fixer/LineLength/DocBlockLineLengthFixer.php, packages/coding-standard/src/ValueObject/DocBlockLines.php, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/DocBlockLineLengthFixerTest.php, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/do_not_reformat_annotations.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/do_not_reformat_inheritdoc.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/indented_doc_block.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/inline_doc_block.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/make_multi_line_if_needed.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/skip_doc_block_with_only_annotations.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/skip_single_line_doc_block_with_only_annotations.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/word_wrapping.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/word_wrapping_with_multiple_lines.php.inc, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/Fixture/word_wrapping_with_multiple_paragraphs.php.inc
This continues @TomasVotruba 's work in #2879 
Things I'd still like to add:
But I'd love some feedback as well. Also, do you test this on real projects? It will be interesting to find out how it works in the real world.
~I have at least one concern: this new fixer looks like it's just adding more behavior to the existing `LineLengthFixer`. Shouldn't the two be merged? Not sure myself.~ As Tomas writes: "Line lenght is sensitive topic, so it's better to have it opt-in as a standalone rule."
=> [CodingStandard] Add DocBlockLineLengthFixer

packages/vendor-patches/src/Finder/OldToNewFilesFinder.php
There are other files in the vendor folder, they are not only .php files there, and sometimes these files need patching too. For example *.js or *.css files. Since the behavior of only finding *.php.old files is not mentioned in the documentation, nor implied in the package's name ("vendor-patches"), nor particularly useful for anything else than a speed optimization (and probably not even that), I removed this artificial limitation.
=>  Find ALL files named *.old, not just *.php.old

packages/rule-doc-generator/tests/Text/KeywordHighlighterTest.php, packages/simple-php-doc-parser/README.md, packages/simple-php-doc-parser/config/config.php, packages/simple-php-doc-parser/src/Contract/PhpDocNodeVisitorInterface.php, packages/simple-php-doc-parser/src/PhpDocNodeTraverser.php, packages/simple-php-doc-parser/src/PhpDocNodeVisitor/AbstractPhpDocNodeVisitor.php, packages/simple-php-doc-parser/src/PhpDocNodeVisitor/CallablePhpDocNodeVisitor.php, packages/simple-php-doc-parser/src/PhpDocNodeVisitor/ParentConnectingPhpDocNodeVisitor.php, packages/simple-php-doc-parser/src/ValueObject/PhpDocAttributeKey.php, packages/simple-php-doc-parser/tests/PhpDocNodeVisitor/ParentConnectingPhpDocNodeVisitorTest.php, phpstan.neon
What if we could get anywhere in php doc block and do any change like with php-parser? 
```diff
/**
- * @param OldNode|string $value
+ * @param NewNode|string $value
- * @return OldNode 
+ * @return NewNode
*/
```
=> [SimplePhpDocParser] Add PhpDocNodeTraverser

packages/git-wrapper/src/GitCommit.php, packages/git-wrapper/src/GitCommits.php, packages/git-wrapper/src/GitWorkingCopy.php, packages/git-wrapper/src/ValueObject/CommandName.php, packages/git-wrapper/tests/GitWorkingCopyTest.php
I am currently working on a library and cli that validates commit messages. I am using the git wrapper to get the commits and commit messages. This is the first step to support access to commits.
In another project I already have the command to get only a range of commits. This could be useful in PR checks to get all commits between `GITHUB_BASE_REF` and s`GITHUB_HEAD_REF`, it is not feature-ready at the moment. So I'll start with this base on which I can add more features.
=> feat(git): Add GitCommits

packages/sniffer-fixer-to-ecs-converter/src/RobotLoader/FixerClassProvider.php, phpstan.neon
Improves PHP-CS-Fixer path detection by avoiding the `vendor` directory name, as it is configurable in `composer.json`.
=> [SnifferFixerToECSConverter] improve PHP-CS-Fixer path detection. Fixes #3089

.github/workflows/test_ecs_prefixed.yaml
On merge:
- clone latest `symplify/easy-coding-standard-prefixed` dev-main branch
- run test immediately
=> Fixing running test ecs prefixed on merge

packages/phpstan-extensions/src/Testing/AbstractServiceAwareRuleTestCase.php
The problem is that T_MATCH is emulated in both PHP_CodeSniffer and php-parser. One with string type, the latter with integer type. See https://github.com/symplify/symplify/pull/3107#issuecomment-822251092
As we can't control which token emulation gets loaded first (composer does), we have to work around it for PHP 7.4 and bellow.
This can happen only in monorepo tests, as we need all classes to be loaded, both PHP_CodeSniffer magic autoload and other packages. That's why it's not reported as a bug in PHP_CodeSniffer.
=> fix emulation T_MATCH conflict type in string/int

packages/easy-coding-standard-tester/composer.json
```
Error : Class 'Symplify\PhpConfigPrinter\HttpKernel\PhpConfigPrinterKernel' not found
/app/vendor/symplify/package-builder/src/Testing/AbstractKernelTestCase.php:104
```
=> [EasyCodingStandardTester] Add missing dependency

packages/easy-coding-standard/composer.json
Fixes #3133
This issue only happens when jean85/pretty-package-versions is locked to version greater than 2.0 before require or update symplify/easy-coding-standard.
=> [ECS] Fix upgrade error when jean85/pretty-package-versions is locked to version greater than 2.0

packages/autowire-array-parameter/src/Skipper/ParameterSkipper.php, packages/symfony-php-config/src/ValueObjectInliner.php
This patch to make it downgrade-able to php 7.0 compatible code at https://github.com/rectorphp/rector-src/pull/50
=> [Autowire] remove @noRector on ParameterSkipper const

packages/easy-coding-standard/composer.json, packages/easy-coding-standard/scoper.php, packages/easy-coding-standard/src/Application/VersionResolver.php, packages/easy-coding-standard/src/Console/EasyCodingStandardConsoleApplication.php, packages/easy-coding-standard/src/Exception/VersionException.php, phpstan.neon
This will prevent bugs with dependency on composer installed hardcoded class with packagist-based versions. Inspired by solution directory from composer versioning itself :+1: 
Inspired in https://github.com/rectorphp/rector-src/commit/e2bd8de3480bc10b518a1713987cbbbf24b54a6b
=> [ECS] Add release-based version constants

packages/amnesia/src/ValueObject/Symfony/ServiceTag.php, packages/astral/src/NodeFinder/SimpleNodeFinder.php, packages/phpstan-rules/config/naming-rules.neon, packages/phpstan-rules/src/Rules/NoVoidGetterMethodRule.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipGetterWithReturn.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipIfElseReturn.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipInterfaceContractGetter.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipNoThrows.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipSetter.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipYielder.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SomeGetterVoid.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SomeGetterWithNoReturn.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/NoVoidGetterMethodRuleTest.php
Closes https://github.com/symplify/symplify/issues/3237
Getter-named methods must return some value:
```php
final class SomeClass
{
public function getData(): void
{
}
}
```
=> [PHPStanRules] Add NoVoidGetterMethodRule

packages/easy-coding-standard/scoper.php
Ref https://github.com/rectorphp/rector-src/runs/2749775822?check_suite_focus=true#step:7:1  . Last In Rector, it got error:
```bash
vendor/bin/ecs check --match-git-diff --fix --ansi
[ERROR] Could not resolve argument "Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator    
$containerConfigurator" for "/Users/samsonasik/www/rector-src/ecs.php".   
```
Ref https://github.com/rectorphp/rector-src/pull/141 for possible fix.
=> [ECS] Fix Could not resolve argument "Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator"

packages/easy-coding-standard/scoper.php, packages/phpstan-rules/src/Rules/ForbiddenArrayWithStringKeysRule.php
Handle error:
```bash
[ERROR] Class                                                                  
'Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator' not found 
```
The `Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator` need to be registered to whitelist.
Ref: 
https://github.com/rectorphp/rector-src/blob/8151fd8cb11ae8a545043ef5e32cdff53bf8551e/utils/compiler/src/PhpScoper/StaticEasyPrefixer.php#L13-L14
=> [ECS] Whitelist ContainerConfigurator on scoper config

rector.php
Remove skip: 
```php
// fix in dev-main
\Rector\Privatization\Rector\Property\PrivatizeLocalPropertyToPrivatePropertyRector::class => [
__DIR__ . '/packages/package-builder/src/Console/Command/AbstractSymplifyCommand.php',
],
```
as there is already new rector release.
=> [Config] Clean up rector.php config

packages/coding-standard/src/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer.php, packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/InlineVarMalformWorker.php, packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/InlineVariableDocBlockMalformWorker.php, packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/MissingVarNameMalformWorker.php, packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/SuperfluousReturnNameMalformWorker.php, packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/SuperfluousVarNameMalformWorker.php, packages/coding-standard/src/TokenRunner/DocBlock/MalformWorker/SwitchedTypeAndNameMalformWorker.php, packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/inlined_var_above.php.inc, packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/wrong5.php.inc, packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/wrong7.php.inc, packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/wrong8.php.inc
closes https://github.com/symplify/symplify/issues/3295
=> ParamReturnAndVarTagMalformsFixer: added support for psalm/phpstan prefixed phpdocs

packages/phpstan-rules/src/Rules/PreventDuplicateClassMethodRule.php
when using this rule as suggested in the docs, you run into strange errors. propagate a better default in the docs, so people like me don't fall into this trap
before this PR:
closes https://github.com/symplify/symplify/issues/3259
=> PreventDuplicateClassMethodRule: fix minimum line count example in docs

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/FixtureSymfony51/services_bind.yaml, packages/php-config-printer/src/ServiceOptionConverter/BindAutowireAutoconfigureServiceOptionKeyYamlToPhpFactory.php
Before, it would only add an empty `bind()` call.
=> [PhpConfigTransformer] Support service `bind` (same as `arguments`)

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_alias.yaml, packages/php-config-printer/src/CaseConverter/AliasCaseConverter.php
Before, it would convert:
```yaml
services:
doctrine.dbal.read_connection: '@doctrine.dbal.read1_connection'
```
to this:
```php
$services->alias('doctrine.dbal.read1_connection');
```
instead of
```php
$services->alias('doctrine.dbal.read_connection', 'doctrine.dbal.read1_connection');
```
=> [PhpConfigPrinter] Keep original key when converting alias

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/resource_arguments_and_bind.yaml, packages/php-config-printer/src/NodeFactory/Service/ServicesPhpNodeFactory.php
This makes sure that YAML config like:
```yaml
services:
App\:
resource: '../src/*'
arguments:
$environment: '%kernel.environment%'
bind:
$debug: '%kernel.debug%'
```
will be properly converted to PHP config like:
```php
$services->load('App\\', __DIR__ . '/../src/*')
->arg('$environment', '%kernel.environment%')
->bind('$debug', '%kernel.debug%');
```
Before this change, it would convert it to this:
```php
$services->load('App\\', __DIR__ . '/../src/*');
```
Resulting in lots of breaks.
=> [PhpConfigPrinter] Support `bind` + `arguments` on resource node

packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Fixture/some.xml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/reference.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_arguments.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_calls.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_configurator.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_factory.yaml, packages/php-config-printer/config/config.php, packages/php-config-printer/src/NodeTraverser/ImportFullyQualifiedNamesNodeTraverser.php, packages/php-config-printer/src/NodeVisitor/ImportFullyQualifiedNamesNodeVisitor.php, packages/php-config-printer/src/Sorter/FullyQualifiedImportSorter.php, packages/php-config-printer/src/ValueObject/AttributeKey.php, packages/php-config-printer/src/ValueObject/FullyQualifiedImport.php, packages/php-config-printer/src/ValueObject/ImportType.php
I noticed that the `service` function would not be imported in my setup.
It would be imported as:
```php
use Symfony\Component\DependencyInjection\Loader\Configurator\service;
```
instead of
```php
use function Symfony\Component\DependencyInjection\Loader\Configurator\service;
```
I checked the code, and it turns out that it's a bit naive. It has a special rule
for when the function is called `ref` (the old `service` function). In other cases
it imports it as function when the function exists.
Instead of doing this, why not use the nodes to know the context of the import?
The `ImportFullyQualifiedNamesNodeVisitor` keeps track of the context in where it finds a
`FullyQualified` node. When the `FullyQualified` node is used inside a `FuncCall` expression
it will import the FQCN as function. …
=> [PhpConfigPrinter] Properly import function calls

packages/coding-standard/src/TokenAnalyzer/DocblockRelatedParamNamesResolver.php
Reverts some of the code that was removed in https://github.com/symplify/symplify/commit/5fd568ca395189440ff6f8e9405f7142c1f88789.
Fixes #3355 
Even though this would fix the issue I'd still be careful since I don't know exactly where else in the project these kinds of errors can appear. I would suggest updating the test matrix to use both PHP 8.0 _and_ PHP 7.1 to prevent any regressions. But that would be out of this PR's scope :)
=> [Coding Standard] Reimplement checking for arrow function support

packages/php-config-printer/src/NodeFactory/ConstantNodeFactory.php, packages/php-config-printer/tests/NodeFactory/ConstantNodeFactoryTest.php
When running PHP 8 with `pdo_pgsql` installed a lot of deprecations are reported:
```
Deprecated: Constant PGSQL_LIBPQ_VERSION_STR is deprecated in /Volumes/CS/www/website/vendor/symplify/php-config-printer/src/NodeFactory/ConstantNodeFactory.php on line 52
PHP Deprecated:  Constant PGSQL_LIBPQ_VERSION_STR is deprecated in /Volumes/CS/www/website/vendor/symplify/php-config-printer/src/NodeFactory/ConstantNodeFactory.php on line 52
```
=> [PhpConfigPrinter] Suppress errors when resolving deprecated constants

packages/config-transformer/bin/config-transformer.php
When using the config transformer on a real project, you often install it like:
```
composer req --dev symplify/config-transformer:dev-main
```
And then run it with: 
```
vendor/bin/config-transformer
```
When you are converting a YAML file that loads resources (e.g. Symfony Auto Wire) you get errors like:
```
Expected to find class "App\AdminBundle\Controller\AdminController" in file "/Volumes/CS/www/src/AdminBundle/Controller/AdminController.php" while importing services from resource "../../{Controller,Repository}", but it was not found! Check the namespace prefix used with the resource.
```
This is caused by the fact that config transformer finds the `vendor/autoload.php` from it's own bundled vendor directory instead of the 
`vendor/autoload.php` from my project. Therefore, when …
=> [ConfigTransformer] Alvast try autoload from current working directory first

packages/phpstan-rules/config/services/services.neon, packages/phpstan-rules/src/Forbidden/ForbiddenCallable.php, packages/phpstan-rules/src/Rules/ForbiddenFuncCallRule.php, packages/phpstan-rules/tests/Rules/ForbiddenFuncCallRule/ForbiddenFuncCallRuleWithArrayDeprecationsTest.php, packages/phpstan-rules/tests/Rules/ForbiddenFuncCallRule/ForbiddenFuncCallRuleWithDeprecationsTest.php, packages/phpstan-rules/tests/Rules/ForbiddenFuncCallRule/config/configured_rule_with_array_deprecations.neon, packages/phpstan-rules/tests/Rules/ForbiddenFuncCallRule/config/configured_rule_with_deprecations.neon
Adds support for adding custom additional error messages, useful to give more context what to use instead of a forbidden function.
example use:
```
services:
-
class: Symplify\PHPStanRules\Rules\ForbiddenFuncCallRule
tags: [phpstan.rules.rule]
arguments:
forbiddenFunctions:
- 'extract': 'you shouldn"t use this dynamic things'
- 'dump': 'seems you missed some debugging function'
- 'curl_*': 'we use a proper http client these days'
- 'property_exists': ''
```
which produces errors like:
```
Function "curl_init()" cannot be used/left in the code: we use a proper http client these days
```
=> ForbiddenFuncCallRule: add support for additional custom errors

.github/workflows/build_monorepo_builder_prefixed.yaml
Remove the attempt to copy a file that doesn't exist (bootstrap.php).
See: https://github.com/symplify/symplify/pull/3292#issuecomment-870570334
=> [MonorepoBuilder] Fix build prefixed action.

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_alias.yaml, packages/php-config-printer/src/CaseConverter/AliasCaseConverter.php
It should convert
```yaml
services:
querybus:
alias: tactician.commandbus.query
```
to
```php
$services->alias('querybus', 'tactician.commandbus.query');
```
Before, it would convert it to:
```php
$services->alias('querybus', tactician.commandbus.query::class);
```
=> [ConfigTransformer] Support aliasing non-FQCN service names

composer.json, ecs.php, packages/astral/src/NodeTraverser/SimpleCallableNodeTraverser.php, packages/coding-standard/config/config.php, packages/coding-standard/src/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer.php, packages/coding-standard/src/Fixer/Commenting/RemoveCommentedCodeFixer.php, packages/coding-standard/src/Fixer/LineLength/DocBlockLineLengthFixer.php, packages/coding-standard/src/TokenAnalyzer/DoctrineAnnotationElementAnalyzer.php, packages/coding-standard/src/TokenAnalyzer/DoctrineAnnotationNameResolver.php, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/DoctrineAnnotationNestedBracketsFixerTest.php, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/Fixture/skip_already_wrapped.php.inc, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/Fixture/skip_not_configured_annotation.php.inc, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/Fixture/some_nested_annotation_without_brackets.php.inc, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/Source/MissingYou.php, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/Source/SomeAnnotation.php, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/Source/SomeAnnotations.php, packages/coding-standard/tests/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer/config/configured_rule.php, packages/phpstan-rules/src/PhpDoc/ClassReferencePhpDocNodeVisitor.php, packages/simple-php-doc-parser/src/Bundle/SimplePhpDocParserBundle.php, packages/simple-php-doc-parser/src/PhpDocNodeVisitor/CloningPhpDocNodeVisitor.php, packages/simple-php-doc-parser/src/PhpDocNodeVisitor/ParentConnectingPhpDocNodeVisitor.php, phpstan.neon, rector.php
Solves https://github.com/doctrine/annotations/issues/418#issue-940872356
```diff
/**
- * @MainAnnotation(
+ * @MainAnnotation({
*     @NestedAnnotation('one'),
*     @NestedAnnotation('two'),
- * )
+ * })
*/
```
```php
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symplify\CodingStandard\Fixer\Annotation\DoctrineAnnotationNestedBracketsFixer;
return static function (ContainerConfigurator $containerConfigurator): void {
$services = $containerConfigurator->services();
$services->set(LineLengthFixer::class);
$services->set(DoctrineAnnotationNestedBracketsFixer::class)
->call('configure', [[
DoctrineAnnotationNestedBracketsFixer::ANNOTATION_CLASSES => [
'MainAnnotation' 
]
]]);
]);
};
```
=> [CodingStandard] Add DoctrineAnnotationNestedBracketsFixer

packages/easy-coding-standard/src/HttpKernel/EasyCodingStandardKernel.php, packages/easy-coding-standard/tests/HttpKernel/EasyCodingStandardKernelTest.php
see https://github.com/symplify/symplify/pull/3399/files#r667500878
This PR makes sure the container cache directory gets purged each time `Kernel#boot()` is called. This makes sure we're using a fresh application container for each run and do not spam the temp directory.
=> Purge container cache directory on boot

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_arguments.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_decoration.yaml, packages/php-config-printer/src/NodeFactory/ArgsNodeFactory.php, packages/phpstan-rules/src/Composer/Psr4PathValidator.php, packages/phpstan-rules/tests/Composer/Psr4PathValidatorTest.php, packages/phpstan-rules/tests/Rules/ForbiddenForeachEmptyMissingArrayRule/ForbiddenForeachEmptyMissingArrayRuleTest.php, phpstan.neon
Manual adjust + merge of https://github.com/symplify/symplify/pull/3366
<br>	
- [ConfigTransformer] Use named parameters when tag uses keys
- add named args only on PHP 8
=> [ConfigTransformer] Use named parameters when tag uses keys

packages/easy-coding-standard/scoper.php
- Add additional patcher to fix `Class 'ECSPrefix20210712\Symplify\PackageBuilder\Testing\AbstractKernelTestCase' not found in .../vendor/symplify/easy-coding-standard/src/Testing/PHPUnit/AbstractCheckerTestCase.php:17` error.
=> [ECS] Add additional patcher to scoper.php

packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/IndentDetector.php, packages/coding-standard/tests/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer/Fixture/correct7.php.inc
This PR adds a test fixture for the issue https://github.com/symplify/symplify/issues/3417
I also tried to dig down and search for the root of the cause. And this is the line
https://github.com/symplify/symplify/blob/c8ffda4e3a6ef6f94e1e520b2878b90c5cf74e2d/packages/coding-standard/src/TokenRunner/Analyzer/FixerAnalyzer/IndentDetector.php#L30
The `$token->getContent()` for the token between `return` and `[` returns two spaces instead of one space. So the if condition passes and `0` is returned from there. `2` is returned in the regular scenario (only one space after return unlike the fixture code).
Not sure how this should be fixed so opening a PR to drive some discussion.
=> tests: Add a test fixture for extra space issue

packages/phpstan-rules/packages/cognitive-complexity/src/NodeAnalyzer/ComplexityAffectingNodeFinder.php
I think this comment is not placed correctly (might be a leftover of a rectoring or similar)
=> ComplexityAffectingNodeFinder: remove wrong comment

packages/phpstan-rules/src/Rules/NoVoidGetterMethodRule.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/Fixture/SkipAbstractGetter.php, packages/phpstan-rules/tests/Rules/NoVoidGetterMethodRule/NoVoidGetterMethodRuleTest.php
closes https://github.com/symplify/symplify/issues/3427
=> NoVoidGetterMethodRule: fix false-positive error on abstract method

packages/coding-standard/src/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer.php, packages/coding-standard/src/Fixer/ArrayNotation/ArrayListItemNewlineFixer.php, packages/coding-standard/src/Fixer/ArrayNotation/ArrayOpenerAndCloserNewlineFixer.php, packages/coding-standard/src/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer.php, packages/coding-standard/src/Fixer/Spacing/StandaloneLinePromotedPropertyFixer.php, packages/config-transformer/src/DependencyInjection/Loader/IdAwareXmlFileLoader.php, packages/monorepo-builder/packages/Merge/ComposerJsonDecorator/AppenderComposerJsonDecorator.php, packages/monorepo-builder/packages/Merge/Contract/ComposerKeyMergerInterface.php, packages/php-config-printer/src/Contract/Converter/ServiceOptionsKeyYamlToPhpFactoryInterface.php, packages/php-config-printer/src/Printer/PhpParserPhpConfigPrinter.php, packages/phpstan-extensions/src/Php/Type/NativeFunctionDynamicFunctionReturnTypeExtension.php, packages/phpstan-rules/config/services/services.neon, packages/phpstan-rules/config/static-rules.neon, packages/phpstan-rules/src/Naming/MissMatchingParamResolver.php, packages/phpstan-rules/src/ParentGuard/ParentElementResolver/ParentMethodResolver.php, packages/phpstan-rules/src/Rules/Explicit/SameNamedParamFamilyRule.php, packages/phpstan-rules/src/ValueObject/MissMatchingParamName.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Fixture/ClassWithDifferentParent.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Fixture/SkipContainerBuilderMissmatch.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Fixture/SkipParentExtraNullableParam.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Fixture/SkipSomeClassWithoutParents.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Fixture/SkipWithCompatibleParent.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/SameNamedParamFamilyRuleTest.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Source/DifferentParent.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/Source/WithNullParam.php, packages/phpstan-rules/tests/Rules/Explicit/SameNamedParamFamilyRule/config/configured_rule.neon, packages/rule-doc-generator/src/DirectoryToMarkdownPrinter.php, packages/simple-php-doc-parser/src/PhpDocNodeVisitor/CloningPhpDocNodeVisitor.php, rector.php
What happens if you use different param name than the parent method?
```php
interface SomeInterface
{
public function run($value);
}
final class SomeClass implements SomeInterface
{
// here is not "$value" as in parent contract!
public function run($differentValue)
{
}
}
```
↓
```php
new SomeClass(value: "boom");
```
<br>
Don't wait for a chance. 
Be ready for a change :+1:  :safety_vest:
=> [PHPStanRules] Add SameNamedParamFamilyRule

packages/phpstan-rules/src/TypeAnalyzer/CallableTypeAnalyzer.php, packages/phpstan-rules/tests/Rules/NoDynamicNameRule/Fixture/SkipIIFE.php, packages/phpstan-rules/tests/Rules/NoDynamicNameRule/Fixture/SkipImmediatelyInvokedFunctionExpression.php, packages/phpstan-rules/tests/Rules/NoDynamicNameRule/NoDynamicNameRuleTest.php
a immediately invoked function expression (IIFE) should not be considered a 'dynamic name'.
=> NoDynamicNameRule: added failing IIFE test-case

packages/easy-testing/src/StaticFixtureSplitter.php
doing less file-IO in `StaticFixtureSplitter->createTemporaryFileInfo()`.
`SmartFileSystem->dump` gives us some gurantees like atomic file writes which protect writing files from race conditions when writing to the same file-path in parallel. this is not necessary for the StaticFixtureSplitter, and therefore using simpler primitives is faster.
with this change I can see a improvement of 2-3 seconds
refs https://github.com/symplify/symplify/issues/3437
=> StaticFixtureSplitter: don't use `SmartFileSystem->dump()` for performance reasons

packages/phpunit-upgrader/config/config.php, packages/phpunit-upgrader/src/Console/PHPUnitUpgraderConsoleApplication.php
Adds support for PHPUnitUpgrader console service
Fixes #3436 "You have requested a non-existent service "Symfony\Component\Console\Application""
=> [PHPUnitUpgrader] Add support for PHPUnitUpgrader console app

packages/composer-json-manipulator/src/ComposerJsonFactory.php, packages/composer-json-manipulator/src/ValueObject/ComposerJson.php, packages/composer-json-manipulator/src/ValueObject/ComposerJsonSection.php, packages/monorepo-builder/config/parameters.php
There is a bug: When running `monorepo-builder release`, my `composer.json` files were having their `suggest` entry removed.
This PR adds support for this entry.
Please notice: there was param `SUGGESTS`, but in `composer.json` it is defined as `"suggest"`: https://getcomposer.org/doc/04-schema.md#suggest
So I renamed it. (This param was in fact not used anywhere.)
=> Fixed bug: Do not remove "suggest" entry from `composer json`

packages/composer-json-manipulator/src/FileSystem/JsonFileManager.php, packages/monorepo-builder/tests/FileSystem/JsonFileManager/JsonFileManagerTest.php, packages/monorepo-builder/tests/FileSystem/JsonFileManager/Source/dynamic.json
When doing this:
```php
$json = $this->jsonFileManager->loadFromFileInfo($packageComposerFileInfo);
```
The contents of the file are cached. If then they are modified, for instance here:
```php
$json = $this->processSectionWithPackages($json, $packageNames, $version, ComposerJsonSection::REQUIRE_DEV);
$this->jsonFileManager->printJsonToFileInfo($json, $packageComposerFileInfo);
```
Then the cache for that file must be purged. Otherwise, this code fails:
```php
// Read 1st time
$json = $this->jsonFileManager->loadFromFileInfo($packageComposerFileInfo);
// Do something ...
$json = $this->processSectionWithPackages($json, $packageNames, $version, ComposerJsonSection::REQUIRE_DEV);
// Save...
$this->jsonFileManager->printJsonToFileInfo($json, $packageComposerFileInfo);
// Read 2nd time
$json …
```
=> Unset cache in `JsonFileManager` after file contents are modified

packages/monorepo-builder/packages/Release/Process/ProcessRunner.php, packages/monorepo-builder/src/Git/MostRecentTagResolver.php, phpstan.neon
Option `--git-dir` does not exist when doing `git tag -l`.
Executing this command:
```bash
git tag -l --sort=committerdate --git-dir <some dir>
```
thows an error:
```
The command "'git' 'tag' '-l' '--sort=committerdate' '--git-dir' '/Users/leo/GitRepos/GitHub/Project  
s/leoloso/PRO/submodules/PoP'" failed.                                                                
Exit Code: 129(Hangup)                                                                                
Working directory: /Users/leo/GitRepos/GitHub/Projects/leoloso/PRO                                    
Output:                                                                                               
================                                                                                      
Error Output: …
```
=> Fix bug: `--git-dir` param does not exist

packages/easy-coding-standard/packages/SniffRunner/ValueObject/File.php
as mentioned in issue #3242, AssignmentInConditionSniff was removed from list of sniffs that only throw warnings in PR #3173
this PR adds it back in
=> AssignmentInConditionSniff should throw errors on warnings

packages/phpstan-rules/packages/symfony/src/Twig/TwigNodeVisitor/MissingMethodCallNodeVisitor.php, packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Fixture/SkipExistingProperty.php, packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/NoTwigMissingMethodCallRuleTest.php, packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Source/SomeType.php, packages/phpstan-rules/packages/symfony/tests/Rules/NoTwigMissingMethodCallRule/Source/skip_existing_property.twig
Closes https://github.com/symplify/symplify/issues/3534
=> [PHPStanRules] Skip existing property in false positive reporting of missing twig method

packages/monorepo-builder/scoper.php
I had the same issue as #3474 and this is my attempt to fix it.
I tried to understand the suggestions by @TomasVotruba, but I don't know anything about [PHP Scoper](https://github.com/humbug/php-scoper) and the structure of this repo is a bit advanced for my skills so I hope I did the right thing.
If I understand correctly, PHP Scoper wraps the whole dependencies of a project under a custom namespace and allows you to build a self-contained packaged with no conflict with the project in which you install it. This cannot be done at runtime, so I can't test any change to the `scoper.php` file without building the "scoped" package locally. _(Is this correct??)_
I cloned the repo and run the commands found in [`build_monorepo_builder_prefixed.yaml`](https://github.com/symplify/symplify/blob/mai …
=> Using non-prefixed class for ComposerJsonSection (fixes #3474)

packages/easy-hydrator/src/ParameterTypeRecognizer.php, packages/easy-hydrator/src/TypeCaster/ArrayTypeCaster.php, packages/easy-hydrator/tests/ArrayToValueObjectHydratorTest.php, packages/easy-hydrator/tests/Fixture/Arrays.php
I found limitation of `ArrayToValieObjectHydrator` in hydrating array of arrays. Error is caused by improper type definition in `ParameterTypeRecognizer` on line 90.
=> Added array of arrays test.

packages/phpstan-rules/packages/nette/src/Rules/LatteCompleteCheckRule.php
I don't get it why to ignore these errors. Imho that's why we are doing this latte check by phpstan or not? Undefined variable is one of most errors in latte, we should not ignore it. Not sure what that second one is, but it is probably something similar :)
=> [PHPStanRules] Do not suppress errors in latte (might not be defined and has an unused variable)

packages/twig-phpstan-compiler/src/PhpParser/NodeVisitor/ReplaceEchoWithVarDocTypeNodeVisitor.php, packages/twig-phpstan-compiler/src/TwigToPhpCompiler.php, packages/twig-phpstan-compiler/src/ValueObject/VarTypeDoc.php, packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Fixture/var_doc_variable.twig, packages/twig-phpstan-compiler/tests/TwigToPhpCompiler/Source/SomeDocType.php
Unfortunately, the Twig parser removes all the comments from original Twig template.
Along with them also useful comments like:
```html
{# @var name string #}
```
That are seen by Symfony plugin as:
```php
/** @var string $name */
```
This PR tried to get them back :)
=> [TwigPHPStanCompiler] Add twig comment

composer.json, packages/astral/composer.json, packages/latte-phpstan-compiler/composer.json, packages/phpstan-extensions/composer.json, packages/phpstan-latte-rules/composer.json, packages/phpstan-rules/composer.json, packages/phpstan-twig-rules/composer.json, packages/rule-doc-generator/composer.json, packages/symfony-php-config/composer.json, packages/symfony-static-dumper/composer.json, packages/template-phpstan-compiler/composer.json, packages/twig-phpstan-compiler/composer.json
Same like in rector-src:
https://github.com/rectorphp/rector-src/blob/e525dad6ab1a005e79b751f4cfb1eaf94ae3c90f/composer.json#L23
The `^1.0` already load `dev-master` if using : 
```javascript
"minimum-stability": "dev",
"prefer-stable": true
```
so when PHPStan next released, it is should no longer need change, as prefer-stable to true.
=> [PHPStan] Using phpstan ^1.0

.github/workflows/daily_pull_request.yaml, .github/workflows/lock_threads.yaml, .github/workflows/weekly_pull_requests.yaml
Currently cronjob workflows not working because it have condition to check to run:
```yaml
if: github.event.pull_request.head.repo.full_name == github.repository
```
but we not have `github.event.pull_request` context. In this PR I have improve the condition.
References:
https://github.com/prisma/prisma/issues/3539
=> fix: cronjob workflows not working.

packages/monorepo-builder/bin/monorepo-builder.php
Hi there,
Look like issue  #3570 still exists because on distribution environment own autoload of `monorepo-builder` package exists and will be use by [L5#scoper-autoload.php](https://github.com/symplify/monorepo-builder/blob/main/vendor/scoper-autoload.php#L5). 
Currently own autoload of `monorepo-builder` get highest priority so dependency autoload never touch and we can not add custom container services, I think dependency autoload should get highest priority.
=> fix: monorepo builder autoload priority.

packages/phpstan-rules/src/NodeAnalyzer/EnumAnalyzer.php, packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/Fixture/SkipPromotedProperty.php, packages/phpstan-rules/tests/Rules/StrictTypes/RespectPropertyTypeInGetterReturnTypeRule/RespectPropertyTypeInGetterReturnTypeRuleTest.php
- skip getter property name
- [PHPStanRules] Extend Enum analyzer to check classes in Enum namespace
=> [PHPStanRules] Extend Enum analyzer to check classes in Enum namespace

packages/config-transformer/build/config/config-downgrade.php, packages/easy-coding-standard/build/config/config-downgrade.php, packages/monorepo-builder/build/config/config-downgrade.php
There is no other constants to compare, so UNSAFE_TYPES_TO_METHODS usage is not needed. Ref https://github.com/rectorphp/rector-src/pull/1451 . Use direct config values instead.
=> [ConfigTransformer]ECS][MonorepoBuilder] Remove unneded usage of UNSAFE_TYPES_TO_METHODS constant in DowngradeParameterTypeWideningRector

packages/latte-phpstan-compiler/src/TemplateFileVarTypeDocBlocksDecorator.php, packages/latte-phpstan-compiler/tests/LatteToPhpCompiler/FixturePresenterVariable/expected_compiled.php, packages/latte-phpstan-compiler/tests/LatteToPhpCompiler/FixturePresenterVariable/input_file.latte, packages/latte-phpstan-compiler/tests/LatteToPhpCompiler/LatteToPhpCompilerTest.php, packages/latte-phpstan-compiler/tests/LatteToPhpCompiler/Source/FooPresenter.php, packages/template-phpstan-compiler/src/NodeFactory/VarDocNodeFactory.php
When we are in scope of Presenter, variables $presenter and $control in template are instances of this presenter, so we can use actual Presenter's type instead of abstract Nette\Application\UI\Presenter / Nette\Application\UI\Control
Also in scope of Control, $presenter is actual presenter (we can't get it in static analysis) and $control is actual rendered Control
=> [Latte PHPStan Compiler] Concrete types for variables $presenter and $control

composer.json, ecs.php, packages/coding-standard/composer.json, packages/easy-coding-standard/composer.json, packages/easy-coding-standard/config/set/common/phpunit.php, packages/rule-doc-generator/composer.json
- [ECS] remove PhpUnitStrictFixer from phpunit set as breaking, use Rector and PHPUnit code quality set instead
- cleanup ecs.php
- bump php-cs-fixer fot 3.4 with Symfony 6 support
=> [ECS] Remove  strict phpunit fixer breaking rule, let Rector handle it

packages/package-builder/src/Reflection/PrivatesAccessor.php, packages/package-builder/tests/Reflection/PrivatesAccessorTest.php, packages/package-builder/tests/Reflection/Source/SomeClassWithPrivateProperty.php
Inspired by the type-mismatches within https://github.com/rectorphp/rector-src/pull/1589/files I figured it would be good to have a method variant which is typesafe and integrates well with phpstan.
that way we can get rid of the ugly inline `@var`-phpdocs and additionally get type safety
=> [PackageBuilder] Added type-safe `PrivatesAccessor`-methods

packages/easy-coding-standard/packages/SniffRunner/ValueObject/File.php
Makes it easier to find responsible sniffs.
Before:
```
src/Support/XML.php:22
------------------------------------------------------------------------------------------------------
Function libxml_disable_entity_loader() has been deprecated
Reported by: "Deprecated"
------------------------------------------------------------------------------------------------------
```
After:
```
src/Support/XML.php:22
------------------------------------------------------------------------------------------------------
Function libxml_disable_entity_loader() has been deprecated
Reported by: "PHP_CodeSniffer\Standards\Generic\Sniffs\PHP\DeprecatedFunctionsSniff.Deprecated"
------------------------------------------------------------------------------------------------------
```
=> [ECS] Use fully qualified code instead of code as checker

packages/easy-coding-standard/packages/SniffRunner/ValueObject/File.php, packages/package-builder/src/Exception/InvalidPrivatePropertyTypeException.php, packages/package-builder/src/Exception/MissingPrivatePropertyException.php, packages/package-builder/src/Reflection/PrivatesAccessor.php
@staabm At the moment the error message is missing, which makes it hard to debug and guess what is wrong:
I've added currect + expected type, to help user nagive through error to success :+1:
=> [PackageBuilder] Improve privates accessor invalid type error message

packages/easy-ci/scoper.php
@TomasVotruba this is to avoid error ref https://github.com/rectorphp/rector-src/runs/4829684998?check_suite_focus=true#step:5:7
```bash
Run vendor/bin/easy-ci validate-file-length packages rules src tests
Error: ] Class "Symplify\EasyCI\ValueObject\Option" not found       
```
as it is not part of included `vendor` that need to be prefixed.
From inspiration https://github.com/rectorphp/rector-src/blob/6b965fe744f438b0614597bec485ad8ec23831d9/utils/compiler/src/PhpScoper/StaticEasyPrefixer.php#L30-L31
which the current workaround is pin to `"symplify/easy-ci": "10.0.9"`  
https://github.com/rectorphp/rector-src/blob/6b965fe744f438b0614597bec485ad8ec23831d9/composer.json#L77
=> [EasyCI] Do not prefix Symplify\EasyCI\* namespace on scoper

packages/easy-ci/scoper.php
@TomasVotruba this PR try to solve the following error on scoped version:
```bash
Run php bin/easy-ci list --ansi
[ERROR] Expected to find class                                                 
"EasyCI20220116\Symplify\EasyCI\ActiveClass\ClassNameResolver" in file 
"/home/runner/work/easy-ci/easy-ci/packages/ActiveClass/ClassNameResolv
er.php" while importing services from resource                         
"/home/runner/work/easy-ci/easy-ci/config/../packages", but it was not 
found! Check the namespace prefix used with the resource in            
/home/runner/work/easy-ci/easy-ci/config/config-packages.php (which is 
being imported from                                                    
"/home/runner/work/easy-ci/easy-ci/src/Kernel/../../config/config.php")
. …
```
=> [EasyCI] Fixing scoper EasyCI for not add prefixed in load() call

packages/easy-coding-standard/packages/SniffRunner/ValueObject/File.php
=> Making the commented out code sniff return warnings as errors

composer.json, packages/coding-standard/src/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer.php, packages/coding-standard/src/TokenAnalyzer/DoctrineAnnotationNameResolver.php, packages/easy-coding-standard/composer.json
This PR contains the following changes
- Allow composer/xdebug-handler 3.x
- Support for friendsofphp/php-cs-fixer 3.5
=> [ECS] Allow composer/xdebug-handler 3.x

packages/astral/tests/HttpKernel/AstralKernel.php, packages/autowire-array-parameter/tests/HttpKernel/AutowireArrayParameterHttpKernel.php, packages/coding-standard/src/Fixer/Annotation/DoctrineAnnotationNestedBracketsFixer.php, packages/coding-standard/tests/HttpKernel/SymplifyCodingStandardKernel.php, packages/composer-json-manipulator/tests/Kernel/ComposerJsonManipulatorKernel.php, packages/config-transformer/src/Kernel/ConfigTransformerKernel.php, packages/easy-ci/src/Kernel/EasyCIKernel.php, packages/easy-coding-standard/src/Kernel/EasyCodingStandardKernel.php, packages/easy-testing/src/Kernel/EasyTestingKernel.php, packages/markdown-diff/tests/HttpKernel/MarkdownDiffKernel.php, packages/monorepo-builder/src/Kernel/MonorepoBuilderKernel.php, packages/neon-config-dumper/src/Kernel/NeonConfigDumperKernel.php, packages/package-builder/tests/HttpKernel/PackageBuilderTestKernel.php, packages/php-config-printer/tests/HttpKernel/PhpConfigPrinterKernel.php, packages/rule-doc-generator/src/Kernel/RuleDocGeneratorKernel.php, packages/simple-php-doc-parser/tests/HttpKernel/SimplePhpDocParserKernel.php, packages/skipper/tests/HttpKernel/SkipperKernel.php, packages/symfony-php-config/tests/HttpKernel/SymfonyPhpConfigKernel.php, packages/symplify-kernel/src/ContainerBuilderFactory.php, packages/symplify-kernel/src/HttpKernel/AbstractSymplifyKernel.php, packages/vendor-patches/src/Kernel/VendorPatchesKernel.php
Ref https://tomasvotruba.com/blog/introducing-light-kernel-for-symfony-console-apps/
=> [SymplifyKernel] Change ContainerBuilderFactory::create() to put configs first

packages/astral/tests/HttpKernel/AstralKernel.php, packages/autowire-array-parameter/tests/HttpKernel/AutowireArrayParameterHttpKernel.php, packages/coding-standard/tests/HttpKernel/SymplifyCodingStandardKernel.php, packages/composer-json-manipulator/tests/Kernel/ComposerJsonManipulatorKernel.php, packages/config-transformer/src/Kernel/ConfigTransformerKernel.php, packages/easy-ci/src/Kernel/EasyCIKernel.php, packages/easy-testing/src/Kernel/EasyTestingKernel.php, packages/markdown-diff/tests/HttpKernel/MarkdownDiffKernel.php, packages/neon-config-dumper/src/Kernel/NeonConfigDumperKernel.php, packages/package-builder/tests/HttpKernel/PackageBuilderTestKernel.php, packages/php-config-printer/tests/HttpKernel/PhpConfigPrinterKernel.php, packages/rule-doc-generator/src/Kernel/RuleDocGeneratorKernel.php, packages/simple-php-doc-parser/tests/HttpKernel/SimplePhpDocParserKernel.php, packages/skipper/tests/HttpKernel/SkipperKernel.php, packages/symfony-php-config/tests/HttpKernel/SymfonyPhpConfigKernel.php, packages/symplify-kernel/src/HttpKernel/AbstractSymplifyKernel.php, packages/vendor-patches/src/Kernel/VendorPatchesKernel.php, phpstan.neon
Ref Ref https://tomasvotruba.com/blog/introducing-light-kernel-for-symfony-console-apps/
=> [SymplifyKernel] Allow empty compiler passes and extensions

packages/coding-standard/src/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer.php, packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/Fixture/skip_callable_has_same_param_previous_definition.php.inc, rector.php
Given the following code:
```php
/**
* @param Node|Node[] $nodes
* @param callable(Node $node): bool $filter
*/
public function findFirst(Node | array $nodes, callable $filter): ?Node
{
}
```
it produce:
```diff
-     * @param Node|Node[] $nodes\n
-     * @param callable(Node $node): bool $filter\n
+     * @param Node|Node[] $filters\n
+     * @param callable(Node $filter): bool $filter\n
```
which should be skipped, @staabm this is for https://github.com/rectorphp/rector-src/pull/1649#discussion_r780695332
=> [CodingStandard] Skip Callable has same param previous definition on ParamReturnAndVarTagMalformsFixer

packages/easy-coding-standard/src/Console/Output/ConsoleOutputFormatter.php, packages/easy-coding-standard/src/Console/Output/ExitCodeResolver.php, packages/easy-coding-standard/src/Console/Output/JsonOutputFormatter.php
Right now `JsonOutputFormatter` fails only if there was a "hard error", but this is different from `ConsoleOutputFormatter` which also checks for file diff count.
```bash
$ vendor/bin/ecs check --output-format=json
Total tests to perform 1 out of 10 available
Executing lint - 1 out of 1 selected [Time Elapsed 00:00:00]
Finished in 00:00:57
Running after_script
00:00
Running after script...
$ ./docker/bin/codeclimate.sh --php-cs-fixer ./codequality/php-cs-fixer.json
File                                                                   Line  Description
----                                                                   ----  -----------
src/JobRunnerBundle/Tests/Service/JobHandler/ExecuteTest.php  0     ECS: NativeFunctionInvocationFixer
src/ReviewBundle/Repository/ReviewRepository.php …
```
=> ECS | `JsonOutputFormatter` should account file diff in exit code

packages/easy-coding-standard/config/config.php, packages/easy-coding-standard/packages/Parallel/Application/ParallelFileProcessor.php, packages/easy-coding-standard/src/ValueObject/Option.php
- make it minimal 120 seconds
- make configurable
@enumag  this is to handle https://github.com/symplify/symplify/issues/3914
Ref for inspiration came from rector : 
- https://github.com/rectorphp/rector-src/pull/1657
- https://github.com/rectorphp/rector-src/pull/1673
=> [ECS] [Parallel] Add Option PARALLEL_TIMEOUT_IN_SECONDS and PARALLEL_SYSTEM_ERROR_COUNT_LIMIT constant to allow reconfigure it in ecs config

packages/easy-coding-standard/src/Console/Command/ShowCommand.php
The "show" command was used only for more output on ECS run.  Kinda of "debug" command.
Now we should use the "--debug" option and process command for debugging output instead :+1:
=> [ECS] Deprecate show command to prefer --debug option

packages/easy-coding-standard/config/config.php, packages/easy-coding-standard/packages/Parallel/Application/ParallelFileProcessor.php, packages/easy-coding-standard/src/ValueObject/Option.php, packages/phpstan-rules/packages/symfony/src/Rules/RequireNamedCommandRule.php
To be consistent with Rector https://github.com/rectorphp/rector-src/pull/1818
=> [DX] Inline PARALLEL_SYSTEM_ERROR_COUNT_LIMIT option to keep user scope outside internal system

packages/phpstan-rules/docs/rules_overview.md, packages/phpstan-rules/src/NodeAnalyzer/PHPUnit/TestAnalyzer.php, packages/phpstan-rules/src/Rules/ForbiddenFinalClassMockRule.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/Fixture/CreateMockMethod.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/Fixture/MockOfFinalClass.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/Fixture/SkipCreateMockMethodOutsideTestCase.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/Fixture/SkipNormalClass.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/ForbiddenFinalClassMockRuleTest.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/Source/FinalClass.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/Source/NormalClass.php, packages/phpstan-rules/tests/Rules/ForbiddenFinalClassMockRule/config/configured_rule.neon
This rule comes handy, when it comes to legacy projects with lot of mocking and finalize Rector rule.
=> [PHPStanRules] Add ForbiddenFinalClassMockRule

packages/config-transformer/tests/Converter/ConfigFormatConverter/XmlToPhp/Fixture/tag_with_additional_attributes.xml, packages/php-config-printer/src/Converter/ServiceOptionsKeyYamlToPhpFactory/TagsServiceOptionKeyYamlToPhpFactory.php
When you have a service configuration in xml which looks like this:
```xml
<service id="mime_types">
<tag name="tag1" priority="1" />
</service>
```
This XML will result in the following yml after converting it:
```yml
services:
mime_types:
tags:
- 0: { name: tag1, priority: 1 }
```
And after parsing the yml, this is the resulting PHP array
```php
[
'services' => [
'mime_types' => [
'tags' => [
0 => [
0 => [
'name' => 'tag1',
'priority' => 1,
],
],
],
],
],
];
```
The multi-nesting from the `tags` key was not handled properly and thus resulted in the following (invalid) code:
```php
$services->set('mime_types')
->tag([['name' => 'tag1', 'priority' => 1]]);
```
Flattening the array before processing it, fixes the issue.
=> Flatten yaml line before creating arguments

packages/git-wrapper/src/GitWrapper.php, packages/git-wrapper/tests/GitWorkingCopyTest.php, packages/git-wrapper/tests/GitWrapperTest.php, phpstan.neon
Currently, the following code:
```
$gitWrapper = new GitWrapper(...);
$gitWrapper->streamOutput(false);
$gitWrapper->streamOutput();
```
will result in:
`Typed property Symplify\GitWrapper\GitWrapper::$outputEventSubscriber must not be accessed before initialization`
This is because the property was being `unset()` when calling `GitWrapper::streamOutput(false)`.
=> Fix typed property being accessed before init

packages/git-wrapper/composer.json, packages/git-wrapper/tests/GitWorkingCopyTest.php, phpstan.neon
@riesjart This is to continue https://github.com/symplify/symplify/pull/3997 to use PrivateAccesor to get clean PHPStan notice.
=> [GitWrapper] Use PrivateAccesor to get outputEventSubscriber property in GitWorkingCopyTest

ecs.php
Same with https://github.com/rectorphp/rector-src/pull/1939#issuecomment-1068878332, the BracesFixer seems cause inlined method after `{`
=> [ECS] Skip BracesFixer

packages/config-transformer/scoper.php, packages/easy-ci/scoper.php, packages/easy-coding-standard/scoper.php, packages/monorepo-builder/scoper.php, packages/phpstan-rules/src/Rules/AnnotateRegexClassConstWithRegexLinkRule.php
The string replace is not applied, even applied, it will invalid as there is space in replacement.
```
return Strings::replace($content, '#use Symfony\\\\Polyfill#', 'use ' . $prefix . ' Symfony\Polyfill');
```
so it can be removed.
=> [Scoper] Clean up missing use with prefixed

composer.json, packages/astral/composer.json, packages/astral/config/config.neon, packages/easy-coding-standard/src/Application/Version/StaticVersionResolver.php, packages/latte-phpstan-compiler/composer.json, packages/latte-phpstan-compiler/config/config.neon, packages/phpstan-extensions/composer.json, packages/phpstan-extensions/config/config.neon, packages/phpstan-latte-rules/composer.json, packages/phpstan-latte-rules/config/config.neon, packages/phpstan-rules/composer.json, packages/phpstan-rules/config/config.neon, packages/rule-doc-generator/composer.json, packages/symfony-static-dumper/composer.json, packages/template-phpstan-compiler/composer.json, packages/template-phpstan-compiler/config/config.neon, phpstan.neon
Based on @ondrejmirtes request at https://github.com/rectorphp/rector-src/pull/2014#pullrequestreview-943347221 , this PR update to set compatible with upcoming PHPStan 1.6.x with update require of phpstan to ^1.5.6 and update `conditionalTags` of `NodeConnectingVisitor` for symplify as well.
=> [PHPStan] Set compatible with upcoming PHPStan 1.6.x with set NodeConnectingVisitor tags

packages/config-transformer/scoper.php
The constants in the `Symplify\PhpConfigPrinter\ValueObject\FunctionName` class should not be prefixed, as they will be used to create php config files and symfony will throw an exception if the generated config files have the prefixed namespace.
Fixes #3976
=> Remove prefix in function name constants

packages/phpstan-rules/config/static-rules.neon, packages/phpstan-rules/docs/rules_overview.md, packages/phpstan-rules/src/Rules/Missing/CheckSprintfMatchingTypesRule.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/CheckSprintfMatchingTypesRuleTest.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Fixture/MissMatchSprintf.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Fixture/SkipCorrectForeachKey.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Fixture/SkipCorrectSprintf.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Fixture/SkipErrorType.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Fixture/SkipToString.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Fixture/SkipValidTernary.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/Source/SomeToString.php, packages/phpstan-rules/tests/Rules/Missing/CheckSprintfMatchingTypesRule/config/configured_rule.neon
See #4062. This PR fixes all the misspellings of "sprintf" I could find.
This probably warrants a major version increase to indicate the breaking change: `CheckSprinfMatchingTypesRule` is now `CheckSprintfMatchingTypesRule`.
=> Fix various "sprintf" typos relating to `CheckSprintfMatchingTypesRule`

packages/phpstan-rules/README.md
Starting from version 10.2.6 the following config files were removed (I assume they have been included somewhere else?):
File 'vendor/symplify/phpstan-rules/config/services-rules.neon' is missing or is not readable.
File 'vendor/symplify/phpstan-rules/config/size-rules.neon' is missing or is not readable.
File 'vendor/symplify/phpstan-rules/config/string-to-constant-rules.neon' is missing or is not readable.
File 'vendor/symplify/phpstan-rules/config/symfony-rules.neon' is missing or is not readable.
But the above files were still in the readme.
=> [phpstan-rules] Removed missing config-files from README.md

packages/config-transformer/build/build-config-transformer-scoped.sh, packages/config-transformer/scoper.php, packages/easy-ci/build/build-easy-ci-scoped.sh, packages/easy-ci/scoper.php, packages/easy-coding-standard/build/build-ecs-scoped.sh, packages/easy-coding-standard/scoper.php, packages/easy-coding-standard/src/Exception/DeprecatedException.php, packages/monorepo-builder/build/build-monorepo-builder-scoped.sh, packages/monorepo-builder/scoper.php
This version brings:
* PHP 8.1 support
* "parent" false-prefixing fix
* easier polyfil skipping
See https://github.com/humbug/php-scoper/releases/tag/0.17.2
=> [build] Bump to php-scoper 0.17.2

easy-ci.php, packages/astral/src/ValueObject/AttributeKey.php, packages/phpstan-rules/config/services/services.neon, packages/phpstan-rules/packages/nette/src/Rules/NoNetteTemplateVariableReadRule.php, packages/phpstan-rules/packages/nette/tests/Rules/NoNetteTemplateVariableReadRule/Fixture/AvoidUnset.php, packages/phpstan-rules/packages/nette/tests/Rules/NoNetteTemplateVariableReadRule/Fixture/SkipPayloadAjaxFullJuggling.php, packages/phpstan-rules/packages/nette/tests/Rules/NoNetteTemplateVariableReadRule/NoNetteTemplateVariableReadRuleTest.php, packages/phpstan-rules/src/NodeVisitor/AssignedToPropertyNodeVisitor.php, packages/phpstan-rules/src/Rules/Explicit/ExplicitMethodCallOverMagicGetSetRule.php, packages/phpstan-rules/src/Rules/NoMultiArrayAssignRule.php, packages/phpstan-rules/tests/Rules/Explicit/ExplicitMethodCallOverMagicGetSetRule/config/configured_rule.neon
- [PHPStanRules] Remove parent from ExplicitMethodCallOverMagicGetSetRule
- [PHPStanRules] Add AssignedToPropertyNodeVisitor, to make NoNetteTemplateVariableReadRule work without parents
=> [PHPStanRules] Add AssignedToPropertyNodeVisitor, to make NoNetteTemplateVariableReadRule work without parents

packages/astral/src/ValueObject/AttributeKey.php, packages/phpstan-rules/config/services/services.neon, packages/phpstan-rules/packages/object-calisthenics/src/NodeVisitor/NullsafeCheckedNodeVisitor.php, packages/phpstan-rules/packages/object-calisthenics/src/Rules/NoChainMethodCallRule.php, packages/phpstan-rules/packages/object-calisthenics/tests/Rules/NoChainMethodCallRule/Fixture/SkipNullsafeCalls.php, packages/phpstan-rules/packages/object-calisthenics/tests/Rules/NoChainMethodCallRule/NoChainMethodCallRuleTest.php
Fixing follow up to https://github.com/symplify/symplify/pull/4133
=> [PHPStanRules] Restore nullsafe check in NoChainMethodCallRule

packages/phpstan-rules/src/ParentClassMethodNodeResolver.php
closes https://github.com/symplify/symplify/issues/4163
=> use ReflectionProvider in ParentClassMethodNodeResolver

composer.json, packages/coding-standard/composer.json, packages/easy-coding-standard/composer.json, packages/easy-coding-standard/tests/Set/Psr12/Fixture/fixture2.php.inc, packages/phpstan-rules/src/Printer/CollectorMetadataPrinter.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Fixture/SkipEqualUnionType.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/NarrowPublicClassMethodParamTypeByCallerTypeRuleTest.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedUnion/CallUnionType.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedUnion/CallUnionTypeFlipped.php, packages/rule-doc-generator/composer.json
This test verify equal union type passed for both ordered or non-ordered type.
=> [PHPStanRules] Skip equal union type passed on NarrowPublicClassMethodParamTypeByCallerTypeRule

packages/phpstan-rules/src/Collector/ClassMethod/MethodCallCollector.php, packages/phpstan-rules/src/Collector/MethodCall/MethodCallArgTypesCollector.php, packages/phpstan-rules/src/Matcher/ClassMethodCallReferenceResolver.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Fixture/SkipUsedInternallyForSecondType.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/NarrowPublicClassMethodParamTypeByCallerTypeRuleTest.php, packages/phpstan-rules/tests/Rules/NarrowType/NarrowPublicClassMethodParamTypeByCallerTypeRule/Source/ExpectedType/OnlyFirstTypeCalledOutside.php
- first type called outside class
- second type called inside class itself
=> [PHPStanRules] Skip used in internal class for second type on Union type on NarrowPublicClassMethodParamTypeByCallerTypeRule

composer.json, packages/config-transformer/composer.json, packages/config-transformer/patches/symfony-dependency-injection-definition-php.patch, packages/config-transformer/patches/symfony-dependency-injection-loader-yamlfileloader-php.patch, packages/config-transformer/src/ConfigLoader.php, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/autowired_type.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Source/SomeService.php, packages/php-config-printer/src/ExprResolver/StringExprResolver.php, packages/php-config-printer/src/NodeFactory/ConstantNodeFactory.php, packages/php-config-printer/src/ServiceOptionConverter/AutowiringTypesOptionKeyYamlToPhpFactory.php, packages/php-config-printer/src/Yaml/CheckerServiceParametersShifter.php, packages/php-config-printer/tests/NodeFactory/ConstantNodeFactoryTest.php, patches/symfony-dependency-injection-definition-php.patch, patches/symfony-dependency-injection-loader-yamlfileloader-php.patch
This adds feature removed in Symfony 4: https://github.com/symfony/symfony/pull/21494,
so it can be easily converted :)
=> [ConfigTransformer] Add suport for autowiring types

config/some_config.yml, packages/config-transformer/config/config.php, packages/config-transformer/src/Command/SwitchFormatCommand.php, packages/config-transformer/src/Converter/ConvertedContentFactory.php, packages/config-transformer/src/FileSystem/ConfigFileDumper.php, packages/config-transformer/src/ValueObject/ConvertedContent.php, packages/package-builder/README.md
I'm running this command on an old Symfony project, and I'm surprised how poor the output format is. Let's give it some useful content :)
---
=> [ConfigTransformer] Improve report of changed files with a rich diff of changed content :+1: 

packages/easy-testing/src/DataProvider/StaticFixtureFinder.php
`StaticFixtureFinder:: yieldFileInfosWithRelativePathname()` maps `SplFileInfo` from arguments to `SmartFileInfo`, but phpDocs were too narrow. This change is required for Rector (MR incoming).
=> Proper yield types for `StaticFixtureFinder`

packages/monorepo-builder/README.md
First of all, thanks for all your heard work. It's really appreciated and helped me out a ton!
Just thought I'd update the documentation while I was using it if that makes sense at all.
For ease of copy pasting we can add `Symplify\MonorepoBuilder\ValueObject\Option`, as this is used in the `dataToRemove` example.
```
$mbConfig->dataToRemove([
ComposerJsonSection::REQUIRE => [
// the line is removed by key, so version is irrelevant, thus *
'phpunit/phpunit' => '*',
],
ComposerJsonSection::REPOSITORIES => [
// this will remove all repositories
Option::REMOVE_COMPLETELY,
],
]);
```
=> Monorepo-builder: Documentation update to ensure code matches example

packages/config-transformer/.gitignore, packages/config-transformer/phpunit.xml, packages/config-transformer/src/ConfigLoader.php, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/hautelook_alice.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/import_already_converted.php, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/import_already_converted_test.yaml, packages/php-config-printer/src/ExprResolver/StringExprResolver.php
Follow up to https://github.com/symplify/symplify/pull/4288
=> [ConfigTransformer] Fix converting sniff class in case of missing PHP_CodeSniffer

packages/symfony-static-dumper/README.md, packages/symfony-static-dumper/src/Command/DumpStaticSiteCommand.php, packages/symfony-static-dumper/src/Enum/Option.php
* Closes https://github.com/symplify/symplify/pull/4210
* Closes https://github.com/symplify/symplify/pull/4244
<br>
@JWBrownie Thanks for the feature proposal :+1:  The input and output directories are no configurable ↓
<br>
These 2 command are equal in functionality:
```bash
vendor/bin/console dump-static-site
vendor/bin/console dump-static-site --public-directory public --output-directory output
```
=> [SymfonyStaticDumper] Add --public-directory and --output-directory to allow customize the io directories

packages/phpstan-rules/docs/symfony_overview.md, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/Fixture/ClassUsedInSymfonyFormButWithConstructor.php, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/Fixture/SkipClassUsedInSymfonyFormWithoutConstructor.php, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/NoConstructorSymfonyFormObjectRuleTest.php, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/Source/SymfonyFormUsingFirstObject.php, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/Source/SymfonyFormUsingSecondObject.php, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/config/configured_rule.neon, packages/phpstan-rules/packages/Symfony/Rules/NoConstructorSymfonyFormObjectRule.php, packages/phpstan-rules/stubs/Symfony/Component/Form/AbstractType.php, phpstan.neon, stubs/Symfony/Component/Form/AbstractType.php
Using constructor value in Symfony Form objects of any kinds is breaking the forms.
See https://stackoverflow.com/a/43962930/1348344
We don't want to think about while upgrading, right?
This can be easily prevent by a PHPStan rule that checks there is no required parmaeter in the constructor of such used class :+1: :wink:
=> [PHPStanRules] Add NoConstructorSymfonyFormObjectRule

packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/NoConstructorSymfonyFormObjectRuleTest.php, packages/phpstan-rules/packages-tests/Symfony/Rules/NoConstructorSymfonyFormObjectRule/Source/SymfonyFormSetDefault.php, packages/phpstan-rules/src/Collector/ClassMethod/FormTypeClassCollector.php
Covers:
```php
public function configureOptions(OptionsResolver $resolver): void
{
$resolver->setDefault('data_class',  ClassUsedInSymfonyFormButWithConstructor::class);
}
```
=> [PHPStanRules] Include the setDeault() in NoConstructorSymfonyFormObjectRule

packages/phpstan-rules/docs/cognitive_complexity_rules_overview.md, packages/phpstan-rules/packages-tests/CognitiveComplexity/Rules/ClassLikeCognitiveComplexityRule/config/configured_composition_rule.neon, packages/phpstan-rules/packages-tests/CognitiveComplexity/Rules/ClassLikeCognitiveComplexityRule/config/configured_rule.neon, packages/phpstan-rules/packages/CognitiveComplexity/Rules/ClassLikeCognitiveComplexityRule.php, phpstan.neon
Based on practical use... or rather non-use :) having class cognitive complexity is good enough :+1:
=> [PHPStanRules] Remove complexity by type in ClassLikeCognitiveComplexityRule, too much overengeneering

packages/config-transformer/tests/Converter/ConfigFormatConverter/Source/InvokableFactory.php, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_configurator.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_factory.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/factory/invokable_factory.yaml, packages/php-config-printer/src/ServiceOptionConverter/FactoryConfiguratorServiceOptionKeyYamlToPhpFactory.php
Fixes #4369 
As you can see in Symfony docs for [factories](https://symfony.com/doc/current/service_container/factories.html#invokable-factories) and [configurators](https://symfony.com/doc/current/service_container/configurators.html#using-the-configurator), when class is invokable `service(...)` reference must NOT be wrapped with array.
=> Proper support for invokable factories/configurators

packages/monorepo-builder/composer.json
Official docker images does not have intl extension enabled and monorepo builder fails hard on missing class. 
```
root@b19bba9b15b0:/code# vendor/bin/monorepo-builder init
PHP Fatal error:  Uncaught Error: Class 'Normalizer' not found in /code/vendor/symplify/monorepo-builder/vendor/symfony/console/Helper/Helper.php:45
Stack trace:
#0 /code/vendor/symplify/monorepo-builder/vendor/symfony/console/Style/SymfonyStyle.php(401): MonorepoBuilder202209\Symfony\Component\Console\Helper\Helper::width(' ')
#1 /code/vendor/symplify/monorepo-builder/vendor/symfony/console/Style/SymfonyStyle.php(64): MonorepoBuilder202209\Symfony\Component\Console\Style\SymfonyStyle->createBlock(Array, 'ERROR', 'fg=white;bg=red', ' ', true, true)
#2 /code/vendor/symplify/monorepo-builder/vendor/symfony/console/Style/S …
```
=> Require intl extension in composer.json

packages/monorepo-builder/composer.json, packages/monorepo-builder/scoper.php
Ref https://github.com/symplify/symplify/pull/4385?notification_referrer_id=NT_kwDOAAcDgLE0MzIxMDQ5NzIzOjQ1OTY0OA#issuecomment-1235294375
=> [MB] Fix Normalizer class not found on scoped Monorepo builder

packages/config-transformer/tests/Converter/ConfigFormatConverter/Source/StaticFactory.php, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/factory/split_factory.yaml, packages/php-config-printer/src/NodeFactory/ConstantNodeFactory.php, packages/php-config-printer/src/ServiceOptionConverter/NodeModifier/SingleFactoryReferenceNodeModifier.php, phpstan.neon
Fixes #4368
I was able to reproduce the problem, but I need help with fixing it 🙂 Could you point me where to look at just to be able to handle splitting by `::` and dumping proper factory with `::class` usage?
FYI: It can be tested locally with `vendor/bin/phpunit --testdox packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/YamlToPhpTest.php --filter=testNormal#39` (runs only failing fixture).
=> [ConfigTransformer] Support for `FQCN::method` format in factories

packages/easy-coding-standard/packages-tests/Skipper/Skipper/Skipper/SkipperTest.php, packages/easy-coding-standard/packages/Skipper/Skipper/Skipper.php, packages/symplify-kernel/src/ValueObject/KernelBootAndApplicationRun.php, phpstan.neon
Like in rector-src's Loop SkipVotter classes hande https://github.com/rectorphp/rector-src/pull/2921/files#diff-3ae415e78c60375cb710124ff66aaacd50a22e34ca69287cb3db14931de3c69c , the loop should not be stopped until it verified that it skipped, as direct return may return false early.
=> [ECS] Loop SkipVotter until verified skipped on Skipper

packages/easy-coding-standard/README.md
I was reading the docs/readme and I couldn't resist creating a PR fixing `extendsions`. 
>**Note**: And after that I couldn't resist putting this meme 👇🏼  🤣
=> Fix typo in README

packages/phpstan-rules/src/Rules/Explicit/NoMixedMethodCallerRule.php, packages/phpstan-rules/tests/Rules/Explicit/NoMixedMethodCallerRule/Fixture/SkipMockObject.php, packages/phpstan-rules/tests/Rules/Explicit/NoMixedMethodCallerRule/NoMixedMethodCallerRuleTest.php
Given the following code on test:
```php
$mock = $this->createMock(MagicMethodName::class);
```
It seems it detected as `PHPStan\Type\ErrorType`, it should be skipped.
=> [PHPStanRules] Skip MockObject on NoMixedMethodCallerRule

packages/easy-parallel/src/ValueObject/ParallelProcess.php
Windows don't like processes being terminated like that - it leads to child process error (https://github.com/phpstan/phpstan-src/actions/runs/3144712914/jobs/5111071107).
Fortunately this line isn't needed at all. I fixed a similar problem in PHPStan a few years ago (https://github.com/phpstan/phpstan-src/commit/54eb9ce142a546f7ee3ccd1bd88c01368ab33941).
I tested it using a Composer patch in PHPStan and it works for Rector too (https://github.com/phpstan/phpstan-src/commit/37c643cd4d4c65837f1d42252b8bbc5f5d9c9a71).
=> Fix parallel processing on Windows

packages/autowire-array-parameter/src/DependencyInjection/CompilerPass/AutowireArrayParameterCompilerPass.php
The `@noRector` only make it can't run any Rector rules, see downgrade Rector error on https://github.com/rectorphp/rector-src/actions/runs/3333691682/jobs/5515884678#step:14:69
```bash
Parse error: rector-prefixed-downgraded/vendor/symplify/autowire-array-parameter/src/DependencyInjection/CompilerPass/AutowireArrayParameterCompilerPass.php:35
33|      * @noRector
34|      */
> 35|     private array $excludedFatalClasses = ['RectorPrefix202210\\Symfony\\Component\\Form\\FormExtensionInterface', 'RectorPrefix202210\\Symfony\\Component\\Asset\\PackageInterface', 'RectorPrefix202210\\Symfony\\Component\\Config\\Loader\\LoaderInterface', 'RectorPrefix202210\\Symfony\\Component\\VarDumper\\Dumper\\ContextProvider\\ContextProviderInterface', …
```
=> [AutowireArrayParameter] Fix @noRector tag usage on AutowireArrayParameterCompilerPass

packages/phpstan-rules/src/Rules/Complexity/NoDuplicatedTraitMethodNameRule.php
Potentially a breaking change due to a nature how PHPStan ignores errors :)
=> Fix a typo

packages/easy-coding-standard/src/Config/ECSConfig.php
I would love to do that:
```php
return static function (ECSConfig $ecsConfig): void {
$ecsConfig->rulesWithConfiguration([
AlignMultilineCommentFixer::class => [
'comment_type' => 'phpdocs_like',
],
ArraySyntaxFixer::class => [
'syntax' => 'short',
],
]);
}
```
=> Adds rulesWithConfiguration in ECSConfig.

packages/phpstan-rules/src/Printer/CollectorMetadataPrinter.php
Fix the following PHPStan notice:
```bash
Note: Using configuration file /Users/samsonasik/www/symplify/phpstan.neon.
1211/1211 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
packages/phpstan-rules/src/Printer/CollectorMetadataPrinter.php:108
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- '#Cannot cast …
```
=> [PHPStan] Fix PHPStan notice IntersectionType inside UnionType to string

packages/easy-coding-standard/config/set/common/array.php, packages/php-config-printer/src/CaseConverter/ImportCaseConverter.php, packages/phpstan-extensions/tests/ErrorFormatter/SymplifyErrorFormatterTest.php, packages/phpstan-rules/tests/Rules/Complexity/NoAbstractRule/NoAbstractRuleTest.php
- remove deprecated rule
- make use of new trialing comma args rules
=> [ECS] Update array comma rule

packages/config-transformer/src/ConfigLoader.php, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/class_constant.yaml
Continuation from #4441 🙂 
Differences between [proposed regex](https://github.com/symplify/symplify/pull/4441#issuecomment-1325862399) and actual change in the PR:
- added support for numbers in constants
- instead of `\\` in first group I had to do `\\\\` because somehow tests were failing: class' FQCN was not properly caught and was causing syntax issues, e.g.:
> Symfony\Component\Yaml\Exception\ParseException: Unexpected characters near "\ConfigTransformer\Tests\Converter\ConfigFormatConverter\YamlToPhp\YamlToPhpTest::TEST" at line 2 (near "class_constant: "%const(Symplify)%"\ConfigTransformer\Tests\Converter\ConfigFormatConverter\YamlToPhp\YamlToPhpTest::TEST").
Regex URL was updated, but currently it does not contain `\\\\` change (works without it).
=> Improve ConfigLoader::PHP_CONST_REGEX

packages/autowire-array-parameter/src/DependencyInjection/CompilerPass/AutowireArrayParameterCompilerPass.php, packages/easy-testing/src/ValueObject/ExpectedAndOutputFileInfoPair.php, packages/rule-doc-generator/src/RuleCodeSamplePrinter/ECSRuleCodeSamplePrinter.php, packages/rule-doc-generator/src/RuleCodeSamplePrinter/PHPStanRuleCodeSamplePrinter.php, packages/rule-doc-generator/src/RuleCodeSamplePrinter/RectorRuleCodeSamplePrinter.php, rector.php
The `@noRector` removal on rector-src PR:
- https://github.com/rectorphp/rector-src/pull/3148
cause downgrade build error, ref https://github.com/rectorphp/rector-src/actions/runs/3609550282/jobs/6082808356#step:10:22
This PR move to skip to make downgrade build on rector-src work.
Note: it require release the symplify components as rector-src require tagged versions of symplify components.
=> Move @noRector usage to rectorConfig->skip()

composer.json, packages/easy-parallel/composer.json, packages/easy-parallel/src/CpuCoreCountProvider.php
See https://github.com/theofidry/cpu-core-counter/issues/11 for the motivations.
The code should be sensibly the same, the notable differences are:
- fixed the deprecated usage of `hw.ncpu`
- /proc/cpuinfo is check _last_
- nproc is checked first (before was not checked at all, it's considered to be more accurate and less convoluted than cpuinfo though)
Also note since this was analogue to PHPStan, I did the PR there too: https://github.com/phpstan/phpstan-src/pull/2047
I would also wait on 1.x before merging this if you're happy with it. Technically the current version is fine, I'm just looking for a round of feedback before publishing 1.0.
=> Integrate FidryCpuCoreCounter

composer.json
Fix error version 0.1.0
```
➜  symplify git:(main) composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Root composer.json requires tomasvotruba/cognitive-complexity ^0.1.0, found tomasvotruba/cognitive-complexity[dev-main, 0.0.1, ..., 0.0.5.72] but it does not match the constraint.
```
=> Fix version dependency of tomasvotruba/cognitive-complexity

composer.json, packages/phpstan-extensions/composer.json, packages/phpstan-rules/build/target-repository/composer.json, packages/phpstan-rules/composer.json, packages/rule-doc-generator/composer.json, packages/symfony-static-dumper/composer.json
PHPStan 1.9.5 released https://github.com/phpstan/phpstan/releases/tag/1.9.5
This PR bump PHPStan requirement to ^1.9.5
=> Bump to PHPStan 1.9.5

composer.json, packages/coding-standard/composer.json, packages/coding-standard/tests/Fixer/Annotation/RemovePHPStormAnnotationFixer/RemovePHPStormAnnotationFixerTest.php, packages/coding-standard/tests/Fixer/ArrayNotation/ArrayListItemNewlineFixer/ArrayListItemNewlineFixerTest.php, packages/coding-standard/tests/Fixer/ArrayNotation/ArrayOpenerAndCloserNewlineFixer/ArrayOpenerAndCloserNewlineFixerTest.php, packages/coding-standard/tests/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer/StandaloneLineInMultilineArrayFixerTest.php, packages/coding-standard/tests/Fixer/ArrayNotation/StandaloneLineInMultilineArrayFixer/StandaloneLineInMultilineArrayFixerTestPhp80Test.php, packages/coding-standard/tests/Fixer/Commenting/ParamReturnAndVarTagMalformsFixer/ParamReturnAndVarTagMalformsFixerTest.php, packages/coding-standard/tests/Fixer/Commenting/RemoveUselessDefaultCommentFixer/RemoveUselessDefaultCommentFixerTest.php, packages/coding-standard/tests/Fixer/LineLength/DocBlockLineLengthFixer/DocBlockLineLengthFixerTest.php, packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/ArrayLineLengthFixerTest.php, packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/ConfiguredLineLengthFixerTest.php, packages/coding-standard/tests/Fixer/LineLength/LineLengthFixer/LineLengthFixerTest.php, packages/coding-standard/tests/Fixer/Naming/StandardizeHereNowDocKeywordFixer/StandardizeHereNowDocKeywordFixerTest.php, packages/coding-standard/tests/Fixer/Spacing/MethodChainingNewlineFixer/MethodChainingNewlineFixerTest.php, packages/coding-standard/tests/Fixer/Spacing/NewlineServiceDefinitionConfigFixer/NewlineServiceDefinitionConfigFixerTest.php, packages/coding-standard/tests/Fixer/Spacing/SpaceAfterCommaHereNowDocFixer/SpaceAfterCommaHereNowDocFixerTest.php, packages/coding-standard/tests/Fixer/Spacing/StandaloneLineConstructorParamFixer/StandaloneLineConstructorParamFixerContraindicationsTest.php, packages/coding-standard/tests/Fixer/Spacing/StandaloneLineConstructorParamFixer/StandaloneLineConstructorParamFixerTest.php, packages/coding-standard/tests/Fixer/Spacing/StandaloneLinePromotedPropertyFixer/StandaloneLinePromotedPropertyFixerTest.php, packages/coding-standard/tests/Fixer/Strict/BlankLineAfterStrictTypesFixer/BlankLineAfterStrictTypesFixerTest.php, packages/coding-standard/tests/Issues/InlineArrayTest.php, packages/coding-standard/tests/Issues/Issue896Test.php, packages/coding-standard/tests/Issues/Issue973Test.php, packages/monorepo-builder/packages-tests/Merge/ComposerJsonMerger/ComposerJsonMergerTest.php, packages/monorepo-builder/packages-tests/Merge/ComposerKeyMerger/MinimalStabilityKeyMergerTest.php, packages/monorepo-builder/packages-tests/Propagate/VersionPropagator/VersionPropagaterTest.php
This will prevent conflicts with `SmartFileInfo` prefixed class:
https://github.com/symplify/symplify/actions/runs/3825967304/jobs/6509374280
=> [CodingStandard] Make use of file path based testing

composer.json, packages/phpstan-extensions/composer.json, packages/phpstan-rules/build/target-repository/composer.json, packages/phpstan-rules/composer.json, packages/rule-doc-generator/composer.json, packages/symfony-static-dumper/composer.json
PHPStan 1.9.6 released https://github.com/phpstan/phpstan/releases/tag/1.9.7
This PR bump PHPStan requirement to ^1.9.7
=> Bump PHPStan ^1.9.7

packages/coding-standard/composer.json
To avoid error:
```bash
- Applying patches for symfony/dependency-injection
https://raw.githubusercontent.com/symplify/vendor-patch-files/main/patches/generic-php-config-loader.patch (0)
Could not apply patch! Skipping. The error was: Cannot apply patch https://raw.githubusercontent.com/symplify/vendor-patch-files/main/patches/generic-php-config-loader.patch
```
ref https://github.com/rectorphp/getrector.org/pull/981
closes https://github.com/rectorphp/getrector.org/pull/981
=> Require symfony/dependency-injection 6.1.* for symplify/coding-standard

packages/phpstan-rules/src/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule.php, packages/phpstan-rules/src/ValueObject/Regex.php, packages/phpstan-rules/tests/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule/CheckNotTestsNamespaceOutsideTestsDirectoryRuleTest.php, packages/phpstan-rules/tests/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule/Fixture/Fail/NotInTestsDirectory/FailNotInTestsDirectoryTest.php, packages/phpstan-rules/tests/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule/Fixture/Pass/EndWithTests/Tests/NameSpaceEndWithTestsFileTest.php, packages/phpstan-rules/tests/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule/Fixture/Pass/Tests/ContainsTestsDirectory/NameSpaceContainsTestsFileTest.php, packages/phpstan-rules/tests/Rules/CheckNotTestsNamespaceOutsideTestsDirectoryRule/Fixture/Tests/InTestsDirectory/NameSpaceStarttWithTestsFileTest.php
Projects like Laravel who wants to use this rule will get immediate complaints as their code is of the following structure:
```
- app
- tests
- vendors
```
This PR avoids such errors while maintaining the intent.
I did not see where to apply tests, please point me in the right direction if necessary.
=> Test rules should also support Test path as Prefix (e.g. Laravel)
